using Microsoft.CodeAnalysis;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using NativeTranspiler.Analyzer.Common;

namespace NativeTranspiler.Analyzer
{
    public static class BindingsGenerator
    {
        private const string NativeLibraryName = "NativeDll";

        public static string GenerateBindingsClass(
            IEnumerable<IMethodSymbol> methods,
            IEnumerable<INamedTypeSymbol> jobStructs,
            Compilation compilation)
        {
            var sb = new StringBuilder();
            sb.AppendLine("// <auto-generated/>");
            // job 结构含 NativeArray/NativeList（内含托管 DisposeSentinel）→ 托管类型。生成代码用
            // sizeof/取址/指针强转把 job 的 blittable 字段搬运/读到 native 侧，是验证过的安全模式；
            // CS8500（对托管类型取大小/地址）为 false positive，按 Unity 生成 interop 代码惯例屏蔽。
            sb.AppendLine("#pragma warning disable CS8500");
            sb.AppendLine("using System;");
            sb.AppendLine("using System.Runtime.InteropServices;");
            sb.AppendLine("using System.Runtime.CompilerServices;");
            sb.AppendLine("using EntJoy;");
            sb.AppendLine("using EntJoy.Collections;");
            sb.AppendLine("using EntJoy.JobSystem;");
            sb.AppendLine();
            sb.AppendLine("namespace NativeTranspiler.Bindings");
            sb.AppendLine("{");
            sb.AppendLine("    public static unsafe partial class NativeExports");
            sb.AppendLine("    {");
            sb.AppendLine("        public delegate void JobFuncDelegate(IntPtr context);");
            sb.AppendLine("        public delegate void BatchJobFuncDelegate(IntPtr context, int startIndex, int count);");
            sb.AppendLine("        public delegate void ChunkJobFuncDelegate(IntPtr context, ChunkJobData* chunkData);");
            sb.AppendLine("        public delegate void CleanupFuncDelegate(IntPtr context);");
            sb.AppendLine();

            var attrSymbol = compilation.GetTypeByMetadataName("NativeTranspiler.NativeTranspileAttribute");

            // GPU Job 无 native 符号（WGSL 由 wgpu 执行）→ 从 native bindings 中排除，
            // 单独走 GpuCompute_*（NativeDll wgpu 后端）→ 生成 ScheduleGpu。
            var nativeJobs = jobStructs
                .Where(j => j == null ||
                            attrSymbol == null ||
                            AttributeHelper.GetBackendTarget(j, attrSymbol) != NativeTranspiler.BackendTarget.Gpu)
                .ToList();
            var gpuJobs = jobStructs
                .Where(j => j != null && attrSymbol != null &&
                            AttributeHelper.GetBackendTarget(j, attrSymbol) == NativeTranspiler.BackendTarget.Gpu)
                .ToList();

            // 1. 为每个 Job 结构体生成静态缓存的委托字段和函数指针
            foreach (var jobStruct in nativeJobs)
            {
                GenerateStaticDelegateFields(sb, jobStruct, compilation);
            }

            // 2. 静态构造函数：初始化所有缓存的委托和函数指针
            sb.AppendLine("        static NativeExports()");
            sb.AppendLine("        {");
            foreach (var jobStruct in nativeJobs)
            {
                GenerateStaticConstructorInitialization(sb, jobStruct, compilation);
            }
            sb.AppendLine("        }");
            sb.AppendLine();

            // 3. 普通方法的 DllImport 和 Wrapper（自动内联 MT 选择）
            foreach (var method in methods)
            {
                GenerateMethodDllImport(sb, method);
                bool useMT = HasUseISPC_MT(method, attrSymbol);
                if (useMT)
                {
                    GenerateMethodDllImportMT(sb, method);
                }
                GenerateMethodWrapper(sb, method, useMT);
            }

            // 4. Job 结构体的 DllImport 和 Schedule 方法
            foreach (var jobStruct in nativeJobs)
            {
                GenerateJobDllImport(sb, jobStruct, compilation);
                GenerateJobScheduleMethod(sb, jobStruct, compilation);
            }

            // 4b. GPU Job：GpuCompute_* P/Invoke（NativeDll wgpu 后端）+ kernel 静态缓存字段
            if (gpuJobs.Count > 0)
            {
                GenerateGpuComputeDllImports(sb);
                foreach (var jobStruct in gpuJobs)
                    sb.AppendLine($"        internal static IntPtr __gpuKernel_{jobStruct.Name} = IntPtr.Zero;");
            }

            sb.AppendLine(GenerateCleanupFactoryMethod());
            sb.AppendLine("    }");
            sb.AppendLine("}");
            sb.AppendLine();

            // 5. Job 扩展方法（Schedule 和 Run）
            sb.AppendLine("public static partial class JobExtensions");
            sb.AppendLine("{");
            foreach (var jobStruct in nativeJobs)
            {
                GenerateJobExtensionMethod(sb, jobStruct);
                GenerateJobRunMethod(sb, jobStruct, compilation);
            }
            foreach (var jobStruct in gpuJobs)
            {
                GenerateGpuScheduleMethod(sb, jobStruct, compilation);
            }
            sb.AppendLine("}");

            return sb.ToString();
        }

        private static bool HasUseISPC_MT(ISymbol symbol, INamedTypeSymbol? attrSymbol)
            => AttributeHelper.HasUseISPC_MT(symbol, attrSymbol);

        // ---------- 方法 DllImport ----------
        private static void GenerateMethodDllImport(StringBuilder sb, IMethodSymbol method)
        {
            var cppFunctionName = CppGenerator.GetCppFunctionName(method);
            var returnType = method.ReturnType.ToDisplayString(SymbolDisplayFormat.FullyQualifiedFormat);
            var methodName = method.Name + "_Native";
            var parameters = BuildMethodDllImportParams(method);
            sb.AppendLine($"        [DllImport(\"{NativeLibraryName}\", EntryPoint = \"{cppFunctionName}\", CallingConvention = CallingConvention.Cdecl)]");
            sb.AppendLine($"        private static extern {returnType} {methodName}({string.Join(", ", parameters)});");
            sb.AppendLine();
        }

        private static void GenerateMethodDllImportMT(StringBuilder sb, IMethodSymbol method)
        {
            var cppFunctionName = CppGenerator.GetCppFunctionName(method) + "_mt";
            var returnType = method.ReturnType.ToDisplayString(SymbolDisplayFormat.FullyQualifiedFormat);
            var methodName = method.Name + "_mt_Native";
            var parameters = BuildMethodDllImportParams(method);
            parameters.Add("int numTasks");
            sb.AppendLine($"        [DllImport(\"{NativeLibraryName}\", EntryPoint = \"{cppFunctionName}\", CallingConvention = CallingConvention.Cdecl)]");
            sb.AppendLine($"        private static extern {returnType} {methodName}({string.Join(", ", parameters)});");
            sb.AppendLine();
        }

        private static void GenerateMethodWrapper(StringBuilder sb, IMethodSymbol method, bool useMT)
        {
            var returnType = method.ReturnType.ToDisplayString(SymbolDisplayFormat.FullyQualifiedFormat);
            var methodName = method.Name;
            var parameters = method.Parameters.Select(p => $"{GetCSharpParameterType(p)} {p.Name}");
            sb.AppendLine($"        public static {returnType} {methodName}({string.Join(", ", parameters)})");
            sb.AppendLine("        {");
            sb.AppendLine("            unsafe {");
            if (method.ReturnType.SpecialType != SpecialType.System_Void)
                sb.Append("            return ");
            else
                sb.Append("            ");

            if (useMT)
            {
                sb.Append($"{methodName}_mt_Native(");
                var args = BuildMethodCallArgs(method);
                args.Add("Environment.ProcessorCount");
                sb.Append(string.Join(", ", args));
            }
            else
            {
                sb.Append($"{methodName}_Native(");
                var args = BuildMethodCallArgs(method);
                sb.Append(string.Join(", ", args));
            }
            sb.AppendLine(");");
            sb.AppendLine("            }");
            sb.AppendLine("        }");
            sb.AppendLine();
        }

        // ---------- Job 委托字段 ----------
        private static void GenerateStaticDelegateFields(StringBuilder sb, INamedTypeSymbol jobStruct, Compilation compilation)
        {
            bool isChunk = CppJobGenerator.IsChunkScheduledJob(jobStruct);
            bool isParallelFor = CppJobGenerator.IsParallelForJob(jobStruct);
            bool isFor = CppJobGenerator.IsForJob(jobStruct);

            if (isChunk)
            {
                if (CppJobGenerator.IsEntityJob(jobStruct))
                {
                    // IJobEntity 统一走 Chunk 级调度（与 ISPC 路径一致）
                    sb.AppendLine($"        private static readonly IntPtr s_{jobStruct.Name}_ChunkFuncPtr;");
                    sb.AppendLine($"        private static readonly IntPtr s_{jobStruct.Name}_ChunkRangeFuncPtr;");
                }
                else
                {
                    sb.AppendLine($"        private static readonly IntPtr s_{jobStruct.Name}_ChunkFuncPtr;");
                    sb.AppendLine($"        private static readonly IntPtr s_{jobStruct.Name}_ChunkRangeFuncPtr;");
                    var attrSym2 = AttributeHelper.GetAttributeSymbol(compilation);
                    bool isIspc2 = attrSym2 != null && AttributeHelper.GetBackendTarget(jobStruct, attrSym2) == NativeTranspiler.BackendTarget.Ispc;
                    if (!isIspc2)
                        sb.AppendLine($"        private static readonly IntPtr s_{jobStruct.Name}_ChunkEntityBatchFuncPtr;");
                }
                var requiredTypes = CppJobGenerator.CollectChunkNativeArrayTypes(jobStruct, compilation);
                string requiredIds = BuildRequiredComponentTypeIdsInitializer(requiredTypes);
                sb.AppendLine($"        private static readonly int[] s_{jobStruct.Name}_RequiredComponentTypeIds = {requiredIds};");
            }
            else if (isParallelFor || isFor)
            {
                sb.AppendLine($"        private static readonly BatchJobFuncDelegate s_{jobStruct.Name}_BatchFunc;");
                sb.AppendLine($"        private static readonly IntPtr s_{jobStruct.Name}_BatchFuncPtr;");
            }
            else
            {
                sb.AppendLine($"        private static readonly JobFuncDelegate s_{jobStruct.Name}_JobFunc;");
                sb.AppendLine($"        private static readonly IntPtr s_{jobStruct.Name}_JobFuncPtr;");
            }
            sb.AppendLine($"        private static readonly CleanupFuncDelegate s_{jobStruct.Name}_CleanupFunc;");
            sb.AppendLine($"        private static readonly IntPtr s_{jobStruct.Name}_CleanupFuncPtr;");
            sb.AppendLine();
        }

        private static void GenerateStaticConstructorInitialization(StringBuilder sb, INamedTypeSymbol jobStruct, Compilation compilation)
        {
            string jobTypeFullName = jobStruct.ToDisplayString();
            bool isParallelFor = CppJobGenerator.IsParallelForJob(jobStruct);
            bool isFor = CppJobGenerator.IsForJob(jobStruct);
            bool isChunk = CppJobGenerator.IsChunkScheduledJob(jobStruct);

            var executeMethod = jobStruct.GetMembers().OfType<IMethodSymbol>().First(m => m.Name == "Execute");
            var methodSyntax = SymbolHelper.GetMethodSyntax(executeMethod);
            bool hasMultiVersion = false;
            string boolFieldName = null;
            List<IFieldSymbol> boolFields = new List<IFieldSymbol>();

            var attrSymbol = compilation.GetTypeByMetadataName("NativeTranspiler.NativeTranspileAttribute");
            bool useMT = HasUseISPC_MT(jobStruct, attrSymbol);

            if (methodSyntax != null)
            {
                var semanticModel = compilation.GetSemanticModel(methodSyntax.SyntaxTree);
                var conditionalFields = NativeTranspileValidator.GetConditionalReadOnlyFields(jobStruct, semanticModel);
                boolFields = conditionalFields.Where(f => f.Type.SpecialType == SpecialType.System_Boolean).ToList();
                if (boolFields.Count > 0)
                {
                    hasMultiVersion = true;
                    boolFieldName = boolFields[0].Name;
                }
            }

            if (isChunk)
            {
                if (CppJobGenerator.IsEntityJob(jobStruct))
                {
                    // IJobEntity 统一走 Chunk 级调度（与 ISPC 路径一致）
                    sb.AppendLine($"            s_{jobStruct.Name}_ChunkFuncPtr = Get_{jobStruct.Name}_ChunkAdapterPtr();");
                    sb.AppendLine($"            s_{jobStruct.Name}_ChunkRangeFuncPtr = Get_{jobStruct.Name}_ChunkRangeAdapterPtr();");
                }
                else
                {
                    sb.AppendLine($"            s_{jobStruct.Name}_ChunkFuncPtr = Get_{jobStruct.Name}_ChunkAdapterPtr();");
                    sb.AppendLine($"            s_{jobStruct.Name}_ChunkRangeFuncPtr = Get_{jobStruct.Name}_ChunkRangeAdapterPtr();");
                    var attrSym2 = AttributeHelper.GetAttributeSymbol(compilation);
                    bool isIspc2 = attrSym2 != null && AttributeHelper.GetBackendTarget(jobStruct, attrSym2) == NativeTranspiler.BackendTarget.Ispc;
                    if (!isIspc2)
                        sb.AppendLine($"            s_{jobStruct.Name}_ChunkEntityBatchFuncPtr = Get_{jobStruct.Name}_ChunkEntityBatchAdapterPtr();");
                }
            }
            else if (isParallelFor || isFor)
            {
                if (useMT)
                {
                // MT（task 内部自己调度）仍用托管 delegate：原生 Adapter 只生成非 MT 变体
                string mtSuffix = "_mt";

                sb.AppendLine($"            s_{jobStruct.Name}_BatchFunc = (IntPtr context, int startIndex, int count) =>");
                sb.AppendLine("            {");
                sb.AppendLine($"                var jobPtr = ({jobTypeFullName}*)context;");

                string batchArgs = BuildBatchCallArgs(jobStruct, "jobPtr");
                string batchArgsWithComma = string.IsNullOrEmpty(batchArgs) ? "" : ", " + batchArgs;
                if (hasMultiVersion)
                {
                    // 生成所有 2^n 个 bool 组合的 if-else 链，与 C++ 端命名一致
                    int totalVariants = 1 << boolFields.Count;
                    var boolVarNames = boolFields.Select(f => $"jobPtr->{f.Name}").ToList();

                    for (int mask = 0; mask < totalVariants; mask++)
                    {
                        var values = new List<bool>();
                        for (int i = 0; i < boolFields.Count; i++)
                            values.Add((mask & (1 << i)) != 0);

                        string suffix = "_" + string.Join("_", values.Select(v => v ? "true" : "false"));

                        bool isLast = (mask == totalVariants - 1);
                        if (mask == 0)
                        {
                            string condition = string.Join(" && ", boolFields.Select((f, i) => values[i] ? $"jobPtr->{f.Name}" : $"!jobPtr->{f.Name}"));
                            sb.AppendLine($"                if ({condition})");
                        }
                        else if (!isLast)
                        {
                            string condition = string.Join(" && ", boolFields.Select((f, i) => values[i] ? $"jobPtr->{f.Name}" : $"!jobPtr->{f.Name}"));
                            sb.AppendLine($"                else if ({condition})");
                        }
                        else
                        {
                            sb.AppendLine("                else");
                        }

                        sb.AppendLine($"                    {jobStruct.Name}_Execute_Batch{suffix}{mtSuffix}(startIndex, count{batchArgsWithComma});");
                    }
                }
                else
                {
                    sb.AppendLine($"                {jobStruct.Name}_Execute_Batch{mtSuffix}(startIndex, count{batchArgsWithComma});");
                }
                sb.AppendLine("            };");
                sb.AppendLine($"            s_{jobStruct.Name}_BatchFuncPtr = Marshal.GetFunctionPointerForDelegate(s_{jobStruct.Name}_BatchFunc);");
                }
                else
                {
                    // 非 MT：调度器直接调原生 _Execute_Adapter(context,start,count)（原生→原生），
                    // 消除托管 BatchFunc delegate 的 原生→托管→原生 双重转换（每 tile ~3μs 开销）。
                    // 原生 Adapter 由 CppJobGenerator 生成：同一套字段偏移解包 / UnsafeList 写回 / bool 变体分派。
                    sb.AppendLine($"            s_{jobStruct.Name}_BatchFuncPtr = Get_{jobStruct.Name}_Execute_AdapterPtr();");
                }
            }
            else
            {
                sb.AppendLine($"            s_{jobStruct.Name}_JobFunc = (IntPtr context) =>");
                sb.AppendLine("            {");
                sb.AppendLine($"                var jobPtr = ({jobTypeFullName}*)context;");
                var args = BuildJobExecuteArgsForPointer(jobStruct);
                sb.AppendLine($"                {jobStruct.Name}_Execute({string.Join(", ", args)});");
                sb.AppendLine("            };");
                sb.AppendLine($"            s_{jobStruct.Name}_JobFuncPtr = Marshal.GetFunctionPointerForDelegate(s_{jobStruct.Name}_JobFunc);");
            }

            sb.AppendLine($"            s_{jobStruct.Name}_CleanupFunc = (IntPtr context) =>");
            sb.AppendLine("            {");
            sb.AppendLine("                Marshal.FreeHGlobal(context);");
            sb.AppendLine("            };");
            sb.AppendLine($"            s_{jobStruct.Name}_CleanupFuncPtr = Marshal.GetFunctionPointerForDelegate(s_{jobStruct.Name}_CleanupFunc);");
            sb.AppendLine();
        }

        private static void GenerateJobDllImport(StringBuilder sb, INamedTypeSymbol jobStruct, Compilation compilation)
        {
            bool isChunk = CppJobGenerator.IsChunkScheduledJob(jobStruct);
            bool isParallelFor = CppJobGenerator.IsParallelForJob(jobStruct);
            bool isFor = CppJobGenerator.IsForJob(jobStruct);

            var attrSymbol = compilation.GetTypeByMetadataName("NativeTranspiler.NativeTranspileAttribute");
            bool useMT = HasUseISPC_MT(jobStruct, attrSymbol);

            if (isChunk)
            {
                if (CppJobGenerator.IsEntityJob(jobStruct))
                {
                    // IJobEntity 统一走 Chunk 级调度
                    var getterName = CppJobGenerator.GetAdapterPtrGetterName(jobStruct);
                    var rangeGetterName = CppJobGenerator.GetRangeAdapterPtrGetterName(jobStruct);
                    sb.AppendLine($"        [DllImport(\"{NativeLibraryName}\", EntryPoint = \"{getterName}\", CallingConvention = CallingConvention.Cdecl)]");
                    sb.AppendLine($"        private static extern IntPtr Get_{jobStruct.Name}_ChunkAdapterPtr();");
                    sb.AppendLine($"        [DllImport(\"{NativeLibraryName}\", EntryPoint = \"{rangeGetterName}\", CallingConvention = CallingConvention.Cdecl)]");
                    sb.AppendLine($"        private static extern IntPtr Get_{jobStruct.Name}_ChunkRangeAdapterPtr();");
                }
                else
                {
                    var getterName = CppJobGenerator.GetAdapterPtrGetterName(jobStruct);
                    var rangeGetterName = CppJobGenerator.GetRangeAdapterPtrGetterName(jobStruct);
                    var entityBatchGetterName = CppJobGenerator.GetEntityBatchAdapterPtrGetterName(jobStruct);
                    sb.AppendLine($"        [DllImport(\"{NativeLibraryName}\", EntryPoint = \"{getterName}\", CallingConvention = CallingConvention.Cdecl)]");
                    sb.AppendLine($"        private static extern IntPtr Get_{jobStruct.Name}_ChunkAdapterPtr();");
                    sb.AppendLine($"        [DllImport(\"{NativeLibraryName}\", EntryPoint = \"{rangeGetterName}\", CallingConvention = CallingConvention.Cdecl)]");
                    sb.AppendLine($"        private static extern IntPtr Get_{jobStruct.Name}_ChunkRangeAdapterPtr();");
                    var attrSym2 = AttributeHelper.GetAttributeSymbol(compilation);
                    bool isIspc2 = attrSym2 != null && AttributeHelper.GetBackendTarget(jobStruct, attrSym2) == NativeTranspiler.BackendTarget.Ispc;
                    if (!isIspc2)
                    {
                        sb.AppendLine($"        [DllImport(\"{NativeLibraryName}\", EntryPoint = \"{entityBatchGetterName}\", CallingConvention = CallingConvention.Cdecl)]");
                        sb.AppendLine($"        private static extern IntPtr Get_{jobStruct.Name}_ChunkEntityBatchAdapterPtr();");
                    }
                }
            }
            else if (isParallelFor || isFor)
            {
                var batchFuncName = CppJobGenerator.GetCppJobFunctionName(jobStruct, isBatch: true);
                var batchParams = BuildBatchJobDllImportParams(jobStruct);

                var executeMethod = jobStruct.GetMembers().OfType<IMethodSymbol>().First(m => m.Name == "Execute");
                var methodSyntax = SymbolHelper.GetMethodSyntax(executeMethod);
                bool hasMultiVersion = false;
                if (methodSyntax != null)
                {
                    var semanticModel = compilation.GetSemanticModel(methodSyntax.SyntaxTree);
                    var conditionalFields = NativeTranspileValidator.GetConditionalReadOnlyFields(jobStruct, semanticModel);
                    hasMultiVersion = conditionalFields.Any(f => f.Type.SpecialType == SpecialType.System_Boolean);
                }

                if (hasMultiVersion)
                {
                    sb.AppendLine($"        [DllImport(\"{NativeLibraryName}\", EntryPoint = \"{batchFuncName}_true\", CallingConvention = CallingConvention.Cdecl)]");
                    sb.AppendLine($"        public static extern void {jobStruct.Name}_Execute_Batch_true({string.Join(", ", batchParams)});");
                    sb.AppendLine($"        [DllImport(\"{NativeLibraryName}\", EntryPoint = \"{batchFuncName}_false\", CallingConvention = CallingConvention.Cdecl)]");
                    sb.AppendLine($"        public static extern void {jobStruct.Name}_Execute_Batch_false({string.Join(", ", batchParams)});");
                }
                else
                {
                    sb.AppendLine($"        [DllImport(\"{NativeLibraryName}\", EntryPoint = \"{batchFuncName}\", CallingConvention = CallingConvention.Cdecl)]");
                    sb.AppendLine($"        public static extern void {jobStruct.Name}_Execute_Batch({string.Join(", ", batchParams)});");
                }

                if (useMT)
                {
                    if (hasMultiVersion)
                    {
                        sb.AppendLine($"        [DllImport(\"{NativeLibraryName}\", EntryPoint = \"{batchFuncName}_true_mt\", CallingConvention = CallingConvention.Cdecl)]");
                        sb.AppendLine($"        private static extern void {jobStruct.Name}_Execute_Batch_true_mt({string.Join(", ", batchParams)});");
                        sb.AppendLine($"        [DllImport(\"{NativeLibraryName}\", EntryPoint = \"{batchFuncName}_false_mt\", CallingConvention = CallingConvention.Cdecl)]");
                        sb.AppendLine($"        private static extern void {jobStruct.Name}_Execute_Batch_false_mt({string.Join(", ", batchParams)});");
                    }
                    else
                    {
                        sb.AppendLine($"        [DllImport(\"{NativeLibraryName}\", EntryPoint = \"{batchFuncName}_mt\", CallingConvention = CallingConvention.Cdecl)]");
                        sb.AppendLine($"        private static extern void {jobStruct.Name}_Execute_Batch_mt({string.Join(", ", batchParams)});");
                    }
                }
                else
                {
                    // 非 MT：声明原生 Adapter 指针 Getter（调度器原生→原生直调路径）
                    var adapterGetterName = CppJobGenerator.GetAdapterPtrGetterName(jobStruct);
                    sb.AppendLine($"        [DllImport(\"{NativeLibraryName}\", EntryPoint = \"{adapterGetterName}\", CallingConvention = CallingConvention.Cdecl)]");
                    sb.AppendLine($"        private static extern IntPtr Get_{jobStruct.Name}_Execute_AdapterPtr();");
                }
            }
            else
            {
                var singleFuncName = CppJobGenerator.GetCppJobFunctionName(jobStruct);
                var singleParams = BuildJobDllImportParams(jobStruct);
                sb.AppendLine($"        [DllImport(\"{NativeLibraryName}\", EntryPoint = \"{singleFuncName}\", CallingConvention = CallingConvention.Cdecl)]");
                sb.AppendLine($"        public static extern void {jobStruct.Name}_Execute({string.Join(", ", singleParams)});");
            }
            sb.AppendLine();
        }

        // ---------- Job Schedule 方法 ----------
        private static void GenerateJobScheduleMethod(StringBuilder sb, INamedTypeSymbol jobStruct, Compilation compilation)
        {
            bool isChunk = CppJobGenerator.IsChunkScheduledJob(jobStruct);
            bool isParallelFor = CppJobGenerator.IsParallelForJob(jobStruct);
            bool isFor = CppJobGenerator.IsForJob(jobStruct);
            string jobTypeName = jobStruct.ToDisplayString();

            var attrSymbol = compilation.GetTypeByMetadataName("NativeTranspiler.NativeTranspileAttribute");
            bool useMT = HasUseISPC_MT(jobStruct, attrSymbol);

            var parameters = new List<string>();
            // Use 'ref' for the internal Schedule_XXX method (caller already has a reference)
            parameters.Add($"ref {jobTypeName} job");
            if (isChunk)
            {
                parameters.Add("QueryBuilder query");
            }
            else if (isParallelFor || isFor)
            {
                parameters.Add("int arrayLength");
                // IJobFor 也允许指定 innerBatchCount，保持接口统一
                parameters.Add("int innerBatchCount = 0");
            }
            parameters.Add("JobHandle dependsOn = default");

            sb.AppendLine($"        public static JobHandle Schedule_{jobStruct.Name}({string.Join(", ", parameters)})");
            sb.AppendLine("        {");
            if (!isChunk)
            {
                sb.AppendLine($"            int size = sizeof({jobTypeName});");
                sb.AppendLine($"            IntPtr nativePtr = Marshal.AllocHGlobal(size);");
                sb.AppendLine($"            void* originalPtr = Unsafe.AsPointer(ref job);");
                sb.AppendLine($"            Unsafe.CopyBlockUnaligned((void*)nativePtr, originalPtr, (uint)size);");
                sb.AppendLine();
            }

            if (isChunk)
            {
                sb.AppendLine("            var world = World.DefaultWorld ?? throw new InvalidOperationException(\"No active World found.\");");
                // 所有 native IJobChunk 走 EntityBatch 路径（Unity 风格），
                // 使用 EntityBatchData 替代 ChunkJobData，消除 requiredComponentArrays 间接层
                string funcPtrName;
                string extraArgs;
                string scheduleMethod;
                if (CppJobGenerator.IsEntityJob(jobStruct))
                {
                    // IJobEntity 统一走 Chunk 级 range 调度
                    scheduleMethod = "ScheduleChunkRangeRaw";
                    funcPtrName = $"s_{jobStruct.Name}_ChunkRangeFuncPtr";
                    extraArgs = "";
                }
                else
                {
                    var attrSym3 = AttributeHelper.GetAttributeSymbol(compilation);
                    bool isIspc3 = attrSym3 != null && AttributeHelper.GetBackendTarget(jobStruct, attrSym3) == NativeTranspiler.BackendTarget.Ispc;
                    if (isIspc3)
                    {
                        scheduleMethod = "ScheduleChunkRangeRaw";
                        funcPtrName = $"s_{jobStruct.Name}_ChunkRangeFuncPtr";
                        extraArgs = "";
                    }
                    else
                    {
                        scheduleMethod = "ScheduleChunkEntityBatchRawWithWorkerCapAndRangeSize";
                        funcPtrName = $"s_{jobStruct.Name}_ChunkEntityBatchFuncPtr";
                        extraArgs = $", 0, 0";
                    }
                }
                sb.AppendLine($"            NativeJobHandle nativeHandle = NativeJobScheduler.{scheduleMethod}(");
                sb.AppendLine($"                ref job, world.EntityManager, query, {funcPtrName}, s_{jobStruct.Name}_RequiredComponentTypeIds{extraArgs}, dependsOn._nativeHandle);");
                sb.AppendLine($"            return new JobHandle(nativeHandle);");
            }
            else if (isParallelFor || isFor)
            {
                // 自适应批次大小
                if (useMT)
                {
                    sb.AppendLine($"            int actualBatchSize = innerBatchCount > 0 ? innerBatchCount : arrayLength;");
                }
                else
                {
                    // 0 = 直通原生 ResolveChunkSize（tiles/worker 通用化粒度），与托管 IJobParallelFor 一致；
                    // >0 显式 batch 原样传。旧的 32*ProcessorCount 硬编码默认会绕过 tiles/worker 调优，
                    // 使 transpiled job 与托管 job 粒度不一致（GridSearch A/B 已验证：非 MT job 走 ResolveChunkSize 更优）。
                    sb.AppendLine($"            int actualBatchSize = innerBatchCount;");
                }

                sb.AppendLine($"            NativeJobHandle nativeHandle = NativeJobScheduler.ScheduleParallelForBatchRaw(");
                sb.AppendLine($"                s_{jobStruct.Name}_BatchFuncPtr, nativePtr, s_{jobStruct.Name}_CleanupFuncPtr, arrayLength, actualBatchSize, dependsOn._nativeHandle);");
                sb.AppendLine($"            return new JobHandle(nativeHandle);");
            }
            else
            {
                sb.AppendLine($"            NativeJobHandle nativeHandle = NativeJobScheduler.ScheduleRaw(");
                sb.AppendLine($"                s_{jobStruct.Name}_JobFuncPtr, nativePtr, s_{jobStruct.Name}_CleanupFuncPtr, dependsOn._nativeHandle);");
                sb.AppendLine($"            return new JobHandle(nativeHandle);");
            }
            sb.AppendLine("        }");
            sb.AppendLine();

            if (isChunk)
            {
                // 确定 ISPC 状态（ScheduleWithWorkerCap 和 ScheduleWithWorkerCapAndRangeSize 共用）
                var attrSymCap = AttributeHelper.GetAttributeSymbol(compilation);
                bool isIspcCap = attrSymCap != null && AttributeHelper.GetBackendTarget(jobStruct, attrSymCap) == NativeTranspiler.BackendTarget.Ispc;

                if (isIspcCap)
                {
                    // ISPC entity jobs use EntityBatch, ISPC chunk jobs use fallback
                    bool isEntityJob = CppJobGenerator.IsEntityJob(jobStruct);
                    // IJobEntity ISPC 使用 chunk 级 range 调度
                    string ispcFuncPtr;
                    string ispcScheduleMethod;
                    if (isEntityJob)
                    {
                        ispcFuncPtr = $"s_{jobStruct.Name}_ChunkRangeFuncPtr";
                        ispcScheduleMethod = "ScheduleChunkRangeRaw";
                    }
                    else
                    {
                        ispcFuncPtr = $"s_{jobStruct.Name}_ChunkFuncPtr";
                        ispcScheduleMethod = "ScheduleChunkRawWithWorkerCap";
                    }

                    sb.AppendLine($"        public static JobHandle ScheduleWithWorkerCap_{jobStruct.Name}(ref {jobTypeName} job, QueryBuilder query, int workerCap, JobHandle dependsOn = default)");
                    sb.AppendLine("        {");
                    sb.AppendLine("            var world = World.DefaultWorld ?? throw new InvalidOperationException(\"No active World found.\");");
                    sb.AppendLine($"            NativeJobHandle nativeHandle = NativeJobScheduler.{ispcScheduleMethod}(");
                    sb.AppendLine(isEntityJob
                        ? $"                ref job, world.EntityManager, query, {ispcFuncPtr}, s_{jobStruct.Name}_RequiredComponentTypeIds, dependsOn._nativeHandle);"
                        : $"                ref job, world.EntityManager, query, {ispcFuncPtr}, s_{jobStruct.Name}_RequiredComponentTypeIds, {(useMT ? "1" : "workerCap")}, dependsOn._nativeHandle);");
                    sb.AppendLine($"            return new JobHandle(nativeHandle);");
                    sb.AppendLine("        }");
                    sb.AppendLine();

                    // ScheduleChunkRawWithWorkerCapAndRangeSize for chunk ISPC, EntityBatch for entity ISPC
                    string ispcScheduleMethod2 = isEntityJob ? "ScheduleChunkRangeRaw" : "ScheduleChunkRawWithWorkerCapAndRangeSize";
                    sb.AppendLine($"        public static JobHandle ScheduleWithWorkerCapAndRangeSize_{jobStruct.Name}(ref {jobTypeName} job, QueryBuilder query, int workerCap, int rangeSize, JobHandle dependsOn = default)");
                    sb.AppendLine("        {");
                    sb.AppendLine("            var world = World.DefaultWorld ?? throw new InvalidOperationException(\"No active World found.\");");
                    sb.AppendLine($"            NativeJobHandle nativeHandle = NativeJobScheduler.{ispcScheduleMethod2}(");
                    sb.AppendLine(isEntityJob
                        ? $"                ref job, world.EntityManager, query, {ispcFuncPtr}, s_{jobStruct.Name}_RequiredComponentTypeIds, dependsOn._nativeHandle);"
                        : $"                ref job, world.EntityManager, query, {ispcFuncPtr}, s_{jobStruct.Name}_RequiredComponentTypeIds, {(useMT ? "1, int.MaxValue" : "workerCap, rangeSize")}, dependsOn._nativeHandle);");
                    sb.AppendLine($"            return new JobHandle(nativeHandle);");
                    sb.AppendLine("        }");
                    sb.AppendLine();
                }
                else
                {
                    string capFuncPtr = CppJobGenerator.IsEntityJob(jobStruct)
                        ? $"s_{jobStruct.Name}_ChunkRangeFuncPtr"
                        : $"s_{jobStruct.Name}_ChunkEntityBatchFuncPtr";
                    string capMethod = CppJobGenerator.IsEntityJob(jobStruct)
                        ? "ScheduleEntityRangeRawWithWorkerCapAndRangeSize"
                        : "ScheduleChunkEntityBatchRawWithWorkerCapAndRangeSize";

                    sb.AppendLine($"        public static JobHandle ScheduleWithWorkerCap_{jobStruct.Name}(ref {jobTypeName} job, QueryBuilder query, int workerCap, JobHandle dependsOn = default)");
                    sb.AppendLine("        {");
                    sb.AppendLine("            var world = World.DefaultWorld ?? throw new InvalidOperationException(\"No active World found.\");");
                    sb.AppendLine($"            NativeJobHandle nativeHandle = NativeJobScheduler.{capMethod}(");
                    sb.AppendLine($"                ref job, world.EntityManager, query, {capFuncPtr}, s_{jobStruct.Name}_RequiredComponentTypeIds, workerCap, 0, dependsOn._nativeHandle);");
                    sb.AppendLine($"            return new JobHandle(nativeHandle);");
                    sb.AppendLine("        }");
                    sb.AppendLine();

                    sb.AppendLine($"        public static JobHandle ScheduleWithWorkerCapAndRangeSize_{jobStruct.Name}(ref {jobTypeName} job, QueryBuilder query, int workerCap, int rangeSize, JobHandle dependsOn = default)");
                    sb.AppendLine("        {");
                    sb.AppendLine("            var world = World.DefaultWorld ?? throw new InvalidOperationException(\"No active World found.\");");
                    sb.AppendLine($"            NativeJobHandle nativeHandle = NativeJobScheduler.{capMethod}(");
                    sb.AppendLine($"                ref job, world.EntityManager, query, {capFuncPtr}, s_{jobStruct.Name}_RequiredComponentTypeIds, workerCap, rangeSize, dependsOn._nativeHandle);");
                    sb.AppendLine($"            return new JobHandle(nativeHandle);");
                    sb.AppendLine("        }");
                    sb.AppendLine();
                }

                sb.AppendLine($"        public static void RunImmediate_{jobStruct.Name}(ref {jobTypeName} job, QueryBuilder query)");
                sb.AppendLine("        {");
                sb.AppendLine($"            Schedule_{jobStruct.Name}(ref job, query, default).Complete();");
                sb.AppendLine("        }");
                sb.AppendLine();
            }
        }

        private static string BuildRequiredComponentTypeIdsInitializer(IEnumerable<INamedTypeSymbol> requiredTypes)
        {
            var ids = string.Join(", ", requiredTypes.Select(t => $"ComponentTypeManager.GetComponentType(typeof({t.ToDisplayString(SymbolDisplayFormat.FullyQualifiedFormat)})).Id"));
            return string.IsNullOrWhiteSpace(ids) ? "Array.Empty<int>()" : $"new int[] {{ {ids} }}";
        }

        // ---------- 辅助：构建参数列表 ----------
        private static List<string> BuildMethodDllImportParams(IMethodSymbol method)
        {
            var parameters = new List<string>();
            foreach (var param in method.Parameters)
            {
                if (NativeTranspiler.IsEntJoyNativeContainerType(param.Type))
                {
                    if (param.Type.Name == "NativeList")
                    {
                        var elementType = ((INamedTypeSymbol)param.Type).TypeArguments[0];
                        var csElementType = elementType.ToDisplayString(SymbolDisplayFormat.FullyQualifiedFormat);
                        parameters.Add($"EntJoy.Collections.UnsafeList<{csElementType}>* {param.Name}_listData");
                    }
                    else
                    {
                        var elementType = ((INamedTypeSymbol)param.Type).TypeArguments[0];
                        var csElementType = elementType.ToDisplayString(SymbolDisplayFormat.FullyQualifiedFormat);
                        parameters.Add($"{csElementType}* {param.Name}_ptr, int {param.Name}_length");
                    }
                }
                else if (param.Type is IPointerTypeSymbol)
                {
                    var cppType = NativeTranspiler.MapCSharpTypeToCpp(param.Type);  // 返回 "int*"
                    parameters.Add($"{cppType} {param.Name}_ptr");
                }
                else
                {
                    var csType = param.Type.ToDisplayString(SymbolDisplayFormat.FullyQualifiedFormat);
                    parameters.Add($"{csType}* {param.Name}_ptr");
                }
            }
            return parameters;
        }

        private static List<string> BuildMethodCallArgs(IMethodSymbol method)
        {
            var args = new List<string>();
            foreach (var param in method.Parameters)
            {
                if (NativeTranspiler.IsEntJoyNativeContainerType(param.Type))
                {
                    if (param.Type.Name == "NativeList")
                    {
                        args.Add($"{param.Name}.GetListData()");
                    }
                    else
                    {
                        var elementType = ((INamedTypeSymbol)param.Type).TypeArguments[0];
                        var csElementType = elementType.ToDisplayString(SymbolDisplayFormat.FullyQualifiedFormat);
                        args.Add($"({csElementType}*){param.Name}.GetUnsafePtr(), {param.Name}.Length");
                    }
                }
                else if (param.Type is IPointerTypeSymbol)
                {
                    args.Add(param.Name);
                }
                else
                {
                    var csType = param.Type.ToDisplayString(SymbolDisplayFormat.FullyQualifiedFormat);
                    args.Add($"({csType}*)Unsafe.AsPointer(ref {param.Name})");
                }
            }
            return args;
        }

        private static List<string> BuildJobDllImportParams(INamedTypeSymbol jobStruct)
        {
            var parameters = new List<string>();
            var executeMethod = jobStruct.GetMembers().OfType<IMethodSymbol>().First(m => m.Name == "Execute");
            if (executeMethod.Parameters.Length == 1 && executeMethod.Parameters[0].Type.SpecialType == SpecialType.System_Int32)
                parameters.Add($"int {executeMethod.Parameters[0].Name}");

            AppendFieldDllImportParams(jobStruct, parameters);
            return parameters;
        }

        private static List<string> BuildBatchJobDllImportParams(INamedTypeSymbol jobStruct)
        {
            var parameters = new List<string> { "int __startIndex", "int __count" };
            AppendFieldDllImportParams(jobStruct, parameters);
            return parameters;
        }

        private static void AppendFieldDllImportParams(INamedTypeSymbol jobStruct, List<string> parameters)
        {
            foreach (var field in jobStruct.GetMembers().OfType<IFieldSymbol>().Where(f => !f.IsStatic))
            {
                if (NativeTranspiler.IsEntJoyNativeContainerType(field.Type))
                {
                    if (field.Type.Name == "NativeList")
                    {
                        var elementType = ((INamedTypeSymbol)field.Type).TypeArguments[0];
                        var csElementType = elementType.ToDisplayString(SymbolDisplayFormat.FullyQualifiedFormat);
                        parameters.Add($"EntJoy.Collections.UnsafeList<{csElementType}>* {field.Name}_listData");
                    }
                    else
                    {
                        var elementType = ((INamedTypeSymbol)field.Type).TypeArguments[0];
                        var csElementType = elementType.ToDisplayString(SymbolDisplayFormat.FullyQualifiedFormat);
                        parameters.Add($"{csElementType}* {field.Name}_ptr, int {field.Name}_length");
                    }
                }
                else if (field.Type is IPointerTypeSymbol)
                {
                    var cppType = NativeTranspiler.MapCSharpTypeToCpp(field.Type);  // 返回 "int*"
                    parameters.Add($"{cppType} {field.Name}_ptr");
                }
                else
                {
                    var csType = field.Type.ToDisplayString(SymbolDisplayFormat.FullyQualifiedFormat);
                    parameters.Add($"{csType}* {field.Name}_ptr");
                }
            }
        }

        private static List<string> BuildJobExecuteArgsForPointer(INamedTypeSymbol jobStruct)
        {
            var args = new List<string>();
            foreach (var field in jobStruct.GetMembers().OfType<IFieldSymbol>().Where(f => !f.IsStatic))
            {
                if (NativeTranspiler.IsEntJoyNativeContainerType(field.Type))
                {
                    if (field.Type.Name == "NativeList")
                    {
                        args.Add($"jobPtr->{field.Name}.GetListData()");
                    }
                    else
                    {
                        var elementType = ((INamedTypeSymbol)field.Type).TypeArguments[0];
                        var csElementType = elementType.ToDisplayString(SymbolDisplayFormat.FullyQualifiedFormat);
                        args.Add($"({csElementType}*)jobPtr->{field.Name}.GetUnsafePtr(), jobPtr->{field.Name}.Length");
                    }
                }
                else
                {
                    if (field.Type is IPointerTypeSymbol)
                        args.Add($"jobPtr->{field.Name}");
                    else
                        args.Add($"&jobPtr->{field.Name}");
                }
            }
            return args;
        }

        private static string BuildBatchCallArgs(INamedTypeSymbol jobStruct, string jobPtrPrefix)
        {
            var args = new List<string>();
            foreach (var field in jobStruct.GetMembers().OfType<IFieldSymbol>().Where(f => !f.IsStatic))
            {
                if (NativeTranspiler.IsEntJoyNativeContainerType(field.Type))
                {
                    if (field.Type.Name == "NativeList")
                        args.Add($"{jobPtrPrefix}->{field.Name}.GetListData()");
                    else
                    {
                        var elementType = ((INamedTypeSymbol)field.Type).TypeArguments[0];
                        var csElementType = elementType.ToDisplayString(SymbolDisplayFormat.FullyQualifiedFormat);
                        args.Add($"({csElementType}*){jobPtrPrefix}->{field.Name}.GetUnsafePtr(), {jobPtrPrefix}->{field.Name}.Length");
                    }
                }
                else if (field.Type is IPointerTypeSymbol)
                {
                    args.Add($"{jobPtrPrefix}->{field.Name}");
                }
                else
                {
                    args.Add($"&{jobPtrPrefix}->{field.Name}");
                }
            }
            return string.Join(", ", args);
        }

        private static void GenerateJobExtensionMethod(StringBuilder sb, INamedTypeSymbol jobStruct)
        {
            bool isChunk = CppJobGenerator.IsChunkScheduledJob(jobStruct);
            bool isParallelFor = CppJobGenerator.IsParallelForJob(jobStruct);
            bool isFor = CppJobGenerator.IsForJob(jobStruct);
            string jobTypeName = jobStruct.ToDisplayString();

            if (isChunk)
            {
                sb.AppendLine($"    public static JobHandle Schedule(this {jobTypeName} job, QueryBuilder query, JobHandle dependsOn = default)");
                sb.AppendLine("    {");
                sb.AppendLine($"        return NativeTranspiler.Bindings.NativeExports.Schedule_{jobStruct.Name}(ref job, query, dependsOn);");
                sb.AppendLine("    }");
                sb.AppendLine();
                sb.AppendLine($"    public static JobHandle ScheduleWithWorkerCap(this {jobTypeName} job, QueryBuilder query, int workerCap, JobHandle dependsOn = default)");
                sb.AppendLine("    {");
                sb.AppendLine($"        return NativeTranspiler.Bindings.NativeExports.ScheduleWithWorkerCap_{jobStruct.Name}(ref job, query, workerCap, dependsOn);");
                sb.AppendLine("    }");
                sb.AppendLine();
                sb.AppendLine($"    public static JobHandle ScheduleWithWorkerCapAndRangeSize(this {jobTypeName} job, QueryBuilder query, int workerCap, int rangeSize, JobHandle dependsOn = default)");
                sb.AppendLine("    {");
                sb.AppendLine($"        return NativeTranspiler.Bindings.NativeExports.ScheduleWithWorkerCapAndRangeSize_{jobStruct.Name}(ref job, query, workerCap, rangeSize, dependsOn);");
                sb.AppendLine("    }");
                sb.AppendLine();
                sb.AppendLine($"    public static void RunImmediate(this {jobTypeName} job, QueryBuilder query)");
                sb.AppendLine("    {");
                sb.AppendLine($"        NativeTranspiler.Bindings.NativeExports.RunImmediate_{jobStruct.Name}(ref job, query);");
                sb.AppendLine("    }");
                sb.AppendLine();
            }
            else if (isParallelFor || isFor)
            {
                // ParallelFor/For: keep optional dependsOn (existing generic Schedule<T> has arrayLength params, no collision)
                var parameters = new List<string>
                {
                    $"this {jobTypeName} job",
                    "int arrayLength",
                    "int innerBatchCount = 0",
                    "JobHandle dependsOn = default"
                };
                sb.AppendLine($"    public static JobHandle Schedule({string.Join(", ", parameters)})");
                sb.AppendLine("    {");
                sb.AppendLine($"        return NativeTranspiler.Bindings.NativeExports.Schedule_{jobStruct.Name}(ref job, arrayLength, innerBatchCount, dependsOn);");
                sb.AppendLine("    }");
                sb.AppendLine();
            }
            else
            {
                // IJob: generate two overloads (no-arg and dependsOn) to beat existing Schedule<T>(this T job)
                sb.AppendLine($"    public static JobHandle Schedule(this {jobTypeName} job)");
                sb.AppendLine("    {");
                sb.AppendLine($"        return NativeTranspiler.Bindings.NativeExports.Schedule_{jobStruct.Name}(ref job, default);");
                sb.AppendLine("    }");
                sb.AppendLine();
                sb.AppendLine($"    public static JobHandle Schedule(this {jobTypeName} job, JobHandle dependsOn)");
                sb.AppendLine("    {");
                sb.AppendLine($"        return NativeTranspiler.Bindings.NativeExports.Schedule_{jobStruct.Name}(ref job, dependsOn);");
                sb.AppendLine("    }");
                sb.AppendLine();
            }
        }

        private static void GenerateJobRunMethod(StringBuilder sb, INamedTypeSymbol jobStruct, Compilation compilation)
        {
            bool isChunk = CppJobGenerator.IsChunkScheduledJob(jobStruct);
            bool isParallelFor = CppJobGenerator.IsParallelForJob(jobStruct);
            bool isFor = CppJobGenerator.IsForJob(jobStruct);
            string jobTypeName = jobStruct.ToDisplayString();

            var parameters = new List<string>();
            // Must match existing JobExtensions signature (this T job) to take precedence in overload resolution
            parameters.Add($"this {jobTypeName} job");
            if (isChunk)
            {
                parameters.Add("QueryBuilder query");
            }
            else if (isParallelFor || isFor)
            {
                parameters.Add("int arrayLength");
            }

            sb.AppendLine($"    public static void Run({string.Join(", ", parameters)})");
            sb.AppendLine("    {");
            if (isChunk)
            {
                sb.AppendLine($"        NativeTranspiler.Bindings.NativeExports.Schedule_{jobStruct.Name}(ref job, query, default).Complete();");
            }
            else if (isParallelFor || isFor)
            {
                sb.AppendLine($"        int startIndex = 0;");
                sb.AppendLine($"        int count = arrayLength;");
                sb.AppendLine($"        unsafe");
                sb.AppendLine($"        {{");
                sb.AppendLine($"            {jobTypeName}* jobPtr = &job;");
                sb.AppendLine($"            {{");

                var executeMethod = jobStruct.GetMembers().OfType<IMethodSymbol>().First(m => m.Name == "Execute");
                var methodSyntax = SymbolHelper.GetMethodSyntax(executeMethod);
                bool hasMultiVersion = false;
                string boolFieldName = null;
                if (methodSyntax != null)
                {
                    var semanticModel = compilation.GetSemanticModel(methodSyntax.SyntaxTree);
                    var conditionalFields = NativeTranspileValidator.GetConditionalReadOnlyFields(jobStruct, semanticModel);
                    var boolField = conditionalFields.FirstOrDefault(f => f.Type.SpecialType == SpecialType.System_Boolean);
                    if (boolField != null)
                    {
                        hasMultiVersion = true;
                        boolFieldName = boolField.Name;
                    }
                }

                string batchArgs2 = BuildBatchCallArgs(jobStruct, "jobPtr");
                string batchArgsWithComma2 = string.IsNullOrEmpty(batchArgs2) ? "" : ", " + batchArgs2;
                if (hasMultiVersion)
                {
                    sb.AppendLine($"                if (jobPtr->{boolFieldName})");
                    sb.AppendLine($"                    NativeTranspiler.Bindings.NativeExports.{jobStruct.Name}_Execute_Batch_true(startIndex, count{batchArgsWithComma2});");
                    sb.AppendLine($"                else");
                    sb.AppendLine($"                    NativeTranspiler.Bindings.NativeExports.{jobStruct.Name}_Execute_Batch_false(startIndex, count{batchArgsWithComma2});");
                }
                else
                {
                    sb.AppendLine($"                NativeTranspiler.Bindings.NativeExports.{jobStruct.Name}_Execute_Batch(startIndex, count{batchArgsWithComma2});");
                }
                sb.AppendLine($"            }}");
                sb.AppendLine($"        }}");
            }
            else
            {
                sb.AppendLine($"        unsafe");
                sb.AppendLine($"        {{");
                sb.AppendLine($"            {jobTypeName}* jobPtr = &job;");
                sb.AppendLine($"            {{");
                var args = BuildJobExecuteArgsForFixed(jobStruct);
                sb.AppendLine($"                NativeTranspiler.Bindings.NativeExports.{jobStruct.Name}_Execute({string.Join(", ", args)});");
                sb.AppendLine($"            }}");
                sb.AppendLine($"        }}");
            }
            sb.AppendLine("    }");
            sb.AppendLine();
        }

        private static List<string> BuildJobExecuteArgsForFixed(INamedTypeSymbol jobStruct)
        {
            var args = new List<string>();
            foreach (var field in jobStruct.GetMembers().OfType<IFieldSymbol>().Where(f => !f.IsStatic))
            {
                if (NativeTranspiler.IsEntJoyNativeContainerType(field.Type))
                {
                    if (field.Type.Name == "NativeList")
                    {
                        args.Add($"jobPtr->{field.Name}.GetListData()");
                    }
                    else
                    {
                        var elementType = ((INamedTypeSymbol)field.Type).TypeArguments[0];
                        var csElementType = elementType.ToDisplayString(SymbolDisplayFormat.FullyQualifiedFormat);
                        args.Add($"({csElementType}*)jobPtr->{field.Name}.GetUnsafePtr(), jobPtr->{field.Name}.Length");
                    }
                }
                else
                {
                    if (field.Type is IPointerTypeSymbol)
                        args.Add($"jobPtr->{field.Name}");
                    else
                        args.Add($"&jobPtr->{field.Name}");
                }
            }
            return args;
        }

        private static string GetCSharpParameterType(IParameterSymbol param)
        {
            var typeName = param.Type.ToDisplayString(SymbolDisplayFormat.FullyQualifiedFormat);
            return param.RefKind switch
            {
                RefKind.Ref => "ref " + typeName,
                RefKind.In => "in " + typeName,
                RefKind.Out => "out " + typeName,
                _ => typeName
            };
        }

        private static string GenerateCleanupFactoryMethod()
        {
            return @"
        private static CleanupFuncDelegate CreateCleanup<T>(int size) where T : struct
        {
            return context =>
            {
                IntPtr native = (IntPtr)context;
                Marshal.FreeHGlobal(native);
            };
        }";
        }

        // ============================================================
        // GPU Job（BackendTarget.Gpu）：ScheduleGpu —— P/Invoke NativeDll GpuCompute_*
        // ============================================================

        private const string NativeLibraryNameGpu = "NativeDll";
        private const int GpuWorkgroupSize = 64;

        private static void GenerateGpuComputeDllImports(StringBuilder sb)
        {
            sb.AppendLine("        // ---- NativeDll GpuCompute_*（wgpu compute 后端，C++ 实现） ----");
            sb.AppendLine($"        [DllImport(\"{NativeLibraryNameGpu}\", EntryPoint = \"GpuCompute_Initialize\", CallingConvention = CallingConvention.Cdecl)]");
            sb.AppendLine("        internal static extern int GpuCompute_Initialize([MarshalAs(UnmanagedType.LPStr)] string wgpuDllPath);");
            sb.AppendLine($"        [DllImport(\"{NativeLibraryNameGpu}\", EntryPoint = \"GpuCompute_Shutdown\", CallingConvention = CallingConvention.Cdecl)]");
            sb.AppendLine("        internal static extern void GpuCompute_Shutdown();");
            sb.AppendLine($"        [DllImport(\"{NativeLibraryNameGpu}\", EntryPoint = \"GpuCompute_GetLastError\", CallingConvention = CallingConvention.Cdecl)]");
            sb.AppendLine("        internal static extern IntPtr GpuCompute_GetLastError();");
            sb.AppendLine($"        [DllImport(\"{NativeLibraryNameGpu}\", EntryPoint = \"GpuCompute_CreateKernel\", CallingConvention = CallingConvention.Cdecl)]");
            sb.AppendLine("        internal static extern IntPtr GpuCompute_CreateKernel([MarshalAs(UnmanagedType.LPStr)] string wgsl, int storageBindingCount, int hasUniform);");
            sb.AppendLine($"        [DllImport(\"{NativeLibraryNameGpu}\", EntryPoint = \"GpuCompute_ReleaseKernel\", CallingConvention = CallingConvention.Cdecl)]");
            sb.AppendLine("        internal static extern void GpuCompute_ReleaseKernel(IntPtr kernel);");
            sb.AppendLine($"        [DllImport(\"{NativeLibraryNameGpu}\", EntryPoint = \"GpuCompute_CreateStorageBuffer\", CallingConvention = CallingConvention.Cdecl)]");
            sb.AppendLine("        internal static extern IntPtr GpuCompute_CreateStorageBuffer(ulong size);");
            sb.AppendLine($"        [DllImport(\"{NativeLibraryNameGpu}\", EntryPoint = \"GpuCompute_CreateUniformBuffer\", CallingConvention = CallingConvention.Cdecl)]");
            sb.AppendLine("        internal static extern IntPtr GpuCompute_CreateUniformBuffer(ulong size);");
            sb.AppendLine($"        [DllImport(\"{NativeLibraryNameGpu}\", EntryPoint = \"GpuCompute_WriteBuffer\", CallingConvention = CallingConvention.Cdecl)]");
            sb.AppendLine("        internal static extern void GpuCompute_WriteBuffer(IntPtr buffer, IntPtr data, ulong size);");
            sb.AppendLine($"        [DllImport(\"{NativeLibraryNameGpu}\", EntryPoint = \"GpuCompute_ReleaseBuffer\", CallingConvention = CallingConvention.Cdecl)]");
            sb.AppendLine("        internal static extern void GpuCompute_ReleaseBuffer(IntPtr buffer);");
            sb.AppendLine($"        [DllImport(\"{NativeLibraryNameGpu}\", EntryPoint = \"GpuCompute_CreateBindGroup\", CallingConvention = CallingConvention.Cdecl)]");
            sb.AppendLine("        internal static extern IntPtr GpuCompute_CreateBindGroup(IntPtr kernel, IntPtr[] buffers, ulong[] sizes, int bufferCount);");
            sb.AppendLine($"        [DllImport(\"{NativeLibraryNameGpu}\", EntryPoint = \"GpuCompute_ReleaseBindGroup\", CallingConvention = CallingConvention.Cdecl)]");
            sb.AppendLine("        internal static extern void GpuCompute_ReleaseBindGroup(IntPtr group);");
            sb.AppendLine($"        [DllImport(\"{NativeLibraryNameGpu}\", EntryPoint = \"GpuCompute_Dispatch\", CallingConvention = CallingConvention.Cdecl)]");
            sb.AppendLine("        internal static extern void GpuCompute_Dispatch(IntPtr kernel, IntPtr bindGroup, uint workgroupX);");
            sb.AppendLine($"        [DllImport(\"{NativeLibraryNameGpu}\", EntryPoint = \"GpuCompute_Sync\", CallingConvention = CallingConvention.Cdecl)]");
            sb.AppendLine("        internal static extern void GpuCompute_Sync();");
            sb.AppendLine($"        [DllImport(\"{NativeLibraryNameGpu}\", EntryPoint = \"GpuCompute_ReadBack\", CallingConvention = CallingConvention.Cdecl)]");
            sb.AppendLine("        internal static extern int GpuCompute_ReadBack(IntPtr buffer, IntPtr outData, ulong size);");
            sb.AppendLine();
            sb.AppendLine("        internal static string GpuCompute_GetLastErrorText()");
            sb.AppendLine("        {");
            sb.AppendLine("            IntPtr p = GpuCompute_GetLastError();");
            sb.AppendLine("            return p == IntPtr.Zero ? null : Marshal.PtrToStringUTF8(p);");
            sb.AppendLine("        }");
            sb.AppendLine();
            sb.AppendLine("        /// <summary>GPU 运行时初始化（幂等；失败抛异常）</summary>");
            sb.AppendLine("        internal static void GpuCompute_EnsureInitialized()");
            sb.AppendLine("        {");
            sb.AppendLine("            if (GpuCompute_Initialize(\"wgpu_native.dll\") == 0)");
            sb.AppendLine("                throw new InvalidOperationException(\"GpuCompute_Initialize 失败: \" + GpuCompute_GetLastErrorText());");
            sb.AppendLine("        }");
            sb.AppendLine();
        }

        /// <summary>
        /// 为 GPU Job 生成 ScheduleGpu：
        ///   storage buffer 逐个创建+上传（NativeArray 指针直传，零拷贝）→ uniform 打包（标量字段序 + _count）→
        ///   bind group → dispatch(ceil(length/64)) → sync → 就地回读 → 释放。
        /// 同步执行（跨帧流水/脏同步属 GpuResidencyManager，后续叠加）。
        /// </summary>
        private static void GenerateGpuScheduleMethod(StringBuilder sb, INamedTypeSymbol jobStruct, Compilation compilation)
        {
            bool isIndexed = CppJobGenerator.IsParallelForJob(jobStruct) || CppJobGenerator.IsForJob(jobStruct);
            string jobTypeName = jobStruct.ToDisplayString();
            string wgsl = WgslGenerator.GenerateWgslSource(jobStruct, compilation);
            string wgslLiteral = "@\"" + wgsl.Replace("\"", "\"\"") + "\"";
            string kernelField = $"NativeTranspiler.Bindings.NativeExports.__gpuKernel_{jobStruct.Name}";

            var arrayFields = new List<IFieldSymbol>();
            var scalarFields = new List<IFieldSymbol>();
            foreach (var field in jobStruct.GetMembers().OfType<IFieldSymbol>().Where(f => !f.IsStatic))
            {
                if (NativeTranspiler.IsEntJoyNativeContainerType(field.Type)) arrayFields.Add(field);
                else scalarFields.Add(field);
            }

            string signature = isIndexed
                ? $"public static unsafe JobHandle ScheduleGpu(this {jobTypeName} job, int length)"
                : $"public static unsafe JobHandle ScheduleGpu(this {jobTypeName} job)";
            sb.AppendLine($"    {signature}");
            sb.AppendLine("    {");
            sb.AppendLine($"        NativeTranspiler.Bindings.NativeExports.GpuCompute_EnsureInitialized();");
            sb.AppendLine($"        const string __wgsl = {wgslLiteral};");
            sb.AppendLine($"        if ({kernelField} == IntPtr.Zero)");
            sb.AppendLine("        {");
            sb.AppendLine($"            {kernelField} = NativeTranspiler.Bindings.NativeExports.GpuCompute_CreateKernel(__wgsl, {arrayFields.Count}, {(scalarFields.Count > 0 || isIndexed ? 1 : 0)});");
            sb.AppendLine($"            if ({kernelField} == IntPtr.Zero)");
            sb.AppendLine("                throw new InvalidOperationException(\"GpuCompute_CreateKernel 失败（naga 拒绝 WGSL）: \" + NativeTranspiler.Bindings.NativeExports.GpuCompute_GetLastErrorText());");
            sb.AppendLine("        }");
            sb.AppendLine("        IntPtr __kernel = " + kernelField + ";");
            sb.AppendLine();
            sb.AppendLine("        try");
            sb.AppendLine("        {");

            // storage buffers：创建 + 上传
            foreach (var f in arrayFields)
            {
                int elemSize = GetGpuElementSize(((INamedTypeSymbol)f.Type).TypeArguments[0]);
                string sizeExpr = $"(ulong)(job.{f.Name}.Length * {elemSize})";
                sb.AppendLine($"            IntPtr __b_{f.Name} = NativeTranspiler.Bindings.NativeExports.GpuCompute_CreateStorageBuffer({sizeExpr});");
                sb.AppendLine($"            NativeTranspiler.Bindings.NativeExports.GpuCompute_WriteBuffer(__b_{f.Name}, (IntPtr)job.{f.Name}.GetUnsafePtr(), {sizeExpr});");
            }

            // uniform buffer：标量字段声明序 + _count
            int uniformSize = 0;
            foreach (var f in scalarFields) uniformSize += GetGpuScalarSize(f.Type);
            if (isIndexed) uniformSize += 4;
            if (uniformSize > 0)
            {
                sb.AppendLine($"            var __uni = new byte[{uniformSize}];");
                int offset = 0;
                foreach (var f in scalarFields)
                {
                    string conv = GetGpuScalarConv(f.Type, $"job.{f.Name}");
                    sb.AppendLine($"            BitConverter.GetBytes({conv}).CopyTo(__uni, {offset});");
                    offset += GetGpuScalarSize(f.Type);
                }
                if (isIndexed)
                {
                    sb.AppendLine($"            BitConverter.GetBytes(length).CopyTo(__uni, {offset});");
                }
                sb.AppendLine("            IntPtr __uniform = NativeTranspiler.Bindings.NativeExports.GpuCompute_CreateUniformBuffer((ulong)__uni.Length);");
                sb.AppendLine("            fixed (byte* __p = __uni)");
                sb.AppendLine("                NativeTranspiler.Bindings.NativeExports.GpuCompute_WriteBuffer(__uniform, (IntPtr)__p, (ulong)__uni.Length);");
            }

            // bind group
            sb.Append("            IntPtr[] __bufs = { ");
            bool firstBuf = true;
            foreach (var f in arrayFields)
            {
                if (!firstBuf) sb.Append(", ");
                sb.Append($"__b_{f.Name}"); firstBuf = false;
            }
            if (uniformSize > 0)
            {
                if (!firstBuf) sb.Append(", ");
                sb.Append("__uniform");
            }
            sb.AppendLine(" };");
            sb.Append("            ulong[] __sizes = { ");
            firstBuf = true;
            foreach (var f in arrayFields)
            {
                if (!firstBuf) sb.Append(", ");
                sb.Append($"(ulong)(job.{f.Name}.Length * {GetGpuElementSize(((INamedTypeSymbol)f.Type).TypeArguments[0])})");
                firstBuf = false;
            }
            if (uniformSize > 0)
            {
                if (!firstBuf) sb.Append(", ");
                sb.Append($"{(ulong)uniformSize}uL");
            }
            sb.AppendLine(" };");
            int bufCount = arrayFields.Count + (uniformSize > 0 ? 1 : 0);
            sb.AppendLine($"            IntPtr __bg = NativeTranspiler.Bindings.NativeExports.GpuCompute_CreateBindGroup(__kernel, __bufs, __sizes, {bufCount});");
            sb.AppendLine("            if (__bg == IntPtr.Zero)");
            sb.AppendLine("                throw new InvalidOperationException(\"GpuCompute_CreateBindGroup 失败\");");
            sb.AppendLine();

            // dispatch + sync
            if (isIndexed)
            {
                sb.AppendLine($"            uint __groups = (uint)((length + {GpuWorkgroupSize} - 1) / {GpuWorkgroupSize});");
                sb.AppendLine("            NativeTranspiler.Bindings.NativeExports.GpuCompute_Dispatch(__kernel, __bg, __groups);");
            }
            else
            {
                sb.AppendLine("            NativeTranspiler.Bindings.NativeExports.GpuCompute_Dispatch(__kernel, __bg, 1u);");
            }
            sb.AppendLine("            NativeTranspiler.Bindings.NativeExports.GpuCompute_Sync();");
            sb.AppendLine();

            // 就地回读（写回 NativeArray）
            foreach (var f in arrayFields)
            {
                int elemSize = GetGpuElementSize(((INamedTypeSymbol)f.Type).TypeArguments[0]);
                sb.AppendLine($"            NativeTranspiler.Bindings.NativeExports.GpuCompute_ReadBack(__b_{f.Name}, (IntPtr)job.{f.Name}.GetUnsafePtr(), (ulong)(job.{f.Name}.Length * {elemSize}));");
            }

            // 释放
            sb.AppendLine("            NativeTranspiler.Bindings.NativeExports.GpuCompute_ReleaseBindGroup(__bg);");
            foreach (var f in arrayFields)
                sb.AppendLine($"            NativeTranspiler.Bindings.NativeExports.GpuCompute_ReleaseBuffer(__b_{f.Name});");
            if (uniformSize > 0)
                sb.AppendLine("            NativeTranspiler.Bindings.NativeExports.GpuCompute_ReleaseBuffer(__uniform);");
            sb.AppendLine("        }");
            sb.AppendLine("        catch");
            sb.AppendLine("        {");
            sb.AppendLine("            throw;");
            sb.AppendLine("        }");
            sb.AppendLine("        return default;");
            sb.AppendLine("    }");
            sb.AppendLine();
        }

        /// <summary>GPU storage buffer 元素字节大小（与 WGSL 布局一致）</summary>
        private static int GetGpuElementSize(ITypeSymbol elemType)
        {
            string w = WgslTypes.ToWgslType(elemType);
            if (w != null)
            {
                return w switch
                {
                    "f32" or "i32" or "u32" => 4,
                    "vec2f" or "vec2i" or "vec2u" => 8,
                    "vec3f" => 12,
                    "vec4f" => 16,
                    _ => 4
                };
            }
            return CppJobGenerator.GetCSharpFieldSize(elemType);
        }

        private static int GetGpuScalarSize(ITypeSymbol type)
        {
            if (type.TypeKind == TypeKind.Enum && type is INamedTypeSymbol et)
                return GetGpuScalarSize(et.EnumUnderlyingType);
            return type.SpecialType switch
            {
                SpecialType.System_Single or SpecialType.System_Int32 or SpecialType.System_UInt32 => 4,
                _ => 4
            };
        }

        private static string GetGpuScalarConv(ITypeSymbol type, string expr)
        {
            if (type.TypeKind == TypeKind.Enum && type is INamedTypeSymbol et)
                return GetGpuScalarConv(et.EnumUnderlyingType, expr);
            return type.SpecialType switch
            {
                SpecialType.System_Single => expr,
                SpecialType.System_Int32 => expr,
                SpecialType.System_UInt32 => expr,
                _ => expr
            };
        }
    }
}
