using Microsoft.CodeAnalysis;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using NativeTranspiler.Analyzer.Common;

namespace NativeTranspiler.Analyzer
{
    public static class BindingsGenerator
    {
        // DLL 鍒嗙鍚庯細鐢熸垚浠ｇ爜锛坵rapper/adapter锛夌紪璇戣繘 NativeTranspiled.dll锛?
        // 鏍稿績 runtime锛圝obSystem 绛夛級浠嶅湪 NativeDll.dll銆?
        private const string NativeLibraryName = "NativeTranspiled";

        public static string GenerateBindingsClass(
            IEnumerable<IMethodSymbol> methods,
            IEnumerable<INamedTypeSymbol> jobStructs,
            Compilation compilation)
        {
            var sb = new StringBuilder();
            sb.AppendLine("// <auto-generated/>");
            // job 缁撴瀯鍚?NativeArray/NativeList锛堝唴鍚墭绠?DisposeSentinel锛夆啋 鎵樼绫诲瀷銆傜敓鎴愪唬鐮佺敤
            // sizeof/鍙栧潃/鎸囬拡寮鸿浆鎶?job 鐨?blittable 瀛楁鎼繍/璇诲埌 native 渚э紝鏄獙璇佽繃鐨勫畨鍏ㄦā寮忥紱
            // CS8500锛堝鎵樼绫诲瀷鍙栧ぇ灏?鍦板潃锛変负 false positive锛屾寜 Unity 鐢熸垚 interop 浠ｇ爜鎯緥灞忚斀銆?
            sb.AppendLine("#pragma warning disable CS8500");
            sb.AppendLine("using System;");
            sb.AppendLine("using System.Runtime.InteropServices;");
            sb.AppendLine("using System.Runtime.CompilerServices;");
            sb.AppendLine("using EntJoy;");
            sb.AppendLine("using EntJoy.Collections;");
            sb.AppendLine("using EntJoy.JobSystem;");
            sb.AppendLine();
            sb.AppendLine("namespace NativeTranspiler.Bindings");
            sb.AppendLine("{");
            sb.AppendLine("    public static unsafe partial class NativeExports");
            sb.AppendLine("    {");
            sb.AppendLine("        public delegate void JobFuncDelegate(IntPtr context);");
            sb.AppendLine("        public delegate void BatchJobFuncDelegate(IntPtr context, int startIndex, int count);");
            sb.AppendLine("        public delegate void ChunkJobFuncDelegate(IntPtr context, ChunkJobData* chunkData);");
            sb.AppendLine("        public delegate void CleanupFuncDelegate(IntPtr context);");
            sb.AppendLine();

            var attrSymbol = compilation.GetTypeByMetadataName("NativeTranspiler.NativeTranspileAttribute");

            // GPU/CUDA 鍚庣宸叉媶鍒嗚嚦 feature/gpu-offload 鍒嗘敮锛沝ev 浠?Cpp/Ispc Job銆?
            var nativeJobs = jobStructs.ToList();

            // 1. 涓烘瘡涓?Job 缁撴瀯浣撶敓鎴愰潤鎬佺紦瀛樼殑濮旀墭瀛楁鍜屽嚱鏁版寚閽?
            foreach (var jobStruct in nativeJobs)
            {
                GenerateStaticDelegateFields(sb, jobStruct, compilation);
            }

            // 2. 闈欐€佹瀯閫犲嚱鏁帮細鍒濆鍖栨墍鏈夌紦瀛樼殑濮旀墭鍜屽嚱鏁版寚閽?
            sb.AppendLine("        static NativeExports()");
            sb.AppendLine("        {");
            foreach (var jobStruct in nativeJobs)
            {
                GenerateStaticConstructorInitialization(sb, jobStruct, compilation);
            }
            // 娉ㄥ唽 Job 瀛楁鏄惧紡鍐欏叆鍣紙chunk 璺緞 CreateChunkContextBlock 鍒嗗彂鐢級
            foreach (var jobStruct in nativeJobs)
            {
                if (ComputeJobFieldMarshal(jobStruct).explicitOk)
                {
                    sb.AppendLine($"            NativeJobScheduler.RegisterJobFieldWriter(typeof({jobStruct.ToDisplayString()}), (NativeJobScheduler.JobFieldWriter<{jobStruct.ToDisplayString()}>)WriteJobFields_{jobStruct.Name});");
                }
            }
            sb.AppendLine("        }");
            sb.AppendLine();

            // 3. 鏅€氭柟娉曠殑 DllImport 鍜?Wrapper锛堣嚜鍔ㄥ唴鑱?MT 閫夋嫨锛?
            foreach (var method in methods)
            {
                GenerateMethodDllImport(sb, method);
                bool useMT = HasUseISPC_MT(method, attrSymbol);
                if (useMT)
                {
                    GenerateMethodDllImportMT(sb, method);
                }
                GenerateMethodWrapper(sb, method, useMT);
            }

            // 4. Job 缁撴瀯浣撶殑 DllImport 鍜?Schedule 鏂规硶
            foreach (var jobStruct in nativeJobs)
            {
                GenerateJobDllImport(sb, jobStruct, compilation);
                GenerateJobScheduleMethod(sb, jobStruct, compilation);
            }

            // 4c. 鏄惧紡 Job 瀛楁鍐欏叆鍣紙chunk 璺緞 CreateChunkContextBlock 鐢級锛?
            //     Debug 涓?DisposeSentinel 浣?Job struct 闈?blittable 鈫?瑁告嫹璐濆竷灞€涓嶅彲闈狅紝
            //     閫?Job 鐢熸垚绫诲瀷鍖栧啓鍏ュ櫒锛岄潤鎬佹瀯閫犳椂娉ㄥ唽杩?NativeJobScheduler 鐨勬敞鍐岃〃锛圗ntJoy 渚э級銆?
            if (nativeJobs.Count > 0)
            {
                foreach (var jobStruct in nativeJobs)
                    GenerateJobFieldWriterMethod(sb, jobStruct);
                sb.AppendLine();
            }

            sb.AppendLine(GenerateCleanupFactoryMethod());
            sb.AppendLine("    }");
            sb.AppendLine("}");
            sb.AppendLine();

            // 5. Job 鎵╁睍鏂规硶锛圫chedule 鍜?Run锛?
            sb.AppendLine("public static partial class JobExtensions");
            sb.AppendLine("{");
            foreach (var jobStruct in nativeJobs)
            {
                GenerateJobExtensionMethod(sb, jobStruct);
                GenerateJobRunMethod(sb, jobStruct, compilation);
            }
            sb.AppendLine("}");

            return sb.ToString();
        }

        private static bool HasUseISPC_MT(ISymbol symbol, INamedTypeSymbol? attrSymbol)
            => AttributeHelper.HasUseISPC_MT(symbol, attrSymbol);

        // ---------- 鏂规硶 DllImport ----------
        private static void GenerateMethodDllImport(StringBuilder sb, IMethodSymbol method)
        {
            var cppFunctionName = CppGenerator.GetCppFunctionName(method);
            var returnType = method.ReturnType.ToDisplayString(SymbolDisplayFormat.FullyQualifiedFormat);
            var methodName = method.Name + "_Native";
            var parameters = BuildMethodDllImportParams(method);
            sb.AppendLine($"        [DllImport(\"{NativeLibraryName}\", EntryPoint = \"{cppFunctionName}\", CallingConvention = CallingConvention.Cdecl)]");
            sb.AppendLine($"        private static extern {returnType} {methodName}({string.Join(", ", parameters)});");
            sb.AppendLine();
        }

        private static void GenerateMethodDllImportMT(StringBuilder sb, IMethodSymbol method)
        {
            var cppFunctionName = CppGenerator.GetCppFunctionName(method) + "_mt";
            var returnType = method.ReturnType.ToDisplayString(SymbolDisplayFormat.FullyQualifiedFormat);
            var methodName = method.Name + "_mt_Native";
            var parameters = BuildMethodDllImportParams(method);
            parameters.Add("int numTasks");
            sb.AppendLine($"        [DllImport(\"{NativeLibraryName}\", EntryPoint = \"{cppFunctionName}\", CallingConvention = CallingConvention.Cdecl)]");
            sb.AppendLine($"        private static extern {returnType} {methodName}({string.Join(", ", parameters)});");
            sb.AppendLine();
        }

        private static void GenerateMethodWrapper(StringBuilder sb, IMethodSymbol method, bool useMT)
        {
            var returnType = method.ReturnType.ToDisplayString(SymbolDisplayFormat.FullyQualifiedFormat);
            var methodName = method.Name;
            var parameters = method.Parameters.Select(p => $"{GetCSharpParameterType(p)} {p.Name}");
            sb.AppendLine($"        public static {returnType} {methodName}({string.Join(", ", parameters)})");
            sb.AppendLine("        {");
            sb.AppendLine("            unsafe {");
            // 鐩磋皟鎵ц绐楀彛锛欱egin 鍦ㄨ皟鐢ㄥ墠寮€绐楀彛锛堝綋鍓嶇嚎绋嬫吵閬擄紝浜嬩欢椹卞姩锛夛紝
            // finally 纭繚鏃犺寮傚父涓庡惁閮藉叧闂獥鍙ｅ苟涓婃姤鍏变韩鏃堕棿绾挎銆?
            sb.AppendLine($"            ulong __dbgId = NativeJobScheduler.BeginDirectCall(\"{methodName}\", {(useMT ? "(uint)Environment.ProcessorCount" : "1u")});");
            sb.AppendLine("            try {");
            if (method.ReturnType.SpecialType != SpecialType.System_Void)
                sb.Append("                return ");
            else
                sb.Append("                ");

            if (useMT)
            {
                sb.Append($"{methodName}_mt_Native(");
                var args = BuildMethodCallArgs(method);
                args.Add("Environment.ProcessorCount");
                sb.Append(string.Join(", ", args));
            }
            else
            {
                sb.Append($"{methodName}_Native(");
                var args = BuildMethodCallArgs(method);
                sb.Append(string.Join(", ", args));
            }
            sb.AppendLine(");");
            sb.AppendLine("            }");
            sb.AppendLine("            finally { NativeJobScheduler.EndDirectCall(__dbgId); }");
            sb.AppendLine("            }");
            sb.AppendLine("        }");
            sb.AppendLine();
        }

        // ---------- Job 濮旀墭瀛楁 ----------
        private static void GenerateStaticDelegateFields(StringBuilder sb, INamedTypeSymbol jobStruct, Compilation compilation)
        {
            bool isChunk = CppJobGenerator.IsChunkScheduledJob(jobStruct);
            bool isParallelFor = CppJobGenerator.IsParallelForJob(jobStruct);
            bool isFor = CppJobGenerator.IsForJob(jobStruct);

            if (isChunk)
            {
                if (CppJobGenerator.IsEntityJob(jobStruct))
                {
                    // IJobEntity 缁熶竴璧?Chunk 绾ц皟搴︼紙涓?ISPC 璺緞涓€鑷达級
                    sb.AppendLine($"        private static readonly IntPtr s_{jobStruct.Name}_ChunkFuncPtr;");
                    sb.AppendLine($"        private static readonly IntPtr s_{jobStruct.Name}_ChunkRangeFuncPtr;");
                }
                else
                {
                    sb.AppendLine($"        private static readonly IntPtr s_{jobStruct.Name}_ChunkFuncPtr;");
                    sb.AppendLine($"        private static readonly IntPtr s_{jobStruct.Name}_ChunkRangeFuncPtr;");
                    var attrSym2 = AttributeHelper.GetAttributeSymbol(compilation);
                    bool isIspc2 = attrSym2 != null && AttributeHelper.GetBackendTarget(jobStruct, attrSym2) == NativeTranspiler.BackendTarget.Ispc;
                    if (!isIspc2)
                        sb.AppendLine($"        private static readonly IntPtr s_{jobStruct.Name}_ChunkEntityBatchFuncPtr;");
                }
                var requiredTypes = CppJobGenerator.CollectChunkNativeArrayTypes(jobStruct, compilation);
                string requiredIds = BuildRequiredComponentTypeIdsInitializer(requiredTypes);
                sb.AppendLine($"        private static readonly int[] s_{jobStruct.Name}_RequiredComponentTypeIds = {requiredIds};");
            }
            else if (isParallelFor || isFor)
            {
                sb.AppendLine($"        private static readonly BatchJobFuncDelegate s_{jobStruct.Name}_BatchFunc;");
                sb.AppendLine($"        private static readonly IntPtr s_{jobStruct.Name}_BatchFuncPtr;");
            }
            else
            {
                sb.AppendLine($"        private static readonly JobFuncDelegate s_{jobStruct.Name}_JobFunc;");
                sb.AppendLine($"        private static readonly IntPtr s_{jobStruct.Name}_JobFuncPtr;");
            }
            sb.AppendLine($"        private static readonly CleanupFuncDelegate s_{jobStruct.Name}_CleanupFunc;");
            sb.AppendLine($"        private static readonly IntPtr s_{jobStruct.Name}_CleanupFuncPtr;");
            sb.AppendLine();
        }

        private static void GenerateStaticConstructorInitialization(StringBuilder sb, INamedTypeSymbol jobStruct, Compilation compilation)
        {
            string jobTypeFullName = jobStruct.ToDisplayString();
            bool isParallelFor = CppJobGenerator.IsParallelForJob(jobStruct);
            bool isFor = CppJobGenerator.IsForJob(jobStruct);
            bool isChunk = CppJobGenerator.IsChunkScheduledJob(jobStruct);

            var executeMethod = jobStruct.GetMembers().OfType<IMethodSymbol>().First(m => m.Name == "Execute");
            var methodSyntax = SymbolHelper.GetMethodSyntax(executeMethod);
            bool hasMultiVersion = false;
            string boolFieldName = null;
            List<IFieldSymbol> boolFields = new List<IFieldSymbol>();

            var attrSymbol = compilation.GetTypeByMetadataName("NativeTranspiler.NativeTranspileAttribute");
            bool useMT = HasUseISPC_MT(jobStruct, attrSymbol);

            if (methodSyntax != null)
            {
                var semanticModel = compilation.GetSemanticModel(methodSyntax.SyntaxTree);
                var conditionalFields = NativeTranspileValidator.GetConditionalReadOnlyFields(jobStruct, semanticModel);
                boolFields = conditionalFields.Where(f => f.Type.SpecialType == SpecialType.System_Boolean).ToList();
                if (boolFields.Count > 0)
                {
                    hasMultiVersion = true;
                    boolFieldName = boolFields[0].Name;
                }
            }

            if (isChunk)
            {
                if (CppJobGenerator.IsEntityJob(jobStruct))
                {
                    // IJobEntity 缁熶竴璧?Chunk 绾ц皟搴︼紙涓?ISPC 璺緞涓€鑷达級
                    sb.AppendLine($"            s_{jobStruct.Name}_ChunkFuncPtr = Get_{jobStruct.Name}_ChunkAdapterPtr();");
                    sb.AppendLine($"            s_{jobStruct.Name}_ChunkRangeFuncPtr = Get_{jobStruct.Name}_ChunkRangeAdapterPtr();");
                }
                else
                {
                    sb.AppendLine($"            s_{jobStruct.Name}_ChunkFuncPtr = Get_{jobStruct.Name}_ChunkAdapterPtr();");
                    sb.AppendLine($"            s_{jobStruct.Name}_ChunkRangeFuncPtr = Get_{jobStruct.Name}_ChunkRangeAdapterPtr();");
                    var attrSym2 = AttributeHelper.GetAttributeSymbol(compilation);
                    bool isIspc2 = attrSym2 != null && AttributeHelper.GetBackendTarget(jobStruct, attrSym2) == NativeTranspiler.BackendTarget.Ispc;
                    if (!isIspc2)
                        sb.AppendLine($"            s_{jobStruct.Name}_ChunkEntityBatchFuncPtr = Get_{jobStruct.Name}_ChunkEntityBatchAdapterPtr();");
                }
            }
            else if (isParallelFor || isFor)
            {
                if (useMT)
                {
                // MT锛坱ask 鍐呴儴鑷繁璋冨害锛変粛鐢ㄦ墭绠?delegate锛氬師鐢?Adapter 鍙敓鎴愰潪 MT 鍙樹綋
                string mtSuffix = "_mt";

                sb.AppendLine($"            s_{jobStruct.Name}_BatchFunc = (IntPtr context, int startIndex, int count) =>");
                sb.AppendLine("            {");
                sb.AppendLine($"                var jobPtr = ({jobTypeFullName}*)context;");

                string batchArgs = BuildBatchCallArgs(jobStruct, "jobPtr");
                string batchArgsWithComma = string.IsNullOrEmpty(batchArgs) ? "" : ", " + batchArgs;
                if (hasMultiVersion)
                {
                    // 鐢熸垚鎵€鏈?2^n 涓?bool 缁勫悎鐨?if-else 閾撅紝涓?C++ 绔懡鍚嶄竴鑷?
                    int totalVariants = 1 << boolFields.Count;
                    var boolVarNames = boolFields.Select(f => $"jobPtr->{f.Name}").ToList();

                    for (int mask = 0; mask < totalVariants; mask++)
                    {
                        var values = new List<bool>();
                        for (int i = 0; i < boolFields.Count; i++)
                            values.Add((mask & (1 << i)) != 0);

                        string suffix = "_" + string.Join("_", values.Select(v => v ? "true" : "false"));

                        bool isLast = (mask == totalVariants - 1);
                        if (mask == 0)
                        {
                            string condition = string.Join(" && ", boolFields.Select((f, i) => values[i] ? $"jobPtr->{f.Name}" : $"!jobPtr->{f.Name}"));
                            sb.AppendLine($"                if ({condition})");
                        }
                        else if (!isLast)
                        {
                            string condition = string.Join(" && ", boolFields.Select((f, i) => values[i] ? $"jobPtr->{f.Name}" : $"!jobPtr->{f.Name}"));
                            sb.AppendLine($"                else if ({condition})");
                        }
                        else
                        {
                            sb.AppendLine("                else");
                        }

                        sb.AppendLine($"                    {jobStruct.Name}_Execute_Batch{suffix}{mtSuffix}(startIndex, count{batchArgsWithComma});");
                    }
                }
                else
                {
                    sb.AppendLine($"                {jobStruct.Name}_Execute_Batch{mtSuffix}(startIndex, count{batchArgsWithComma});");
                }
                sb.AppendLine("            };");
                sb.AppendLine($"            s_{jobStruct.Name}_BatchFuncPtr = Marshal.GetFunctionPointerForDelegate(s_{jobStruct.Name}_BatchFunc);");
                }
                else
                {
                    // 闈?MT锛氳皟搴﹀櫒鐩存帴璋冨師鐢?_Execute_Adapter(context,start,count)锛堝師鐢熲啋鍘熺敓锛夛紝
                    // 娑堥櫎鎵樼 BatchFunc delegate 鐨?鍘熺敓鈫掓墭绠♀啋鍘熺敓 鍙岄噸杞崲锛堟瘡 tile ~3渭s 寮€閿€锛夈€?
                    // 鍘熺敓 Adapter 鐢?CppJobGenerator 鐢熸垚锛氬悓涓€濂楀瓧娈靛亸绉昏В鍖?/ UnsafeList 鍐欏洖 / bool 鍙樹綋鍒嗘淳銆?
                    sb.AppendLine($"            s_{jobStruct.Name}_BatchFuncPtr = Get_{jobStruct.Name}_Execute_AdapterPtr();");
                }
            }
            else
            {
                sb.AppendLine($"            s_{jobStruct.Name}_JobFunc = (IntPtr context) =>");
                sb.AppendLine("            {");
                sb.AppendLine($"                var jobPtr = ({jobTypeFullName}*)context;");
                var args = BuildJobExecuteArgsForPointer(jobStruct);
                sb.AppendLine($"                {jobStruct.Name}_Execute({string.Join(", ", args)});");
                sb.AppendLine("            };");
                sb.AppendLine($"            s_{jobStruct.Name}_JobFuncPtr = Marshal.GetFunctionPointerForDelegate(s_{jobStruct.Name}_JobFunc);");
            }

            sb.AppendLine($"            s_{jobStruct.Name}_CleanupFunc = (IntPtr context) =>");
            sb.AppendLine("            {");
            sb.AppendLine("                Marshal.FreeHGlobal(context);");
            sb.AppendLine("            };");
            sb.AppendLine($"            s_{jobStruct.Name}_CleanupFuncPtr = Marshal.GetFunctionPointerForDelegate(s_{jobStruct.Name}_CleanupFunc);");
            sb.AppendLine();
        }

        private static void GenerateJobDllImport(StringBuilder sb, INamedTypeSymbol jobStruct, Compilation compilation)
        {
            bool isChunk = CppJobGenerator.IsChunkScheduledJob(jobStruct);
            bool isParallelFor = CppJobGenerator.IsParallelForJob(jobStruct);
            bool isFor = CppJobGenerator.IsForJob(jobStruct);

            var attrSymbol = compilation.GetTypeByMetadataName("NativeTranspiler.NativeTranspileAttribute");
            bool useMT = HasUseISPC_MT(jobStruct, attrSymbol);

            if (isChunk)
            {
                if (CppJobGenerator.IsEntityJob(jobStruct))
                {
                    // IJobEntity 缁熶竴璧?Chunk 绾ц皟搴?
                    var getterName = CppJobGenerator.GetAdapterPtrGetterName(jobStruct);
                    var rangeGetterName = CppJobGenerator.GetRangeAdapterPtrGetterName(jobStruct);
                    sb.AppendLine($"        [DllImport(\"{NativeLibraryName}\", EntryPoint = \"{getterName}\", CallingConvention = CallingConvention.Cdecl)]");
                    sb.AppendLine($"        private static extern IntPtr Get_{jobStruct.Name}_ChunkAdapterPtr();");
                    sb.AppendLine($"        [DllImport(\"{NativeLibraryName}\", EntryPoint = \"{rangeGetterName}\", CallingConvention = CallingConvention.Cdecl)]");
                    sb.AppendLine($"        private static extern IntPtr Get_{jobStruct.Name}_ChunkRangeAdapterPtr();");
                }
                else
                {
                    var getterName = CppJobGenerator.GetAdapterPtrGetterName(jobStruct);
                    var rangeGetterName = CppJobGenerator.GetRangeAdapterPtrGetterName(jobStruct);
                    var entityBatchGetterName = CppJobGenerator.GetEntityBatchAdapterPtrGetterName(jobStruct);
                    sb.AppendLine($"        [DllImport(\"{NativeLibraryName}\", EntryPoint = \"{getterName}\", CallingConvention = CallingConvention.Cdecl)]");
                    sb.AppendLine($"        private static extern IntPtr Get_{jobStruct.Name}_ChunkAdapterPtr();");
                    sb.AppendLine($"        [DllImport(\"{NativeLibraryName}\", EntryPoint = \"{rangeGetterName}\", CallingConvention = CallingConvention.Cdecl)]");
                    sb.AppendLine($"        private static extern IntPtr Get_{jobStruct.Name}_ChunkRangeAdapterPtr();");
                    var attrSym2 = AttributeHelper.GetAttributeSymbol(compilation);
                    bool isIspc2 = attrSym2 != null && AttributeHelper.GetBackendTarget(jobStruct, attrSym2) == NativeTranspiler.BackendTarget.Ispc;
                    if (!isIspc2)
                    {
                        sb.AppendLine($"        [DllImport(\"{NativeLibraryName}\", EntryPoint = \"{entityBatchGetterName}\", CallingConvention = CallingConvention.Cdecl)]");
                        sb.AppendLine($"        private static extern IntPtr Get_{jobStruct.Name}_ChunkEntityBatchAdapterPtr();");
                    }
                }
            }
            else if (isParallelFor || isFor)
            {
                var batchFuncName = CppJobGenerator.GetCppJobFunctionName(jobStruct, isBatch: true);
                var batchParams = BuildBatchJobDllImportParams(jobStruct);

                var executeMethod = jobStruct.GetMembers().OfType<IMethodSymbol>().First(m => m.Name == "Execute");
                var methodSyntax = SymbolHelper.GetMethodSyntax(executeMethod);
                bool hasMultiVersion = false;
                if (methodSyntax != null)
                {
                    var semanticModel = compilation.GetSemanticModel(methodSyntax.SyntaxTree);
                    var conditionalFields = NativeTranspileValidator.GetConditionalReadOnlyFields(jobStruct, semanticModel);
                    hasMultiVersion = conditionalFields.Any(f => f.Type.SpecialType == SpecialType.System_Boolean);
                }

                if (hasMultiVersion)
                {
                    sb.AppendLine($"        [DllImport(\"{NativeLibraryName}\", EntryPoint = \"{batchFuncName}_true\", CallingConvention = CallingConvention.Cdecl)]");
                    sb.AppendLine($"        public static extern void {jobStruct.Name}_Execute_Batch_true({string.Join(", ", batchParams)});");
                    sb.AppendLine($"        [DllImport(\"{NativeLibraryName}\", EntryPoint = \"{batchFuncName}_false\", CallingConvention = CallingConvention.Cdecl)]");
                    sb.AppendLine($"        public static extern void {jobStruct.Name}_Execute_Batch_false({string.Join(", ", batchParams)});");
                }
                else
                {
                    sb.AppendLine($"        [DllImport(\"{NativeLibraryName}\", EntryPoint = \"{batchFuncName}\", CallingConvention = CallingConvention.Cdecl)]");
                    sb.AppendLine($"        public static extern void {jobStruct.Name}_Execute_Batch({string.Join(", ", batchParams)});");
                }

                if (useMT)
                {
                    if (hasMultiVersion)
                    {
                        sb.AppendLine($"        [DllImport(\"{NativeLibraryName}\", EntryPoint = \"{batchFuncName}_true_mt\", CallingConvention = CallingConvention.Cdecl)]");
                        sb.AppendLine($"        private static extern void {jobStruct.Name}_Execute_Batch_true_mt({string.Join(", ", batchParams)});");
                        sb.AppendLine($"        [DllImport(\"{NativeLibraryName}\", EntryPoint = \"{batchFuncName}_false_mt\", CallingConvention = CallingConvention.Cdecl)]");
                        sb.AppendLine($"        private static extern void {jobStruct.Name}_Execute_Batch_false_mt({string.Join(", ", batchParams)});");
                    }
                    else
                    {
                        sb.AppendLine($"        [DllImport(\"{NativeLibraryName}\", EntryPoint = \"{batchFuncName}_mt\", CallingConvention = CallingConvention.Cdecl)]");
                        sb.AppendLine($"        private static extern void {jobStruct.Name}_Execute_Batch_mt({string.Join(", ", batchParams)});");
                    }
                }
                else
                {
                    // 闈?MT锛氬０鏄庡師鐢?Adapter 鎸囬拡 Getter锛堣皟搴﹀櫒鍘熺敓鈫掑師鐢熺洿璋冭矾寰勶級
                    var adapterGetterName = CppJobGenerator.GetAdapterPtrGetterName(jobStruct);
                    sb.AppendLine($"        [DllImport(\"{NativeLibraryName}\", EntryPoint = \"{adapterGetterName}\", CallingConvention = CallingConvention.Cdecl)]");
                    sb.AppendLine($"        private static extern IntPtr Get_{jobStruct.Name}_Execute_AdapterPtr();");
                }
            }
            else
            {
                var singleFuncName = CppJobGenerator.GetCppJobFunctionName(jobStruct);
                var singleParams = BuildJobDllImportParams(jobStruct);
                sb.AppendLine($"        [DllImport(\"{NativeLibraryName}\", EntryPoint = \"{singleFuncName}\", CallingConvention = CallingConvention.Cdecl)]");
                sb.AppendLine($"        public static extern void {jobStruct.Name}_Execute({string.Join(", ", singleParams)});");
            }
            sb.AppendLine();
        }

        // ---------- Job Schedule 鏂规硶 ----------
        private static void GenerateJobScheduleMethod(StringBuilder sb, INamedTypeSymbol jobStruct, Compilation compilation)
        {
            bool isChunk = CppJobGenerator.IsChunkScheduledJob(jobStruct);
            bool isParallelFor = CppJobGenerator.IsParallelForJob(jobStruct);
            bool isFor = CppJobGenerator.IsForJob(jobStruct);
            string jobTypeName = jobStruct.ToDisplayString();

            var attrSymbol = compilation.GetTypeByMetadataName("NativeTranspiler.NativeTranspileAttribute");
            bool useMT = HasUseISPC_MT(jobStruct, attrSymbol);

            var parameters = new List<string>();
            // Use 'ref' for the internal Schedule_XXX method (caller already has a reference)
            parameters.Add($"ref {jobTypeName} job");
            if (isChunk)
            {
                parameters.Add("QueryBuilder query");
            }
            else if (isParallelFor || isFor)
            {
                parameters.Add("int arrayLength");
                // IJobFor 涔熷厑璁告寚瀹?innerBatchCount锛屼繚鎸佹帴鍙ｇ粺涓€
                parameters.Add("int innerBatchCount = 0");
            }
            parameters.Add("JobHandle dependsOn = default");

            sb.AppendLine($"        public static JobHandle Schedule_{jobStruct.Name}({string.Join(", ", parameters)})");
            sb.AppendLine("        {");
            if (!isChunk)
            {
                // Debug 涓?NativeArray 鍚?GC 寮曠敤锛圖isposeSentinel锛夆啋 Job struct 闈?blittable锛岃８鎷疯礉甯冨眬涓嶅彲闈狅紱
                // 鏀逛负鏄惧紡閫愬瓧娈靛啓鍏ワ紙涓?C++ Adapter 鍋忕Щ涓€鑷达級锛孌ebug/Release 鍧囨纭€?
                var (marshalled, explicitOk, totalSize) = ComputeJobFieldMarshal(jobStruct);
                if (explicitOk)
                {
                    sb.AppendLine($"            int size = {totalSize};");
                    sb.AppendLine("            IntPtr nativePtr = Marshal.AllocHGlobal(size);");
                    sb.AppendLine("            byte* __dst = (byte*)nativePtr;");
                    EmitExplicitFieldWrites(sb, marshalled, "__dst", "job");
                    sb.AppendLine();
                }
                else
                {
                    // 鍚笉鏀寔瀛楁锛圢ativeList 绛夛級锛氶€€鍥炶８鎷疯礉锛圧elease 姝ｇ‘锛汥ebug 鐢辨樉寮忚矾寰勮鐩栫殑鍦烘櫙澶栵級
                    sb.AppendLine($"            int size = sizeof({jobTypeName});");
                    sb.AppendLine("            IntPtr nativePtr = Marshal.AllocHGlobal(size);");
                    sb.AppendLine("            void* originalPtr = Unsafe.AsPointer(ref job);");
                    sb.AppendLine("            Unsafe.CopyBlockUnaligned((void*)nativePtr, originalPtr, (uint)size);");
                    sb.AppendLine();
                }
            }

            if (isChunk)
            {
                sb.AppendLine("            var world = World.DefaultWorld ?? throw new InvalidOperationException(\"No active World found.\");");
                // 鎵€鏈?native IJobChunk 璧?EntityBatch 璺緞锛圲nity 椋庢牸锛夛紝
                // 浣跨敤 EntityBatchData 鏇夸唬 ChunkJobData锛屾秷闄?requiredComponentArrays 闂存帴灞?
                string funcPtrName;
                string extraArgs;
                string scheduleMethod;
                if (CppJobGenerator.IsEntityJob(jobStruct))
                {
                    // IJobEntity 缁熶竴璧?Chunk 绾?range 璋冨害
                    scheduleMethod = "ScheduleChunkRangeRaw";
                    funcPtrName = $"s_{jobStruct.Name}_ChunkRangeFuncPtr";
                    extraArgs = "";
                }
                else
                {
                    var attrSym3 = AttributeHelper.GetAttributeSymbol(compilation);
                    bool isIspc3 = attrSym3 != null && AttributeHelper.GetBackendTarget(jobStruct, attrSym3) == NativeTranspiler.BackendTarget.Ispc;
                    if (isIspc3)
                    {
                        scheduleMethod = "ScheduleChunkRangeRaw";
                        funcPtrName = $"s_{jobStruct.Name}_ChunkRangeFuncPtr";
                        extraArgs = "";
                    }
                    else
                    {
                        scheduleMethod = "ScheduleChunkEntityBatchRawWithWorkerCapAndRangeSize";
                        funcPtrName = $"s_{jobStruct.Name}_ChunkEntityBatchFuncPtr";
                        extraArgs = $", 0, 0";
                    }
                }
                sb.AppendLine($"            NativeJobHandle nativeHandle = NativeEcsScheduler.{scheduleMethod}(");
                sb.AppendLine($"                ref job, world.EntityManager, query, {funcPtrName}, s_{jobStruct.Name}_RequiredComponentTypeIds{extraArgs}, dependsOn._nativeHandle);");
                sb.AppendLine($"            return new JobHandle(nativeHandle);");
            }
            else if (isParallelFor || isFor)
            {
                // 鑷€傚簲鎵规澶у皬
                if (useMT)
                {
                    sb.AppendLine($"            int actualBatchSize = innerBatchCount > 0 ? innerBatchCount : arrayLength;");
                }
                else
                {
                    // 0 = 鐩撮€氬師鐢?ResolveChunkSize锛坱iles/worker 閫氱敤鍖栫矑搴︼級锛?0 鏄惧紡 batch 鍘熸牱浼?
                    sb.AppendLine($"            int actualBatchSize = innerBatchCount;");
                }

                sb.AppendLine($"            NativeJobHandle nativeHandle = NativeJobScheduler.ScheduleParallelForBatchRaw(");
                sb.AppendLine($"                s_{jobStruct.Name}_BatchFuncPtr, nativePtr, s_{jobStruct.Name}_CleanupFuncPtr, arrayLength, actualBatchSize, dependsOn._nativeHandle);");
                sb.AppendLine($"            NativeJobScheduler.RegisterScheduledJob(nativeHandle.Handle, \"{jobStruct.Name}\");");
                sb.AppendLine($"            return new JobHandle(nativeHandle);");
            }
            else
            {
                sb.AppendLine($"            NativeJobHandle nativeHandle = NativeJobScheduler.ScheduleRaw(");
                sb.AppendLine($"                s_{jobStruct.Name}_JobFuncPtr, nativePtr, s_{jobStruct.Name}_CleanupFuncPtr, dependsOn._nativeHandle);");
                sb.AppendLine($"            NativeJobScheduler.RegisterScheduledJob(nativeHandle.Handle, \"{jobStruct.Name}\");");
                sb.AppendLine($"            return new JobHandle(nativeHandle);");
            }
            sb.AppendLine("        }");
            sb.AppendLine();

            if (isChunk)
            {
                // 纭畾 ISPC 鐘舵€侊紙ScheduleWithWorkerCap 鍜?ScheduleWithWorkerCapAndRangeSize 鍏辩敤锛?
                var attrSymCap = AttributeHelper.GetAttributeSymbol(compilation);
                bool isIspcCap = attrSymCap != null && AttributeHelper.GetBackendTarget(jobStruct, attrSymCap) == NativeTranspiler.BackendTarget.Ispc;

                if (isIspcCap)
                {
                    // ISPC entity jobs use EntityBatch, ISPC chunk jobs use fallback
                    bool isEntityJob = CppJobGenerator.IsEntityJob(jobStruct);
                    // IJobEntity ISPC 浣跨敤 chunk 绾?range 璋冨害
                    string ispcFuncPtr;
                    string ispcScheduleMethod;
                    if (isEntityJob)
                    {
                        ispcFuncPtr = $"s_{jobStruct.Name}_ChunkRangeFuncPtr";
                        ispcScheduleMethod = "ScheduleChunkRangeRaw";
                    }
                    else
                    {
                        ispcFuncPtr = $"s_{jobStruct.Name}_ChunkFuncPtr";
                        ispcScheduleMethod = "ScheduleChunkRawWithWorkerCap";
                    }

                    sb.AppendLine($"        public static JobHandle ScheduleWithWorkerCap_{jobStruct.Name}(ref {jobTypeName} job, QueryBuilder query, int workerCap, JobHandle dependsOn = default)");
                    sb.AppendLine("        {");
                    sb.AppendLine("            var world = World.DefaultWorld ?? throw new InvalidOperationException(\"No active World found.\");");
                    sb.AppendLine($"            NativeJobHandle nativeHandle = NativeEcsScheduler.{ispcScheduleMethod}(");
                    sb.AppendLine(isEntityJob
                        ? $"                ref job, world.EntityManager, query, {ispcFuncPtr}, s_{jobStruct.Name}_RequiredComponentTypeIds, dependsOn._nativeHandle);"
                        : $"                ref job, world.EntityManager, query, {ispcFuncPtr}, s_{jobStruct.Name}_RequiredComponentTypeIds, {(useMT ? "1" : "workerCap")}, dependsOn._nativeHandle);");
                    sb.AppendLine($"            return new JobHandle(nativeHandle);");
                    sb.AppendLine("        }");
                    sb.AppendLine();

                    // ScheduleChunkRawWithWorkerCapAndRangeSize for chunk ISPC, EntityBatch for entity ISPC
                    string ispcScheduleMethod2 = isEntityJob ? "ScheduleChunkRangeRaw" : "ScheduleChunkRawWithWorkerCapAndRangeSize";
                    sb.AppendLine($"        public static JobHandle ScheduleWithWorkerCapAndRangeSize_{jobStruct.Name}(ref {jobTypeName} job, QueryBuilder query, int workerCap, int rangeSize, JobHandle dependsOn = default)");
                    sb.AppendLine("        {");
                    sb.AppendLine("            var world = World.DefaultWorld ?? throw new InvalidOperationException(\"No active World found.\");");
                    sb.AppendLine($"            NativeJobHandle nativeHandle = NativeEcsScheduler.{ispcScheduleMethod2}(");
                    sb.AppendLine(isEntityJob
                        ? $"                ref job, world.EntityManager, query, {ispcFuncPtr}, s_{jobStruct.Name}_RequiredComponentTypeIds, dependsOn._nativeHandle);"
                        : $"                ref job, world.EntityManager, query, {ispcFuncPtr}, s_{jobStruct.Name}_RequiredComponentTypeIds, {(useMT ? "1, int.MaxValue" : "workerCap, rangeSize")}, dependsOn._nativeHandle);");
                    sb.AppendLine($"            return new JobHandle(nativeHandle);");
                    sb.AppendLine("        }");
                    sb.AppendLine();
                }
                else
                {
                    string capFuncPtr = CppJobGenerator.IsEntityJob(jobStruct)
                        ? $"s_{jobStruct.Name}_ChunkRangeFuncPtr"
                        : $"s_{jobStruct.Name}_ChunkEntityBatchFuncPtr";
                    string capMethod = CppJobGenerator.IsEntityJob(jobStruct)
                        ? "ScheduleEntityRangeRawWithWorkerCapAndRangeSize"
                        : "ScheduleChunkEntityBatchRawWithWorkerCapAndRangeSize";

                    sb.AppendLine($"        public static JobHandle ScheduleWithWorkerCap_{jobStruct.Name}(ref {jobTypeName} job, QueryBuilder query, int workerCap, JobHandle dependsOn = default)");
                    sb.AppendLine("        {");
                    sb.AppendLine("            var world = World.DefaultWorld ?? throw new InvalidOperationException(\"No active World found.\");");
                    sb.AppendLine($"            NativeJobHandle nativeHandle = NativeEcsScheduler.{capMethod}(");
                    sb.AppendLine($"                ref job, world.EntityManager, query, {capFuncPtr}, s_{jobStruct.Name}_RequiredComponentTypeIds, workerCap, 0, dependsOn._nativeHandle);");
                    sb.AppendLine($"            return new JobHandle(nativeHandle);");
                    sb.AppendLine("        }");
                    sb.AppendLine();

                    sb.AppendLine($"        public static JobHandle ScheduleWithWorkerCapAndRangeSize_{jobStruct.Name}(ref {jobTypeName} job, QueryBuilder query, int workerCap, int rangeSize, JobHandle dependsOn = default)");
                    sb.AppendLine("        {");
                    sb.AppendLine("            var world = World.DefaultWorld ?? throw new InvalidOperationException(\"No active World found.\");");
                    sb.AppendLine($"            NativeJobHandle nativeHandle = NativeEcsScheduler.{capMethod}(");
                    sb.AppendLine($"                ref job, world.EntityManager, query, {capFuncPtr}, s_{jobStruct.Name}_RequiredComponentTypeIds, workerCap, rangeSize, dependsOn._nativeHandle);");
                    sb.AppendLine($"            return new JobHandle(nativeHandle);");
                    sb.AppendLine("        }");
                    sb.AppendLine();
                }

                sb.AppendLine($"        public static void RunImmediate_{jobStruct.Name}(ref {jobTypeName} job, QueryBuilder query)");
                sb.AppendLine("        {");
                sb.AppendLine($"            Schedule_{jobStruct.Name}(ref job, query, default).Complete();");
                sb.AppendLine("        }");
                sb.AppendLine();
            }
        }

        private static string BuildRequiredComponentTypeIdsInitializer(IEnumerable<INamedTypeSymbol> requiredTypes)
        {
            var ids = string.Join(", ", requiredTypes.Select(t => $"ComponentTypeManager.GetComponentType(typeof({t.ToDisplayString(SymbolDisplayFormat.FullyQualifiedFormat)})).Id"));
            return string.IsNullOrWhiteSpace(ids) ? "Array.Empty<int>()" : $"new int[] {{ {ids} }}";
        }

        // ---------- 杈呭姪锛氭瀯寤哄弬鏁板垪琛?----------
        private static List<string> BuildMethodDllImportParams(IMethodSymbol method)
        {
            var parameters = new List<string>();
            foreach (var param in method.Parameters)
            {
                if (NativeTranspiler.IsEntJoyNativeContainerType(param.Type))
                {
                    if (param.Type.Name == "NativeList")
                    {
                        var elementType = ((INamedTypeSymbol)param.Type).TypeArguments[0];
                        var csElementType = elementType.ToDisplayString(SymbolDisplayFormat.FullyQualifiedFormat);
                        parameters.Add($"EntJoy.Collections.UnsafeList<{csElementType}>* {param.Name}_listData");
                    }
                    else
                    {
                        var elementType = ((INamedTypeSymbol)param.Type).TypeArguments[0];
                        var csElementType = elementType.ToDisplayString(SymbolDisplayFormat.FullyQualifiedFormat);
                        parameters.Add($"{csElementType}* {param.Name}_ptr, int {param.Name}_length");
                    }
                }
                else if (param.Type is IPointerTypeSymbol)
                {
                    var cppType = NativeTranspiler.MapCSharpTypeToCpp(param.Type);  // 杩斿洖 "int*"
                    parameters.Add($"{cppType} {param.Name}_ptr");
                }
                else
                {
                    var csType = param.Type.ToDisplayString(SymbolDisplayFormat.FullyQualifiedFormat);
                    parameters.Add($"{csType}* {param.Name}_ptr");
                }
            }
            return parameters;
        }

        private static List<string> BuildMethodCallArgs(IMethodSymbol method)
        {
            var args = new List<string>();
            foreach (var param in method.Parameters)
            {
                if (NativeTranspiler.IsEntJoyNativeContainerType(param.Type))
                {
                    if (param.Type.Name == "NativeList")
                    {
                        args.Add($"{param.Name}.GetListData()");
                    }
                    else
                    {
                        var elementType = ((INamedTypeSymbol)param.Type).TypeArguments[0];
                        var csElementType = elementType.ToDisplayString(SymbolDisplayFormat.FullyQualifiedFormat);
                        args.Add($"({csElementType}*){param.Name}.GetUnsafePtr(), {param.Name}.Length");
                    }
                }
                else if (param.Type is IPointerTypeSymbol)
                {
                    args.Add(param.Name);
                }
                else
                {
                    var csType = param.Type.ToDisplayString(SymbolDisplayFormat.FullyQualifiedFormat);
                    args.Add($"({csType}*)Unsafe.AsPointer(ref {param.Name})");
                }
            }
            return args;
        }

        private static List<string> BuildJobDllImportParams(INamedTypeSymbol jobStruct)
        {
            var parameters = new List<string>();
            var executeMethod = jobStruct.GetMembers().OfType<IMethodSymbol>().First(m => m.Name == "Execute");
            if (executeMethod.Parameters.Length == 1 && executeMethod.Parameters[0].Type.SpecialType == SpecialType.System_Int32)
                parameters.Add($"int {executeMethod.Parameters[0].Name}");

            AppendFieldDllImportParams(jobStruct, parameters);
            return parameters;
        }

        private static List<string> BuildBatchJobDllImportParams(INamedTypeSymbol jobStruct)
        {
            var parameters = new List<string> { "int __startIndex", "int __count" };
            AppendFieldDllImportParams(jobStruct, parameters);
            return parameters;
        }

        private static void AppendFieldDllImportParams(INamedTypeSymbol jobStruct, List<string> parameters)
        {
            foreach (var field in jobStruct.GetMembers().OfType<IFieldSymbol>().Where(f => !f.IsStatic))
            {
                if (NativeTranspiler.IsEntJoyNativeContainerType(field.Type))
                {
                    if (field.Type.Name == "NativeList")
                    {
                        var elementType = ((INamedTypeSymbol)field.Type).TypeArguments[0];
                        var csElementType = elementType.ToDisplayString(SymbolDisplayFormat.FullyQualifiedFormat);
                        parameters.Add($"EntJoy.Collections.UnsafeList<{csElementType}>* {field.Name}_listData");
                    }
                    else
                    {
                        var elementType = ((INamedTypeSymbol)field.Type).TypeArguments[0];
                        var csElementType = elementType.ToDisplayString(SymbolDisplayFormat.FullyQualifiedFormat);
                        parameters.Add($"{csElementType}* {field.Name}_ptr, int {field.Name}_length");
                    }
                }
                else if (field.Type is IPointerTypeSymbol)
                {
                    var cppType = NativeTranspiler.MapCSharpTypeToCpp(field.Type);  // 杩斿洖 "int*"
                    parameters.Add($"{cppType} {field.Name}_ptr");
                }
                else
                {
                    var csType = field.Type.ToDisplayString(SymbolDisplayFormat.FullyQualifiedFormat);
                    parameters.Add($"{csType}* {field.Name}_ptr");
                }
            }
        }

        private static List<string> BuildJobExecuteArgsForPointer(INamedTypeSymbol jobStruct)
        {
            var args = new List<string>();
            foreach (var field in jobStruct.GetMembers().OfType<IFieldSymbol>().Where(f => !f.IsStatic))
            {
                if (NativeTranspiler.IsEntJoyNativeContainerType(field.Type))
                {
                    if (field.Type.Name == "NativeList")
                    {
                        args.Add($"jobPtr->{field.Name}.GetListData()");
                    }
                    else
                    {
                        var elementType = ((INamedTypeSymbol)field.Type).TypeArguments[0];
                        var csElementType = elementType.ToDisplayString(SymbolDisplayFormat.FullyQualifiedFormat);
                        args.Add($"({csElementType}*)jobPtr->{field.Name}.GetUnsafePtr(), jobPtr->{field.Name}.Length");
                    }
                }
                else
                {
                    if (field.Type is IPointerTypeSymbol)
                        args.Add($"jobPtr->{field.Name}");
                    else
                        args.Add($"&jobPtr->{field.Name}");
                }
            }
            return args;
        }

        private static string BuildBatchCallArgs(INamedTypeSymbol jobStruct, string jobPtrPrefix)
        {
            var args = new List<string>();
            foreach (var field in jobStruct.GetMembers().OfType<IFieldSymbol>().Where(f => !f.IsStatic))
            {
                if (NativeTranspiler.IsEntJoyNativeContainerType(field.Type))
                {
                    if (field.Type.Name == "NativeList")
                        args.Add($"{jobPtrPrefix}->{field.Name}.GetListData()");
                    else
                    {
                        var elementType = ((INamedTypeSymbol)field.Type).TypeArguments[0];
                        var csElementType = elementType.ToDisplayString(SymbolDisplayFormat.FullyQualifiedFormat);
                        args.Add($"({csElementType}*){jobPtrPrefix}->{field.Name}.GetUnsafePtr(), {jobPtrPrefix}->{field.Name}.Length");
                    }
                }
                else if (field.Type is IPointerTypeSymbol)
                {
                    args.Add($"{jobPtrPrefix}->{field.Name}");
                }
                else
                {
                    args.Add($"&{jobPtrPrefix}->{field.Name}");
                }
            }
            return string.Join(", ", args);
        }

        // ---------- 鏄惧紡閫愬瓧娈?marshalling锛圖ebug sentinel 甯冨眬淇鍏辩敤锛?----------

        /// <summary>
        /// 璁＄畻 Job 缁撴瀯浣撴墍鏈夊疄渚嬪瓧娈靛湪 C++ context 甯冨眬涓嬬殑鍋忕Щ锛堜笌 CppJobGenerator.CalculateFieldOffset 鍚屾簮锛夛紝
        /// 骞舵妸瀛楁閫掑綊灞曞紑涓?鍙跺瓙"锛堝惈 GC 寮曠敤鐨勯潪 blittable struct 涔熼€掑綊锛氬€煎瓙瀛楁鏄惧紡鍐欍€佸紩鐢ㄦЫ闆跺～鍏咃級銆?
        /// 鍙跺瓙锛歵ype==null 琛ㄧず寮曠敤妲斤紙8B 闆跺～鍏咃紝C++ 渚т负 void*锛孍xecute 涓嶅簲璁块棶锛夈€?
        /// 杩斿洖 (鍙跺瓙鍒楄〃, 鏄惁鍏ㄩ儴鏀寔, 鎬诲ぇ灏?銆?
        /// </summary>
        private static (List<(string accessor, int offset, ITypeSymbol type)> leaves, bool explicitOk, int totalSize) ComputeJobFieldMarshal(INamedTypeSymbol jobStruct)
        {
            var leaves = new List<(string accessor, int offset, ITypeSymbol type)>();
            int running = 0;
            foreach (var field in jobStruct.GetMembers().OfType<IFieldSymbol>().Where(f => !f.IsStatic))
            {
                int off = CppJobGenerator.CalculateFieldOffset(field, ref running);
                if (field.Type.IsReferenceType)
                {
                    leaves.Add(("", off, null));   // 椤跺眰寮曠敤瀛楁 鈫?void* 妲介浂濉厖
                    continue;
                }
                if (!CollectLeaves(leaves, field.Name, field.Type, off)) return (leaves, false, running);
            }
            return (leaves, true, running);
        }

        /// <summary>閫掑綊灞曞紑瀛楁涓哄彾瀛愶細瀹瑰櫒/鎸囬拡/鏍囬噺/鏋氫妇/blittable struct 鈫?鍗曞彾瀛愶紱闈?blittable struct 鈫?閫掑綊锛堝紩鐢ㄥ瓙瀛楁 鈫?闆跺～鍏呮Ы锛?/summary>
        private static bool CollectLeaves(List<(string accessor, int offset, ITypeSymbol type)> leaves,
            string accessor, ITypeSymbol type, int offset)
        {
            if (type is IPointerTypeSymbol) { leaves.Add((accessor, offset, type)); return true; }
            if (NativeTranspiler.IsEntJoyNativeContainerType(type)) { leaves.Add((accessor, offset, type)); return true; }
            if (type.TypeKind == TypeKind.Enum) { leaves.Add((accessor, offset, type)); return true; }
            var st = type.SpecialType;
            if (st is SpecialType.System_Single or SpecialType.System_Int32
                or SpecialType.System_UInt32 or SpecialType.System_Boolean)
            { leaves.Add((accessor, offset, type)); return true; }
            if (type is INamedTypeSymbol nts && nts.IsValueType)
            {
                if (IsBlittableStruct(nts)) { leaves.Add((accessor, offset, type)); return true; }
                int running = 0;
                foreach (var f in nts.GetMembers().OfType<IFieldSymbol>().Where(f => !f.IsStatic))
                {
                    int subOff = CppJobGenerator.CalculateFieldOffset(f, ref running);
                    if (f.Type.IsReferenceType)
                    {
                        leaves.Add(("", offset + subOff, null));   // 寮曠敤妲斤細8B 闆跺～鍏咃紙C++ 涓?void*锛孍xecute 涓嶅簲璁块棶锛?
                        continue;
                    }
                    string child = accessor.Length == 0 ? f.Name : accessor + "." + f.Name;
                    if (!CollectLeaves(leaves, child, f.Type, offset + subOff)) return false;
                }
                return true;
            }
            return false;
        }

        /// <summary>struct 鏄惁 blittable锛堥€掑綊锛氭寚閽?鏍囬噺/鏋氫妇/浠呭惈杩欎簺鐨勫祵濂?struct锛夆€斺€擠ebug sentinel 鍚?GC 寮曠敤锛岄潪 blittable</summary>
        private static bool IsBlittableStruct(INamedTypeSymbol structType)
        {
            foreach (var member in structType.GetMembers().OfType<IFieldSymbol>().Where(f => !f.IsStatic))
            {
                if (member.Type is IPointerTypeSymbol) continue;
                if (member.Type.TypeKind == TypeKind.Enum) continue;
                var st = member.Type.SpecialType;
                if (st is SpecialType.System_Single or SpecialType.System_Int32
                    or SpecialType.System_UInt32 or SpecialType.System_Boolean
                    or SpecialType.System_Int64 or SpecialType.System_UInt64
                    or SpecialType.System_Double or SpecialType.System_Byte
                    or SpecialType.System_SByte or SpecialType.System_Int16
                    or SpecialType.System_UInt16 or SpecialType.System_Char) continue;
                if (member.Type is INamedTypeSymbol nested && nested.IsValueType)
                {
                    if (IsBlittableStruct(nested)) continue;
                    return false;
                }
                return false;   // 寮曠敤绫诲瀷/鍏朵粬 鈫?闈?blittable
            }
            return true;
        }

        /// <summary>鐢熸垚閫愬瓧娈垫樉寮忓啓鍏ヨ鍙ワ細{srcExpr}.{accessor} 鍐欏埌 {dstExpr} + 鍋忕Щ锛堜笉渚濊禆 struct 杩愯鏃跺竷灞€锛?/summary>
        private static void EmitExplicitFieldWrites(StringBuilder sb,
            List<(string accessor, int offset, ITypeSymbol type)> leaves, string dstExpr, string srcExpr)
        {
            foreach (var (accessor, off, type) in leaves)
            {
                if (type == null)
                {
                    // 寮曠敤妲斤紙object/string 绛夛級锛?B 闆跺～鍏咃紙C++ 渚т负 void*锛孍xecute 涓嶅簲璁块棶锛?
                    sb.AppendLine($"            *((long*)({dstExpr} + {off})) = 0;");
                    continue;
                }
                if (NativeTranspiler.IsEntJoyNativeContainerType(type))
                {
                    if (type.Name == "NativeArray")
                    {
                        // NativeArray锛氭樉寮忓啓 buffer@off / length@off+8锛堜笌 Adapter 璇诲彇涓€鑷达級
                        sb.AppendLine($"            *((void**)({dstExpr} + {off})) = (void*){srcExpr}.{accessor}.GetUnsafePtr();");
                        sb.AppendLine($"            *((int*)({dstExpr} + {off + 8})) = {srcExpr}.{accessor}.Length;");
                    }
                    else if (type.Name == "NativeList")
                    {
                        // NativeList锛歘listData锛圲nsafeList*锛屽爢涓婄ǔ瀹氾級鍦ㄥ亸绉?0锛孋++ 瑙ｅ紩鐢ㄨ鍙?
                        sb.AppendLine($"            *((void**)({dstExpr} + {off})) = (void*){srcExpr}.{accessor}.GetListData();");
                    }
                    else // UnsafeList锛堝€煎瓧娈碉級锛欳++ 鍙?&blob[off] 涓?UnsafeList* 鈫?鍐呰仈鍐?Ptr/Length/Capacity/Allocator
                    {
                        sb.AppendLine($"            *((void**)({dstExpr} + {off})) = (void*){srcExpr}.{accessor}.Ptr;");
                        sb.AppendLine($"            *((int*)({dstExpr} + {off + 8})) = {srcExpr}.{accessor}.Length;");
                        sb.AppendLine($"            *((int*)({dstExpr} + {off + 12})) = {srcExpr}.{accessor}.Capacity;");
                        sb.AppendLine($"            *((int*)({dstExpr} + {off + 16})) = (int){srcExpr}.{accessor}.Allocator;");
                    }
                }
                else if (type is IPointerTypeSymbol)
                {
                    // 鎸囬拡瀛楁锛氬啓鎸囬拡鍊硷紙鍚屼竴杩涚▼鍦板潃绌洪棿锛孋++ 鐩存帴瑙ｅ紩鐢紱鎸囧悜鍐呭瓨椤婚潪鎵樼/鍥哄畾涓斿湪 Job 鏈熼棿瀛樻椿锛?
                    sb.AppendLine($"            *((void**)({dstExpr} + {off})) = (void*){srcExpr}.{accessor};");
                }
                else if (type.TypeKind == TypeKind.Enum && type is INamedTypeSymbol enumSym)
                {
                    string underlying = enumSym.EnumUnderlyingType.SpecialType == SpecialType.System_UInt32 ? "uint" : "int";
                    sb.AppendLine($"            *(({underlying}*)({dstExpr} + {off})) = ({underlying}){srcExpr}.{accessor};");
                }
                else if (type.SpecialType == SpecialType.System_Single)
                {
                    sb.AppendLine($"            *((float*)({dstExpr} + {off})) = {srcExpr}.{accessor};");
                }
                else if (type.SpecialType == SpecialType.System_Int32)
                {
                    sb.AppendLine($"            *((int*)({dstExpr} + {off})) = {srcExpr}.{accessor};");
                }
                else if (type.SpecialType == SpecialType.System_UInt32)
                {
                    sb.AppendLine($"            *((uint*)({dstExpr} + {off})) = {srcExpr}.{accessor};");
                }
                else if (type.SpecialType == SpecialType.System_Boolean)
                {
                    sb.AppendLine($"            *((byte*)({dstExpr} + {off})) = (byte)({srcExpr}.{accessor} ? 1 : 0);");
                }
                else
                {
                    // blittable 鍊?struct锛坒loat2/鐢ㄦ埛绾€肩粨鏋勭瓑锛夛細Unsafe.Write 鐩村啓锛坆littable 鈫?Sequential 鐢熸晥锛?
                    sb.AppendLine($"            System.Runtime.CompilerServices.Unsafe.Write((void*)({dstExpr} + {off}), {srcExpr}.{accessor});");
                }
            }
        }

        /// <summary>
        /// 鐢熸垚 Job 瀛楁鏄惧紡鍐欏叆鍣紙chunk 璺緞 CreateChunkContextBlock 鐢級锛?
        /// 浠ョ被鍨嬪寲 ref 璇诲彇閫昏緫瀛楁鍊硷紙甯冨眬鏃犲叧锛夛紝鏄惧紡鍐欏埌 C++ context 鍋忕Щ銆?
        /// </summary>
        private static void GenerateJobFieldWriterMethod(StringBuilder sb, INamedTypeSymbol jobStruct)
        {
            var (marshalled, explicitOk, _) = ComputeJobFieldMarshal(jobStruct);
            if (!explicitOk) return;   // 鍚笉鏀寔瀛楁锛氫笉娉ㄥ唽锛宑hunk 璺緞鍥為€€瑁告嫹璐?
            string jobTypeName = jobStruct.ToDisplayString();
            sb.AppendLine($"        internal static void WriteJobFields_{jobStruct.Name}(byte* dst, ref {jobTypeName} job)");
            sb.AppendLine("        {");
            EmitExplicitFieldWrites(sb, marshalled, "dst", "job");
            sb.AppendLine("        }");
            sb.AppendLine();
        }

        private static void GenerateJobExtensionMethod(StringBuilder sb, INamedTypeSymbol jobStruct)
        {
            bool isChunk = CppJobGenerator.IsChunkScheduledJob(jobStruct);
            bool isParallelFor = CppJobGenerator.IsParallelForJob(jobStruct);
            bool isFor = CppJobGenerator.IsForJob(jobStruct);
            string jobTypeName = jobStruct.ToDisplayString();

            if (isChunk)
            {
                sb.AppendLine($"    public static JobHandle Schedule(this {jobTypeName} job, QueryBuilder query, JobHandle dependsOn = default)");
                sb.AppendLine("    {");
                sb.AppendLine($"        return NativeTranspiler.Bindings.NativeExports.Schedule_{jobStruct.Name}(ref job, query, dependsOn);");
                sb.AppendLine("    }");
                sb.AppendLine();
                sb.AppendLine($"    public static JobHandle ScheduleWithWorkerCap(this {jobTypeName} job, QueryBuilder query, int workerCap, JobHandle dependsOn = default)");
                sb.AppendLine("    {");
                sb.AppendLine($"        return NativeTranspiler.Bindings.NativeExports.ScheduleWithWorkerCap_{jobStruct.Name}(ref job, query, workerCap, dependsOn);");
                sb.AppendLine("    }");
                sb.AppendLine();
                sb.AppendLine($"    public static JobHandle ScheduleWithWorkerCapAndRangeSize(this {jobTypeName} job, QueryBuilder query, int workerCap, int rangeSize, JobHandle dependsOn = default)");
                sb.AppendLine("    {");
                sb.AppendLine($"        return NativeTranspiler.Bindings.NativeExports.ScheduleWithWorkerCapAndRangeSize_{jobStruct.Name}(ref job, query, workerCap, rangeSize, dependsOn);");
                sb.AppendLine("    }");
                sb.AppendLine();
                sb.AppendLine($"    public static void RunImmediate(this {jobTypeName} job, QueryBuilder query)");
                sb.AppendLine("    {");
                sb.AppendLine($"        NativeTranspiler.Bindings.NativeExports.RunImmediate_{jobStruct.Name}(ref job, query);");
                sb.AppendLine("    }");
                sb.AppendLine();
            }
            else if (isParallelFor || isFor)
            {
                // ParallelFor/For: keep optional dependsOn (existing generic Schedule<T> has arrayLength params, no collision)
                var parameters = new List<string>
                {
                    $"this {jobTypeName} job",
                    "int arrayLength",
                    "int innerBatchCount = 0",
                    "JobHandle dependsOn = default"
                };
                sb.AppendLine($"    public static JobHandle Schedule({string.Join(", ", parameters)})");
                sb.AppendLine("    {");
                sb.AppendLine($"        return NativeTranspiler.Bindings.NativeExports.Schedule_{jobStruct.Name}(ref job, arrayLength, innerBatchCount, dependsOn);");
                sb.AppendLine("    }");
                sb.AppendLine();
            }
            else
            {
                // IJob: generate two overloads (no-arg and dependsOn) to beat existing Schedule<T>(this T job)
                sb.AppendLine($"    public static JobHandle Schedule(this {jobTypeName} job)");
                sb.AppendLine("    {");
                sb.AppendLine($"        return NativeTranspiler.Bindings.NativeExports.Schedule_{jobStruct.Name}(ref job, default);");
                sb.AppendLine("    }");
                sb.AppendLine();
                sb.AppendLine($"    public static JobHandle Schedule(this {jobTypeName} job, JobHandle dependsOn)");
                sb.AppendLine("    {");
                sb.AppendLine($"        return NativeTranspiler.Bindings.NativeExports.Schedule_{jobStruct.Name}(ref job, dependsOn);");
                sb.AppendLine("    }");
                sb.AppendLine();
            }
        }

        private static void GenerateJobRunMethod(StringBuilder sb, INamedTypeSymbol jobStruct, Compilation compilation)
        {
            bool isChunk = CppJobGenerator.IsChunkScheduledJob(jobStruct);
            bool isParallelFor = CppJobGenerator.IsParallelForJob(jobStruct);
            bool isFor = CppJobGenerator.IsForJob(jobStruct);
            string jobTypeName = jobStruct.ToDisplayString();

            var parameters = new List<string>();
            // Must match existing JobExtensions signature (this T job) to take precedence in overload resolution
            parameters.Add($"this {jobTypeName} job");
            if (isChunk)
            {
                parameters.Add("QueryBuilder query");
            }
            else if (isParallelFor || isFor)
            {
                parameters.Add("int arrayLength");
            }

            sb.AppendLine($"    public static void Run({string.Join(", ", parameters)})");
            sb.AppendLine("    {");
            if (isChunk)
            {
                sb.AppendLine($"        NativeTranspiler.Bindings.NativeExports.Schedule_{jobStruct.Name}(ref job, query, default).Complete();");
            }
            else if (isParallelFor || isFor)
            {
                sb.AppendLine($"        int startIndex = 0;");
                sb.AppendLine($"        int count = arrayLength;");
                sb.AppendLine($"        unsafe");
                sb.AppendLine($"        {{");
                sb.AppendLine($"            {jobTypeName}* jobPtr = &job;");
                sb.AppendLine($"            {{");

                var executeMethod = jobStruct.GetMembers().OfType<IMethodSymbol>().First(m => m.Name == "Execute");
                var methodSyntax = SymbolHelper.GetMethodSyntax(executeMethod);
                bool hasMultiVersion = false;
                string boolFieldName = null;
                if (methodSyntax != null)
                {
                    var semanticModel = compilation.GetSemanticModel(methodSyntax.SyntaxTree);
                    var conditionalFields = NativeTranspileValidator.GetConditionalReadOnlyFields(jobStruct, semanticModel);
                    var boolField = conditionalFields.FirstOrDefault(f => f.Type.SpecialType == SpecialType.System_Boolean);
                    if (boolField != null)
                    {
                        hasMultiVersion = true;
                        boolFieldName = boolField.Name;
                    }
                }

                string batchArgs2 = BuildBatchCallArgs(jobStruct, "jobPtr");
                string batchArgsWithComma2 = string.IsNullOrEmpty(batchArgs2) ? "" : ", " + batchArgs2;
                if (hasMultiVersion)
                {
                    sb.AppendLine($"                if (jobPtr->{boolFieldName})");
                    sb.AppendLine($"                    NativeTranspiler.Bindings.NativeExports.{jobStruct.Name}_Execute_Batch_true(startIndex, count{batchArgsWithComma2});");
                    sb.AppendLine($"                else");
                    sb.AppendLine($"                    NativeTranspiler.Bindings.NativeExports.{jobStruct.Name}_Execute_Batch_false(startIndex, count{batchArgsWithComma2});");
                }
                else
                {
                    sb.AppendLine($"                NativeTranspiler.Bindings.NativeExports.{jobStruct.Name}_Execute_Batch(startIndex, count{batchArgsWithComma2});");
                }
                sb.AppendLine($"            }}");
                sb.AppendLine($"        }}");
            }
            else
            {
                sb.AppendLine($"        unsafe");
                sb.AppendLine($"        {{");
                sb.AppendLine($"            {jobTypeName}* jobPtr = &job;");
                sb.AppendLine($"            {{");
                var args = BuildJobExecuteArgsForFixed(jobStruct);
                sb.AppendLine($"                NativeTranspiler.Bindings.NativeExports.{jobStruct.Name}_Execute({string.Join(", ", args)});");
                sb.AppendLine($"            }}");
                sb.AppendLine($"        }}");
            }
            sb.AppendLine("    }");
            sb.AppendLine();
        }

        private static List<string> BuildJobExecuteArgsForFixed(INamedTypeSymbol jobStruct)
        {
            var args = new List<string>();
            foreach (var field in jobStruct.GetMembers().OfType<IFieldSymbol>().Where(f => !f.IsStatic))
            {
                if (NativeTranspiler.IsEntJoyNativeContainerType(field.Type))
                {
                    if (field.Type.Name == "NativeList")
                    {
                        args.Add($"jobPtr->{field.Name}.GetListData()");
                    }
                    else
                    {
                        var elementType = ((INamedTypeSymbol)field.Type).TypeArguments[0];
                        var csElementType = elementType.ToDisplayString(SymbolDisplayFormat.FullyQualifiedFormat);
                        args.Add($"({csElementType}*)jobPtr->{field.Name}.GetUnsafePtr(), jobPtr->{field.Name}.Length");
                    }
                }
                else
                {
                    if (field.Type is IPointerTypeSymbol)
                        args.Add($"jobPtr->{field.Name}");
                    else
                        args.Add($"&jobPtr->{field.Name}");
                }
            }
            return args;
        }

        private static string GetCSharpParameterType(IParameterSymbol param)
        {
            var typeName = param.Type.ToDisplayString(SymbolDisplayFormat.FullyQualifiedFormat);
            return param.RefKind switch
            {
                RefKind.Ref => "ref " + typeName,
                RefKind.In => "in " + typeName,
                RefKind.Out => "out " + typeName,
                _ => typeName
            };
        }

        private static string GenerateCleanupFactoryMethod()
        {
            return @"
        private static CleanupFuncDelegate CreateCleanup<T>(int size) where T : struct
        {
            return context =>
            {
                IntPtr native = (IntPtr)context;
                Marshal.FreeHGlobal(native);
            };
        }";
        }

    }
}
