using Microsoft.CodeAnalysis;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using NativeTranspiler.Analyzer.Common;

namespace NativeTranspiler.Analyzer
{
    public static class BindingsGenerator
    {
        public static string GenerateBindingsClass(
            IEnumerable<IMethodSymbol> methods,
            IEnumerable<INamedTypeSymbol> jobStructs,
            Compilation compilation)
        {
            var sb = new StringBuilder();
            sb.AppendLine("// <auto-generated/>");
            sb.AppendLine("using System;");
            sb.AppendLine("using System.Runtime.InteropServices;");
            sb.AppendLine("using System.Runtime.CompilerServices;");
            sb.AppendLine("using EntJoy.Collections;");
            sb.AppendLine();
            sb.AppendLine("namespace NativeTranspiler.Bindings");
            sb.AppendLine("{");
            sb.AppendLine("    public static unsafe partial class NativeExports");
            sb.AppendLine("    {");
            sb.AppendLine("        public delegate void JobFuncDelegate(IntPtr context);");
            sb.AppendLine("        public delegate void BatchJobFuncDelegate(IntPtr context, int startIndex, int count);");
            sb.AppendLine("        public delegate void CleanupFuncDelegate(IntPtr context);");
            sb.AppendLine();

            var attrSymbol = compilation.GetTypeByMetadataName("NativeTranspiler.NativeTranspileAttribute");

            // 1. 为每个 Job 结构体生成静态缓存的委托字段和函数指针
            foreach (var jobStruct in jobStructs)
            {
                GenerateStaticDelegateFields(sb, jobStruct);
            }

            // 2. 静态构造函数：初始化所有缓存的委托和函数指针
            sb.AppendLine("        static NativeExports()");
            sb.AppendLine("        {");
            foreach (var jobStruct in jobStructs)
            {
                GenerateStaticConstructorInitialization(sb, jobStruct, compilation);
            }
            sb.AppendLine("        }");
            sb.AppendLine();

            // 3. 普通方法的 DllImport 和 Wrapper（自动内联 MT 选择）
            foreach (var method in methods)
            {
                GenerateMethodDllImport(sb, method);
                bool useMT = HasUseISPC_MT(method, attrSymbol);
                if (useMT)
                {
                    GenerateMethodDllImportMT(sb, method);
                }
                GenerateMethodWrapper(sb, method, useMT);
            }

            // 4. Job 结构体的 DllImport 和 Schedule 方法
            foreach (var jobStruct in jobStructs)
            {
                GenerateJobDllImport(sb, jobStruct, compilation);
                GenerateJobScheduleMethod(sb, jobStruct, compilation);
            }

            sb.AppendLine(GenerateCleanupFactoryMethod());
            sb.AppendLine("    }");
            sb.AppendLine("}");
            sb.AppendLine();

            // 5. Job 扩展方法（Schedule 和 Run）
            sb.AppendLine("public static partial class JobExtensions");
            sb.AppendLine("{");
            foreach (var jobStruct in jobStructs)
            {
                GenerateJobExtensionMethod(sb, jobStruct);
                GenerateJobRunMethod(sb, jobStruct, compilation);
            }
            sb.AppendLine("}");

            return sb.ToString();
        }

        private static bool HasUseISPC_MT(ISymbol symbol, INamedTypeSymbol? attrSymbol)
            => AttributeHelper.HasUseISPC_MT(symbol, attrSymbol);

        // ---------- 方法 DllImport ----------
        private static void GenerateMethodDllImport(StringBuilder sb, IMethodSymbol method)
        {
            var cppFunctionName = CppGenerator.GetCppFunctionName(method);
            var returnType = method.ReturnType.ToDisplayString(SymbolDisplayFormat.FullyQualifiedFormat);
            var methodName = method.Name + "_Native";
            var parameters = BuildMethodDllImportParams(method);
            sb.AppendLine($"        [DllImport(\"NativeTranspiler_Generated\", EntryPoint = \"{cppFunctionName}\", CallingConvention = CallingConvention.Cdecl)]");
            sb.AppendLine($"        private static extern {returnType} {methodName}({string.Join(", ", parameters)});");
            sb.AppendLine();
        }

        private static void GenerateMethodDllImportMT(StringBuilder sb, IMethodSymbol method)
        {
            var cppFunctionName = CppGenerator.GetCppFunctionName(method) + "_mt";
            var returnType = method.ReturnType.ToDisplayString(SymbolDisplayFormat.FullyQualifiedFormat);
            var methodName = method.Name + "_mt_Native";
            var parameters = BuildMethodDllImportParams(method);
            parameters.Add("int numTasks");
            sb.AppendLine($"        [DllImport(\"NativeTranspiler_Generated\", EntryPoint = \"{cppFunctionName}\", CallingConvention = CallingConvention.Cdecl)]");
            sb.AppendLine($"        private static extern {returnType} {methodName}({string.Join(", ", parameters)});");
            sb.AppendLine();
        }

        private static void GenerateMethodWrapper(StringBuilder sb, IMethodSymbol method, bool useMT)
        {
            var returnType = method.ReturnType.ToDisplayString(SymbolDisplayFormat.FullyQualifiedFormat);
            var methodName = method.Name;
            var parameters = method.Parameters.Select(p => $"{GetCSharpParameterType(p)} {p.Name}");
            sb.AppendLine($"        public static {returnType} {methodName}({string.Join(", ", parameters)})");
            sb.AppendLine("        {");
            sb.AppendLine("            unsafe {");
            if (method.ReturnType.SpecialType != SpecialType.System_Void)
                sb.Append("            return ");
            else
                sb.Append("            ");

            if (useMT)
            {
                sb.Append($"{methodName}_mt_Native(");
                var args = BuildMethodCallArgs(method);
                args.Add("Environment.ProcessorCount");
                sb.Append(string.Join(", ", args));
            }
            else
            {
                sb.Append($"{methodName}_Native(");
                var args = BuildMethodCallArgs(method);
                sb.Append(string.Join(", ", args));
            }
            sb.AppendLine(");");
            sb.AppendLine("            }");
            sb.AppendLine("        }");
            sb.AppendLine();
        }

        // ---------- Job 委托字段 ----------
        private static void GenerateStaticDelegateFields(StringBuilder sb, INamedTypeSymbol jobStruct)
        {
            bool isParallelFor = CppJobGenerator.IsParallelForJob(jobStruct);
            bool isFor = CppJobGenerator.IsForJob(jobStruct);

            if (isParallelFor || isFor)
            {
                sb.AppendLine($"        private static readonly BatchJobFuncDelegate s_{jobStruct.Name}_BatchFunc;");
                sb.AppendLine($"        private static readonly IntPtr s_{jobStruct.Name}_BatchFuncPtr;");
            }
            else
            {
                sb.AppendLine($"        private static readonly JobFuncDelegate s_{jobStruct.Name}_JobFunc;");
                sb.AppendLine($"        private static readonly IntPtr s_{jobStruct.Name}_JobFuncPtr;");
            }
            sb.AppendLine($"        private static readonly CleanupFuncDelegate s_{jobStruct.Name}_CleanupFunc;");
            sb.AppendLine($"        private static readonly IntPtr s_{jobStruct.Name}_CleanupFuncPtr;");
            sb.AppendLine();
        }

        private static void GenerateStaticConstructorInitialization(StringBuilder sb, INamedTypeSymbol jobStruct, Compilation compilation)
        {
            string jobTypeFullName = jobStruct.ToDisplayString();
            bool isParallelFor = CppJobGenerator.IsParallelForJob(jobStruct);
            bool isFor = CppJobGenerator.IsForJob(jobStruct);

            var executeMethod = jobStruct.GetMembers().OfType<IMethodSymbol>().First(m => m.Name == "Execute");
            var methodSyntax = SymbolHelper.GetMethodSyntax(executeMethod);
            bool hasMultiVersion = false;
            string boolFieldName = null;

            var attrSymbol = compilation.GetTypeByMetadataName("NativeTranspiler.NativeTranspileAttribute");
            bool useMT = HasUseISPC_MT(jobStruct, attrSymbol);

            if (methodSyntax != null)
            {
                var semanticModel = compilation.GetSemanticModel(methodSyntax.SyntaxTree);
                var conditionalFields = NativeTranspileValidator.GetConditionalReadOnlyFields(jobStruct, semanticModel);
                var boolField = conditionalFields.FirstOrDefault(f => f.Type.SpecialType == SpecialType.System_Boolean);
                if (boolField != null)
                {
                    hasMultiVersion = true;
                    boolFieldName = boolField.Name;
                }
            }

            if (isParallelFor || isFor)
            {
                string mtSuffix = useMT ? "_mt" : "";

                sb.AppendLine($"            s_{jobStruct.Name}_BatchFunc = (IntPtr context, int startIndex, int count) =>");
                sb.AppendLine("            {");
                sb.AppendLine($"                var jobPtr = ({jobTypeFullName}*)context;");

                string batchArgs = BuildBatchCallArgs(jobStruct, "jobPtr");
                string batchArgsWithComma = string.IsNullOrEmpty(batchArgs) ? "" : ", " + batchArgs;
                if (hasMultiVersion)
                {
                    sb.AppendLine($"                if (jobPtr->{boolFieldName})");
                    sb.AppendLine($"                    {jobStruct.Name}_Execute_Batch_true{mtSuffix}(startIndex, count{batchArgsWithComma});");
                    sb.AppendLine($"                else");
                    sb.AppendLine($"                    {jobStruct.Name}_Execute_Batch_false{mtSuffix}(startIndex, count{batchArgsWithComma});");
                }
                else
                {
                    sb.AppendLine($"                {jobStruct.Name}_Execute_Batch{mtSuffix}(startIndex, count{batchArgsWithComma});");
                }
                sb.AppendLine("            };");
                sb.AppendLine($"            s_{jobStruct.Name}_BatchFuncPtr = Marshal.GetFunctionPointerForDelegate(s_{jobStruct.Name}_BatchFunc);");
            }
            else
            {
                sb.AppendLine($"            s_{jobStruct.Name}_JobFunc = (IntPtr context) =>");
                sb.AppendLine("            {");
                sb.AppendLine($"                var jobPtr = ({jobTypeFullName}*)context;");
                var args = BuildJobExecuteArgsForPointer(jobStruct);
                sb.AppendLine($"                {jobStruct.Name}_Execute({string.Join(", ", args)});");
                sb.AppendLine("            };");
                sb.AppendLine($"            s_{jobStruct.Name}_JobFuncPtr = Marshal.GetFunctionPointerForDelegate(s_{jobStruct.Name}_JobFunc);");
            }

            sb.AppendLine($"            s_{jobStruct.Name}_CleanupFunc = (IntPtr context) =>");
            sb.AppendLine("            {");
            sb.AppendLine("                Marshal.FreeHGlobal(context);");
            sb.AppendLine("            };");
            sb.AppendLine($"            s_{jobStruct.Name}_CleanupFuncPtr = Marshal.GetFunctionPointerForDelegate(s_{jobStruct.Name}_CleanupFunc);");
            sb.AppendLine();
        }

        private static void GenerateJobDllImport(StringBuilder sb, INamedTypeSymbol jobStruct, Compilation compilation)
        {
            bool isParallelFor = CppJobGenerator.IsParallelForJob(jobStruct);
            bool isFor = CppJobGenerator.IsForJob(jobStruct);

            var attrSymbol = compilation.GetTypeByMetadataName("NativeTranspiler.NativeTranspileAttribute");
            bool useMT = HasUseISPC_MT(jobStruct, attrSymbol);

            if (isParallelFor || isFor)
            {
                var batchFuncName = CppJobGenerator.GetCppJobFunctionName(jobStruct, isBatch: true);
                var batchParams = BuildBatchJobDllImportParams(jobStruct);

                var executeMethod = jobStruct.GetMembers().OfType<IMethodSymbol>().First(m => m.Name == "Execute");
                var methodSyntax = SymbolHelper.GetMethodSyntax(executeMethod);
                bool hasMultiVersion = false;
                if (methodSyntax != null)
                {
                    var semanticModel = compilation.GetSemanticModel(methodSyntax.SyntaxTree);
                    var conditionalFields = NativeTranspileValidator.GetConditionalReadOnlyFields(jobStruct, semanticModel);
                    hasMultiVersion = conditionalFields.Any(f => f.Type.SpecialType == SpecialType.System_Boolean);
                }

                if (hasMultiVersion)
                {
                    sb.AppendLine($"        [DllImport(\"NativeTranspiler_Generated\", EntryPoint = \"{batchFuncName}_true\", CallingConvention = CallingConvention.Cdecl)]");
                    sb.AppendLine($"        public static extern void {jobStruct.Name}_Execute_Batch_true({string.Join(", ", batchParams)});");
                    sb.AppendLine($"        [DllImport(\"NativeTranspiler_Generated\", EntryPoint = \"{batchFuncName}_false\", CallingConvention = CallingConvention.Cdecl)]");
                    sb.AppendLine($"        public static extern void {jobStruct.Name}_Execute_Batch_false({string.Join(", ", batchParams)});");
                }
                else
                {
                    sb.AppendLine($"        [DllImport(\"NativeTranspiler_Generated\", EntryPoint = \"{batchFuncName}\", CallingConvention = CallingConvention.Cdecl)]");
                    sb.AppendLine($"        public static extern void {jobStruct.Name}_Execute_Batch({string.Join(", ", batchParams)});");
                }

                if (useMT)
                {
                    if (hasMultiVersion)
                    {
                        sb.AppendLine($"        [DllImport(\"NativeTranspiler_Generated\", EntryPoint = \"{batchFuncName}_true_mt\", CallingConvention = CallingConvention.Cdecl)]");
                        sb.AppendLine($"        private static extern void {jobStruct.Name}_Execute_Batch_true_mt({string.Join(", ", batchParams)});");
                        sb.AppendLine($"        [DllImport(\"NativeTranspiler_Generated\", EntryPoint = \"{batchFuncName}_false_mt\", CallingConvention = CallingConvention.Cdecl)]");
                        sb.AppendLine($"        private static extern void {jobStruct.Name}_Execute_Batch_false_mt({string.Join(", ", batchParams)});");
                    }
                    else
                    {
                        sb.AppendLine($"        [DllImport(\"NativeTranspiler_Generated\", EntryPoint = \"{batchFuncName}_mt\", CallingConvention = CallingConvention.Cdecl)]");
                        sb.AppendLine($"        private static extern void {jobStruct.Name}_Execute_Batch_mt({string.Join(", ", batchParams)});");
                    }
                }
            }
            else
            {
                var singleFuncName = CppJobGenerator.GetCppJobFunctionName(jobStruct);
                var singleParams = BuildJobDllImportParams(jobStruct);
                sb.AppendLine($"        [DllImport(\"NativeTranspiler_Generated\", EntryPoint = \"{singleFuncName}\", CallingConvention = CallingConvention.Cdecl)]");
                sb.AppendLine($"        public static extern void {jobStruct.Name}_Execute({string.Join(", ", singleParams)});");
            }
            sb.AppendLine();
        }

        // ---------- Job Schedule 方法 ----------
        private static void GenerateJobScheduleMethod(StringBuilder sb, INamedTypeSymbol jobStruct, Compilation compilation)
        {
            bool isParallelFor = CppJobGenerator.IsParallelForJob(jobStruct);
            bool isFor = CppJobGenerator.IsForJob(jobStruct);
            string jobTypeName = jobStruct.ToDisplayString();

            var attrSymbol = compilation.GetTypeByMetadataName("NativeTranspiler.NativeTranspileAttribute");
            bool useMT = HasUseISPC_MT(jobStruct, attrSymbol);

            var parameters = new List<string>();
            // Use 'ref' for the internal Schedule_XXX method (caller already has a reference)
            parameters.Add($"ref {jobTypeName} job");
            if (isParallelFor || isFor)
            {
                parameters.Add("int arrayLength");
                // IJobFor 也允许指定 innerBatchCount，保持接口统一
                parameters.Add("int innerBatchCount = 0");
            }
            parameters.Add("JobHandle dependsOn = default");

            sb.AppendLine($"        public static JobHandle Schedule_{jobStruct.Name}({string.Join(", ", parameters)})");
            sb.AppendLine("        {");
            sb.AppendLine($"            int size = sizeof({jobTypeName});");
            sb.AppendLine($"            IntPtr nativePtr = Marshal.AllocHGlobal(size);");
            sb.AppendLine($"            void* originalPtr = Unsafe.AsPointer(ref job);");
            sb.AppendLine($"            Unsafe.CopyBlockUnaligned((void*)nativePtr, originalPtr, (uint)size);");
            sb.AppendLine();

            if (isParallelFor || isFor)
            {
                // 自适应批次大小
                if (useMT)
                {
                    sb.AppendLine($"            int actualBatchSize = innerBatchCount > 0 ? innerBatchCount : arrayLength;");
                }
                else
                {
                    sb.AppendLine($"            int defaultBatchSize = Math.Min(arrayLength, Math.Max(1, 32 * Environment.ProcessorCount));");
                    sb.AppendLine($"            int actualBatchSize = innerBatchCount > 0 ? innerBatchCount : defaultBatchSize;");
                }

                sb.AppendLine($"            NativeJobHandle nativeHandle = NativeJobScheduler.ScheduleParallelForBatchRaw(");
                sb.AppendLine($"                s_{jobStruct.Name}_BatchFuncPtr, nativePtr, s_{jobStruct.Name}_CleanupFuncPtr, arrayLength, actualBatchSize, dependsOn._nativeHandle);");
                sb.AppendLine($"            return new JobHandle(nativeHandle);");
            }
            else
            {
                sb.AppendLine($"            NativeJobHandle nativeHandle = NativeJobScheduler.ScheduleRaw(");
                sb.AppendLine($"                s_{jobStruct.Name}_JobFuncPtr, nativePtr, s_{jobStruct.Name}_CleanupFuncPtr, dependsOn._nativeHandle);");
                sb.AppendLine($"            return new JobHandle(nativeHandle);");
            }
            sb.AppendLine("        }");
            sb.AppendLine();
        }

        // ---------- 辅助：构建参数列表 ----------
        private static List<string> BuildMethodDllImportParams(IMethodSymbol method)
        {
            var parameters = new List<string>();
            foreach (var param in method.Parameters)
            {
                if (NativeTranspiler.IsEntJoyNativeContainerType(param.Type))
                {
                    if (param.Type.Name == "NativeList")
                    {
                        var elementType = ((INamedTypeSymbol)param.Type).TypeArguments[0];
                        var csElementType = elementType.ToDisplayString(SymbolDisplayFormat.FullyQualifiedFormat);
                        parameters.Add($"EntJoy.Collections.UnsafeList<{csElementType}>* {param.Name}_listData");
                    }
                    else
                    {
                        var elementType = ((INamedTypeSymbol)param.Type).TypeArguments[0];
                        var csElementType = elementType.ToDisplayString(SymbolDisplayFormat.FullyQualifiedFormat);
                        parameters.Add($"{csElementType}* {param.Name}_ptr, int {param.Name}_length");
                    }
                }
                else if (param.Type is IPointerTypeSymbol)
                {
                    var cppType = NativeTranspiler.MapCSharpTypeToCpp(param.Type);  // 返回 "int*"
                    parameters.Add($"{cppType} {param.Name}_ptr");
                }
                else
                {
                    var csType = param.Type.ToDisplayString(SymbolDisplayFormat.FullyQualifiedFormat);
                    parameters.Add($"{csType}* {param.Name}_ptr");
                }
            }
            return parameters;
        }

        private static List<string> BuildMethodCallArgs(IMethodSymbol method)
        {
            var args = new List<string>();
            foreach (var param in method.Parameters)
            {
                if (NativeTranspiler.IsEntJoyNativeContainerType(param.Type))
                {
                    if (param.Type.Name == "NativeList")
                    {
                        args.Add($"{param.Name}.GetListData()");
                    }
                    else
                    {
                        var elementType = ((INamedTypeSymbol)param.Type).TypeArguments[0];
                        var csElementType = elementType.ToDisplayString(SymbolDisplayFormat.FullyQualifiedFormat);
                        args.Add($"({csElementType}*){param.Name}.GetUnsafePtr(), {param.Name}.Length");
                    }
                }
                else if (param.Type is IPointerTypeSymbol)
                {
                    args.Add(param.Name);
                }
                else
                {
                    var csType = param.Type.ToDisplayString(SymbolDisplayFormat.FullyQualifiedFormat);
                    args.Add($"({csType}*)Unsafe.AsPointer(ref {param.Name})");
                }
            }
            return args;
        }

        private static List<string> BuildJobDllImportParams(INamedTypeSymbol jobStruct)
        {
            var parameters = new List<string>();
            var executeMethod = jobStruct.GetMembers().OfType<IMethodSymbol>().First(m => m.Name == "Execute");
            if (executeMethod.Parameters.Length == 1 && executeMethod.Parameters[0].Type.SpecialType == SpecialType.System_Int32)
                parameters.Add($"int {executeMethod.Parameters[0].Name}");

            AppendFieldDllImportParams(jobStruct, parameters);
            return parameters;
        }

        private static List<string> BuildBatchJobDllImportParams(INamedTypeSymbol jobStruct)
        {
            var parameters = new List<string> { "int __startIndex", "int __count" };
            AppendFieldDllImportParams(jobStruct, parameters);
            return parameters;
        }

        private static void AppendFieldDllImportParams(INamedTypeSymbol jobStruct, List<string> parameters)
        {
            foreach (var field in jobStruct.GetMembers().OfType<IFieldSymbol>().Where(f => !f.IsStatic))
            {
                if (NativeTranspiler.IsEntJoyNativeContainerType(field.Type))
                {
                    if (field.Type.Name == "NativeList")
                    {
                        var elementType = ((INamedTypeSymbol)field.Type).TypeArguments[0];
                        var csElementType = elementType.ToDisplayString(SymbolDisplayFormat.FullyQualifiedFormat);
                        parameters.Add($"EntJoy.Collections.UnsafeList<{csElementType}>* {field.Name}_listData");
                    }
                    else
                    {
                        var elementType = ((INamedTypeSymbol)field.Type).TypeArguments[0];
                        var csElementType = elementType.ToDisplayString(SymbolDisplayFormat.FullyQualifiedFormat);
                        parameters.Add($"{csElementType}* {field.Name}_ptr, int {field.Name}_length");
                    }
                }
                else if (field.Type is IPointerTypeSymbol)
                {
                    var cppType = NativeTranspiler.MapCSharpTypeToCpp(field.Type);  // 返回 "int*"
                    parameters.Add($"{cppType} {field.Name}_ptr");
                }
                else
                {
                    var csType = field.Type.ToDisplayString(SymbolDisplayFormat.FullyQualifiedFormat);
                    parameters.Add($"{csType}* {field.Name}_ptr");
                }
            }
        }

        private static List<string> BuildJobExecuteArgsForPointer(INamedTypeSymbol jobStruct)
        {
            var args = new List<string>();
            foreach (var field in jobStruct.GetMembers().OfType<IFieldSymbol>().Where(f => !f.IsStatic))
            {
                if (NativeTranspiler.IsEntJoyNativeContainerType(field.Type))
                {
                    if (field.Type.Name == "NativeList")
                    {
                        args.Add($"jobPtr->{field.Name}.GetListData()");
                    }
                    else
                    {
                        var elementType = ((INamedTypeSymbol)field.Type).TypeArguments[0];
                        var csElementType = elementType.ToDisplayString(SymbolDisplayFormat.FullyQualifiedFormat);
                        args.Add($"({csElementType}*)jobPtr->{field.Name}.GetUnsafePtr(), jobPtr->{field.Name}.Length");
                    }
                }
                else
                {
                    if (field.Type is IPointerTypeSymbol)
                        args.Add($"jobPtr->{field.Name}");
                    else
                        args.Add($"&jobPtr->{field.Name}");
                }
            }
            return args;
        }

        private static string BuildBatchCallArgs(INamedTypeSymbol jobStruct, string jobPtrPrefix)
        {
            var args = new List<string>();
            foreach (var field in jobStruct.GetMembers().OfType<IFieldSymbol>().Where(f => !f.IsStatic))
            {
                if (NativeTranspiler.IsEntJoyNativeContainerType(field.Type))
                {
                    if (field.Type.Name == "NativeList")
                        args.Add($"{jobPtrPrefix}->{field.Name}.GetListData()");
                    else
                    {
                        var elementType = ((INamedTypeSymbol)field.Type).TypeArguments[0];
                        var csElementType = elementType.ToDisplayString(SymbolDisplayFormat.FullyQualifiedFormat);
                        args.Add($"({csElementType}*){jobPtrPrefix}->{field.Name}.GetUnsafePtr(), {jobPtrPrefix}->{field.Name}.Length");
                    }
                }
                else if (field.Type is IPointerTypeSymbol)
                {
                    args.Add($"{jobPtrPrefix}->{field.Name}");
                }
                else
                {
                    args.Add($"&{jobPtrPrefix}->{field.Name}");
                }
            }
            return string.Join(", ", args);
        }

        private static void GenerateJobExtensionMethod(StringBuilder sb, INamedTypeSymbol jobStruct)
        {
            bool isParallelFor = CppJobGenerator.IsParallelForJob(jobStruct);
            bool isFor = CppJobGenerator.IsForJob(jobStruct);
            string jobTypeName = jobStruct.ToDisplayString();

            if (isParallelFor || isFor)
            {
                // ParallelFor/For: keep optional dependsOn (existing generic Schedule<T> has arrayLength params, no collision)
                var parameters = new List<string>
                {
                    $"this {jobTypeName} job",
                    "int arrayLength",
                    "int innerBatchCount = 0",
                    "JobHandle dependsOn = default"
                };
                sb.AppendLine($"    public static JobHandle Schedule({string.Join(", ", parameters)})");
                sb.AppendLine("    {");
                sb.AppendLine($"        return NativeTranspiler.Bindings.NativeExports.Schedule_{jobStruct.Name}(ref job, arrayLength, innerBatchCount, dependsOn);");
                sb.AppendLine("    }");
                sb.AppendLine();
            }
            else
            {
                // IJob: generate two overloads (no-arg and dependsOn) to beat existing Schedule<T>(this T job)
                sb.AppendLine($"    public static JobHandle Schedule(this {jobTypeName} job)");
                sb.AppendLine("    {");
                sb.AppendLine($"        return NativeTranspiler.Bindings.NativeExports.Schedule_{jobStruct.Name}(ref job, default);");
                sb.AppendLine("    }");
                sb.AppendLine();
                sb.AppendLine($"    public static JobHandle Schedule(this {jobTypeName} job, JobHandle dependsOn)");
                sb.AppendLine("    {");
                sb.AppendLine($"        return NativeTranspiler.Bindings.NativeExports.Schedule_{jobStruct.Name}(ref job, dependsOn);");
                sb.AppendLine("    }");
                sb.AppendLine();
            }
        }

        private static void GenerateJobRunMethod(StringBuilder sb, INamedTypeSymbol jobStruct, Compilation compilation)
        {
            bool isParallelFor = CppJobGenerator.IsParallelForJob(jobStruct);
            bool isFor = CppJobGenerator.IsForJob(jobStruct);
            string jobTypeName = jobStruct.ToDisplayString();

            var parameters = new List<string>();
            // Must match existing JobExtensions signature (this T job) to take precedence in overload resolution
            parameters.Add($"this {jobTypeName} job");
            if (isParallelFor || isFor)
            {
                parameters.Add("int arrayLength");
            }

            sb.AppendLine($"    public static void Run({string.Join(", ", parameters)})");
            sb.AppendLine("    {");
            if (isParallelFor || isFor)
            {
                sb.AppendLine($"        int startIndex = 0;");
                sb.AppendLine($"        int count = arrayLength;");
                sb.AppendLine($"        unsafe");
                sb.AppendLine($"        {{");
                sb.AppendLine($"            {jobTypeName}* jobPtr = &job;");
                sb.AppendLine($"            {{");

                var executeMethod = jobStruct.GetMembers().OfType<IMethodSymbol>().First(m => m.Name == "Execute");
                var methodSyntax = SymbolHelper.GetMethodSyntax(executeMethod);
                bool hasMultiVersion = false;
                string boolFieldName = null;
                if (methodSyntax != null)
                {
                    var semanticModel = compilation.GetSemanticModel(methodSyntax.SyntaxTree);
                    var conditionalFields = NativeTranspileValidator.GetConditionalReadOnlyFields(jobStruct, semanticModel);
                    var boolField = conditionalFields.FirstOrDefault(f => f.Type.SpecialType == SpecialType.System_Boolean);
                    if (boolField != null)
                    {
                        hasMultiVersion = true;
                        boolFieldName = boolField.Name;
                    }
                }

                string batchArgs2 = BuildBatchCallArgs(jobStruct, "jobPtr");
                string batchArgsWithComma2 = string.IsNullOrEmpty(batchArgs2) ? "" : ", " + batchArgs2;
                if (hasMultiVersion)
                {
                    sb.AppendLine($"                if (jobPtr->{boolFieldName})");
                    sb.AppendLine($"                    NativeTranspiler.Bindings.NativeExports.{jobStruct.Name}_Execute_Batch_true(startIndex, count{batchArgsWithComma2});");
                    sb.AppendLine($"                else");
                    sb.AppendLine($"                    NativeTranspiler.Bindings.NativeExports.{jobStruct.Name}_Execute_Batch_false(startIndex, count{batchArgsWithComma2});");
                }
                else
                {
                    sb.AppendLine($"                NativeTranspiler.Bindings.NativeExports.{jobStruct.Name}_Execute_Batch(startIndex, count{batchArgsWithComma2});");
                }
                sb.AppendLine($"            }}");
                sb.AppendLine($"        }}");
            }
            else
            {
                sb.AppendLine($"        unsafe");
                sb.AppendLine($"        {{");
                sb.AppendLine($"            {jobTypeName}* jobPtr = &job;");
                sb.AppendLine($"            {{");
                var args = BuildJobExecuteArgsForFixed(jobStruct);
                sb.AppendLine($"                NativeTranspiler.Bindings.NativeExports.{jobStruct.Name}_Execute({string.Join(", ", args)});");
                sb.AppendLine($"            }}");
                sb.AppendLine($"        }}");
            }
            sb.AppendLine("    }");
            sb.AppendLine();
        }

        private static List<string> BuildJobExecuteArgsForFixed(INamedTypeSymbol jobStruct)
        {
            var args = new List<string>();
            foreach (var field in jobStruct.GetMembers().OfType<IFieldSymbol>().Where(f => !f.IsStatic))
            {
                if (NativeTranspiler.IsEntJoyNativeContainerType(field.Type))
                {
                    if (field.Type.Name == "NativeList")
                    {
                        args.Add($"jobPtr->{field.Name}.GetListData()");
                    }
                    else
                    {
                        var elementType = ((INamedTypeSymbol)field.Type).TypeArguments[0];
                        var csElementType = elementType.ToDisplayString(SymbolDisplayFormat.FullyQualifiedFormat);
                        args.Add($"({csElementType}*)jobPtr->{field.Name}.GetUnsafePtr(), jobPtr->{field.Name}.Length");
                    }
                }
                else
                {
                    if (field.Type is IPointerTypeSymbol)
                        args.Add($"jobPtr->{field.Name}");
                    else
                        args.Add($"&jobPtr->{field.Name}");
                }
            }
            return args;
        }

        private static string GetCSharpParameterType(IParameterSymbol param)
        {
            var typeName = param.Type.ToDisplayString(SymbolDisplayFormat.FullyQualifiedFormat);
            return param.RefKind switch
            {
                RefKind.Ref => "ref " + typeName,
                RefKind.In => "in " + typeName,
                RefKind.Out => "out " + typeName,
                _ => typeName
            };
        }

        private static string GenerateCleanupFactoryMethod()
        {
            return @"
        private static CleanupFuncDelegate CreateCleanup<T>(int size) where T : struct
        {
            return context =>
            {
                IntPtr native = (IntPtr)context;
                Marshal.FreeHGlobal(native);
            };
        }";
        }
    }
}
