using System;
using System.Collections.Generic;
using System.Text;

namespace EntJoy.SourceGenerator.Utils
{
    /// <summary>
    /// 宏定义
    /// </summary>
    internal class Def
    {
        public const string Dom_Generateds = "EntJoy.SourceGenerators.Generateds";
        public const string Dom_Declarations = "/// <summary>\r\n/// This is generated by tool, do not modify it manually.\r\n/// </summary>\r\n";
    }
}
