using Microsoft.CodeAnalysis;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using NativeTranspiler.Analyzer.Common;

namespace NativeTranspiler.Analyzer
{
    public static class BindingsGenerator
    {
        // DLL 分离后：生成代码（wrapper/adapter）编译进 NativeTranspiled.dll。
        // 核心 runtime（JobSystem 等）仍在 NativeDll.dll。
        private const string NativeLibraryName = "NativeTranspiled";

        public static string GenerateBindingsClass(
            IEnumerable<IMethodSymbol> methods,
            IEnumerable<INamedTypeSymbol> jobStructs,
            Compilation compilation)
        {
            var sb = new StringBuilder();
            sb.AppendLine("// <auto-generated/>");
            // job 结构含 NativeArray/NativeList（内含托管 DisposeSentinel）→ 托管类型。生成代码用
            // sizeof/取址/指针强转??job ??blittable 字段搬运/读到 native 侧，是验证过的安全模式；
            // CS8500（对托管类型取大??地址）为 false positive，按 Unity 生成 interop 代码惯例屏蔽??
            sb.AppendLine("#pragma warning disable CS8500");
            sb.AppendLine("using System;");
            sb.AppendLine("using System.Runtime.InteropServices;");
            sb.AppendLine("using System.Runtime.CompilerServices;");
            sb.AppendLine("using EntJoy.ECS;");
            sb.AppendLine("using EntJoy.ECS.JobSystem;");
            sb.AppendLine("using EntJoy.Collections;");
            sb.AppendLine("using EntJoy.JobSystem;");
            sb.AppendLine();
            sb.AppendLine("namespace NativeTranspiler.Bindings");
            sb.AppendLine("{");
            sb.AppendLine("    public static unsafe partial class NativeExports");
            sb.AppendLine("    {");
            sb.AppendLine("        public delegate void JobFuncDelegate(IntPtr context);");
            sb.AppendLine("        public delegate void BatchJobFuncDelegate(IntPtr context, int startIndex, int count);");
            sb.AppendLine("        public delegate void ChunkJobFuncDelegate(IntPtr context, ChunkJobData* chunkData);");
            sb.AppendLine("        public delegate void CleanupFuncDelegate(IntPtr context);");
            sb.AppendLine();

            var attrSymbol = compilation.GetTypeByMetadataName("NativeTranspiler.NativeTranspileAttribute");

            // GPU/CUDA 后端已拆分至 feature/gpu-offload 分支；dev 仅保留 Cpp/Ispc Job。
            var nativeJobs = jobStructs.ToList();

            // 1. 为每个 Job 结构体生成静态缓存的委托字段和函数指针。
            foreach (var jobStruct in nativeJobs)
            {
                GenerateStaticDelegateFields(sb, jobStruct, compilation);
            }

            // 2. 静态构造函数：初始化所有缓存的委托和函数指针。
            sb.AppendLine("        static NativeExports()");
            sb.AppendLine("        {");
            foreach (var jobStruct in nativeJobs)
            {
                GenerateStaticConstructorInitialization(sb, jobStruct, compilation);
            }
            // 注册 Job 字段显式写入器（chunk 路径 CreateChunkContextBlock 分发用）
            foreach (var jobStruct in nativeJobs)
            {
                if (ComputeJobFieldMarshal(jobStruct).explicitOk)
                {
                    sb.AppendLine($"            NativeJobScheduler.RegisterJobFieldWriter(typeof({jobStruct.ToDisplayString()}), (NativeJobScheduler.JobFieldWriter<{jobStruct.ToDisplayString()}>)WriteJobFields_{jobStruct.Name});");
                }
            }
            sb.AppendLine("        }");
            sb.AppendLine();

            // 3. 鏅€氭柟娉曠殑 DllImport 鍜?Wrapper锛堣嚜鍔ㄥ唴鑱?MT 閫夋嫨锛?
            foreach (var method in methods)
            {
                GenerateMethodDllImport(sb, method);
                bool useMT = HasUseISPC_MT(method, attrSymbol);
                if (useMT)
                {
                    GenerateMethodDllImportMT(sb, method);
                }
                GenerateMethodWrapper(sb, method, useMT);
            }

            // 4. Job 结构体的 DllImport 和 Schedule 方法。
            foreach (var jobStruct in nativeJobs)
            {
                GenerateJobDllImport(sb, jobStruct, compilation);
                GenerateJobScheduleMethod(sb, jobStruct, compilation);
            }

            // 4c. 显式 Job 字段写入器（chunk 路径 CreateChunkContextBlock 用）??
            //     Debug ??DisposeSentinel ??Job struct ??blittable ??裸拷贝布局不可靠，
            //     ??Job 生成类型化写入器，静态构造时注册??NativeJobScheduler 的注册表（EntJoy 侧）??
            if (nativeJobs.Count > 0)
            {
                foreach (var jobStruct in nativeJobs)
                    GenerateJobFieldWriterMethod(sb, jobStruct);
                sb.AppendLine();
            }

            sb.AppendLine(GenerateCleanupFactoryMethod());
            sb.AppendLine("    }");
            sb.AppendLine("}");
            sb.AppendLine();

            // 5. Job 扩展方法（Schedule 和 Run）
            // 注意：IJobEntity 的 JobExtensions 由 ECS 生成器生成（路由到原生/托管路径）
            // 这里只为 IJobChunk/IJobParallelFor/IJobFor/IJob 生成
            var nonEntityJobs = nativeJobs.Where(j => !CppJobGenerator.IsEntityJob(j)).ToList();
            if (nonEntityJobs.Count > 0)
            {
                sb.AppendLine("public static partial class JobExtensions");
                sb.AppendLine("{");
                foreach (var jobStruct in nonEntityJobs)
                {
                    GenerateJobExtensionMethod(sb, jobStruct);
                    GenerateJobRunMethod(sb, jobStruct, compilation);
                }
                sb.AppendLine("}");
            }

            return sb.ToString();
        }

        private static bool HasUseISPC_MT(ISymbol symbol, INamedTypeSymbol? attrSymbol)
            => AttributeHelper.HasUseISPC_MT(symbol, attrSymbol);

        // ---------- 方法 DllImport ----------
        private static void GenerateMethodDllImport(StringBuilder sb, IMethodSymbol method)
        {
            var cppFunctionName = CppGenerator.GetCppFunctionName(method);
            var returnType = method.ReturnType.ToDisplayString(SymbolDisplayFormat.FullyQualifiedFormat);
            var methodName = method.Name + "_Native";
            var parameters = BuildMethodDllImportParams(method);
            sb.AppendLine($"        [DllImport(\"{NativeLibraryName}\", EntryPoint = \"{cppFunctionName}\", CallingConvention = CallingConvention.Cdecl)]");
            sb.AppendLine($"        private static extern {returnType} {methodName}({string.Join(", ", parameters)});");
            sb.AppendLine();
        }

        private static void GenerateMethodDllImportMT(StringBuilder sb, IMethodSymbol method)
        {
            var cppFunctionName = CppGenerator.GetCppFunctionName(method) + "_mt";
            var returnType = method.ReturnType.ToDisplayString(SymbolDisplayFormat.FullyQualifiedFormat);
            var methodName = method.Name + "_mt_Native";
            var parameters = BuildMethodDllImportParams(method);
            parameters.Add("int numTasks");
            sb.AppendLine($"        [DllImport(\"{NativeLibraryName}\", EntryPoint = \"{cppFunctionName}\", CallingConvention = CallingConvention.Cdecl)]");
            sb.AppendLine($"        private static extern {returnType} {methodName}({string.Join(", ", parameters)});");
            sb.AppendLine();
        }

        private static void GenerateMethodWrapper(StringBuilder sb, IMethodSymbol method, bool useMT)
        {
            var returnType = method.ReturnType.ToDisplayString(SymbolDisplayFormat.FullyQualifiedFormat);
            var methodName = method.Name;
            var parameters = method.Parameters.Select(p => $"{GetCSharpParameterType(p)} {p.Name}");
            sb.AppendLine($"        public static {returnType} {methodName}({string.Join(", ", parameters)})");
            sb.AppendLine("        {");
            sb.AppendLine("            unsafe {");
            // 直调执行窗口：Begin 在调用前开窗口（当前线程泳道，事件驱动），
            // finally 确保无论异常与否都关闭窗口并上报共享时间线段??
            sb.AppendLine($"            ulong __dbgId = NativeJobScheduler.BeginDirectCall(\"{methodName}\", {(useMT ? "(uint)Environment.ProcessorCount" : "1u")});");
            sb.AppendLine("            try {");
            if (method.ReturnType.SpecialType != SpecialType.System_Void)
                sb.Append("                return ");
            else
                sb.Append("                ");

            if (useMT)
            {
                sb.Append($"{methodName}_mt_Native(");
                var args = BuildMethodCallArgs(method);
                args.Add("Environment.ProcessorCount");
                sb.Append(string.Join(", ", args));
            }
            else
            {
                sb.Append($"{methodName}_Native(");
                var args = BuildMethodCallArgs(method);
                sb.Append(string.Join(", ", args));
            }
            sb.AppendLine(");");
            sb.AppendLine("            }");
            sb.AppendLine("            finally { NativeJobScheduler.EndDirectCall(__dbgId); }");
            sb.AppendLine("            }");
            sb.AppendLine("        }");
            sb.AppendLine();
        }

        // ---------- Job 委托字段 ----------
        private static void GenerateStaticDelegateFields(StringBuilder sb, INamedTypeSymbol jobStruct, Compilation compilation)
        {
            bool isChunk = CppJobGenerator.IsChunkScheduledJob(jobStruct);
            bool isParallelFor = CppJobGenerator.IsParallelForJob(jobStruct);
            bool isFor = CppJobGenerator.IsForJob(jobStruct);

            if (isChunk)
            {
                if (CppJobGenerator.IsEntityJob(jobStruct))
                {
            // IJobEntity 统一走 Chunk 级调度（与 ISPC 路径一致）。
                    sb.AppendLine($"        private static readonly IntPtr s_{jobStruct.Name}_ChunkFuncPtr;");
                    sb.AppendLine($"        private static readonly IntPtr s_{jobStruct.Name}_ChunkRangeFuncPtr;");
                }
                else
                {
                    sb.AppendLine($"        private static readonly IntPtr s_{jobStruct.Name}_ChunkFuncPtr;");
                    sb.AppendLine($"        private static readonly IntPtr s_{jobStruct.Name}_ChunkRangeFuncPtr;");
                    var attrSym2 = AttributeHelper.GetAttributeSymbol(compilation);
                    bool isIspc2 = attrSym2 != null && AttributeHelper.GetBackendTarget(jobStruct, attrSym2) == NativeTranspiler.BackendTarget.Ispc;
                    if (!isIspc2)
                        sb.AppendLine($"        private static readonly IntPtr s_{jobStruct.Name}_ChunkEntityBatchFuncPtr;");
                }
                var requiredTypes = CppJobGenerator.CollectChunkNativeArrayTypes(jobStruct, compilation);
                string requiredIds = BuildRequiredComponentTypeIdsInitializer(requiredTypes);
                sb.AppendLine($"        private static readonly int[] s_{jobStruct.Name}_RequiredComponentTypeIds = {requiredIds};");
            }
            else if (isParallelFor || isFor)
            {
                sb.AppendLine($"        private static readonly BatchJobFuncDelegate s_{jobStruct.Name}_BatchFunc;");
                sb.AppendLine($"        private static readonly IntPtr s_{jobStruct.Name}_BatchFuncPtr;");
            }
            else
            {
                sb.AppendLine($"        private static readonly JobFuncDelegate s_{jobStruct.Name}_JobFunc;");
                sb.AppendLine($"        private static readonly IntPtr s_{jobStruct.Name}_JobFuncPtr;");
            }
            sb.AppendLine($"        private static readonly CleanupFuncDelegate s_{jobStruct.Name}_CleanupFunc;");
            sb.AppendLine($"        private static readonly IntPtr s_{jobStruct.Name}_CleanupFuncPtr;");
            sb.AppendLine();
        }

        private static void GenerateStaticConstructorInitialization(StringBuilder sb, INamedTypeSymbol jobStruct, Compilation compilation)
        {
            string jobTypeFullName = jobStruct.ToDisplayString();
            bool isParallelFor = CppJobGenerator.IsParallelForJob(jobStruct);
            bool isFor = CppJobGenerator.IsForJob(jobStruct);
            bool isChunk = CppJobGenerator.IsChunkScheduledJob(jobStruct);

            var executeMethod = jobStruct.GetMembers().OfType<IMethodSymbol>().First(m => m.Name == Config.Execute);
            var methodSyntax = SymbolHelper.GetMethodSyntax(executeMethod);
            bool hasMultiVersion = false;
            string boolFieldName = null;
            List<IFieldSymbol> boolFields = new List<IFieldSymbol>();

            var attrSymbol = compilation.GetTypeByMetadataName("NativeTranspiler.NativeTranspileAttribute");
            bool useMT = HasUseISPC_MT(jobStruct, attrSymbol);

            if (methodSyntax != null)
            {
                var semanticModel = compilation.GetSemanticModel(methodSyntax.SyntaxTree);
                var conditionalFields = NativeTranspileValidator.GetConditionalReadOnlyFields(jobStruct, semanticModel);
                boolFields = conditionalFields.Where(f => f.Type.SpecialType == SpecialType.System_Boolean).ToList();
                if (boolFields.Count > 0)
                {
                    hasMultiVersion = true;
                    boolFieldName = boolFields[0].Name;
                }
            }

            if (isChunk)
            {
                if (CppJobGenerator.IsEntityJob(jobStruct))
                {
            // IJobEntity 统一走 Chunk 级调度（与 ISPC 路径一致）。
                    sb.AppendLine($"            s_{jobStruct.Name}_ChunkFuncPtr = Get_{jobStruct.Name}_ChunkAdapterPtr();");
                    sb.AppendLine($"            s_{jobStruct.Name}_ChunkRangeFuncPtr = Get_{jobStruct.Name}_ChunkRangeAdapterPtr();");
                }
                else
                {
                    sb.AppendLine($"            s_{jobStruct.Name}_ChunkFuncPtr = Get_{jobStruct.Name}_ChunkAdapterPtr();");
                    sb.AppendLine($"            s_{jobStruct.Name}_ChunkRangeFuncPtr = Get_{jobStruct.Name}_ChunkRangeAdapterPtr();");
                    var attrSym2 = AttributeHelper.GetAttributeSymbol(compilation);
                    bool isIspc2 = attrSym2 != null && AttributeHelper.GetBackendTarget(jobStruct, attrSym2) == NativeTranspiler.BackendTarget.Ispc;
                    if (!isIspc2)
                        sb.AppendLine($"            s_{jobStruct.Name}_ChunkEntityBatchFuncPtr = Get_{jobStruct.Name}_ChunkEntityBatchAdapterPtr();");
                }
            }
            else if (isParallelFor || isFor)
            {
                if (useMT)
                {
            // MT（task 内部自己调度）仍用托管 delegate：原生 Adapter 只生成非 MT 变体。
                string mtSuffix = "_mt";

                sb.AppendLine($"            s_{jobStruct.Name}_BatchFunc = (IntPtr context, int startIndex, int count) =>");
                sb.AppendLine("            {");
                sb.AppendLine($"                var jobPtr = ({jobTypeFullName}*)context;");

                string batchArgs = BuildBatchCallArgs(jobStruct, "jobPtr");
                string batchArgsWithComma = string.IsNullOrEmpty(batchArgs) ? "" : ", " + batchArgs;
                if (hasMultiVersion)
                {
                    // 生成所??2^n ??bool 组合??if-else 链，??C++ 端命名一??
                    int totalVariants = 1 << boolFields.Count;
                    var boolVarNames = boolFields.Select(f => $"jobPtr->{f.Name}").ToList();

                    for (int mask = 0; mask < totalVariants; mask++)
                    {
                        var values = new List<bool>();
                        for (int i = 0; i < boolFields.Count; i++)
                            values.Add((mask & (1 << i)) != 0);

                        string suffix = "_" + string.Join("_", values.Select(v => v ? "true" : "false"));

                        bool isLast = (mask == totalVariants - 1);
                        if (mask == 0)
                        {
                            string condition = string.Join(" && ", boolFields.Select((f, i) => values[i] ? $"jobPtr->{f.Name}" : $"!jobPtr->{f.Name}"));
                            sb.AppendLine($"                if ({condition})");
                        }
                        else if (!isLast)
                        {
                            string condition = string.Join(" && ", boolFields.Select((f, i) => values[i] ? $"jobPtr->{f.Name}" : $"!jobPtr->{f.Name}"));
                            sb.AppendLine($"                else if ({condition})");
                        }
                        else
                        {
                            sb.AppendLine("                else");
                        }

                        sb.AppendLine($"                    {jobStruct.Name}_Execute_Batch{suffix}{mtSuffix}(startIndex, count{batchArgsWithComma});");
                    }
                }
                else
                {
                    sb.AppendLine($"                {jobStruct.Name}_Execute_Batch{mtSuffix}(startIndex, count{batchArgsWithComma});");
                }
                sb.AppendLine("            };");
                sb.AppendLine($"            s_{jobStruct.Name}_BatchFuncPtr = Marshal.GetFunctionPointerForDelegate(s_{jobStruct.Name}_BatchFunc);");
                }
                else
                {
                    // ??MT：调度器直接调原??_Execute_Adapter(context,start,count)（原生→原生），
                    // 消除托管 BatchFunc delegate ??原生→托管→原生 双重转换（每 tile ~3μs 开销）??
                    // 原生 Adapter ??CppJobGenerator 生成：同一套字段偏移解??/ UnsafeList 写回 / bool 变体分派??
                    sb.AppendLine($"            s_{jobStruct.Name}_BatchFuncPtr = Get_{jobStruct.Name}_Execute_AdapterPtr();");
                }
            }
            else
            {
                sb.AppendLine($"            s_{jobStruct.Name}_JobFunc = (IntPtr context) =>");
                sb.AppendLine("            {");
                sb.AppendLine($"                var jobPtr = ({jobTypeFullName}*)context;");
                var args = BuildJobExecuteArgsForPointer(jobStruct);
                sb.AppendLine($"                {jobStruct.Name}_Execute({string.Join(", ", args)});");
                sb.AppendLine("            };");
                sb.AppendLine($"            s_{jobStruct.Name}_JobFuncPtr = Marshal.GetFunctionPointerForDelegate(s_{jobStruct.Name}_JobFunc);");
            }

            sb.AppendLine($"            s_{jobStruct.Name}_CleanupFunc = (IntPtr context) =>");
            sb.AppendLine("            {");
            sb.AppendLine("                Marshal.FreeHGlobal(context);");
            sb.AppendLine("            };");
            sb.AppendLine($"            s_{jobStruct.Name}_CleanupFuncPtr = Marshal.GetFunctionPointerForDelegate(s_{jobStruct.Name}_CleanupFunc);");
            sb.AppendLine();
        }

        private static void GenerateJobDllImport(StringBuilder sb, INamedTypeSymbol jobStruct, Compilation compilation)
        {
            bool isChunk = CppJobGenerator.IsChunkScheduledJob(jobStruct);
            bool isParallelFor = CppJobGenerator.IsParallelForJob(jobStruct);
            bool isFor = CppJobGenerator.IsForJob(jobStruct);

            var attrSymbol = compilation.GetTypeByMetadataName("NativeTranspiler.NativeTranspileAttribute");
            bool useMT = HasUseISPC_MT(jobStruct, attrSymbol);

            if (isChunk)
            {
                if (CppJobGenerator.IsEntityJob(jobStruct))
                {
            // IJobEntity 统一走 Chunk 级调度。
                    var getterName = CppJobGenerator.GetAdapterPtrGetterName(jobStruct);
                    var rangeGetterName = CppJobGenerator.GetRangeAdapterPtrGetterName(jobStruct);
                    sb.AppendLine($"        [DllImport(\"{NativeLibraryName}\", EntryPoint = \"{getterName}\", CallingConvention = CallingConvention.Cdecl)]");
                    sb.AppendLine($"        private static extern IntPtr Get_{jobStruct.Name}_ChunkAdapterPtr();");
                    sb.AppendLine($"        [DllImport(\"{NativeLibraryName}\", EntryPoint = \"{rangeGetterName}\", CallingConvention = CallingConvention.Cdecl)]");
                    sb.AppendLine($"        private static extern IntPtr Get_{jobStruct.Name}_ChunkRangeAdapterPtr();");
                }
                else
                {
                    var getterName = CppJobGenerator.GetAdapterPtrGetterName(jobStruct);
                    var rangeGetterName = CppJobGenerator.GetRangeAdapterPtrGetterName(jobStruct);
                    var entityBatchGetterName = CppJobGenerator.GetEntityBatchAdapterPtrGetterName(jobStruct);
                    sb.AppendLine($"        [DllImport(\"{NativeLibraryName}\", EntryPoint = \"{getterName}\", CallingConvention = CallingConvention.Cdecl)]");
                    sb.AppendLine($"        private static extern IntPtr Get_{jobStruct.Name}_ChunkAdapterPtr();");
                    sb.AppendLine($"        [DllImport(\"{NativeLibraryName}\", EntryPoint = \"{rangeGetterName}\", CallingConvention = CallingConvention.Cdecl)]");
                    sb.AppendLine($"        private static extern IntPtr Get_{jobStruct.Name}_ChunkRangeAdapterPtr();");
                    var attrSym2 = AttributeHelper.GetAttributeSymbol(compilation);
                    bool isIspc2 = attrSym2 != null && AttributeHelper.GetBackendTarget(jobStruct, attrSym2) == NativeTranspiler.BackendTarget.Ispc;
                    if (!isIspc2)
                    {
                        sb.AppendLine($"        [DllImport(\"{NativeLibraryName}\", EntryPoint = \"{entityBatchGetterName}\", CallingConvention = CallingConvention.Cdecl)]");
                        sb.AppendLine($"        private static extern IntPtr Get_{jobStruct.Name}_ChunkEntityBatchAdapterPtr();");
                    }
                }
            }
            else if (isParallelFor || isFor)
            {
                var batchFuncName = CppJobGenerator.GetCppJobFunctionName(jobStruct, isBatch: true);
                var batchParams = BuildBatchJobDllImportParams(jobStruct);

                var executeMethod = jobStruct.GetMembers().OfType<IMethodSymbol>().First(m => m.Name == Config.Execute);
                var methodSyntax = SymbolHelper.GetMethodSyntax(executeMethod);
                bool hasMultiVersion = false;
                if (methodSyntax != null)
                {
                    var semanticModel = compilation.GetSemanticModel(methodSyntax.SyntaxTree);
                    var conditionalFields = NativeTranspileValidator.GetConditionalReadOnlyFields(jobStruct, semanticModel);
                    hasMultiVersion = conditionalFields.Any(f => f.Type.SpecialType == SpecialType.System_Boolean);
                }

                if (hasMultiVersion)
                {
                    sb.AppendLine($"        [DllImport(\"{NativeLibraryName}\", EntryPoint = \"{batchFuncName}_true\", CallingConvention = CallingConvention.Cdecl)]");
                    sb.AppendLine($"        public static extern void {jobStruct.Name}_Execute_Batch_true({string.Join(", ", batchParams)});");
                    sb.AppendLine($"        [DllImport(\"{NativeLibraryName}\", EntryPoint = \"{batchFuncName}_false\", CallingConvention = CallingConvention.Cdecl)]");
                    sb.AppendLine($"        public static extern void {jobStruct.Name}_Execute_Batch_false({string.Join(", ", batchParams)});");
                }
                else
                {
                    sb.AppendLine($"        [DllImport(\"{NativeLibraryName}\", EntryPoint = \"{batchFuncName}\", CallingConvention = CallingConvention.Cdecl)]");
                    sb.AppendLine($"        public static extern void {jobStruct.Name}_Execute_Batch({string.Join(", ", batchParams)});");
                }

                if (useMT)
                {
                    if (hasMultiVersion)
                    {
                        sb.AppendLine($"        [DllImport(\"{NativeLibraryName}\", EntryPoint = \"{batchFuncName}_true_mt\", CallingConvention = CallingConvention.Cdecl)]");
                        sb.AppendLine($"        private static extern void {jobStruct.Name}_Execute_Batch_true_mt({string.Join(", ", batchParams)});");
                        sb.AppendLine($"        [DllImport(\"{NativeLibraryName}\", EntryPoint = \"{batchFuncName}_false_mt\", CallingConvention = CallingConvention.Cdecl)]");
                        sb.AppendLine($"        private static extern void {jobStruct.Name}_Execute_Batch_false_mt({string.Join(", ", batchParams)});");
                    }
                    else
                    {
                        sb.AppendLine($"        [DllImport(\"{NativeLibraryName}\", EntryPoint = \"{batchFuncName}_mt\", CallingConvention = CallingConvention.Cdecl)]");
                        sb.AppendLine($"        private static extern void {jobStruct.Name}_Execute_Batch_mt({string.Join(", ", batchParams)});");
                    }
                }
                else
                {
                    // ??MT：声明原??Adapter 指针 Getter（调度器原生→原生直调路径）
                    var adapterGetterName = CppJobGenerator.GetAdapterPtrGetterName(jobStruct);
                    sb.AppendLine($"        [DllImport(\"{NativeLibraryName}\", EntryPoint = \"{adapterGetterName}\", CallingConvention = CallingConvention.Cdecl)]");
                    sb.AppendLine($"        private static extern IntPtr Get_{jobStruct.Name}_Execute_AdapterPtr();");
                }
            }
            else
            {
                var singleFuncName = CppJobGenerator.GetCppJobFunctionName(jobStruct);
                var singleParams = BuildJobDllImportParams(jobStruct);
                sb.AppendLine($"        [DllImport(\"{NativeLibraryName}\", EntryPoint = \"{singleFuncName}\", CallingConvention = CallingConvention.Cdecl)]");
                sb.AppendLine($"        public static extern void {jobStruct.Name}_Execute({string.Join(", ", singleParams)});");
            }
            sb.AppendLine();
        }

        // ---------- Job Schedule 方法 ----------
        private static void GenerateJobScheduleMethod(StringBuilder sb, INamedTypeSymbol jobStruct, Compilation compilation)
        {
            bool isChunk = CppJobGenerator.IsChunkScheduledJob(jobStruct);
            bool isParallelFor = CppJobGenerator.IsParallelForJob(jobStruct);
            bool isFor = CppJobGenerator.IsForJob(jobStruct);
            string jobTypeName = jobStruct.ToDisplayString();

            var attrSymbol = compilation.GetTypeByMetadataName("NativeTranspiler.NativeTranspileAttribute");
            bool useMT = HasUseISPC_MT(jobStruct, attrSymbol);

            var parameters = new List<string>();
            // Use 'ref' for the internal Schedule_XXX method (caller already has a reference)
            parameters.Add($"ref {jobTypeName} job");
            if (isChunk)
            {
                parameters.Add("QueryBuilder query");
            }
            else if (isParallelFor || isFor)
            {
                parameters.Add("int arrayLength");
            // IJobFor 也允许指定 innerBatchCount，保持接口统一。
                parameters.Add("int innerBatchCount = 0");
            }
            parameters.Add("JobHandle dependsOn = default");

            sb.AppendLine($"        public static JobHandle Schedule_{jobStruct.Name}({string.Join(", ", parameters)})");
            sb.AppendLine("        {");
            if (!isChunk)
            {
                // Debug ??NativeArray ??GC 引用（DisposeSentinel）→ Job struct ??blittable，裸拷贝布局不可靠；
                // 改为显式逐字段写入（??C++ Adapter 偏移一致），Debug/Release 均正确??
                var (marshalled, explicitOk, totalSize) = ComputeJobFieldMarshal(jobStruct);
                if (explicitOk)
                {
                    sb.AppendLine($"            int size = {totalSize};");
                    sb.AppendLine("            IntPtr nativePtr = Marshal.AllocHGlobal(size);");
                    sb.AppendLine("            byte* __dst = (byte*)nativePtr;");
                    EmitExplicitFieldWrites(sb, marshalled, "__dst", "job");
                    sb.AppendLine();
                }
                else
                {
                    // 含不支持字段（NativeList 等）：退回裸拷贝（Release 正确；Debug 由显式路径覆盖的场景外）
                    sb.AppendLine($"            int size = sizeof({jobTypeName});");
                    sb.AppendLine("            IntPtr nativePtr = Marshal.AllocHGlobal(size);");
                    sb.AppendLine("            void* originalPtr = Unsafe.AsPointer(ref job);");
                    sb.AppendLine("            Unsafe.CopyBlockUnaligned((void*)nativePtr, originalPtr, (uint)size);");
                    sb.AppendLine();
                }
            }

            if (isChunk)
            {
                sb.AppendLine("            var world = World.DefaultWorld ?? throw new InvalidOperationException(\"No active World found.\");");
                // 鎵€鏈?native IJobChunk 璧?EntityBatch 璺緞锛圲nity 椋庢牸锛夛紝
                // 浣跨敤 EntityBatchData 鏇夸唬 ChunkJobData锛屾秷闄?requiredComponentArrays 闂存帴灞?
                string funcPtrName;
                string extraArgs;
                string scheduleMethod;
                if (CppJobGenerator.IsEntityJob(jobStruct))
                {
            // IJobEntity 统一走 Chunk 级 range 调度。
                    scheduleMethod = "ScheduleChunkRangeRaw";
                    funcPtrName = $"s_{jobStruct.Name}_ChunkRangeFuncPtr";
                    extraArgs = "";
                }
                else
                {
                    var attrSym3 = AttributeHelper.GetAttributeSymbol(compilation);
                    bool isIspc3 = attrSym3 != null && AttributeHelper.GetBackendTarget(jobStruct, attrSym3) == NativeTranspiler.BackendTarget.Ispc;
                    if (isIspc3)
                    {
                        scheduleMethod = "ScheduleChunkRangeRaw";
                        funcPtrName = $"s_{jobStruct.Name}_ChunkRangeFuncPtr";
                        extraArgs = "";
                    }
                    else
                    {
                        scheduleMethod = "ScheduleChunkEntityBatchRawWithWorkerCapAndRangeSize";
                        funcPtrName = $"s_{jobStruct.Name}_ChunkEntityBatchFuncPtr";
                        extraArgs = $", 0, 0";
                    }
                }
                sb.AppendLine($"            NativeJobHandle nativeHandle = NativeEcsScheduler.{scheduleMethod}(");
                sb.AppendLine($"                ref job, world.EntityManager, query, {funcPtrName}, s_{jobStruct.Name}_RequiredComponentTypeIds{extraArgs}, dependsOn._nativeHandle);");
                sb.AppendLine($"            return new JobHandle(nativeHandle);");
            }
            else if (isParallelFor || isFor)
            {
                // 自适应批次大小
                if (useMT)
                {
                    sb.AppendLine($"            int actualBatchSize = innerBatchCount > 0 ? innerBatchCount : arrayLength;");
                }
                else
                {
                    // 0 = 直通原??ResolveChunkSize（tiles/worker 通用化粒度）??0 显式 batch 原样??
                    sb.AppendLine($"            int actualBatchSize = innerBatchCount;");
                }

                sb.AppendLine($"            NativeJobHandle nativeHandle = NativeJobScheduler.ScheduleParallelForBatchRaw(");
                sb.AppendLine($"                s_{jobStruct.Name}_BatchFuncPtr, nativePtr, s_{jobStruct.Name}_CleanupFuncPtr, arrayLength, actualBatchSize, dependsOn._nativeHandle);");
                sb.AppendLine($"            NativeJobScheduler.RegisterScheduledJob(nativeHandle.Handle, \"{jobStruct.Name}\");");
                sb.AppendLine($"            return new JobHandle(nativeHandle);");
            }
            else
            {
                sb.AppendLine($"            NativeJobHandle nativeHandle = NativeJobScheduler.ScheduleRaw(");
                sb.AppendLine($"                s_{jobStruct.Name}_JobFuncPtr, nativePtr, s_{jobStruct.Name}_CleanupFuncPtr, dependsOn._nativeHandle);");
                sb.AppendLine($"            NativeJobScheduler.RegisterScheduledJob(nativeHandle.Handle, \"{jobStruct.Name}\");");
                sb.AppendLine($"            return new JobHandle(nativeHandle);");
            }
            sb.AppendLine("        }");
            sb.AppendLine();

            if (isChunk)
            {
                // 确定 ISPC 状态（ScheduleWithWorkerCap ??ScheduleWithWorkerCapAndRangeSize 共用??
                var attrSymCap = AttributeHelper.GetAttributeSymbol(compilation);
                bool isIspcCap = attrSymCap != null && AttributeHelper.GetBackendTarget(jobStruct, attrSymCap) == NativeTranspiler.BackendTarget.Ispc;

                if (isIspcCap)
                {
                    // ISPC entity jobs use EntityBatch, ISPC chunk jobs use fallback
                    bool isEntityJob = CppJobGenerator.IsEntityJob(jobStruct);
                    // IJobEntity ISPC 浣跨敤 chunk 绾?range 璋冨害
                    string ispcFuncPtr;
                    string ispcScheduleMethod;
                    if (isEntityJob)
                    {
                        ispcFuncPtr = $"s_{jobStruct.Name}_ChunkRangeFuncPtr";
                        ispcScheduleMethod = "ScheduleChunkRangeRaw";
                    }
                    else
                    {
                        ispcFuncPtr = $"s_{jobStruct.Name}_ChunkFuncPtr";
                        ispcScheduleMethod = "ScheduleChunkRawWithWorkerCap";
                    }

                    sb.AppendLine($"        public static JobHandle ScheduleWithWorkerCap_{jobStruct.Name}(ref {jobTypeName} job, QueryBuilder query, int workerCap, JobHandle dependsOn = default)");
                    sb.AppendLine("        {");
                    sb.AppendLine("            var world = World.DefaultWorld ?? throw new InvalidOperationException(\"No active World found.\");");
                    sb.AppendLine($"            NativeJobHandle nativeHandle = NativeEcsScheduler.{ispcScheduleMethod}(");
                    sb.AppendLine(isEntityJob
                        ? $"                ref job, world.EntityManager, query, {ispcFuncPtr}, s_{jobStruct.Name}_RequiredComponentTypeIds, dependsOn._nativeHandle);"
                        : $"                ref job, world.EntityManager, query, {ispcFuncPtr}, s_{jobStruct.Name}_RequiredComponentTypeIds, {(useMT ? "1" : "workerCap")}, dependsOn._nativeHandle);");
                    sb.AppendLine($"            return new JobHandle(nativeHandle);");
                    sb.AppendLine("        }");
                    sb.AppendLine();

                    // ScheduleChunkRawWithWorkerCapAndRangeSize for chunk ISPC, EntityBatch for entity ISPC
                    string ispcScheduleMethod2 = isEntityJob ? "ScheduleChunkRangeRaw" : "ScheduleChunkRawWithWorkerCapAndRangeSize";
                    sb.AppendLine($"        public static JobHandle ScheduleWithWorkerCapAndRangeSize_{jobStruct.Name}(ref {jobTypeName} job, QueryBuilder query, int workerCap, int rangeSize, JobHandle dependsOn = default)");
                    sb.AppendLine("        {");
                    sb.AppendLine("            var world = World.DefaultWorld ?? throw new InvalidOperationException(\"No active World found.\");");
                    sb.AppendLine($"            NativeJobHandle nativeHandle = NativeEcsScheduler.{ispcScheduleMethod2}(");
                    sb.AppendLine(isEntityJob
                        ? $"                ref job, world.EntityManager, query, {ispcFuncPtr}, s_{jobStruct.Name}_RequiredComponentTypeIds, dependsOn._nativeHandle);"
                        : $"                ref job, world.EntityManager, query, {ispcFuncPtr}, s_{jobStruct.Name}_RequiredComponentTypeIds, {(useMT ? "1, int.MaxValue" : "workerCap, rangeSize")}, dependsOn._nativeHandle);");
                    sb.AppendLine($"            return new JobHandle(nativeHandle);");
                    sb.AppendLine("        }");
                    sb.AppendLine();
                }
                else
                {
                    string capFuncPtr = CppJobGenerator.IsEntityJob(jobStruct)
                        ? $"s_{jobStruct.Name}_ChunkRangeFuncPtr"
                        : $"s_{jobStruct.Name}_ChunkEntityBatchFuncPtr";
                    string capMethod = CppJobGenerator.IsEntityJob(jobStruct)
                        ? "ScheduleEntityRangeRawWithWorkerCapAndRangeSize"
                        : "ScheduleChunkEntityBatchRawWithWorkerCapAndRangeSize";

                    sb.AppendLine($"        public static JobHandle ScheduleWithWorkerCap_{jobStruct.Name}(ref {jobTypeName} job, QueryBuilder query, int workerCap, JobHandle dependsOn = default)");
                    sb.AppendLine("        {");
                    sb.AppendLine("            var world = World.DefaultWorld ?? throw new InvalidOperationException(\"No active World found.\");");
                    sb.AppendLine($"            NativeJobHandle nativeHandle = NativeEcsScheduler.{capMethod}(");
                    sb.AppendLine($"                ref job, world.EntityManager, query, {capFuncPtr}, s_{jobStruct.Name}_RequiredComponentTypeIds, workerCap, 0, dependsOn._nativeHandle);");
                    sb.AppendLine($"            return new JobHandle(nativeHandle);");
                    sb.AppendLine("        }");
                    sb.AppendLine();

                    sb.AppendLine($"        public static JobHandle ScheduleWithWorkerCapAndRangeSize_{jobStruct.Name}(ref {jobTypeName} job, QueryBuilder query, int workerCap, int rangeSize, JobHandle dependsOn = default)");
                    sb.AppendLine("        {");
                    sb.AppendLine("            var world = World.DefaultWorld ?? throw new InvalidOperationException(\"No active World found.\");");
                    sb.AppendLine($"            NativeJobHandle nativeHandle = NativeEcsScheduler.{capMethod}(");
                    sb.AppendLine($"                ref job, world.EntityManager, query, {capFuncPtr}, s_{jobStruct.Name}_RequiredComponentTypeIds, workerCap, rangeSize, dependsOn._nativeHandle);");
                    sb.AppendLine($"            return new JobHandle(nativeHandle);");
                    sb.AppendLine("        }");
                    sb.AppendLine();
                }

                sb.AppendLine($"        public static void RunImmediate_{jobStruct.Name}(ref {jobTypeName} job, QueryBuilder query)");
                sb.AppendLine("        {");
                sb.AppendLine($"            Schedule_{jobStruct.Name}(ref job, query, default).Complete();");
                sb.AppendLine("        }");
                sb.AppendLine();
            }
        }

        private static string BuildRequiredComponentTypeIdsInitializer(IEnumerable<INamedTypeSymbol> requiredTypes)
        {
            var ids = string.Join(", ", requiredTypes.Select(t => $"ComponentTypeManager.GetComponentType(typeof({t.ToDisplayString(SymbolDisplayFormat.FullyQualifiedFormat)})).Id"));
            return string.IsNullOrWhiteSpace(ids) ? "Array.Empty<int>()" : $"new int[] {{ {ids} }}";
        }

        // ---------- 杈呭姪锛氭瀯寤哄弬鏁板垪琛?----------
        private static List<string> BuildMethodDllImportParams(IMethodSymbol method)
        {
            var parameters = new List<string>();
            foreach (var param in method.Parameters)
            {
                if (NativeTranspiler.IsEntJoyNativeContainerType(param.Type))
                {
                    if (NativeTranspiler.IsEntJoyContainerNamed(param.Type, Config.NativeList))
                    {
                        var elementType = ((INamedTypeSymbol)param.Type).TypeArguments[0];
                        var csElementType = elementType.ToDisplayString(SymbolDisplayFormat.FullyQualifiedFormat);
                        parameters.Add($"EntJoy.Collections.UnsafeList<{csElementType}>* {param.Name}_listData");
                    }
                    else
                    {
                        var elementType = ((INamedTypeSymbol)param.Type).TypeArguments[0];
                        var csElementType = elementType.ToDisplayString(SymbolDisplayFormat.FullyQualifiedFormat);
                        parameters.Add($"{csElementType}* {param.Name}_ptr, int {param.Name}_length");
                    }
                }
                else if (param.Type is IPointerTypeSymbol)
                {
                    var cppType = NativeTranspiler.MapCSharpTypeToCpp(param.Type);  // 杩斿洖 "int*"
                    parameters.Add($"{cppType} {param.Name}_ptr");
                }
                else
                {
                    var csType = param.Type.ToDisplayString(SymbolDisplayFormat.FullyQualifiedFormat);
                    parameters.Add($"{csType}* {param.Name}_ptr");
                }
            }
            return parameters;
        }

        private static List<string> BuildMethodCallArgs(IMethodSymbol method)
        {
            var args = new List<string>();
            foreach (var param in method.Parameters)
            {
                if (NativeTranspiler.IsEntJoyNativeContainerType(param.Type))
                {
                    if (NativeTranspiler.IsEntJoyContainerNamed(param.Type, Config.NativeList))
                    {
                        args.Add($"{param.Name}.GetListData()");
                    }
                    else
                    {
                        var elementType = ((INamedTypeSymbol)param.Type).TypeArguments[0];
                        var csElementType = elementType.ToDisplayString(SymbolDisplayFormat.FullyQualifiedFormat);
                        args.Add($"({csElementType}*){param.Name}.GetUnsafePtr(), {param.Name}.Length");
                    }
                }
                else if (param.Type is IPointerTypeSymbol)
                {
                    args.Add(param.Name);
                }
                else
                {
                    var csType = param.Type.ToDisplayString(SymbolDisplayFormat.FullyQualifiedFormat);
                    args.Add($"({csType}*)Unsafe.AsPointer(ref {param.Name})");
                }
            }
            return args;
        }

        private static List<string> BuildJobDllImportParams(INamedTypeSymbol jobStruct)
        {
            var parameters = new List<string>();
            var executeMethod = jobStruct.GetMembers().OfType<IMethodSymbol>().First(m => m.Name == Config.Execute);
            if (executeMethod.Parameters.Length == 1 && executeMethod.Parameters[0].Type.SpecialType == SpecialType.System_Int32)
                parameters.Add($"int {executeMethod.Parameters[0].Name}");

            AppendFieldDllImportParams(jobStruct, parameters);
            return parameters;
        }

        private static List<string> BuildBatchJobDllImportParams(INamedTypeSymbol jobStruct)
        {
            var parameters = new List<string> { "int __startIndex", "int __count" };
            AppendFieldDllImportParams(jobStruct, parameters);
            return parameters;
        }

        private static void AppendFieldDllImportParams(INamedTypeSymbol jobStruct, List<string> parameters)
        {
            foreach (var field in jobStruct.GetMembers().OfType<IFieldSymbol>().Where(f => !f.IsStatic))
            {
                if (NativeTranspiler.IsEntJoyNativeContainerType(field.Type))
                {
                    if (NativeTranspiler.IsEntJoyContainerNamed(field.Type, Config.NativeList))
                    {
                        var elementType = ((INamedTypeSymbol)field.Type).TypeArguments[0];
                        var csElementType = elementType.ToDisplayString(SymbolDisplayFormat.FullyQualifiedFormat);
                        parameters.Add($"EntJoy.Collections.UnsafeList<{csElementType}>* {field.Name}_listData");
                    }
                    else
                    {
                        var elementType = ((INamedTypeSymbol)field.Type).TypeArguments[0];
                        var csElementType = elementType.ToDisplayString(SymbolDisplayFormat.FullyQualifiedFormat);
                        parameters.Add($"{csElementType}* {field.Name}_ptr, int {field.Name}_length");
                    }
                }
                else if (field.Type is IPointerTypeSymbol)
                {
                    var cppType = NativeTranspiler.MapCSharpTypeToCpp(field.Type);  // 杩斿洖 "int*"
                    parameters.Add($"{cppType} {field.Name}_ptr");
                }
                else
                {
                    var csType = field.Type.ToDisplayString(SymbolDisplayFormat.FullyQualifiedFormat);
                    parameters.Add($"{csType}* {field.Name}_ptr");
                }
            }
        }

        private static List<string> BuildJobExecuteArgsForPointer(INamedTypeSymbol jobStruct)
        {
            var args = new List<string>();
            foreach (var field in jobStruct.GetMembers().OfType<IFieldSymbol>().Where(f => !f.IsStatic))
            {
                if (NativeTranspiler.IsEntJoyNativeContainerType(field.Type))
                {
                    if (NativeTranspiler.IsEntJoyContainerNamed(field.Type, Config.NativeList))
                    {
                        args.Add($"jobPtr->{field.Name}.GetListData()");
                    }
                    else
                    {
                        var elementType = ((INamedTypeSymbol)field.Type).TypeArguments[0];
                        var csElementType = elementType.ToDisplayString(SymbolDisplayFormat.FullyQualifiedFormat);
                        args.Add($"({csElementType}*)jobPtr->{field.Name}.GetUnsafePtr(), jobPtr->{field.Name}.Length");
                    }
                }
                else
                {
                    if (field.Type is IPointerTypeSymbol)
                        args.Add($"jobPtr->{field.Name}");
                    else
                        args.Add($"&jobPtr->{field.Name}");
                }
            }
            return args;
        }

        private static string BuildBatchCallArgs(INamedTypeSymbol jobStruct, string jobPtrPrefix)
        {
            var args = new List<string>();
            foreach (var field in jobStruct.GetMembers().OfType<IFieldSymbol>().Where(f => !f.IsStatic))
            {
                if (NativeTranspiler.IsEntJoyNativeContainerType(field.Type))
                {
                    if (NativeTranspiler.IsEntJoyContainerNamed(field.Type, Config.NativeList))
                        args.Add($"{jobPtrPrefix}->{field.Name}.GetListData()");
                    else
                    {
                        var elementType = ((INamedTypeSymbol)field.Type).TypeArguments[0];
                        var csElementType = elementType.ToDisplayString(SymbolDisplayFormat.FullyQualifiedFormat);
                        args.Add($"({csElementType}*){jobPtrPrefix}->{field.Name}.GetUnsafePtr(), {jobPtrPrefix}->{field.Name}.Length");
                    }
                }
                else if (field.Type is IPointerTypeSymbol)
                {
                    args.Add($"{jobPtrPrefix}->{field.Name}");
                }
                else
                {
                    args.Add($"&{jobPtrPrefix}->{field.Name}");
                }
            }
            return string.Join(", ", args);
        }

        // ---------- 显式逐字??marshalling（Debug sentinel 布局修复共用??----------

        /// <summary>
        /// 计算 Job 结构体所有实例字段在 C++ context 布局下的偏移（与 CppJobGenerator.CalculateFieldOffset 同源），
        /// 并把字段递归展开??叶子"（含 GC 引用的非 blittable struct 也递归：值子字段显式写、引用槽零填充）??
        /// 叶子：type==null 表示引用槽（8B 零填充，C++ 侧为 void*，Execute 不应访问）??
        /// 返回 (叶子列表, 是否全部支持, 总大????
        /// </summary>
        private static (List<(string accessor, int offset, ITypeSymbol type)> leaves, bool explicitOk, int totalSize) ComputeJobFieldMarshal(INamedTypeSymbol jobStruct)
        {
            var leaves = new List<(string accessor, int offset, ITypeSymbol type)>();
            int running = 0;
            foreach (var field in jobStruct.GetMembers().OfType<IFieldSymbol>().Where(f => !f.IsStatic))
            {
                int off = CppJobGenerator.CalculateFieldOffset(field, ref running);
                if (field.Type.IsReferenceType)
                {
                    leaves.Add(("", off, null));   // 顶层引用字段 -> void* 槽零填充
                    continue;
                }
                if (!CollectLeaves(leaves, field.Name, field.Type, off)) return (leaves, false, running);
            }
            return (leaves, true, running);
        }

        /// <summary>递归展开字段为叶子：容器/指针/标量/枚举/blittable struct ??单叶子；??blittable struct ??递归（引用子字段 ??零填充槽??/summary>
        private static bool CollectLeaves(List<(string accessor, int offset, ITypeSymbol type)> leaves,
            string accessor, ITypeSymbol type, int offset)
        {
            if (type is IPointerTypeSymbol) { leaves.Add((accessor, offset, type)); return true; }
            if (NativeTranspiler.IsEntJoyNativeContainerType(type)) { leaves.Add((accessor, offset, type)); return true; }
            if (type.TypeKind == TypeKind.Enum) { leaves.Add((accessor, offset, type)); return true; }
            var st = type.SpecialType;
            if (st is SpecialType.System_Single or SpecialType.System_Int32
                or SpecialType.System_UInt32 or SpecialType.System_Boolean)
            { leaves.Add((accessor, offset, type)); return true; }
            if (type is INamedTypeSymbol nts && nts.IsValueType)
            {
                if (IsBlittableStruct(nts)) { leaves.Add((accessor, offset, type)); return true; }
                int running = 0;
                foreach (var f in nts.GetMembers().OfType<IFieldSymbol>().Where(f => !f.IsStatic))
                {
                    int subOff = CppJobGenerator.CalculateFieldOffset(f, ref running);
                    if (f.Type.IsReferenceType)
                    {
                        leaves.Add(("", offset + subOff, null));   // 引用槽：8B 零填充（C++ 为 void*，Execute 不应访问）
                        continue;
                    }
                    string child = accessor.Length == 0 ? f.Name : accessor + "." + f.Name;
                    if (!CollectLeaves(leaves, child, f.Type, offset + subOff)) return false;
                }
                return true;
            }
            return false;
        }

        /// <summary>struct 是否 blittable（递归：指??标量/枚举/仅含这些的嵌??struct）——Debug sentinel ??GC 引用，非 blittable</summary>
        private static bool IsBlittableStruct(INamedTypeSymbol structType)
        {
            foreach (var member in structType.GetMembers().OfType<IFieldSymbol>().Where(f => !f.IsStatic))
            {
                if (member.Type is IPointerTypeSymbol) continue;
                if (member.Type.TypeKind == TypeKind.Enum) continue;
                var st = member.Type.SpecialType;
                if (st is SpecialType.System_Single or SpecialType.System_Int32
                    or SpecialType.System_UInt32 or SpecialType.System_Boolean
                    or SpecialType.System_Int64 or SpecialType.System_UInt64
                    or SpecialType.System_Double or SpecialType.System_Byte
                    or SpecialType.System_SByte or SpecialType.System_Int16
                    or SpecialType.System_UInt16 or SpecialType.System_Char) continue;
                if (member.Type is INamedTypeSymbol nested && nested.IsValueType)
                {
                    if (IsBlittableStruct(nested)) continue;
                    return false;
                }
                return false;   // 引用类型/其他 -> 非 blittable
            }
            return true;
        }

        /// <summary>生成逐字段显式写入语句：{srcExpr}.{accessor} 写到 {dstExpr} + 偏移（不依赖 struct 运行时布局??/summary>
        private static void EmitExplicitFieldWrites(StringBuilder sb,
            List<(string accessor, int offset, ITypeSymbol type)> leaves, string dstExpr, string srcExpr)
        {
            foreach (var (accessor, off, type) in leaves)
            {
                if (type == null)
                {
                    // 引用槽（object/string 等）??B 零填充（C++ 侧为 void*，Execute 不应访问??
                    sb.AppendLine($"            *((long*)({dstExpr} + {off})) = 0;");
                    continue;
                }
                if (NativeTranspiler.IsEntJoyNativeContainerType(type))
                {
                    if (NativeTranspiler.IsEntJoyContainerNamed(type, Config.NativeArray))
                    {
                        // NativeArray：显式写 buffer@off / length@off+8（与 Adapter 读取一致）
                        sb.AppendLine($"            *((void**)({dstExpr} + {off})) = (void*){srcExpr}.{accessor}.GetUnsafePtr();");
                        sb.AppendLine($"            *((int*)({dstExpr} + {off + 8})) = {srcExpr}.{accessor}.Length;");
                    }
                    else if (NativeTranspiler.IsEntJoyContainerNamed(type, Config.NativeList))
                    {
            // NativeList：_listData（UnsafeList*，堆上稳定）在偏移 0，C++ 解引用读取。
                        sb.AppendLine($"            *((void**)({dstExpr} + {off})) = (void*){srcExpr}.{accessor}.GetListData();");
                    }
                    else // UnsafeList（值字段）：C++ 取 &blob[off] 作为 UnsafeList* -> 内联读 Ptr/Length/Capacity/Allocator
                    {
                        sb.AppendLine($"            *((void**)({dstExpr} + {off})) = (void*){srcExpr}.{accessor}.Ptr;");
                        sb.AppendLine($"            *((int*)({dstExpr} + {off + 8})) = {srcExpr}.{accessor}.Length;");
                        sb.AppendLine($"            *((int*)({dstExpr} + {off + 12})) = {srcExpr}.{accessor}.Capacity;");
                        sb.AppendLine($"            *((int*)({dstExpr} + {off + 16})) = (int){srcExpr}.{accessor}.Allocator;");
                    }
                }
                else if (type is IPointerTypeSymbol)
                {
                    // 指针字段：写指针值（同一进程地址空间，C++ 直接解引用；指向内存须非托管/固定且在 Job 期间存活??
                    sb.AppendLine($"            *((void**)({dstExpr} + {off})) = (void*){srcExpr}.{accessor};");
                }
                else if (type.TypeKind == TypeKind.Enum && type is INamedTypeSymbol enumSym)
                {
                    string underlying = enumSym.EnumUnderlyingType.SpecialType == SpecialType.System_UInt32 ? "uint" : "int";
                    sb.AppendLine($"            *(({underlying}*)({dstExpr} + {off})) = ({underlying}){srcExpr}.{accessor};");
                }
                else if (type.SpecialType == SpecialType.System_Single)
                {
                    sb.AppendLine($"            *((float*)({dstExpr} + {off})) = {srcExpr}.{accessor};");
                }
                else if (type.SpecialType == SpecialType.System_Int32)
                {
                    sb.AppendLine($"            *((int*)({dstExpr} + {off})) = {srcExpr}.{accessor};");
                }
                else if (type.SpecialType == SpecialType.System_UInt32)
                {
                    sb.AppendLine($"            *((uint*)({dstExpr} + {off})) = {srcExpr}.{accessor};");
                }
                else if (type.SpecialType == SpecialType.System_Boolean)
                {
                    sb.AppendLine($"            *((byte*)({dstExpr} + {off})) = (byte)({srcExpr}.{accessor} ? 1 : 0);");
                }
                else
                {
                    // blittable ??struct（float2/用户纯值结构等）：Unsafe.Write 直写（blittable ??Sequential 生效??
                    sb.AppendLine($"            System.Runtime.CompilerServices.Unsafe.Write((void*)({dstExpr} + {off}), {srcExpr}.{accessor});");
                }
            }
        }

        /// <summary>
        /// 生成 Job 字段显式写入器（chunk 路径 CreateChunkContextBlock 用）??
        /// 以类型化 ref 读取逻辑字段值（布局无关），显式写到 C++ context 偏移??
        /// </summary>
        private static void GenerateJobFieldWriterMethod(StringBuilder sb, INamedTypeSymbol jobStruct)
        {
            var (marshalled, explicitOk, _) = ComputeJobFieldMarshal(jobStruct);
            if (!explicitOk) return;   // 含不支持字段：不注册，chunk 路径回退裸拷贝。
            string jobTypeName = jobStruct.ToDisplayString();
            sb.AppendLine($"        internal static void WriteJobFields_{jobStruct.Name}(byte* dst, ref {jobTypeName} job)");
            sb.AppendLine("        {");
            EmitExplicitFieldWrites(sb, marshalled, "dst", "job");
            sb.AppendLine("        }");
            sb.AppendLine();
        }

        private static void GenerateJobExtensionMethod(StringBuilder sb, INamedTypeSymbol jobStruct)
        {
            bool isChunk = CppJobGenerator.IsChunkScheduledJob(jobStruct);
            bool isParallelFor = CppJobGenerator.IsParallelForJob(jobStruct);
            bool isFor = CppJobGenerator.IsForJob(jobStruct);
            string jobTypeName = jobStruct.ToDisplayString();

            if (isChunk)
            {
                sb.AppendLine($"    public static JobHandle Schedule(this {jobTypeName} job, QueryBuilder query, JobHandle dependsOn = default)");
                sb.AppendLine("    {");
                sb.AppendLine($"        return NativeTranspiler.Bindings.NativeExports.Schedule_{jobStruct.Name}(ref job, query, dependsOn);");
                sb.AppendLine("    }");
                sb.AppendLine();
                sb.AppendLine($"    public static JobHandle ScheduleWithWorkerCap(this {jobTypeName} job, QueryBuilder query, int workerCap, JobHandle dependsOn = default)");
                sb.AppendLine("    {");
                sb.AppendLine($"        return NativeTranspiler.Bindings.NativeExports.ScheduleWithWorkerCap_{jobStruct.Name}(ref job, query, workerCap, dependsOn);");
                sb.AppendLine("    }");
                sb.AppendLine();
                sb.AppendLine($"    public static JobHandle ScheduleWithWorkerCapAndRangeSize(this {jobTypeName} job, QueryBuilder query, int workerCap, int rangeSize, JobHandle dependsOn = default)");
                sb.AppendLine("    {");
                sb.AppendLine($"        return NativeTranspiler.Bindings.NativeExports.ScheduleWithWorkerCapAndRangeSize_{jobStruct.Name}(ref job, query, workerCap, rangeSize, dependsOn);");
                sb.AppendLine("    }");
                sb.AppendLine();
                sb.AppendLine($"    public static void RunImmediate(this {jobTypeName} job, QueryBuilder query)");
                sb.AppendLine("    {");
                sb.AppendLine($"        NativeTranspiler.Bindings.NativeExports.RunImmediate_{jobStruct.Name}(ref job, query);");
                sb.AppendLine("    }");
                sb.AppendLine();
            }
            else if (isParallelFor || isFor)
            {
                // ParallelFor/For: keep optional dependsOn (existing generic Schedule<T> has arrayLength params, no collision)
                var parameters = new List<string>
                {
                    $"this {jobTypeName} job",
                    "int arrayLength",
                    "int innerBatchCount = 0",
                    "JobHandle dependsOn = default"
                };
                sb.AppendLine($"    public static JobHandle Schedule({string.Join(", ", parameters)})");
                sb.AppendLine("    {");
                sb.AppendLine($"        return NativeTranspiler.Bindings.NativeExports.Schedule_{jobStruct.Name}(ref job, arrayLength, innerBatchCount, dependsOn);");
                sb.AppendLine("    }");
                sb.AppendLine();
            }
            else
            {
                // IJob: generate two overloads (no-arg and dependsOn) to beat existing Schedule<T>(this T job)
                sb.AppendLine($"    public static JobHandle Schedule(this {jobTypeName} job)");
                sb.AppendLine("    {");
                sb.AppendLine($"        return NativeTranspiler.Bindings.NativeExports.Schedule_{jobStruct.Name}(ref job, default);");
                sb.AppendLine("    }");
                sb.AppendLine();
                sb.AppendLine($"    public static JobHandle Schedule(this {jobTypeName} job, JobHandle dependsOn)");
                sb.AppendLine("    {");
                sb.AppendLine($"        return NativeTranspiler.Bindings.NativeExports.Schedule_{jobStruct.Name}(ref job, dependsOn);");
                sb.AppendLine("    }");
                sb.AppendLine();
            }
        }

        private static void GenerateJobRunMethod(StringBuilder sb, INamedTypeSymbol jobStruct, Compilation compilation)
        {
            bool isChunk = CppJobGenerator.IsChunkScheduledJob(jobStruct);
            bool isParallelFor = CppJobGenerator.IsParallelForJob(jobStruct);
            bool isFor = CppJobGenerator.IsForJob(jobStruct);
            string jobTypeName = jobStruct.ToDisplayString();

            var parameters = new List<string>();
            // Must match existing JobExtensions signature (this T job) to take precedence in overload resolution
            parameters.Add($"this {jobTypeName} job");
            if (isChunk)
            {
                parameters.Add("QueryBuilder query");
            }
            else if (isParallelFor || isFor)
            {
                parameters.Add("int arrayLength");
            }

            sb.AppendLine($"    public static void Run({string.Join(", ", parameters)})");
            sb.AppendLine("    {");
            if (isChunk)
            {
                sb.AppendLine($"        NativeTranspiler.Bindings.NativeExports.Schedule_{jobStruct.Name}(ref job, query, default).Complete();");
            }
            else if (isParallelFor || isFor)
            {
                sb.AppendLine($"        int startIndex = 0;");
                sb.AppendLine($"        int count = arrayLength;");
                sb.AppendLine($"        unsafe");
                sb.AppendLine($"        {{");
                sb.AppendLine($"            {jobTypeName}* jobPtr = &job;");
                sb.AppendLine($"            {{");

                var executeMethod = jobStruct.GetMembers().OfType<IMethodSymbol>().First(m => m.Name == Config.Execute);
                var methodSyntax = SymbolHelper.GetMethodSyntax(executeMethod);
                bool hasMultiVersion = false;
                string boolFieldName = null;
                if (methodSyntax != null)
                {
                    var semanticModel = compilation.GetSemanticModel(methodSyntax.SyntaxTree);
                    var conditionalFields = NativeTranspileValidator.GetConditionalReadOnlyFields(jobStruct, semanticModel);
                    var boolField = conditionalFields.FirstOrDefault(f => f.Type.SpecialType == SpecialType.System_Boolean);
                    if (boolField != null)
                    {
                        hasMultiVersion = true;
                        boolFieldName = boolField.Name;
                    }
                }

                string batchArgs2 = BuildBatchCallArgs(jobStruct, "jobPtr");
                string batchArgsWithComma2 = string.IsNullOrEmpty(batchArgs2) ? "" : ", " + batchArgs2;
                if (hasMultiVersion)
                {
                    sb.AppendLine($"                if (jobPtr->{boolFieldName})");
                    sb.AppendLine($"                    NativeTranspiler.Bindings.NativeExports.{jobStruct.Name}_Execute_Batch_true(startIndex, count{batchArgsWithComma2});");
                    sb.AppendLine($"                else");
                    sb.AppendLine($"                    NativeTranspiler.Bindings.NativeExports.{jobStruct.Name}_Execute_Batch_false(startIndex, count{batchArgsWithComma2});");
                }
                else
                {
                    sb.AppendLine($"                NativeTranspiler.Bindings.NativeExports.{jobStruct.Name}_Execute_Batch(startIndex, count{batchArgsWithComma2});");
                }
                sb.AppendLine($"            }}");
                sb.AppendLine($"        }}");
            }
            else
            {
                sb.AppendLine($"        unsafe");
                sb.AppendLine($"        {{");
                sb.AppendLine($"            {jobTypeName}* jobPtr = &job;");
                sb.AppendLine($"            {{");
                var args = BuildJobExecuteArgsForFixed(jobStruct);
                sb.AppendLine($"                NativeTranspiler.Bindings.NativeExports.{jobStruct.Name}_Execute({string.Join(", ", args)});");
                sb.AppendLine($"            }}");
                sb.AppendLine($"        }}");
            }
            sb.AppendLine("    }");
            sb.AppendLine();
        }

        private static List<string> BuildJobExecuteArgsForFixed(INamedTypeSymbol jobStruct)
        {
            var args = new List<string>();
            foreach (var field in jobStruct.GetMembers().OfType<IFieldSymbol>().Where(f => !f.IsStatic))
            {
                if (NativeTranspiler.IsEntJoyNativeContainerType(field.Type))
                {
                    if (NativeTranspiler.IsEntJoyContainerNamed(field.Type, Config.NativeList))
                    {
                        args.Add($"jobPtr->{field.Name}.GetListData()");
                    }
                    else
                    {
                        var elementType = ((INamedTypeSymbol)field.Type).TypeArguments[0];
                        var csElementType = elementType.ToDisplayString(SymbolDisplayFormat.FullyQualifiedFormat);
                        args.Add($"({csElementType}*)jobPtr->{field.Name}.GetUnsafePtr(), jobPtr->{field.Name}.Length");
                    }
                }
                else
                {
                    if (field.Type is IPointerTypeSymbol)
                        args.Add($"jobPtr->{field.Name}");
                    else
                        args.Add($"&jobPtr->{field.Name}");
                }
            }
            return args;
        }

        private static string GetCSharpParameterType(IParameterSymbol param)
        {
            var typeName = param.Type.ToDisplayString(SymbolDisplayFormat.FullyQualifiedFormat);
            return param.RefKind switch
            {
                RefKind.Ref => "ref " + typeName,
                RefKind.In => "in " + typeName,
                RefKind.Out => "out " + typeName,
                _ => typeName
            };
        }

        private static string GenerateCleanupFactoryMethod()
        {
            return @"
        private static CleanupFuncDelegate CreateCleanup<T>(int size) where T : struct
        {
            return context =>
            {
                IntPtr native = (IntPtr)context;
                Marshal.FreeHGlobal(native);
            };
        }";
        }

        /// <summary>
        /// 为 IJobEntity 生成 C# IJobChunk 适配器，内部调用原生 Execute 函数。
        /// 该适配器会被 ECS 源生成器检测并使用（通过命名约定）。
        /// </summary>
        private static void GenerateNativeIJobChunkAdapter(StringBuilder sb, INamedTypeSymbol jobStruct, Compilation compilation)
        {
            string jobTypeName = jobStruct.ToDisplayString();
            string adapterName = $"__NativeTranspiler_IJobChunkAdapter_{jobStruct.Name}";

            // 生成 Execute 方法的 DllImport（从原生代码调用）
            string executeFuncName = CppJobGenerator.GetCppJobFunctionName(jobStruct, isBatch: false);
            var executeMethod = jobStruct.GetMembers().OfType<IMethodSymbol>().First(m => m.Name == Config.Execute);
            var execParams = new List<string>();
            execParams.Add("IntPtr jobPtr");
            execParams.Add("ChunkJobData* chunkData");
            sb.AppendLine($"        [DllImport(\"{NativeLibraryName}\", EntryPoint = \"{executeFuncName}\", CallingConvention = CallingConvention.Cdecl)]");
            sb.AppendLine($"        private static extern void {jobStruct.Name}_Execute_Native({string.Join(", ", execParams)});");
            sb.AppendLine();

            // 生成 IJobChunk 适配器结构体
            sb.AppendLine($"    /// <summary>");
            sb.AppendLine($"    /// NativeTranspiler 生成的 IJobChunk 适配器，用于 {jobTypeName}。");
            sb.AppendLine($"    /// 该适配器调用原生 Execute 函数，实现高性能执行。");
            sb.AppendLine($"    /// </summary>");
            sb.AppendLine($"    [System.Runtime.InteropServices.StructLayout(System.Runtime.InteropServices.LayoutKind.Sequential)]");
            sb.AppendLine($"    public struct {adapterName} : IJobChunk");
            sb.AppendLine($"    {{");
            sb.AppendLine($"        public {jobTypeName} Job;");
            sb.AppendLine();
            sb.AppendLine($"        public void Execute(ArchetypeChunk chunk, in ChunkEnabledMask enabledMask)");
            sb.AppendLine($"        {{");
            sb.AppendLine($"            unsafe");
            sb.AppendLine($"            {{");
            sb.AppendLine($"                fixed ({jobTypeName}* jobPtr = &Job)");
            sb.AppendLine($"                {{");
            sb.AppendLine($"                    // 调用原生 Execute 函数");
            sb.AppendLine($"                    {jobStruct.Name}_Execute_Native((IntPtr)jobPtr, null);");
            sb.AppendLine($"                }}");
            sb.AppendLine($"            }}");
            sb.AppendLine($"        }}");
            sb.AppendLine($"    }}");
            sb.AppendLine();

            // 生成 JobExtensions 适配器（调用原生 Schedule）
            sb.AppendLine($"    /// <summary>");
            sb.AppendLine($"    /// 为 {jobTypeName} 生成的 JobExtensions，调用原生调度路径。");
            sb.AppendLine($"    /// </summary>");
            sb.AppendLine($"    public static partial class NativeJobExtensions_{jobStruct.Name}");
            sb.AppendLine($"    {{");
            sb.AppendLine($"        public static JobHandle Schedule(this {jobTypeName} job, QueryBuilder query, JobHandle dependsOn = default)");
            sb.AppendLine($"        {{");
            sb.AppendLine($"            return NativeExports.Schedule_{jobStruct.Name}(ref job, query, dependsOn);");
            sb.AppendLine($"        }}");
            sb.AppendLine();
            sb.AppendLine($"        public static JobHandle ScheduleWithWorkerCap(this {jobTypeName} job, QueryBuilder query, int workerCap, JobHandle dependsOn = default)");
            sb.AppendLine($"        {{");
            sb.AppendLine($"            return NativeExports.ScheduleWithWorkerCap_{jobStruct.Name}(ref job, query, workerCap, dependsOn);");
            sb.AppendLine($"        }}");
            sb.AppendLine();
            sb.AppendLine($"        public static void Run(this {jobTypeName} job, QueryBuilder query)");
            sb.AppendLine($"        {{");
            sb.AppendLine($"            NativeExports.Schedule_{jobStruct.Name}(ref job, query, default).Complete();");
            sb.AppendLine($"        }}");
            sb.AppendLine($"    }}");
            sb.AppendLine();
        }

    }
}
