using Microsoft.CodeAnalysis;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using NativeTranspiler.Analyzer.Common;

namespace NativeTranspiler.Analyzer
{
    public static class BindingsGenerator
    {
        // DLL 分离后：生成代码（wrapper/adapter）编译进 NativeTranspiled.dll。
        // 核心 runtime（JobSystem 等）仍在 NativeDll.dll。
        private const string NativeLibraryName = "NativeTranspiled";

        public static string GenerateBindingsClass(
            IEnumerable<IMethodSymbol> methods,
            IEnumerable<INamedTypeSymbol> jobStructs,
            Compilation compilation)
        {
            var sb = new StringBuilder();
            sb.AppendLine("// <auto-generated/>");
            // job 结构含 NativeArray/NativeList（内含托管 DisposeSentinel）→ 托管类型。生成代码用
            // sizeof/取址/指针强转把 job 的 blittable 字段搬运/读到 native 侧，是验证过的安全模式；
            // CS8500（对托管类型取大小/地址）为 false positive，按 Unity 生成 interop 代码惯例屏蔽。
            sb.AppendLine("#pragma warning disable CS8500");
            sb.AppendLine("using System;");
            sb.AppendLine("using System.Runtime.InteropServices;");
            sb.AppendLine("using System.Runtime.CompilerServices;");
            // Jobs-only 支持：无 chunk/entity（ECS）job 时不发射 ECS 命名空间与 ECS 类型成员，
            // 使只引用 EntJoy.Collections/EntJoy.Jobs 的项目也能编译生成的 bindings。
            var jobList = jobStructs.ToList();
            bool hasChunkScheduledJob = jobList.Any(CppJobGenerator.IsChunkScheduledJob);
            if (hasChunkScheduledJob)
            {
                sb.AppendLine("using EntJoy.ECS;");
                sb.AppendLine("using EntJoy.ECS.JobSystem;");
            }
            sb.AppendLine("using EntJoy.Collections;");
            sb.AppendLine("using EntJoy.JobSystem;");
            sb.AppendLine();
            sb.AppendLine("namespace NativeTranspiler.Bindings");
            sb.AppendLine("{");
            sb.AppendLine("    public static unsafe partial class NativeExports");
            sb.AppendLine("    {");
            sb.AppendLine("        public delegate void JobFuncDelegate(IntPtr context);");
            sb.AppendLine("        public delegate void BatchJobFuncDelegate(IntPtr context, int startIndex, int count);");
            if (hasChunkScheduledJob)
                sb.AppendLine("        public delegate void ChunkJobFuncDelegate(IntPtr context, ChunkJobData* chunkData);");
            sb.AppendLine("        public delegate void CleanupFuncDelegate(IntPtr context);");
            sb.AppendLine();

            var attrSymbol = compilation.GetTypeByMetadataName("NativeTranspiler.NativeTranspileAttribute");

            // GPU/CUDA 后端已拆分至 feature/gpu-offload 分支；dev 仅保留 Cpp/Ispc Job。
            var nativeJobs = jobList;

            // 1. 为每个 Job 结构体生成静态缓存的委托字段和函数指针。
            foreach (var jobStruct in nativeJobs)
            {
                GenerateStaticDelegateFields(sb, jobStruct, compilation);
            }

            // 2. 静态构造函数：初始化所有缓存的委托和函数指针。
            sb.AppendLine("        static NativeExports()");
            sb.AppendLine("        {");
            foreach (var jobStruct in nativeJobs)
            {
                GenerateStaticConstructorInitialization(sb, jobStruct, compilation);
            }
            // 注册 Job 字段显式写入器（chunk 路径 CreateChunkContextBlock 分发用）
            foreach (var jobStruct in nativeJobs)
            {
                if (ComputeJobFieldMarshal(jobStruct).explicitOk)
                {
                    sb.AppendLine($"            NativeJobScheduler.RegisterJobFieldWriter(typeof({jobStruct.ToDisplayString()}), (NativeJobScheduler.JobFieldWriter<{jobStruct.ToDisplayString()}>)WriteJobFields_{jobStruct.Name});");
                }
            }
            // 2026-10-02（09 §22.6）：注册单任务 job 的**原生 adapter 指针**，让运行时泛型
            // `JobScheduler.Schedule(ref job)`（= 宿主实际调用的路径）也能走原生直调，
            // 而不是只在生成的 `job.Schedule()` 扩展上可用。
            // 只在"字段可显式写入"（explicitOk）时注册：原生 adapter 按 C++ 偏移读 ctx，
            // Debug 下 NativeArray 带 DisposeSentinel ⇒ 裸拷贝布局不可靠，两侧必须同一套逐字段写入。
            foreach (var jobStruct in nativeJobs)
            {
                var marshalInfo = ComputeJobFieldMarshal(jobStruct);
                if (!marshalInfo.explicitOk) continue;
                var attrSymReg = AttributeHelper.GetAttributeSymbol(compilation);
                bool useMTReg = HasUseISPC_MT(jobStruct, attrSymReg);
                if (CppJobGenerator.IsIJob(jobStruct))
                {
                    // ctx 字节数取生成器算出的 `totalSize`（= `WriteJobFields_X` 实际写入的长度），
                    // 不能由运行时用 `Marshal.SizeOf<T>()` 猜（含 NativeArray 的泛型类型会抛）。
                    sb.AppendLine($"            NativeJobScheduler.RegisterNativeJobAdapter(typeof({jobStruct.ToDisplayString()}), s_{jobStruct.Name}_JobFuncPtr, {marshalInfo.totalSize});");
                }
                else if (CppJobGenerator.IsRangeScheduledJob(jobStruct))
                {
                    // 2026-10-02（同类修复，09 §24/§25）：批形态的原生 adapter 签名 `(void*, int, int)`
                    // 与原生 `BatchJobFunc` 逐字一致 ⇒ 静态运行期 API 也能直换指针。
                    // ⚠ MT 变体的 `s_X_BatchFuncPtr` 是**托管 delegate**（有意保留）⇒ 不注册。
                    if (!useMTReg)
                        sb.AppendLine($"            NativeJobScheduler.RegisterNativeJobAdapter(typeof({jobStruct.ToDisplayString()}), s_{jobStruct.Name}_BatchFuncPtr, {marshalInfo.totalSize});");
                    // 2026-10-02（09 §26）：`IJobFor` 另有 **index 形** adapter（`IndexJobFunc(void*, int)`），
                    // 供运行时 `ScheduleFor`（单线程串行语义）直调 —— 与批形分开注册，避免 ABI 混用。
                    if (!useMTReg && CppJobGenerator.IsForJob(jobStruct))
                        sb.AppendLine($"            NativeJobScheduler.RegisterNativeForAdapter(typeof({jobStruct.ToDisplayString()}), Get_{jobStruct.Name}_IndexAdapterPtr(), {marshalInfo.totalSize});");
                }
            }
            sb.AppendLine("        }");
            sb.AppendLine();
            // 2026-10-02（09 §25，注册时机）：上面的注册发生在 `NativeExports` 的**静态构造**里，
            // 而它只在该类**首次被触碰**时执行。若调用方在触碰它之前就走运行时静态 API
            //（`JobScheduler.Schedule*` / `ScheduleFor`），那一刻注册表还是空的 ⇒ 该次派发会**回退托管**
            //（正确但慢），造成"第一拍不是原生"的隐性退化。
            // 用 `[ModuleInitializer]` 把注册钉在**程序集加载**时，消除对外部调用顺序的依赖。
            // ⚠ 可移植性：`ModuleInitializerAttribute` 是 net5+ 才有的 BCL 类型。消费方若 target
            //   netstandard2.x / net472 会 CS0246 ⇒ 先探测再发射；缺该类型时**不发射**，
            //   注册退回"首次触碰 NativeExports 时"（即本改动之前的惰性语义，正确但仍有时序依赖）。
            bool hasModuleInitializer = compilation
                .GetTypeByMetadataName("System.Runtime.CompilerServices.ModuleInitializerAttribute") != null;
            if (hasModuleInitializer)
            {
                // 自动方式：程序集加载即注册。**方法体为空是有意的** ——
                //   本类型有显式静态构造 ⇒ 运行时在**调用本方法之前**必然先跑 cctor（注册在其中完成）。
                //   （注意：`_ = typeof(X)` **不保证**触发 cctor，别再用那种写法来表达"触碰类型"。）
                // 手动方式（AOT/IL2CPP 或不信任 module initializer 的宿主）：直接调用public 的
                //   `EnsureNativeJobRegistrations()`；cctor 只跑一次 ⇒ 幂等、可重复调用。
                sb.AppendLine("        /// <summary>");
                sb.AppendLine("        /// 原生 adapter / 字段写入器注册（自动：本方法标了 [ModuleInitializer]，程序集加载即调用；");
                sb.AppendLine("        /// 手动：AOT/IL2CPP 宿主或需要确定性顺序时，可在启动处直接调用 —— 幂等，可重复调用）。");
                sb.AppendLine("        /// </summary>");
                sb.AppendLine("        [global::System.Runtime.CompilerServices.ModuleInitializer]");
                sb.AppendLine("        public static void EnsureNativeJobRegistrations()");
                sb.AppendLine("        {");
                sb.AppendLine("            // 有意留空：进入本方法前运行时已完成本类型的静态构造（注册在那里完成）。");
                sb.AppendLine("        }");
            }
            else
            {
                // 无 ModuleInitializerAttribute（netstandard2.x / net472）：仍需一个**公开的手动入口**，
                // 否则消费方无法保证注册先于首次调度。方法体同样为空（调用即触发 cctor）。
                sb.AppendLine("        /// <summary>");
                sb.AppendLine("        /// 原生 adapter / 字段写入器注册（手动：本目标框架无 [ModuleInitializer]，");
                sb.AppendLine("        /// 请在启动处调用一次；幂等，可重复调用）。");
                sb.AppendLine("        /// </summary>");
                sb.AppendLine("        public static void EnsureNativeJobRegistrations()");
                sb.AppendLine("        {");
                sb.AppendLine("            // 有意留空：进入本方法前运行时已完成本类型的静态构造（注册在那里完成）。");
                sb.AppendLine("        }");
            }
            sb.AppendLine();

            // 3. 普通方法的 DllImport 和 Wrapper（MT 变体按方法上的 UseISPC_MT 决定）
            foreach (var method in methods)
            {
                GenerateMethodDllImport(sb, method);
                bool useMT = HasUseISPC_MT(method, attrSymbol);
                if (useMT)
                {
                    GenerateMethodDllImportMT(sb, method);
                }
                GenerateMethodWrapper(sb, method, useMT);
            }

            // 4. Job 结构体的 DllImport 和 Schedule 方法。
            foreach (var jobStruct in nativeJobs)
            {
                GenerateJobDllImport(sb, jobStruct, compilation);
                GenerateJobScheduleMethod(sb, jobStruct, compilation);
            }

            // 4c. 显式 Job 字段写入器（chunk 路径 CreateChunkContextBlock 用）。
            //     Debug 下 DisposeSentinel 让 Job struct 变成非 blittable ⇒ 裸拷贝布局不可靠，
            //     ⇒ 为 Job 生成类型化写入器，静态构造时注册到 NativeJobScheduler 的注册表（EntJoy 侧）。
            if (nativeJobs.Count > 0)
            {
                foreach (var jobStruct in nativeJobs)
                    GenerateJobFieldWriterMethod(sb, jobStruct);
                sb.AppendLine();
            }

            sb.AppendLine(GenerateCleanupFactoryMethod());
            sb.AppendLine("    }");
            sb.AppendLine("}");
            sb.AppendLine();

            // 5. Job 扩展方法（Schedule 和 Run）
            // 注意：IJobChunk / IJobEntity 的扩展方法由 ECS 生成器生成（job 所在命名空间，与
            // 用户代码同域），不在此生成。这里只保留 IJob/IJobParallelFor/IJobFor。
            var nonChunkJobs = nativeJobs.Where(j => !CppJobGenerator.IsChunkScheduledJob(j)).ToList();
            if (nonChunkJobs.Count > 0)
            {
                sb.AppendLine("public static partial class JobExtensions");
                sb.AppendLine("{");
                foreach (var jobStruct in nonChunkJobs)
                {
                    GenerateJobExtensionMethod(sb, jobStruct);
                    GenerateJobRunMethod(sb, jobStruct, compilation);
                }
                sb.AppendLine("}");
            }

            return sb.ToString();
        }

        private static bool HasUseISPC_MT(ISymbol symbol, INamedTypeSymbol? attrSymbol)
            => AttributeHelper.HasUseISPC_MT(symbol, attrSymbol);

        // ---------- 方法 DllImport ----------
        private static void GenerateMethodDllImport(StringBuilder sb, IMethodSymbol method)
        {
            var cppFunctionName = CppGenerator.GetCppFunctionName(method);
            var returnType = method.ReturnType.ToDisplayString(SymbolDisplayFormat.FullyQualifiedFormat);
            var methodName = method.Name + "_Native";
            var parameters = BuildMethodDllImportParams(method);
            sb.AppendLine($"        [DllImport(\"{NativeLibraryName}\", EntryPoint = \"{cppFunctionName}\", CallingConvention = CallingConvention.Cdecl)]");
            sb.AppendLine($"        private static extern {returnType} {methodName}({string.Join(", ", parameters)});");
            sb.AppendLine();
        }

        private static void GenerateMethodDllImportMT(StringBuilder sb, IMethodSymbol method)
        {
            var cppFunctionName = CppGenerator.GetCppFunctionName(method) + "_mt";
            var returnType = method.ReturnType.ToDisplayString(SymbolDisplayFormat.FullyQualifiedFormat);
            var methodName = method.Name + "_mt_Native";
            var parameters = BuildMethodDllImportParams(method);
            parameters.Add("int numTasks");
            sb.AppendLine($"        [DllImport(\"{NativeLibraryName}\", EntryPoint = \"{cppFunctionName}\", CallingConvention = CallingConvention.Cdecl)]");
            sb.AppendLine($"        private static extern {returnType} {methodName}({string.Join(", ", parameters)});");
            sb.AppendLine();
        }

        private static void GenerateMethodWrapper(StringBuilder sb, IMethodSymbol method, bool useMT)
        {
            var returnType = method.ReturnType.ToDisplayString(SymbolDisplayFormat.FullyQualifiedFormat);
            var methodName = method.Name;
            var parameters = method.Parameters.Select(p => $"{GetCSharpParameterType(p)} {p.Name}");
            sb.AppendLine($"        public static {returnType} {methodName}({string.Join(", ", parameters)})");
            sb.AppendLine("        {");
            sb.AppendLine("            unsafe {");
            // 直调执行窗口：Begin 在调用前开窗口（当前线程泳道，事件驱动），
            // finally 确保无论异常与否都关闭窗口并上报共享时间线段。
            sb.AppendLine($"            ulong __dbgId = NativeJobScheduler.BeginDirectCall(\"{methodName}\", {(useMT ? "(uint)Environment.ProcessorCount" : "1u")});");
            sb.AppendLine("            try {");
            if (method.ReturnType.SpecialType != SpecialType.System_Void)
                sb.Append("                return ");
            else
                sb.Append("                ");

            if (useMT)
            {
                sb.Append($"{methodName}_mt_Native(");
                var args = BuildMethodCallArgs(method);
                args.Add("Environment.ProcessorCount");
                sb.Append(string.Join(", ", args));
            }
            else
            {
                sb.Append($"{methodName}_Native(");
                var args = BuildMethodCallArgs(method);
                sb.Append(string.Join(", ", args));
            }
            sb.AppendLine(");");
            sb.AppendLine("            }");
            sb.AppendLine("            finally { NativeJobScheduler.EndDirectCall(__dbgId); }");
            sb.AppendLine("            }");
            sb.AppendLine("        }");
            sb.AppendLine();
        }

        // ---------- Job 委托字段 ----------
        private static void GenerateStaticDelegateFields(StringBuilder sb, INamedTypeSymbol jobStruct, Compilation compilation)
        {
            bool isChunk = CppJobGenerator.IsChunkScheduledJob(jobStruct);
            bool isParallelFor = CppJobGenerator.IsRangeScheduledJob(jobStruct);
            bool isFor = CppJobGenerator.IsForJob(jobStruct);

            if (isChunk)
            {
                if (CppJobGenerator.IsEntityJob(jobStruct))
                {
            // IJobEntity 统一走 Chunk 级调度（与 ISPC 路径一致）。
                    sb.AppendLine($"        private static readonly IntPtr s_{jobStruct.Name}_ChunkFuncPtr;");
                    sb.AppendLine($"        private static readonly IntPtr s_{jobStruct.Name}_ChunkRangeFuncPtr;");
                }
                else
                {
                    sb.AppendLine($"        private static readonly IntPtr s_{jobStruct.Name}_ChunkFuncPtr;");
                    sb.AppendLine($"        private static readonly IntPtr s_{jobStruct.Name}_ChunkRangeFuncPtr;");
                    var attrSym2 = AttributeHelper.GetAttributeSymbol(compilation);
                    bool isIspc2 = attrSym2 != null && AttributeHelper.GetBackendTarget(jobStruct, attrSym2) == NativeTranspiler.BackendTarget.Ispc;
                    // EntityBatch 指针仅对无 shared 的 C++ job 声明（shared 时 adapter 不生成，
                    // 与初始化/调度分流一致）
                    bool hasShared2 = CppJobGenerator.CollectSharedComponentTypes(jobStruct, compilation).Count > 0;
                    if (!isIspc2 && !hasShared2)
                        sb.AppendLine($"        private static readonly IntPtr s_{jobStruct.Name}_ChunkEntityBatchFuncPtr;");
                }
                var requiredTypes = CppJobGenerator.CollectChunkNativeArrayTypes(jobStruct, compilation);
                string requiredIds = BuildRequiredComponentTypeIdsInitializer(requiredTypes);
                sb.AppendLine($"        private static readonly int[] s_{jobStruct.Name}_RequiredComponentTypeIds = {requiredIds};");
                // SharedComponent 类型 ID 数组（per-chunk 值指针，blittable only）
                var sharedTypes = CppJobGenerator.CollectSharedComponentTypes(jobStruct, compilation);
                string sharedIds = BuildRequiredComponentTypeIdsInitializer(sharedTypes);
                sb.AppendLine($"        private static readonly int[] s_{jobStruct.Name}_RequiredSharedTypeIds = {sharedIds};");
            }
            else if (isParallelFor || isFor)
            {
                sb.AppendLine($"        private static readonly BatchJobFuncDelegate s_{jobStruct.Name}_BatchFunc;");
                sb.AppendLine($"        private static readonly IntPtr s_{jobStruct.Name}_BatchFuncPtr;");
            }
            else
            {
                // 2026-10-02（09 §22.6）：单任务 job 改走原生 adapter 直调 ⇒ 不再需要托管
                // `JobFuncDelegate` 字段（顺带消掉 CS0169）。只保留指针字段。
                sb.AppendLine($"        private static readonly IntPtr s_{jobStruct.Name}_JobFuncPtr;");
            }
            sb.AppendLine($"        private static readonly CleanupFuncDelegate s_{jobStruct.Name}_CleanupFunc;");
            sb.AppendLine($"        private static readonly IntPtr s_{jobStruct.Name}_CleanupFuncPtr;");
            sb.AppendLine();
        }

        private static void GenerateStaticConstructorInitialization(StringBuilder sb, INamedTypeSymbol jobStruct, Compilation compilation)
        {
            string jobTypeFullName = jobStruct.ToDisplayString();
            bool isParallelFor = CppJobGenerator.IsRangeScheduledJob(jobStruct);
            bool isFor = CppJobGenerator.IsForJob(jobStruct);
            bool isChunk = CppJobGenerator.IsChunkScheduledJob(jobStruct);

            var executeMethod = jobStruct.GetMembers().OfType<IMethodSymbol>().First(m => m.Name == Config.Execute);
            var methodSyntax = SymbolHelper.GetMethodSyntax(executeMethod);
            bool hasMultiVersion = false;
            string boolFieldName = null;
            List<IFieldSymbol> boolFields = new List<IFieldSymbol>();

            var attrSymbol = compilation.GetTypeByMetadataName("NativeTranspiler.NativeTranspileAttribute");
            bool useMT = HasUseISPC_MT(jobStruct, attrSymbol);

            if (methodSyntax != null)
            {
                var semanticModel = compilation.GetSemanticModel(methodSyntax.SyntaxTree);
                var conditionalFields = NativeTranspileValidator.GetConditionalReadOnlyFields(jobStruct, semanticModel);
                boolFields = conditionalFields.Where(f => f.Type.SpecialType == SpecialType.System_Boolean).ToList();
                if (boolFields.Count > 0)
                {
                    hasMultiVersion = true;
                    boolFieldName = boolFields[0].Name;
                }
            }

            if (isChunk)
            {
                if (CppJobGenerator.IsEntityJob(jobStruct))
                {
            // IJobEntity 统一走 Chunk 级调度（与 ISPC 路径一致）。
                    sb.AppendLine($"            s_{jobStruct.Name}_ChunkFuncPtr = Get_{jobStruct.Name}_ChunkAdapterPtr();");
                    sb.AppendLine($"            s_{jobStruct.Name}_ChunkRangeFuncPtr = Get_{jobStruct.Name}_ChunkRangeAdapterPtr();");
                }
                else
                {
                    sb.AppendLine($"            s_{jobStruct.Name}_ChunkFuncPtr = Get_{jobStruct.Name}_ChunkAdapterPtr();");
                    sb.AppendLine($"            s_{jobStruct.Name}_ChunkRangeFuncPtr = Get_{jobStruct.Name}_ChunkRangeAdapterPtr();");
                    var attrSym2 = AttributeHelper.GetAttributeSymbol(compilation);
                    bool isIspc2 = attrSym2 != null && AttributeHelper.GetBackendTarget(jobStruct, attrSym2) == NativeTranspiler.BackendTarget.Ispc;
                    // EntityBatchAdapter 不支持 shared components（shared 值 per-chunk，batch 层无访问）
                    bool hasShared = CppJobGenerator.CollectSharedComponentTypes(jobStruct, compilation).Count > 0;
                    if (!isIspc2 && !hasShared)
                        sb.AppendLine($"            s_{jobStruct.Name}_ChunkEntityBatchFuncPtr = Get_{jobStruct.Name}_ChunkEntityBatchAdapterPtr();");
                }
            }
            else if (isParallelFor || isFor)
            {
                if (useMT)
                {
            // MT（task 内部自己调度）仍用托管 delegate：原生 Adapter 只生成非 MT 变体。
                string mtSuffix = "_mt";

                sb.AppendLine($"            s_{jobStruct.Name}_BatchFunc = (IntPtr context, int startIndex, int count) =>");
                sb.AppendLine("            {");
                sb.AppendLine($"                var jobPtr = ({jobTypeFullName}*)context;");

                string batchArgs = BuildBatchCallArgs(jobStruct, "jobPtr");
                string batchArgsWithComma = string.IsNullOrEmpty(batchArgs) ? "" : ", " + batchArgs;
                if (hasMultiVersion)
                {
                    // 生成所有 2^n 个 bool 组合的 if-else 链，与 C++ 端命名一致。
                    int totalVariants = 1 << boolFields.Count;
                    var boolVarNames = boolFields.Select(f => $"jobPtr->{f.Name}").ToList();

                    for (int mask = 0; mask < totalVariants; mask++)
                    {
                        var values = new List<bool>();
                        for (int i = 0; i < boolFields.Count; i++)
                            values.Add((mask & (1 << i)) != 0);

                        string suffix = "_" + string.Join("_", values.Select(v => v ? "true" : "false"));

                        bool isLast = (mask == totalVariants - 1);
                        if (mask == 0)
                        {
                            string condition = string.Join(" && ", boolFields.Select((f, i) => values[i] ? $"jobPtr->{f.Name}" : $"!jobPtr->{f.Name}"));
                            sb.AppendLine($"                if ({condition})");
                        }
                        else if (!isLast)
                        {
                            string condition = string.Join(" && ", boolFields.Select((f, i) => values[i] ? $"jobPtr->{f.Name}" : $"!jobPtr->{f.Name}"));
                            sb.AppendLine($"                else if ({condition})");
                        }
                        else
                        {
                            sb.AppendLine("                else");
                        }

                        sb.AppendLine($"                    {jobStruct.Name}_Execute_Batch{suffix}{mtSuffix}(startIndex, count{batchArgsWithComma});");
                    }
                }
                else
                {
                    sb.AppendLine($"                {jobStruct.Name}_Execute_Batch{mtSuffix}(startIndex, count{batchArgsWithComma});");
                }
                sb.AppendLine("            };");
                sb.AppendLine($"            s_{jobStruct.Name}_BatchFuncPtr = Marshal.GetFunctionPointerForDelegate(s_{jobStruct.Name}_BatchFunc);");
                }
                else
                {
                    // 走 MT：调度器直接调原生 _Execute_Adapter(context,start,count)（原生→原生），
                    // 消除托管 BatchFunc delegate 的 原生→托管→原生 双重转换（每 tile ~3μs 开销）。
                    // 原生 Adapter 由 CppJobGenerator 生成：同一套字段偏移解析 / UnsafeList 写回 / bool 变体分派。
                    sb.AppendLine($"            s_{jobStruct.Name}_BatchFuncPtr = Get_{jobStruct.Name}_Execute_AdapterPtr();");
                }
            }
            else
            {
                // 2026-10-02（IJob 原生直调，09 §22.6）：与 IJobParallelFor(非 MT)/Chunk 系一致 ——
                // 直接取**原生 adapter** 指针，去掉 `Marshal.GetFunctionPointerForDelegate` 造的
                // native→managed→native 反向 thunk。adapter 由 CppJobGenerator 一直为 IJob 产出
                //（`X_Execute_Adapter(void* context)`：按 C++ 偏移解字段后调原生内核）。
                // ⚠ 布局前提：adapter 按 C++ 偏移读 ctx ⇒ 必须用生成代码的**逐字段写入**
                //（`WriteJobFields_X`），不能用裸拷贝（Debug 下 NativeArray 带 DisposeSentinel）。
                // 未注册/不可显式写入的情形由运行时**回退托管 delegate**（行为不变）。
                sb.AppendLine($"            s_{jobStruct.Name}_JobFuncPtr = Get_{jobStruct.Name}_Execute_AdapterPtr();");
            }

            sb.AppendLine($"            s_{jobStruct.Name}_CleanupFunc = (IntPtr context) =>");
            sb.AppendLine("            {");
            sb.AppendLine("                Marshal.FreeHGlobal(context);");
            sb.AppendLine("            };");
            sb.AppendLine($"            s_{jobStruct.Name}_CleanupFuncPtr = Marshal.GetFunctionPointerForDelegate(s_{jobStruct.Name}_CleanupFunc);");
            sb.AppendLine();
        }

        private static void GenerateJobDllImport(StringBuilder sb, INamedTypeSymbol jobStruct, Compilation compilation)
        {
            bool isChunk = CppJobGenerator.IsChunkScheduledJob(jobStruct);
            bool isParallelFor = CppJobGenerator.IsRangeScheduledJob(jobStruct);
            bool isFor = CppJobGenerator.IsForJob(jobStruct);

            var attrSymbol = compilation.GetTypeByMetadataName("NativeTranspiler.NativeTranspileAttribute");
            bool useMT = HasUseISPC_MT(jobStruct, attrSymbol);

            if (isChunk)
            {
                if (CppJobGenerator.IsEntityJob(jobStruct))
                {
            // IJobEntity 统一走 Chunk 级调度。
                    var getterName = CppJobGenerator.GetAdapterPtrGetterName(jobStruct);
                    var rangeGetterName = CppJobGenerator.GetRangeAdapterPtrGetterName(jobStruct);
                    sb.AppendLine($"        [DllImport(\"{NativeLibraryName}\", EntryPoint = \"{getterName}\", CallingConvention = CallingConvention.Cdecl)]");
                    sb.AppendLine($"        private static extern IntPtr Get_{jobStruct.Name}_ChunkAdapterPtr();");
                    sb.AppendLine($"        [DllImport(\"{NativeLibraryName}\", EntryPoint = \"{rangeGetterName}\", CallingConvention = CallingConvention.Cdecl)]");
                    sb.AppendLine($"        private static extern IntPtr Get_{jobStruct.Name}_ChunkRangeAdapterPtr();");
                }
                else
                {
                    var getterName = CppJobGenerator.GetAdapterPtrGetterName(jobStruct);
                    var rangeGetterName = CppJobGenerator.GetRangeAdapterPtrGetterName(jobStruct);
                    var entityBatchGetterName = CppJobGenerator.GetEntityBatchAdapterPtrGetterName(jobStruct);
                    sb.AppendLine($"        [DllImport(\"{NativeLibraryName}\", EntryPoint = \"{getterName}\", CallingConvention = CallingConvention.Cdecl)]");
                    sb.AppendLine($"        private static extern IntPtr Get_{jobStruct.Name}_ChunkAdapterPtr();");
                    sb.AppendLine($"        [DllImport(\"{NativeLibraryName}\", EntryPoint = \"{rangeGetterName}\", CallingConvention = CallingConvention.Cdecl)]");
                    sb.AppendLine($"        private static extern IntPtr Get_{jobStruct.Name}_ChunkRangeAdapterPtr();");
                    var attrSym2 = AttributeHelper.GetAttributeSymbol(compilation);
                    bool isIspc2 = attrSym2 != null && AttributeHelper.GetBackendTarget(jobStruct, attrSym2) == NativeTranspiler.BackendTarget.Ispc;
                    // 与声明/初始化一致：shared job 无 EntityBatch adapter，不生成 extern
                    bool hasShared2 = CppJobGenerator.CollectSharedComponentTypes(jobStruct, compilation).Count > 0;
                    if (!isIspc2 && !hasShared2)
                    {
                        sb.AppendLine($"        [DllImport(\"{NativeLibraryName}\", EntryPoint = \"{entityBatchGetterName}\", CallingConvention = CallingConvention.Cdecl)]");
                        sb.AppendLine($"        private static extern IntPtr Get_{jobStruct.Name}_ChunkEntityBatchAdapterPtr();");
                    }
                }
            }
            else if (isParallelFor || isFor)
            {
                var batchFuncName = CppJobGenerator.GetCppJobFunctionName(jobStruct, isBatch: true);
                var batchParams = BuildBatchJobDllImportParams(jobStruct);

                var executeMethod = jobStruct.GetMembers().OfType<IMethodSymbol>().First(m => m.Name == Config.Execute);
                var methodSyntax = SymbolHelper.GetMethodSyntax(executeMethod);
                bool hasMultiVersion = false;
                if (methodSyntax != null)
                {
                    var semanticModel = compilation.GetSemanticModel(methodSyntax.SyntaxTree);
                    var conditionalFields = NativeTranspileValidator.GetConditionalReadOnlyFields(jobStruct, semanticModel);
                    hasMultiVersion = conditionalFields.Any(f => f.Type.SpecialType == SpecialType.System_Boolean);
                }

                if (hasMultiVersion)
                {
                    sb.AppendLine($"        [DllImport(\"{NativeLibraryName}\", EntryPoint = \"{batchFuncName}_true\", CallingConvention = CallingConvention.Cdecl)]");
                    sb.AppendLine($"        public static extern void {jobStruct.Name}_Execute_Batch_true({string.Join(", ", batchParams)});");
                    sb.AppendLine($"        [DllImport(\"{NativeLibraryName}\", EntryPoint = \"{batchFuncName}_false\", CallingConvention = CallingConvention.Cdecl)]");
                    sb.AppendLine($"        public static extern void {jobStruct.Name}_Execute_Batch_false({string.Join(", ", batchParams)});");
                }
                else
                {
                    sb.AppendLine($"        [DllImport(\"{NativeLibraryName}\", EntryPoint = \"{batchFuncName}\", CallingConvention = CallingConvention.Cdecl)]");
                    sb.AppendLine($"        public static extern void {jobStruct.Name}_Execute_Batch({string.Join(", ", batchParams)});");
                }

                if (useMT)
                {
                    if (hasMultiVersion)
                    {
                        sb.AppendLine($"        [DllImport(\"{NativeLibraryName}\", EntryPoint = \"{batchFuncName}_true_mt\", CallingConvention = CallingConvention.Cdecl)]");
                        sb.AppendLine($"        private static extern void {jobStruct.Name}_Execute_Batch_true_mt({string.Join(", ", batchParams)});");
                        sb.AppendLine($"        [DllImport(\"{NativeLibraryName}\", EntryPoint = \"{batchFuncName}_false_mt\", CallingConvention = CallingConvention.Cdecl)]");
                        sb.AppendLine($"        private static extern void {jobStruct.Name}_Execute_Batch_false_mt({string.Join(", ", batchParams)});");
                    }
                    else
                    {
                        sb.AppendLine($"        [DllImport(\"{NativeLibraryName}\", EntryPoint = \"{batchFuncName}_mt\", CallingConvention = CallingConvention.Cdecl)]");
                        sb.AppendLine($"        private static extern void {jobStruct.Name}_Execute_Batch_mt({string.Join(", ", batchParams)});");
                    }
                }
                else
                {
                    // 走 MT：声明原生 Adapter 指针 Getter（调度器原生→原生直调路径）
                    var adapterGetterName = CppJobGenerator.GetAdapterPtrGetterName(jobStruct);
                    sb.AppendLine($"        [DllImport(\"{NativeLibraryName}\", EntryPoint = \"{adapterGetterName}\", CallingConvention = CallingConvention.Cdecl)]");
                    sb.AppendLine($"        private static extern IntPtr Get_{jobStruct.Name}_Execute_AdapterPtr();");
                    // 2026-10-02（09 §26）：`IJobFor` 另有一个 **index 形** adapter getter
                    //（`void(void*, int)`，供 `ScheduleFor` 的单线程串行语义直调）。
                    if (CppJobGenerator.IsForJob(jobStruct))
                    {
                        var indexGetter = CppJobGenerator.GetIndexAdapterPtrGetterName(jobStruct);
                        sb.AppendLine($"        [DllImport(\"{NativeLibraryName}\", EntryPoint = \"{indexGetter}\", CallingConvention = CallingConvention.Cdecl)]");
                        sb.AppendLine($"        private static extern IntPtr Get_{jobStruct.Name}_IndexAdapterPtr();");
                    }
                }
            }
            else
            {
                var singleFuncName = CppJobGenerator.GetCppJobFunctionName(jobStruct);
                var singleParams = BuildJobDllImportParams(jobStruct);
                sb.AppendLine($"        [DllImport(\"{NativeLibraryName}\", EntryPoint = \"{singleFuncName}\", CallingConvention = CallingConvention.Cdecl)]");
                sb.AppendLine($"        public static extern void {jobStruct.Name}_Execute({string.Join(", ", singleParams)});");
                // 2026-10-02（IJob 原生直调）：与 IJobParallelFor(非 MT)/Chunk 系保持一致 ——
                // 声明原生 Adapter getter，供调度器 原生→原生 直调，去掉 Marshal 反向 thunk。
                // 背景（09 §22）：generate 侧（CppJobGenerator）一直为 IJob 产出 adapter+getter，
                //   但绑定侧自 c382dbd 起就漏接线（2eed4ad 同一次重构里只接了 chunk 系与批处理）。
                //   Unity 侧是 IL2CPP（原生 AOT）⇒ 只有走原生直调才是同性质对比。
                var adapterGetterName2 = CppJobGenerator.GetAdapterPtrGetterName(jobStruct);
                sb.AppendLine($"        [DllImport(\"{NativeLibraryName}\", EntryPoint = \"{adapterGetterName2}\", CallingConvention = CallingConvention.Cdecl)]");
                sb.AppendLine($"        private static extern IntPtr Get_{jobStruct.Name}_Execute_AdapterPtr();");
            }
            sb.AppendLine();
        }

        // ---------- Job Schedule 方法 ----------
        private static void GenerateJobScheduleMethod(StringBuilder sb, INamedTypeSymbol jobStruct, Compilation compilation)
        {
            bool isChunk = CppJobGenerator.IsChunkScheduledJob(jobStruct);
            bool isParallelFor = CppJobGenerator.IsRangeScheduledJob(jobStruct);
            bool isFor = CppJobGenerator.IsForJob(jobStruct);
            string jobTypeName = jobStruct.ToDisplayString();

            var attrSymbol = compilation.GetTypeByMetadataName("NativeTranspiler.NativeTranspileAttribute");
            bool useMT = HasUseISPC_MT(jobStruct, attrSymbol);

            var parameters = new List<string>();
            // Use 'ref' for the internal Schedule_XXX method (caller already has a reference)
            parameters.Add($"ref {jobTypeName} job");
            if (isChunk)
            {
                parameters.Add("QueryBuilder query");
            }
            else if (isParallelFor || isFor)
            {
                parameters.Add("int arrayLength");
            // IJobFor 也允许指定 innerBatchCount，保持接口统一。
                parameters.Add("int innerBatchCount = 0");
            }
            parameters.Add("JobHandle dependsOn = default");
            // 2026-10-03（docs/gridsearch/09 §52.5）：**调用点声明的认领几何必须能透到原生**。
            //   此前生成的重载里没有任何几何形参 ⇒ 调用点写成 `job.Schedule(len, 0, h, ClaimPolicy.Spread)`
            //   时 C# 重载解析绑不到原生重载，**静默**落到托管的 `JobExtensions.Schedule<T>`：
            //   键从"模块内 RVA"变成堆地址（批表/[JOBPERKEY] 全部对不上）、`applied` 15→12、
            //   该 pass 慢 2.4×（宿主注释实测 place 2.2→5.3 ms）。
            //   位置与扩展方法保持一致（跟在 dependsOn 之后）且带默认值 ⇒ 既有调用点逐位不变。
            if (isParallelFor) parameters.Add("ClaimPolicy claim = ClaimPolicy.Auto");
            if (isChunk)
            {
                // 多 World 支持：显式指定 World（默认 DefaultWorld）。
                // 数组类 job（IJobFor/IJobParallelFor/Batch）无 World 概念，不发射该参数
                // ——它会让 Jobs-only 项目因 World 类型缺失而编译失败。
                parameters.Add("World world = null");
            }

            sb.AppendLine($"        public static JobHandle Schedule_{jobStruct.Name}({string.Join(", ", parameters)})");
            sb.AppendLine("        {");
            if (!isChunk)
            {
                // Debug 下 NativeArray 带 GC 引用（DisposeSentinel）→ Job struct 非 blittable，裸拷贝布局不可靠；
                // 改为显式逐字段写入（与 C++ Adapter 偏移一致），Debug/Release 均正确。
                var (marshalled, explicitOk, totalSize) = ComputeJobFieldMarshal(jobStruct);
                if (explicitOk)
                {
                    sb.AppendLine($"            int size = {totalSize};");
                    sb.AppendLine("            IntPtr nativePtr = Marshal.AllocHGlobal(size);");
                    sb.AppendLine("            byte* __dst = (byte*)nativePtr;");
                    EmitExplicitFieldWrites(sb, marshalled, "__dst", "job");
                    sb.AppendLine();
                }
                else
                {
                    // 含不支持字段（NativeList 等）：退回裸拷贝（Release 正确；Debug 由显式路径覆盖的场景外）
                    sb.AppendLine($"            int size = sizeof({jobTypeName});");
                    sb.AppendLine("            IntPtr nativePtr = Marshal.AllocHGlobal(size);");
                    sb.AppendLine("            void* originalPtr = Unsafe.AsPointer(ref job);");
                    sb.AppendLine("            Unsafe.CopyBlockUnaligned((void*)nativePtr, originalPtr, (uint)size);");
                    sb.AppendLine();
                }
            }

            if (isChunk)
            {
                sb.AppendLine("            world ??= World.DefaultWorld;");
                sb.AppendLine("            if (world == null) throw new InvalidOperationException(\"No active World found.\");");
                // ─── SendEvent: 内联注册事件元数据 ───
                var evtTypesInline = CppJobGenerator.CollectSendEventTypes(jobStruct, compilation);
                if (evtTypesInline.Count > 0)
                {
                    var evtTypeArgs = string.Join(", ", evtTypesInline.Select(t =>
                        $"typeof({t.ToDisplayString(SymbolDisplayFormat.FullyQualifiedFormat)})"));
                    sb.AppendLine($"            ChunkJobScheduler.RegisterEventBufferMeta(typeof({jobTypeName}), new Type[] {{ {evtTypeArgs} }});");
                }
                // native IJobEntity 走 EntityBatch 路径（Unity 风格），
                // 使用 EntityBatchData 代替 ChunkJobData，消除 requiredComponentArrays 间接层。
                string funcPtrName;
                string extraArgs;
                string scheduleMethod;
                if (CppJobGenerator.IsEntityJob(jobStruct))
                {
            // IJobEntity 统一走 Chunk 级 range 调度。
                    scheduleMethod = "ScheduleChunkRangeRaw";
                    funcPtrName = $"s_{jobStruct.Name}_ChunkRangeFuncPtr";
                    extraArgs = "";
                }
                else
                {
                    var attrSym3 = AttributeHelper.GetAttributeSymbol(compilation);
                    bool isIspc3 = attrSym3 != null && AttributeHelper.GetBackendTarget(jobStruct, attrSym3) == NativeTranspiler.BackendTarget.Ispc;
                    // ISPC 走 ChunkRange；AutoSIMD 和普通 C++ 走 EntityBatch（AutoSIMD adapter 已支持
                    // SimdControlFlowGenerator 真 SIMD，不再需要回退 ChunkRange）。
                    // 有 shared 组件时 EntityBatchAdapter 不存在（shared 值 per-chunk），走 ChunkRange 回退。
                    bool hasShared3 = CppJobGenerator.CollectSharedComponentTypes(jobStruct, compilation).Count > 0;
                    if (isIspc3 || hasShared3)
                    {
                        scheduleMethod = "ScheduleChunkRangeRaw";
                        funcPtrName = $"s_{jobStruct.Name}_ChunkRangeFuncPtr";
                        extraArgs = "";
                    }
                    else
                    {
                        scheduleMethod = "ScheduleChunkEntityBatchRawWithWorkerCapAndRangeSize";
                        funcPtrName = $"s_{jobStruct.Name}_ChunkEntityBatchFuncPtr";
                        extraArgs = $", 0, 0";
                    }
                }
                sb.AppendLine($"            NativeJobHandle nativeHandle = ChunkJobScheduler.{scheduleMethod}(");
                sb.AppendLine($"                ref job, world.EntityManager, query, {funcPtrName}, s_{jobStruct.Name}_RequiredComponentTypeIds{extraArgs}, dependsOn._nativeHandle, world);");
                sb.AppendLine($"            return new JobHandle(nativeHandle);");
            }
            else if (isParallelFor || isFor)
            {
                // 自适应批次大小
                if (useMT)
                {
                    sb.AppendLine($"            int actualBatchSize = innerBatchCount > 0 ? innerBatchCount : arrayLength;");
                }
                else
                {
                    // 0 = 直通原生 ResolveChunkSize（tiles/worker 通用化粒度）；非 0 显式 batch 原样传。
                    sb.AppendLine($"            int actualBatchSize = innerBatchCount;");
                }

                // 几何只在真并行批上有意义（IJobFor 是单线程串行语义）⇒ 只在 isParallelFor 时透传。
                string claimArg = isParallelFor ? ", claim" : "";
                sb.AppendLine($"            NativeJobHandle nativeHandle = NativeJobScheduler.ScheduleParallelForBatchRaw(");
                sb.AppendLine($"                s_{jobStruct.Name}_BatchFuncPtr, nativePtr, s_{jobStruct.Name}_CleanupFuncPtr, arrayLength, actualBatchSize, dependsOn._nativeHandle{claimArg});");
                sb.AppendLine($"            NativeJobScheduler.RegisterScheduledJob(nativeHandle.Handle, \"{jobStruct.Name}\");");
                sb.AppendLine($"            return new JobHandle(nativeHandle);");
            }
            else
            {
                sb.AppendLine($"            NativeJobHandle nativeHandle = NativeJobScheduler.ScheduleRaw(");
                sb.AppendLine($"                s_{jobStruct.Name}_JobFuncPtr, nativePtr, s_{jobStruct.Name}_CleanupFuncPtr, dependsOn._nativeHandle);");
                sb.AppendLine($"            NativeJobScheduler.RegisterScheduledJob(nativeHandle.Handle, \"{jobStruct.Name}\");");
                sb.AppendLine($"            return new JobHandle(nativeHandle);");
            }
            sb.AppendLine("        }");
            sb.AppendLine();

            if (isChunk)
            {
                // 确定后端是否为 ISPC（ScheduleWithWorkerCap 与 ScheduleWithWorkerCapAndRangeSize 共用）
                var attrSymCap = AttributeHelper.GetAttributeSymbol(compilation);
                bool isIspcCap = attrSymCap != null && AttributeHelper.GetBackendTarget(jobStruct, attrSymCap) == NativeTranspiler.BackendTarget.Ispc;

                if (isIspcCap)
                {
                    // ISPC entity jobs use EntityBatch, ISPC chunk jobs use fallback
                    bool isEntityJob = CppJobGenerator.IsEntityJob(jobStruct);
                    // IJobEntity ISPC 使用 chunk 级 range 调度
                    string ispcFuncPtr;
                    string ispcScheduleMethod;
                    if (isEntityJob)
                    {
                        ispcFuncPtr = $"s_{jobStruct.Name}_ChunkRangeFuncPtr";
                        ispcScheduleMethod = "ScheduleChunkRangeRaw";
                    }
                    else
                    {
                        ispcFuncPtr = $"s_{jobStruct.Name}_ChunkFuncPtr";
                        ispcScheduleMethod = "ScheduleChunkRawWithWorkerCap";
                    }

                    sb.AppendLine($"        public static JobHandle ScheduleWithWorkerCap_{jobStruct.Name}(ref {jobTypeName} job, QueryBuilder query, int workerCap, JobHandle dependsOn = default, World world = null)");
                    sb.AppendLine("        {");
                    sb.AppendLine("            world ??= World.DefaultWorld;");
                    sb.AppendLine("            if (world == null) throw new InvalidOperationException(\"No active World found.\");");
                    sb.AppendLine($"            NativeJobHandle nativeHandle = ChunkJobScheduler.{ispcScheduleMethod}(");
                    sb.AppendLine(isEntityJob
                        ? $"                ref job, world.EntityManager, query, {ispcFuncPtr}, s_{jobStruct.Name}_RequiredComponentTypeIds, dependsOn._nativeHandle, world);"
                        : $"                ref job, world.EntityManager, query, {ispcFuncPtr}, s_{jobStruct.Name}_RequiredComponentTypeIds, {(useMT ? "1" : "workerCap")}, dependsOn._nativeHandle, world);");
                    sb.AppendLine($"            return new JobHandle(nativeHandle);");
                    sb.AppendLine("        }");
                    sb.AppendLine();

                    // ScheduleChunkRawWithWorkerCapAndRangeSize for chunk ISPC, EntityBatch for entity ISPC
                    string ispcScheduleMethod2 = isEntityJob ? "ScheduleChunkRangeRaw" : "ScheduleChunkRawWithWorkerCapAndRangeSize";
                    sb.AppendLine($"        public static JobHandle ScheduleWithWorkerCapAndRangeSize_{jobStruct.Name}(ref {jobTypeName} job, QueryBuilder query, int workerCap, int rangeSize, JobHandle dependsOn = default, World world = null)");
                    sb.AppendLine("        {");
                    sb.AppendLine("            world ??= World.DefaultWorld;");
                    sb.AppendLine("            if (world == null) throw new InvalidOperationException(\"No active World found.\");");
                    sb.AppendLine($"            NativeJobHandle nativeHandle = ChunkJobScheduler.{ispcScheduleMethod2}(");
                    sb.AppendLine(isEntityJob
                        ? $"                ref job, world.EntityManager, query, {ispcFuncPtr}, s_{jobStruct.Name}_RequiredComponentTypeIds, dependsOn._nativeHandle, world);"
                        : $"                ref job, world.EntityManager, query, {ispcFuncPtr}, s_{jobStruct.Name}_RequiredComponentTypeIds, {(useMT ? "1, int.MaxValue" : "workerCap, rangeSize")}, dependsOn._nativeHandle, world);");
                    sb.AppendLine($"            return new JobHandle(nativeHandle);");
                    sb.AppendLine("        }");
                    sb.AppendLine();
                }
                else
                {
                    // AutoSIMD/普通 C++：无 shared → EntityBatch；有 shared → ChunkRaw 回退
                    // （与 ISPC chunk 分支一致用 ChunkFuncPtr + ScheduleChunkRawWithWorkerCap*，
                    //   EntityBatch 指针在 shared 时不生成，避免传 IntPtr.Zero）
                    bool hasSharedCap = CppJobGenerator.CollectSharedComponentTypes(jobStruct, compilation).Count > 0;
                    bool isEntityJobCap = CppJobGenerator.IsEntityJob(jobStruct);
                    string capFuncPtr = (isEntityJobCap || hasSharedCap)
                        ? (isEntityJobCap ? $"s_{jobStruct.Name}_ChunkRangeFuncPtr" : $"s_{jobStruct.Name}_ChunkFuncPtr")
                        : $"s_{jobStruct.Name}_ChunkEntityBatchFuncPtr";
                    string capMethod = isEntityJobCap
                        ? "ScheduleEntityRangeRawWithWorkerCapAndRangeSize"
                        : hasSharedCap
                            ? "ScheduleChunkRawWithWorkerCapAndRangeSize"
                            : "ScheduleChunkEntityBatchRawWithWorkerCapAndRangeSize";

                    sb.AppendLine($"        public static JobHandle ScheduleWithWorkerCap_{jobStruct.Name}(ref {jobTypeName} job, QueryBuilder query, int workerCap, JobHandle dependsOn = default, World world = null)");
                    sb.AppendLine("        {");
                    sb.AppendLine("            world ??= World.DefaultWorld;");
                    sb.AppendLine("            if (world == null) throw new InvalidOperationException(\"No active World found.\");");
                    sb.AppendLine($"            NativeJobHandle nativeHandle = ChunkJobScheduler.{capMethod}(");
                    sb.AppendLine($"                ref job, world.EntityManager, query, {capFuncPtr}, s_{jobStruct.Name}_RequiredComponentTypeIds, workerCap, 0, dependsOn._nativeHandle, world);");
                    sb.AppendLine($"            return new JobHandle(nativeHandle);");
                    sb.AppendLine("        }");
                    sb.AppendLine();

                    sb.AppendLine($"        public static JobHandle ScheduleWithWorkerCapAndRangeSize_{jobStruct.Name}(ref {jobTypeName} job, QueryBuilder query, int workerCap, int rangeSize, JobHandle dependsOn = default, World world = null)");
                    sb.AppendLine("        {");
                    sb.AppendLine("            world ??= World.DefaultWorld;");
                    sb.AppendLine("            if (world == null) throw new InvalidOperationException(\"No active World found.\");");
                    sb.AppendLine($"            NativeJobHandle nativeHandle = ChunkJobScheduler.{capMethod}(");
                    sb.AppendLine($"                ref job, world.EntityManager, query, {capFuncPtr}, s_{jobStruct.Name}_RequiredComponentTypeIds, workerCap, rangeSize, dependsOn._nativeHandle, world);");
                    sb.AppendLine($"            return new JobHandle(nativeHandle);");
                    sb.AppendLine("        }");
                    sb.AppendLine();
                }

                sb.AppendLine($"        public static void RunImmediate_{jobStruct.Name}(ref {jobTypeName} job, QueryBuilder query, World world = null)");
                sb.AppendLine("        {");
                // ImmediateNative：主线程同步执行，零 worker 唤醒、无 handle 往返
                sb.AppendLine("            world ??= World.DefaultWorld;");
                sb.AppendLine("            if (world == null) throw new InvalidOperationException(\"No active World found.\");");
                // ─── SendEvent: 内联注册事件元数据 ───
                var runEvtTypes = CppJobGenerator.CollectSendEventTypes(jobStruct, compilation);
                if (runEvtTypes.Count > 0)
                {
                    var evtTypeArgs = string.Join(", ", runEvtTypes.Select(t =>
                        $"typeof({t.ToDisplayString(SymbolDisplayFormat.FullyQualifiedFormat)})"));
                    sb.AppendLine($"            ChunkJobScheduler.RegisterEventBufferMeta(typeof({jobTypeName}), new Type[] {{ {evtTypeArgs} }});");
                }
                if (isIspcCap)
                    sb.AppendLine($"            ChunkJobScheduler.RunChunkRangeImmediate(ref job, world.EntityManager, query, s_{jobStruct.Name}_ChunkRangeFuncPtr, s_{jobStruct.Name}_RequiredComponentTypeIds, world);");
                else if (CppJobGenerator.IsEntityJob(jobStruct))
                    sb.AppendLine($"            ChunkJobScheduler.RunChunkRangeImmediate(ref job, world.EntityManager, query, s_{jobStruct.Name}_ChunkRangeFuncPtr, s_{jobStruct.Name}_RequiredComponentTypeIds, world);");
                else
                {
                    // 有 shared 组件时 EntityBatchAdapter 不存在（shared 值 per-chunk），走 ChunkRange 回退
                    bool hasShared = CppJobGenerator.CollectSharedComponentTypes(jobStruct, compilation).Count > 0;
                    if (hasShared)
                        sb.AppendLine($"            ChunkJobScheduler.RunChunkRangeImmediate(ref job, world.EntityManager, query, s_{jobStruct.Name}_ChunkRangeFuncPtr, s_{jobStruct.Name}_RequiredComponentTypeIds, world);");
                    else
                        sb.AppendLine($"            ChunkJobScheduler.RunChunkImmediate(ref job, world.EntityManager, query, s_{jobStruct.Name}_ChunkEntityBatchFuncPtr, s_{jobStruct.Name}_RequiredComponentTypeIds, world);");
                }
                sb.AppendLine("        }");
                sb.AppendLine();
            }
        }

        private static string BuildRequiredComponentTypeIdsInitializer(IEnumerable<INamedTypeSymbol> requiredTypes)
        {
            var ids = string.Join(", ", requiredTypes.Select(t => $"ComponentTypeManager.GetComponentType(typeof({t.ToDisplayString(SymbolDisplayFormat.FullyQualifiedFormat)})).Id"));
            return string.IsNullOrWhiteSpace(ids) ? "Array.Empty<int>()" : $"new int[] {{ {ids} }}";
        }

        // ---------- 辅助：构建参数列表 ----------
        private static List<string> BuildMethodDllImportParams(IMethodSymbol method)
        {
            var parameters = new List<string>();
            foreach (var param in method.Parameters)
            {
                if (NativeTranspiler.IsEntJoyNativeContainerType(param.Type))
                {
                    if (NativeTranspiler.IsEntJoyContainerNamed(param.Type, Config.NativeList))
                    {
                        var elementType = ((INamedTypeSymbol)param.Type).TypeArguments[0];
                        var csElementType = elementType.ToDisplayString(SymbolDisplayFormat.FullyQualifiedFormat);
                        parameters.Add($"EntJoy.Collections.UnsafeList<{csElementType}>* {param.Name}_listData");
                    }
                    else
                    {
                        var elementType = ((INamedTypeSymbol)param.Type).TypeArguments[0];
                        var csElementType = elementType.ToDisplayString(SymbolDisplayFormat.FullyQualifiedFormat);
                        parameters.Add($"{csElementType}* {param.Name}_ptr, int {param.Name}_length");
                    }
                }
                else if (param.Type is IPointerTypeSymbol)
                {
                    var cppType = NativeTranspiler.MapCSharpTypeToCpp(param.Type);  // 杩斿洖 "int*"
                    parameters.Add($"{cppType} {param.Name}_ptr");
                }
                else if (param.RefKind == RefKind.Ref || param.RefKind == RefKind.Out)
                {
                    // ref/out：指针 ABI
                    var csType = param.Type.ToDisplayString(SymbolDisplayFormat.FullyQualifiedFormat);
                    parameters.Add($"{csType}* {param.Name}_ptr");
                }
                else
                {
                    // 按值参数：与 C++ 侧一致按值传递（C# 值参数语义即副本）
                    var csType = param.Type.ToDisplayString(SymbolDisplayFormat.FullyQualifiedFormat);
                    parameters.Add($"{csType} {param.Name}");
                }
            }
            return parameters;
        }

        private static List<string> BuildMethodCallArgs(IMethodSymbol method)
        {
            var args = new List<string>();
            foreach (var param in method.Parameters)
            {
                if (NativeTranspiler.IsEntJoyNativeContainerType(param.Type))
                {
                    if (NativeTranspiler.IsEntJoyContainerNamed(param.Type, Config.NativeList))
                    {
                        args.Add($"{param.Name}.GetListData()");
                    }
                    else
                    {
                        var elementType = ((INamedTypeSymbol)param.Type).TypeArguments[0];
                        var csElementType = elementType.ToDisplayString(SymbolDisplayFormat.FullyQualifiedFormat);
                        args.Add($"({csElementType}*){param.Name}.GetUnsafePtr(), {param.Name}.Length");
                    }
                }
                else if (param.Type is IPointerTypeSymbol)
                {
                    args.Add(param.Name);
                }
                else if (param.RefKind == RefKind.Ref || param.RefKind == RefKind.Out)
                {
                    var csType = param.Type.ToDisplayString(SymbolDisplayFormat.FullyQualifiedFormat);
                    args.Add($"({csType}*)Unsafe.AsPointer(ref {param.Name})");
                }
                else
                {
                    // 按值参数：与 C++ 侧一致直接传值
                    args.Add(param.Name);
                }
            }
            return args;
        }

        private static List<string> BuildJobDllImportParams(INamedTypeSymbol jobStruct)
        {
            var parameters = new List<string>();
            var executeMethod = jobStruct.GetMembers().OfType<IMethodSymbol>().First(m => m.Name == Config.Execute);
            if (executeMethod.Parameters.Length == 1 && executeMethod.Parameters[0].Type.SpecialType == SpecialType.System_Int32)
                parameters.Add($"int {executeMethod.Parameters[0].Name}");

            AppendFieldDllImportParams(jobStruct, parameters);
            return parameters;
        }

        private static List<string> BuildBatchJobDllImportParams(INamedTypeSymbol jobStruct)
        {
            var parameters = new List<string> { "int __startIndex", "int __count" };
            AppendFieldDllImportParams(jobStruct, parameters);
            return parameters;
        }

        private static void AppendFieldDllImportParams(INamedTypeSymbol jobStruct, List<string> parameters)
        {
            foreach (var field in jobStruct.GetMembers().OfType<IFieldSymbol>().Where(f => !f.IsStatic))
            {
                if (NativeTranspiler.IsEntJoyNativeContainerType(field.Type))
                {
                    if (NativeTranspiler.IsEntJoyContainerNamed(field.Type, Config.NativeList))
                    {
                        var elementType = ((INamedTypeSymbol)field.Type).TypeArguments[0];
                        var csElementType = elementType.ToDisplayString(SymbolDisplayFormat.FullyQualifiedFormat);
                        parameters.Add($"EntJoy.Collections.UnsafeList<{csElementType}>* {field.Name}_listData");
                    }
                    else
                    {
                        var elementType = ((INamedTypeSymbol)field.Type).TypeArguments[0];
                        var csElementType = elementType.ToDisplayString(SymbolDisplayFormat.FullyQualifiedFormat);
                        parameters.Add($"{csElementType}* {field.Name}_ptr, int {field.Name}_length");
                    }
                }
                else if (field.Type is IPointerTypeSymbol pointerField)
                {
                    // P0-5c：此处生成的是**托管 trampoline 的 C# 方法签名**，不能用 C++ 类型名 ——
                    // `MapCSharpTypeToCpp` 对用户结构体会给出 `EntJoy::ECS::X*`，C# 侧解析为"别名"⇒ CS0432
                    //（基元指针 `int*`/`void*` 两语言同名，所以此前没有暴露）。
                    // 正确做法：取**被指类型的 C# 限定名**再加 `*`。
                    var csPointeeType = pointerField.PointedAtType.ToDisplayString(SymbolDisplayFormat.FullyQualifiedFormat);
                    parameters.Add($"{csPointeeType}* {field.Name}_ptr");
                }
                else
                {
                    var csType = field.Type.ToDisplayString(SymbolDisplayFormat.FullyQualifiedFormat);
                    parameters.Add($"{csType}* {field.Name}_ptr");
                }
            }
        }

        private static string BuildBatchCallArgs(INamedTypeSymbol jobStruct, string jobPtrPrefix)
        {
            var args = new List<string>();
            foreach (var field in jobStruct.GetMembers().OfType<IFieldSymbol>().Where(f => !f.IsStatic))
            {
                if (NativeTranspiler.IsEntJoyNativeContainerType(field.Type))
                {
                    if (NativeTranspiler.IsEntJoyContainerNamed(field.Type, Config.NativeList))
                        args.Add($"{jobPtrPrefix}->{field.Name}.GetListData()");
                    else
                    {
                        var elementType = ((INamedTypeSymbol)field.Type).TypeArguments[0];
                        var csElementType = elementType.ToDisplayString(SymbolDisplayFormat.FullyQualifiedFormat);
                        args.Add($"({csElementType}*){jobPtrPrefix}->{field.Name}.GetUnsafePtr(), {jobPtrPrefix}->{field.Name}.Length");
                    }
                }
                else if (field.Type is IPointerTypeSymbol)
                {
                    args.Add($"{jobPtrPrefix}->{field.Name}");
                }
                else
                {
                    args.Add($"&{jobPtrPrefix}->{field.Name}");
                }
            }
            return string.Join(", ", args);
        }

        // ---------- 显式逐字段 marshalling（Debug sentinel 布局修复共用） ----------

        /// <summary>
        /// 计算 Job 结构体所有实例字段在 C++ context 布局下的偏移（与 CppJobGenerator.CalculateFieldOffset 同源），
        /// 并把字段递归展开成"叶子"（含 GC 引用的非 blittable struct 也递归：值子字段显式写、引用槽零填充）。
        /// 叶子：type==null 表示引用槽（8B 零填充，C++ 侧为 void*，Execute 不应访问）。
        /// 返回 (叶子列表, 是否全部支持, 总大小)。
        /// </summary>
        private static (List<(string accessor, int offset, ITypeSymbol type)> leaves, bool explicitOk, int totalSize) ComputeJobFieldMarshal(INamedTypeSymbol jobStruct)
        {
            var leaves = new List<(string accessor, int offset, ITypeSymbol type)>();
            int running = 0;
            foreach (var field in jobStruct.GetMembers().OfType<IFieldSymbol>().Where(f => !f.IsStatic))
            {
                int off = CppJobGenerator.CalculateFieldOffset(field, ref running);
                if (field.Type.IsReferenceType)
                {
                    leaves.Add(("", off, null));   // 顶层引用字段 -> void* 槽零填充
                    continue;
                }
                if (!CollectLeaves(leaves, field.Name, field.Type, off)) return (leaves, false, running);
            }
            return (leaves, true, running);
        }

        /// <summary>递归展开字段为叶子：容器/指针/标量/枚举/blittable struct 为单叶子；非 blittable struct 递归（引用子字段 → 零填充槽）。</summary>
        private static bool CollectLeaves(List<(string accessor, int offset, ITypeSymbol type)> leaves,
            string accessor, ITypeSymbol type, int offset)
        {
            if (type is IPointerTypeSymbol) { leaves.Add((accessor, offset, type)); return true; }
            if (NativeTranspiler.IsEntJoyNativeContainerType(type)) { leaves.Add((accessor, offset, type)); return true; }
            if (type.TypeKind == TypeKind.Enum) { leaves.Add((accessor, offset, type)); return true; }
            var st = type.SpecialType;
            if (st is SpecialType.System_Single or SpecialType.System_Int32
                or SpecialType.System_UInt32 or SpecialType.System_Boolean)
            { leaves.Add((accessor, offset, type)); return true; }
            if (type is INamedTypeSymbol nts && nts.IsValueType)
            {
                if (IsBlittableStruct(nts)) { leaves.Add((accessor, offset, type)); return true; }
                int running = 0;
                foreach (var f in nts.GetMembers().OfType<IFieldSymbol>().Where(f => !f.IsStatic))
                {
                    int subOff = CppJobGenerator.CalculateFieldOffset(f, ref running);
                    if (f.Type.IsReferenceType)
                    {
                        leaves.Add(("", offset + subOff, null));   // 引用槽：8B 零填充（C++ 为 void*，Execute 不应访问）
                        continue;
                    }
                    string child = accessor.Length == 0 ? f.Name : accessor + "." + f.Name;
                    if (!CollectLeaves(leaves, child, f.Type, offset + subOff)) return false;
                }
                return true;
            }
            return false;
        }

        /// <summary>struct 是否 blittable（递归：指针/标量/枚举/仅含这些的嵌套 struct）——Debug sentinel 带 GC 引用，非 blittable</summary>
        private static bool IsBlittableStruct(INamedTypeSymbol structType)
        {
            foreach (var member in structType.GetMembers().OfType<IFieldSymbol>().Where(f => !f.IsStatic))
            {
                if (member.Type is IPointerTypeSymbol) continue;
                if (member.Type.TypeKind == TypeKind.Enum) continue;
                var st = member.Type.SpecialType;
                if (st is SpecialType.System_Single or SpecialType.System_Int32
                    or SpecialType.System_UInt32 or SpecialType.System_Boolean
                    or SpecialType.System_Int64 or SpecialType.System_UInt64
                    or SpecialType.System_Double or SpecialType.System_Byte
                    or SpecialType.System_SByte or SpecialType.System_Int16
                    or SpecialType.System_UInt16 or SpecialType.System_Char) continue;
                if (member.Type is INamedTypeSymbol nested && nested.IsValueType)
                {
                    if (IsBlittableStruct(nested)) continue;
                    return false;
                }
                return false;   // 引用类型/其他 -> 非 blittable
            }
            return true;
        }

        /// <summary>生成逐字段显式写入语句：{srcExpr}.{accessor} 写到 {dstExpr} + 偏移（不依赖 struct 运行时布局）。</summary>
        private static void EmitExplicitFieldWrites(StringBuilder sb,
            List<(string accessor, int offset, ITypeSymbol type)> leaves, string dstExpr, string srcExpr)
        {
            foreach (var (accessor, off, type) in leaves)
            {
                if (type == null)
                {
                    // 引用槽（object/string 等）以 8B 零填充（C++ 侧为 void*，Execute 不应访问）。
                    sb.AppendLine($"            *((long*)({dstExpr} + {off})) = 0;");
                    continue;
                }
                if (NativeTranspiler.IsEntJoyNativeContainerType(type))
                {
                    if (NativeTranspiler.IsEntJoyContainerNamed(type, Config.NativeArray))
                    {
                        // NativeArray：显式写 buffer@off / length@off+8（与 Adapter 读取一致）
                        sb.AppendLine($"            *((void**)({dstExpr} + {off})) = (void*){srcExpr}.{accessor}.GetUnsafePtr();");
                        sb.AppendLine($"            *((int*)({dstExpr} + {off + 8})) = {srcExpr}.{accessor}.Length;");
                    }
                    else if (NativeTranspiler.IsEntJoyContainerNamed(type, Config.NativeList))
                    {
            // NativeList：_listData（UnsafeList*，堆上稳定）在偏移 0，C++ 解引用读取。
                        sb.AppendLine($"            *((void**)({dstExpr} + {off})) = (void*){srcExpr}.{accessor}.GetListData();");
                    }
                    else // UnsafeList（值字段）：C++ 侧按 ptr+length 读取（与 NativeArray 一致），Capacity/Allocator 不跨边界
                    {
                        sb.AppendLine($"            *((void**)({dstExpr} + {off})) = (void*){srcExpr}.{accessor}.Ptr;");
                        sb.AppendLine($"            *((int*)({dstExpr} + {off + 8})) = {srcExpr}.{accessor}.Length;");
                    }
                }
                else if (type is IPointerTypeSymbol)
                {
                    // 指针字段：写指针值（同一进程地址空间，C++ 直接解引用；指向内存须非托管/固定且在 Job 期间存活）。
                    sb.AppendLine($"            *((void**)({dstExpr} + {off})) = (void*){srcExpr}.{accessor};");
                }
                else if (type.TypeKind == TypeKind.Enum && type is INamedTypeSymbol enumSym)
                {
                    // 按底层类型写满对应字节数（byte/short/int/long…），与 CppJobAbi 的枚举 size=underlying 一致；
                    // 否则 : long 枚举只写 4 字节，C++ 侧按 8 字节解引用读到垃圾高半部。
                    string underlying = enumSym.EnumUnderlyingType.SpecialType switch
                    {
                        SpecialType.System_Byte => "byte",
                        SpecialType.System_SByte => "sbyte",
                        SpecialType.System_Int16 => "short",
                        SpecialType.System_UInt16 => "ushort",
                        SpecialType.System_Int32 => "int",
                        SpecialType.System_UInt32 => "uint",
                        SpecialType.System_Int64 => "long",
                        SpecialType.System_UInt64 => "ulong",
                        _ => "int"
                    };
                    sb.AppendLine($"            *(({underlying}*)({dstExpr} + {off})) = ({underlying}){srcExpr}.{accessor};");
                }
                else if (type.SpecialType == SpecialType.System_Single)
                {
                    sb.AppendLine($"            *((float*)({dstExpr} + {off})) = {srcExpr}.{accessor};");
                }
                else if (type.SpecialType == SpecialType.System_Int32)
                {
                    sb.AppendLine($"            *((int*)({dstExpr} + {off})) = {srcExpr}.{accessor};");
                }
                else if (type.SpecialType == SpecialType.System_UInt32)
                {
                    sb.AppendLine($"            *((uint*)({dstExpr} + {off})) = {srcExpr}.{accessor};");
                }
                else if (type.SpecialType == SpecialType.System_Boolean)
                {
                    sb.AppendLine($"            *((byte*)({dstExpr} + {off})) = (byte)({srcExpr}.{accessor} ? 1 : 0);");
                }
                else
                {
                    // blittable 值 struct（float2/用户纯值结构等）：Unsafe.Write 直写（blittable 且 Sequential 生效）。
                    sb.AppendLine($"            System.Runtime.CompilerServices.Unsafe.Write((void*)({dstExpr} + {off}), {srcExpr}.{accessor});");
                }
            }
        }

        /// <summary>
        /// 生成 Job 字段显式写入器（chunk 路径 CreateChunkContextBlock 用）。
        /// 以类型化 ref 读取逻辑字段值（布局无关），显式写到 C++ context 偏移。
        /// </summary>
        private static void GenerateJobFieldWriterMethod(StringBuilder sb, INamedTypeSymbol jobStruct)
        {
            var (marshalled, explicitOk, _) = ComputeJobFieldMarshal(jobStruct);
            if (!explicitOk) return;   // 含不支持字段：不注册，chunk 路径回退裸拷贝。
            string jobTypeName = jobStruct.ToDisplayString();
            sb.AppendLine($"        internal static void WriteJobFields_{jobStruct.Name}(byte* dst, ref {jobTypeName} job)");
            sb.AppendLine("        {");
            EmitExplicitFieldWrites(sb, marshalled, "dst", "job");
            sb.AppendLine("        }");
            sb.AppendLine();
        }

        private static void GenerateJobExtensionMethod(StringBuilder sb, INamedTypeSymbol jobStruct)
        {
            bool isChunk = CppJobGenerator.IsChunkScheduledJob(jobStruct);
            bool isParallelFor = CppJobGenerator.IsRangeScheduledJob(jobStruct);
            bool isFor = CppJobGenerator.IsForJob(jobStruct);
            string jobTypeName = jobStruct.ToDisplayString();

            if (isChunk)
            {
                sb.AppendLine($"    public static JobHandle Schedule(this {jobTypeName} job, QueryBuilder query, JobHandle dependsOn = default)");
                sb.AppendLine("    {");
                sb.AppendLine($"        return NativeTranspiler.Bindings.NativeExports.Schedule_{jobStruct.Name}(ref job, query, dependsOn);");
                sb.AppendLine("    }");
                sb.AppendLine();
                sb.AppendLine($"    public static JobHandle ScheduleWithWorkerCap(this {jobTypeName} job, QueryBuilder query, int workerCap, JobHandle dependsOn = default)");
                sb.AppendLine("    {");
                sb.AppendLine($"        return NativeTranspiler.Bindings.NativeExports.ScheduleWithWorkerCap_{jobStruct.Name}(ref job, query, workerCap, dependsOn);");
                sb.AppendLine("    }");
                sb.AppendLine();
                sb.AppendLine($"    public static JobHandle ScheduleWithWorkerCapAndRangeSize(this {jobTypeName} job, QueryBuilder query, int workerCap, int rangeSize, JobHandle dependsOn = default)");
                sb.AppendLine("    {");
                sb.AppendLine($"        return NativeTranspiler.Bindings.NativeExports.ScheduleWithWorkerCapAndRangeSize_{jobStruct.Name}(ref job, query, workerCap, rangeSize, dependsOn);");
                sb.AppendLine("    }");
                sb.AppendLine();
                sb.AppendLine($"    public static void RunImmediate(this {jobTypeName} job, QueryBuilder query)");
                sb.AppendLine("    {");
                sb.AppendLine($"        NativeTranspiler.Bindings.NativeExports.RunImmediate_{jobStruct.Name}(ref job, query);");
                sb.AppendLine("    }");
                sb.AppendLine();
            }
            else if (isParallelFor || isFor)
            {
                // ParallelFor/For: keep optional dependsOn (existing generic Schedule<T> has arrayLength params, no collision)
                var parameters = new List<string>
                {
                    $"this {jobTypeName} job",
                    "int arrayLength",
                    "int innerBatchCount = 0",
                    "JobHandle dependsOn = default"
                };
                // 2026-10-03（09 §52.5）：调用点透传认领几何（仅在真并行批上；IJobFor 是单线程串行语义）。
                // 末尾 + 默认值 ⇒ 既有调用点不变，且**不会**与托管 `JobExtensions.Schedule<T>` 产生歧义
                // （具体扩展方法优先于泛型）。
                string claimParam = isParallelFor ? ", ClaimPolicy claim = ClaimPolicy.Auto" : "";
                string claimArgE = isParallelFor ? ", claim" : "";
                sb.AppendLine($"    public static JobHandle Schedule({string.Join(", ", parameters)}{claimParam})");
                sb.AppendLine("    {");
                sb.AppendLine($"        return NativeTranspiler.Bindings.NativeExports.Schedule_{jobStruct.Name}(ref job, arrayLength, innerBatchCount, dependsOn{claimArgE});");
                sb.AppendLine("    }");
                sb.AppendLine();
            }
            else
            {
                // IJob: generate two overloads (no-arg and dependsOn) to beat existing Schedule<T>(this T job)
                sb.AppendLine($"    public static JobHandle Schedule(this {jobTypeName} job)");
                sb.AppendLine("    {");
                sb.AppendLine($"        return NativeTranspiler.Bindings.NativeExports.Schedule_{jobStruct.Name}(ref job, default);");
                sb.AppendLine("    }");
                sb.AppendLine();
                sb.AppendLine($"    public static JobHandle Schedule(this {jobTypeName} job, JobHandle dependsOn)");
                sb.AppendLine("    {");
                sb.AppendLine($"        return NativeTranspiler.Bindings.NativeExports.Schedule_{jobStruct.Name}(ref job, dependsOn);");
                sb.AppendLine("    }");
                sb.AppendLine();
            }
        }

        private static void GenerateJobRunMethod(StringBuilder sb, INamedTypeSymbol jobStruct, Compilation compilation)
        {
            bool isChunk = CppJobGenerator.IsChunkScheduledJob(jobStruct);
            bool isParallelFor = CppJobGenerator.IsRangeScheduledJob(jobStruct);
            bool isFor = CppJobGenerator.IsForJob(jobStruct);
            string jobTypeName = jobStruct.ToDisplayString();

            var parameters = new List<string>();
            // Must match existing JobExtensions signature (this T job) to take precedence in overload resolution
            parameters.Add($"this {jobTypeName} job");
            if (isChunk)
            {
                parameters.Add("QueryBuilder query");
            }
            else if (isParallelFor || isFor)
            {
                parameters.Add("int arrayLength");
            }

            sb.AppendLine($"    public static void Run({string.Join(", ", parameters)})");
            sb.AppendLine("    {");
            if (isChunk)
            {
                // ImmediateNative：主线程同步执行，零 worker 唤醒、无 handle 往返
                sb.AppendLine($"        NativeTranspiler.Bindings.NativeExports.RunImmediate_{jobStruct.Name}(ref job, query);");
            }
            else if (isParallelFor || isFor)
            {
                sb.AppendLine($"        int startIndex = 0;");
                sb.AppendLine($"        int count = arrayLength;");
                sb.AppendLine($"        unsafe");
                sb.AppendLine($"        {{");
                sb.AppendLine($"            {jobTypeName}* jobPtr = &job;");
                sb.AppendLine($"            {{");

                var executeMethod = jobStruct.GetMembers().OfType<IMethodSymbol>().First(m => m.Name == Config.Execute);
                var methodSyntax = SymbolHelper.GetMethodSyntax(executeMethod);
                bool hasMultiVersion = false;
                string boolFieldName = null;
                if (methodSyntax != null)
                {
                    var semanticModel = compilation.GetSemanticModel(methodSyntax.SyntaxTree);
                    var conditionalFields = NativeTranspileValidator.GetConditionalReadOnlyFields(jobStruct, semanticModel);
                    var boolField = conditionalFields.FirstOrDefault(f => f.Type.SpecialType == SpecialType.System_Boolean);
                    if (boolField != null)
                    {
                        hasMultiVersion = true;
                        boolFieldName = boolField.Name;
                    }
                }

                string batchArgs2 = BuildBatchCallArgs(jobStruct, "jobPtr");
                string batchArgsWithComma2 = string.IsNullOrEmpty(batchArgs2) ? "" : ", " + batchArgs2;
                if (hasMultiVersion)
                {
                    sb.AppendLine($"                if (jobPtr->{boolFieldName})");
                    sb.AppendLine($"                    NativeTranspiler.Bindings.NativeExports.{jobStruct.Name}_Execute_Batch_true(startIndex, count{batchArgsWithComma2});");
                    sb.AppendLine($"                else");
                    sb.AppendLine($"                    NativeTranspiler.Bindings.NativeExports.{jobStruct.Name}_Execute_Batch_false(startIndex, count{batchArgsWithComma2});");
                }
                else
                {
                    sb.AppendLine($"                NativeTranspiler.Bindings.NativeExports.{jobStruct.Name}_Execute_Batch(startIndex, count{batchArgsWithComma2});");
                }
                sb.AppendLine($"            }}");
                sb.AppendLine($"        }}");
            }
            else
            {
                sb.AppendLine($"        unsafe");
                sb.AppendLine($"        {{");
                sb.AppendLine($"            {jobTypeName}* jobPtr = &job;");
                sb.AppendLine($"            {{");
                var args = BuildJobExecuteArgsForFixed(jobStruct);
                sb.AppendLine($"                NativeTranspiler.Bindings.NativeExports.{jobStruct.Name}_Execute({string.Join(", ", args)});");
                sb.AppendLine($"            }}");
                sb.AppendLine($"        }}");
            }
            sb.AppendLine("    }");
            sb.AppendLine();
        }

        private static List<string> BuildJobExecuteArgsForFixed(INamedTypeSymbol jobStruct)
        {
            var args = new List<string>();
            foreach (var field in jobStruct.GetMembers().OfType<IFieldSymbol>().Where(f => !f.IsStatic))
            {
                if (NativeTranspiler.IsEntJoyNativeContainerType(field.Type))
                {
                    if (NativeTranspiler.IsEntJoyContainerNamed(field.Type, Config.NativeList))
                    {
                        args.Add($"jobPtr->{field.Name}.GetListData()");
                    }
                    else
                    {
                        var elementType = ((INamedTypeSymbol)field.Type).TypeArguments[0];
                        var csElementType = elementType.ToDisplayString(SymbolDisplayFormat.FullyQualifiedFormat);
                        args.Add($"({csElementType}*)jobPtr->{field.Name}.GetUnsafePtr(), jobPtr->{field.Name}.Length");
                    }
                }
                else
                {
                    if (field.Type is IPointerTypeSymbol)
                        args.Add($"jobPtr->{field.Name}");
                    else
                        args.Add($"&jobPtr->{field.Name}");
                }
            }
            return args;
        }

        private static string GetCSharpParameterType(IParameterSymbol param)
        {
            var typeName = param.Type.ToDisplayString(SymbolDisplayFormat.FullyQualifiedFormat);
            return param.RefKind switch
            {
                RefKind.Ref => "ref " + typeName,
                RefKind.In => "in " + typeName,
                RefKind.Out => "out " + typeName,
                _ => typeName
            };
        }

        private static string GenerateCleanupFactoryMethod()
        {
            return @"
        private static CleanupFuncDelegate CreateCleanup<T>(int size) where T : struct
        {
            return context =>
            {
                IntPtr native = (IntPtr)context;
                Marshal.FreeHGlobal(native);
            };
        }";
        }
    }
}
