using EntJoy.Collections;
using EntJoy.JobSystem;

namespace EntJoySample.AutoSIMDTest
{
    // =====================================================================
    // Case8: EdgeCase 鈥?special floats + adversarial boundary semantics
    // Each Case: C# baseline + AutoSIMD variant, output must match element-wise.
    // Coverage: 卤Inf / NaN / 卤0 / subnormal / FLT_MAX / INT_MIN-MAX overflow /
    //           multi-level && || mixed continue / nested loop return / non-constant loop bound.
    // Input generated by tools/AutoSIMDEdgeCases (special-value injection + random fuzz).
    // =====================================================================

    // ── EC1: Special float arithmetic + MathF (sqrt/sin/log for Inf/NaN/0/negative) ──
    public struct EdgeCase1_CSharp_For : IJobFor
    {
        public NativeArray<float> A, R;
        public void Execute(int i)
        {
            float a = A[i];
            float r;
            if (a > 10f)
            {
                r = a * 2f + MathF.Sqrt(a);
                if (a > 100f) r += MathF.Sin(a);
                else if (a > 50f) r -= MathF.Cos(a);
                else r += MathF.Log(a);
            }
            else if (a > -1f)
            {
                r = a * a - 3f;
                if (a != 0f) r = r / a;
                else r = 1234.5f;
            }
            else
            {
                r = -a * 0.5f;
                r += MathF.Log(-a);
            }
            R[i] = r;
        }
    }

    [NativeTranspiler.NativeTranspile(AutoSIMD = NativeTranspiler.AutoSIMD.Enabled)]
    public struct EdgeCase1_SIMD_For : IJobFor
    {
        public NativeArray<float> A, R;
        public void Execute(int i)
        {
            float a = A[i];
            float r;
            if (a > 10f)
            {
                r = a * 2f + MathF.Sqrt(a);
                if (a > 100f) r += MathF.Sin(a);
                else if (a > 50f) r -= MathF.Cos(a);
                else r += MathF.Log(a);
            }
            else if (a > -1f)
            {
                r = a * a - 3f;
                if (a != 0f) r = r / a;
                else r = 1234.5f;
            }
            else
            {
                r = -a * 0.5f;
                r += MathF.Log(-a);
            }
            R[i] = r;
        }
    }

    // ── EC2: Sign-zero + NaN compare semantics (NaN comparisons are always false 鈫?else branch) ──
    public struct EdgeCase2_CSharp_For : IJobFor
    {
        public NativeArray<float> A, R;
        public void Execute(int i)
        {
            float f = A[i];
            float r;
            if (f > 0f) r = f + 1f;
            else if (f < 0f) r = f - 1f;
            else if (f == 0f) r = 0.25f;
            else r = -999f;
            R[i] = r;
        }
    }

    [NativeTranspiler.NativeTranspile(AutoSIMD = NativeTranspiler.AutoSIMD.Enabled)]
    public struct EdgeCase2_SIMD_For : IJobFor
    {
        public NativeArray<float> A, R;
        public void Execute(int i)
        {
            float f = A[i];
            float r;
            if (f > 0f) r = f + 1f;
            else if (f < 0f) r = f - 1f;
            else if (f == 0f) r = 0.25f;
            else r = -999f;
            R[i] = r;
        }
    }

    // ── EC3: int overflow boundary (INT_MIN/MAX arithmetic + unsigned compare) ──
    public struct EdgeCase3_CSharp_For : IJobFor
    {
        public NativeArray<int> A, B, R;
        public void Execute(int i)
        {
            int x = A[i];
            int y = B[i];
            if ((uint)x > (uint)y)
            {
                int sum = unchecked(x + y);
                R[i] = (sum ^ y) + (x * 3);
            }
            else if (x == int.MinValue)
            {
                R[i] = unchecked(-x);
            }
            else if (y == -1 && x == int.MaxValue)
            {
                R[i] = x * y;
            }
            else
            {
                R[i] = (x >> 1) ^ (y << 2) & ~3;
            }
        }
    }

    [NativeTranspiler.NativeTranspile(AutoSIMD = NativeTranspiler.AutoSIMD.Enabled)]
    public struct EdgeCase3_SIMD_For : IJobFor
    {
        public NativeArray<int> A, B, R;
        public void Execute(int i)
        {
            int x = A[i];
            int y = B[i];
            if ((uint)x > (uint)y)
            {
                int sum = unchecked(x + y);
                R[i] = (sum ^ y) + (x * 3);
            }
            else if (x == int.MinValue)
            {
                R[i] = unchecked(-x);
            }
            else if (y == -1 && x == int.MaxValue)
            {
                R[i] = x * y;
            }
            else
            {
                R[i] = (x >> 1) ^ (y << 2) & ~3;
            }
        }
    }

    // ── EC4: Multi-level && / || mixed continue (De Morgan hybrid) ──
    public struct EdgeCase4_CSharp_For : IJobFor
    {
        public NativeArray<float> A, R;
        public void Execute(int i)
        {
            int cx = i % 20, cy = (i / 20) % 20;
            float sum = 0f;
            for (int dx = -2; dx <= 2; dx++)
            {
                int nx = cx + dx;
                if ((nx < 0 || nx >= 20) || (dx == 0 && i % 3 == 0)) continue;
                for (int dy = -2; dy <= 2; dy++)
                {
                    if ((dx == 0 && dy == 0) || (dx + dy == 0 && (i & 1) == 1)) continue;
                    int ny = cy + dy;
                    if ((uint)ny >= 20u || dx * dy > 2) continue;
                    float v = A[ny * 20 + nx];
                    if (v > 5f && v < 50f) sum += v;
                    else if (v < -5f || v > 100f) sum -= v * 0.25f;
                    else sum += 1f;
                }
            }
            R[i] = sum;
        }
    }

    [NativeTranspiler.NativeTranspile(AutoSIMD = NativeTranspiler.AutoSIMD.Enabled)]
    public struct EdgeCase4_SIMD_For : IJobFor
    {
        public NativeArray<float> A, R;
        public void Execute(int i)
        {
            int cx = i % 20, cy = (i / 20) % 20;
            float sum = 0f;
            for (int dx = -2; dx <= 2; dx++)
            {
                int nx = cx + dx;
                if ((nx < 0 || nx >= 20) || (dx == 0 && i % 3 == 0)) continue;
                for (int dy = -2; dy <= 2; dy++)
                {
                    if ((dx == 0 && dy == 0) || (dx + dy == 0 && (i & 1) == 1)) continue;
                    int ny = cy + dy;
                    if ((uint)ny >= 20u || dx * dy > 2) continue;
                    float v = A[ny * 20 + nx];
                    if (v > 5f && v < 50f) sum += v;
                    else if (v < -5f || v > 100f) sum -= v * 0.25f;
                    else sum += 1f;
                }
            }
            R[i] = sum;
        }
    }

    // ── EC5: Nested loop return (early exit + computed result) ──
    public struct EdgeCase5_CSharp_For : IJobFor
    {
        public NativeArray<float> A, R;
        public void Execute(int i)
        {
            for (int j = 0; j < 8; j++)
            {
                for (int k = j; k < 8; k++)
                {
                    float v = A[i * 64 + j * 8 + k];
                    if (v > 1000f) { R[i] = j * 10f + k * 1.5f; return; }
                    if (v < -1000f) { R[i] = -j - k; return; }
                }
            }
            R[i] = 777f;
        }
    }

    [NativeTranspiler.NativeTranspile(AutoSIMD = NativeTranspiler.AutoSIMD.Enabled)]
    public struct EdgeCase5_SIMD_For : IJobFor
    {
        public NativeArray<float> A, R;
        public void Execute(int i)
        {
            for (int j = 0; j < 8; j++)
            {
                for (int k = j; k < 8; k++)
                {
                    float v = A[i * 64 + j * 8 + k];
                    if (v > 1000f) { R[i] = j * 10f + k * 1.5f; return; }
                    if (v < -1000f) { R[i] = -j - k; return; }
                }
            }
            R[i] = 777f;
        }
    }

    // ── EC6: Non-constant loop bound + branch (bound depends on runtime data; pure float accumulation) ──
    public struct EdgeCase6_CSharp_For : IJobFor
    {
        public NativeArray<float> A, R;
        public NativeArray<int> Counts;
        public void Execute(int i)
        {
            int n = Counts[i] & 31;
            float acc = 0f;
            for (int j = 0; j < n; j++)
            {
                float v = A[i * 32 + j];
                if (v > 0f) acc += v;
                else if (v < -0.5f) acc -= v;
                else acc += 0.01f;
            }
            if (acc > 3f) R[i] = acc * 2f;
            else R[i] = acc + 0.25f;
        }
    }

    [NativeTranspiler.NativeTranspile(AutoSIMD = NativeTranspiler.AutoSIMD.Enabled)]
    public struct EdgeCase6_SIMD_For : IJobFor
    {
        public NativeArray<float> A, R;
        public NativeArray<int> Counts;
        public void Execute(int i)
        {
            int n = Counts[i] & 31;
            float acc = 0f;
            for (int j = 0; j < n; j++)
            {
                float v = A[i * 32 + j];
                if (v > 0f) acc += v;
                else if (v < -0.5f) acc -= v;
                else acc += 0.01f;
            }
            if (acc > 3f) R[i] = acc * 2f;
            else R[i] = acc + 0.25f;
        }
    }

    // ── EC7: Accumulation loop (for semantics, equivalent to while; while path has known bugs 鈥?see report 搂5.1) ──
    public struct EdgeCase7_CSharp_For : IJobFor
    {
        public NativeArray<float> A, R;
        public void Execute(int i)
        {
            float acc = 0f;
            int j = 0;
            while (j < 10)
            {
                float v = A[i * 10 + j];
                if (v > 3f) acc += v;
                j++;
            }
            R[i] = acc;
        }
    }

    [NativeTranspiler.NativeTranspile(AutoSIMD = NativeTranspiler.AutoSIMD.Enabled)]
    public struct EdgeCase7_SIMD_For : IJobFor
    {
        public NativeArray<float> A, R;
        public void Execute(int i)
        {
            float acc = 0f;
            for (int j = 0; j < 10; j++)
            {
                float v = A[i * 10 + j];
                if (v > 3f) acc += v;
            }
            R[i] = acc;
        }
    }

    // ── EC8: Subnormal + sign-zero (卤0 branch semantics) ──
    public struct EdgeCase8_CSharp_For : IJobFor
    {
        public NativeArray<float> A, R;
        public void Execute(int i)
        {
            float acc = 0f;
            float t = A[i];
            if (t > 0f) acc += t;
            else if (t < 0f) acc -= t;
            else acc += 0.5f;
            R[i] = acc;
        }
    }

    [NativeTranspiler.NativeTranspile(AutoSIMD = NativeTranspiler.AutoSIMD.Enabled)]
    public struct EdgeCase8_SIMD_For : IJobFor
    {
        public NativeArray<float> A, R;
        public void Execute(int i)
        {
            float acc = 0f;
            float t = A[i];
            if (t > 0f) acc += t;
            else if (t < 0f) acc -= t;
            else acc += 0.5f;
            R[i] = acc;
        }
    }

    // ── EC9: Multi-level nested if-else + float accumulator multi-branch write (regression: save-blend nesting) ──
    public struct EdgeCase9_CSharp_For : IJobFor
    {
        public NativeArray<float> A, R;
        public void Execute(int i)
        {
            float a = A[i];
            float acc = 0f;
            if (a > 0f)
            {
                acc += a;
                if (a > 10f) acc += a * 2f;
                else acc -= a;
            }
            else
            {
                acc -= a;
                if (a < -10f) acc += a * 3f;
                else if (a < -5f) acc += a * 0.1f;
                else acc += 0.01f;
            }
            if (acc > 100f)
            {
                acc *= 0.5f;
                if (acc > 1000f) acc -= 5f;
            }
            R[i] = acc;
        }
    }

    [NativeTranspiler.NativeTranspile(AutoSIMD = NativeTranspiler.AutoSIMD.Enabled)]
    public struct EdgeCase9_SIMD_For : IJobFor
    {
        public NativeArray<float> A, R;
        public void Execute(int i)
        {
            float a = A[i];
            float acc = 0f;
            if (a > 0f)
            {
                acc += a;
                if (a > 10f) acc += a * 2f;
                else acc -= a;
            }
            else
            {
                acc -= a;
                if (a < -10f) acc += a * 3f;
                else if (a < -5f) acc += a * 0.1f;
                else acc += 0.01f;
            }
            if (acc > 100f)
            {
                acc *= 0.5f;
                if (acc > 1000f) acc -= 5f;
            }
            R[i] = acc;
        }
    }

    // ── EC10: Focused regression 鈥?all-INT_MIN input for unchecked(-x) ──
    public struct EdgeCase10_CSharp_For : IJobFor
    {
        public NativeArray<int> A, R;
        public void Execute(int i)
        {
            int x = A[i];
            if (x == int.MinValue) R[i] = unchecked(-x);
            else R[i] = x * 2;
        }
    }

    [NativeTranspiler.NativeTranspile(AutoSIMD = NativeTranspiler.AutoSIMD.Enabled)]
    public struct EdgeCase10_SIMD_For : IJobFor
    {
        public NativeArray<int> A, R;
        public void Execute(int i)
        {
            int x = A[i];
            if (x == int.MinValue) R[i] = unchecked(-x);
            else R[i] = x * 2;
        }
    }
}
