//
// SharpNative_Job__global_namespace__GridSearch2D_ClosestPointJobPointer_Execute_Batch_ispc.h
// (Header automatically generated by the ispc compiler.)
// DO NOT EDIT THIS FILE.
//

#pragma once
#include <stdint.h>

#if !defined(__cplusplus)
#if defined(__STDC_VERSION__) && (__STDC_VERSION__ >= 199901L)
#include <stdbool.h>
#else
typedef int bool;
#endif
#endif



#ifdef __cplusplus
namespace ispc { /* namespace */
#endif // __cplusplus

/* Portable alignment macro that works across different compilers and standards */
#if defined(__cplusplus) && __cplusplus >= 201103L
/* C++11 or newer - use alignas keyword */
#define __ISPC_ALIGN__(x) alignas(x)
#elif defined(__GNUC__) || defined(__clang__)
/* GCC or Clang - use __attribute__ */
#define __ISPC_ALIGN__(x) __attribute__((aligned(x)))
#elif defined(_MSC_VER)
/* Microsoft Visual C++ - use __declspec */
#define __ISPC_ALIGN__(x) __declspec(align(x))
#else
/* Unknown compiler/standard - alignment not supported */
#define __ISPC_ALIGN__(x)
#warning "Alignment not supported on this compiler"
#endif // defined(__cplusplus) && __cplusplus >= 201103L
#ifndef __ISPC_ALIGNED_STRUCT__
#if defined(__clang__) || !defined(_MSC_VER) || _MSC_VER > 1943
// Clang, GCC, ICC, Visual Studio
#define __ISPC_ALIGNED_STRUCT__(s) struct __ISPC_ALIGN__(s)
#else
// Older Visual Studio
#define __ISPC_ALIGNED_STRUCT__(s) __ISPC_ALIGN__(s) struct
#endif // defined(__clang__) || !defined(_MSC_VER) || _MSC_VER > 1943
#endif // __ISPC_ALIGNED_STRUCT__

#ifndef __ISPC_STRUCT_float2__
#define __ISPC_STRUCT_float2__
struct float2 {
    float x;
    float y;
};
#endif

#ifndef __ISPC_STRUCT_int2__
#define __ISPC_STRUCT_int2__
struct int2 {
    int32_t x;
    int32_t y;
};
#endif

#ifndef __ISPC_STRUCT_UnsafeList_Context_int2__
#define __ISPC_STRUCT_UnsafeList_Context_int2__
struct UnsafeList_Context_int2 {
    void * _data;
    int32_t _length;
    int32_t _capacity;
    int32_t _allocator;
    void ( * ResizeFunc)(void *  * _data, int32_t * _length, int32_t * _capacity, int32_t * _allocator, int32_t newSize, bool clear);
};
#endif


///////////////////////////////////////////////////////////////////////////
// Functions exported from ispc code
///////////////////////////////////////////////////////////////////////////
#if defined(__cplusplus) && (! defined(__ISPC_NO_EXTERN_C) || !__ISPC_NO_EXTERN_C )
extern "C" {
#endif // __cplusplus
    extern void SharpNative_Job__global_namespace__GridSearch2D_ClosestPointJobPointer_Execute_Batch_false_impl(int32_t, int32_t, struct float2 * GridOrigin_ptr, float * GridResolutionInv_ptr, struct int2 * GridDimensions_ptr, struct float2 * QueryPositions_ptr, int32_t QueryPositions_length, struct float2 * SortedPositions_ptr, int32_t SortedPositions_length, struct int2 * HashIndex_ptr, int32_t HashIndex_length, struct UnsafeList_Context_int2 * CellStartEnd, int32_t * SortedLength_ptr, bool * IgnoreSelf_ptr, float * SquaredEpsilonSelf_ptr, int32_t * Results_ptr, int32_t Results_length);
    extern void SharpNative_Job__global_namespace__GridSearch2D_ClosestPointJobPointer_Execute_Batch_true_impl(int32_t, int32_t, struct float2 * GridOrigin_ptr, float * GridResolutionInv_ptr, struct int2 * GridDimensions_ptr, struct float2 * QueryPositions_ptr, int32_t QueryPositions_length, struct float2 * SortedPositions_ptr, int32_t SortedPositions_length, struct int2 * HashIndex_ptr, int32_t HashIndex_length, struct UnsafeList_Context_int2 * CellStartEnd, int32_t * SortedLength_ptr, bool * IgnoreSelf_ptr, float * SquaredEpsilonSelf_ptr, int32_t * Results_ptr, int32_t Results_length);
#if defined(__cplusplus) && (! defined(__ISPC_NO_EXTERN_C) || !__ISPC_NO_EXTERN_C )
} /* end extern C */
#endif // __cplusplus


#ifdef __cplusplus
} /* namespace */
#endif // __cplusplus
