<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <AllowUnsafeBlocks>true</AllowUnsafeBlocks>
    <Optimize>true</Optimize>
    <AssemblyName>EntJoy.ECS</AssemblyName>
  </PropertyGroup>
  <ItemGroup>
    <ProjectReference Include="..\EntJoy.Collections\EntJoy.Collections.csproj" />
    <ProjectReference Include="..\EntJoy.Jobs\EntJoy.Jobs.csproj" />
  </ItemGroup>
</Project>
