using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.CSharp;
using Microsoft.CodeAnalysis.CSharp.Syntax;
using System.Collections.Generic;
using System.Linq;
using System.Text;

namespace EntJoy.SourceGenerator
{
    [Generator]
    public sealed class IJobEntitySourceGenerator : ISourceGenerator
    {
        public void Initialize(GeneratorInitializationContext context)
        {
            context.RegisterForSyntaxNotifications(() => new Receiver());
        }

        public void Execute(GeneratorExecutionContext context)
        {
            if (!(context.SyntaxReceiver is Receiver receiver))
                return;

            foreach (var candidate in receiver.Candidates)
            {
                var model = context.Compilation.GetSemanticModel(candidate.SyntaxTree);
                if (!(model.GetDeclaredSymbol(candidate) is INamedTypeSymbol jobType))
                    continue;

                if (!jobType.AllInterfaces.Any(i => i.Name == "IJobEntity"))
                    continue;

                if (jobType.GetAttributes().Any(a => a.AttributeClass?.Name == "NativeTranspileAttribute"))
                    continue;

                var execute = jobType.GetMembers().OfType<IMethodSymbol>()
                    .FirstOrDefault(m => m.Name == "Execute" && m.Parameters.Length > 0 && m.ReturnsVoid);
                if (execute == null)
                    continue;

                string source = Generate(jobType, execute);
                context.AddSource($"{Sanitize(jobType.ToDisplayString())}_IJobEntityAdapter.g.cs", source);
            }
        }

        private static string Generate(INamedTypeSymbol jobType, IMethodSymbol execute)
        {
            string jobFullName = jobType.ToDisplayString(SymbolDisplayFormat.FullyQualifiedFormat);
            string adapterName = $"__EntJoy_IJobEntityAdapter_{Sanitize(jobType.ToDisplayString())}";
            string batchExecutorName = $"__EntJoy_IJobEntityBatchExecutor_{Sanitize(jobType.ToDisplayString())}";
            string requiredTypesField = $"__EntJoy_IJobEntityRequiredTypes_{Sanitize(jobType.ToDisplayString())}";
            bool supportsDirectBatch = jobType.IsUnmanagedType && execute.Parameters.All(p => p.Type.IsUnmanagedType);
            string namespaceName = jobType.ContainingNamespace?.IsGlobalNamespace == false
                ? jobType.ContainingNamespace.ToDisplayString()
                : string.Empty;
            string componentDecls = string.Join("\n", execute.Parameters.Select((p, i) =>
                $"            var __c{i} = chunk.GetComponentDataSpan<{p.Type.ToDisplayString(SymbolDisplayFormat.FullyQualifiedFormat)}>();"));
            string callArgs = string.Join(", ", execute.Parameters.Select((p, i) =>
                p.RefKind == RefKind.In ? $"in __c{i}[i]" : $"ref __c{i}[i]"));
            string requiredTypeIds = string.Join(", ", execute.Parameters.Select(p =>
                $"global::EntJoy.ComponentTypeManager.GetComponentType(typeof({p.Type.ToDisplayString(SymbolDisplayFormat.FullyQualifiedFormat)})).Id"));
            string batchCallArgs = string.Join(", ", execute.Parameters.Select((p, i) =>
                p.RefKind == RefKind.In ? $"in __p{i}[__entityIndex]" :
                p.RefKind == RefKind.Ref ? $"ref __p{i}[__entityIndex]" :
                $"__p{i}[__entityIndex]"));

            var sb = new StringBuilder();
            sb.AppendLine("// <auto-generated/>");
            sb.AppendLine("using EntJoy;");
            sb.AppendLine("using System.Runtime.CompilerServices;");
            sb.AppendLine();
            if (!string.IsNullOrEmpty(namespaceName))
            {
                sb.AppendLine($"namespace {namespaceName}");
                sb.AppendLine("{");
            }
            sb.AppendLine("public static partial class JobExtensions");
            sb.AppendLine("{");
            if (supportsDirectBatch)
            {
                sb.AppendLine($"    private static readonly int[] {requiredTypesField} = new int[] {{ {requiredTypeIds} }};");
                sb.AppendLine();
            }
            sb.AppendLine($"    public static JobHandle Schedule(this {jobFullName} job, QueryBuilder query, JobHandle dependsOn = default)");
            sb.AppendLine("    {");
            if (supportsDirectBatch)
            {
                sb.AppendLine("        if (query.AllEnabled != null && query.AllEnabled.Length > 0)");
                sb.AppendLine($"            return new {adapterName} {{ Job = job }}.Schedule(query, dependsOn);");
                sb.AppendLine("        var world = World.DefaultWorld ?? throw new global::System.InvalidOperationException(\"No active World found.\");");
                sb.AppendLine($"        var handle = NativeJobScheduler.ScheduleManagedEntityBatch<{jobFullName}, {batchExecutorName}>(");
                sb.AppendLine($"            ref job, world.EntityManager, query, {requiredTypesField}, dependsOn._nativeHandle);");
                sb.AppendLine("        return new JobHandle(handle);");
            }
            else
            {
                sb.AppendLine($"        return new {adapterName} {{ Job = job }}.Schedule(query, dependsOn);");
            }
            sb.AppendLine("    }");
            sb.AppendLine();
            sb.AppendLine($"    public static void Run(this {jobFullName} job, QueryBuilder query)");
            sb.AppendLine("    {");
            if (supportsDirectBatch)
            {
                sb.AppendLine("        if (query.AllEnabled != null && query.AllEnabled.Length > 0)");
                sb.AppendLine("        {");
                sb.AppendLine($"            new {adapterName} {{ Job = job }}.Run(query);");
                sb.AppendLine("            return;");
                sb.AppendLine("        }");
                sb.AppendLine("        Schedule(job, query).Complete();");
            }
            else
            {
                sb.AppendLine($"        new {adapterName} {{ Job = job }}.Run(query);");
            }
            sb.AppendLine("    }");
            sb.AppendLine("}");
            sb.AppendLine();
            if (supportsDirectBatch)
            {
                sb.AppendLine($"internal unsafe struct {batchExecutorName} : IJobEntityBatchExecutor<{jobFullName}>");
                sb.AppendLine("{");
                sb.AppendLine("    [MethodImpl(MethodImplOptions.AggressiveInlining | MethodImplOptions.AggressiveOptimization)]");
                sb.AppendLine($"    public static void Execute(ref {jobFullName} job, EntityBatchData* batches, int startIndex, int count)");
                sb.AppendLine("    {");
                sb.AppendLine("        int end = startIndex + count;");
                sb.AppendLine("        for (int batchIndex = startIndex; batchIndex < end; batchIndex++)");
                sb.AppendLine("        {");
                sb.AppendLine("            EntityBatchData* batch = &batches[batchIndex];");
                foreach (var parameter in execute.Parameters.Select((p, i) => (p, i)))
                {
                    string typeName = parameter.p.Type.ToDisplayString(SymbolDisplayFormat.FullyQualifiedFormat);
                    sb.AppendLine($"            {typeName}* __p{parameter.i} = ({typeName}*)batch->componentArrays[{parameter.i}];");
                }
                sb.AppendLine("            int entityCount = batch->entityCount;");
                sb.AppendLine("            for (int __entityIndex = 0; __entityIndex < entityCount; __entityIndex++)");
                sb.AppendLine("            {");
                sb.AppendLine($"                job.Execute({batchCallArgs});");
                sb.AppendLine("            }");
                sb.AppendLine("        }");
                sb.AppendLine("    }");
                sb.AppendLine("}");
                sb.AppendLine();
            }
            sb.AppendLine($"internal struct {adapterName} : IJobChunk");
            sb.AppendLine("{");
            sb.AppendLine($"    public {jobFullName} Job;");
            sb.AppendLine();
            sb.AppendLine("    [MethodImpl(MethodImplOptions.AggressiveInlining | MethodImplOptions.AggressiveOptimization)]");
            sb.AppendLine("    public void Execute(ArchetypeChunk chunk, in ChunkEnabledMask enabledMask)");
            sb.AppendLine("    {");
            sb.AppendLine(componentDecls);
            sb.AppendLine("        int count = chunk.Count;");
            sb.AppendLine("        for (int i = 0; i < count; i++)");
            sb.AppendLine("        {");
            sb.AppendLine($"            Job.Execute({callArgs});");
            sb.AppendLine("        }");
            sb.AppendLine("    }");
            sb.AppendLine("}");
            if (!string.IsNullOrEmpty(namespaceName))
            {
                sb.AppendLine("}");
            }
            return sb.ToString();
        }

        private static string Sanitize(string value)
        {
            var sb = new StringBuilder(value.Length);
            foreach (char c in value)
                sb.Append(char.IsLetterOrDigit(c) ? c : '_');
            return sb.ToString();
        }

        private sealed class Receiver : ISyntaxReceiver
        {
            public readonly List<StructDeclarationSyntax> Candidates = new List<StructDeclarationSyntax>();

            public void OnVisitSyntaxNode(SyntaxNode syntaxNode)
            {
                if (syntaxNode is StructDeclarationSyntax s &&
                    s.BaseList != null &&
                    s.BaseList.Types.Any(t => t.Type.ToString().Contains("IJobEntity")))
                {
                    Candidates.Add(s);
                }
            }
        }
    }
}
