#nullable enable
using System;
using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.CSharp;
using Microsoft.CodeAnalysis.CSharp.Syntax;
using Microsoft.CodeAnalysis.Text;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading;

namespace EntJoy.ECS.SourceGenerator
{
    /// <summary>
    /// N 元组 chunk 级查询生成器：扫描 <c>world.QueryChunks&lt;T0..Tn&gt;()</c> 调用点
    /// （接收者符号类型必须是 <see cref="Config.WorldFullName"/>，arity ≥ 3），为每个
    /// arity 生成一份泛型模板：<c>ChunkEnumerable</c>/<c>ChunkEnumerator</c>/<c>ChunkResult</c>
    /// 及 <c>World.QueryChunks</c> 扩展方法。与库内 2 元组 chunk 三件套同构，逐 N 展开。
    /// 
    /// 扩展方法 body 直接构建 <c>builder.All</c>（不依赖 WithAll 生成器——两生成器扫描面
    /// 不同，用户可能只调 QueryChunks 不调 WithAll）。类名带 arity 后缀防同名冲突。
    /// </summary>
    internal sealed class ChunkQueryTupleSourceGenerator : IIncrementalGenerator
    {
        public void Initialize(IncrementalGeneratorInitializationContext context)
        {
            var arityProvider = context.SyntaxProvider
                .CreateSyntaxProvider(
                    predicate: static (node, _) => IsCandidate(node),
                    transform: static (ctx, ct) => GetArity(ctx, ct))
                .Where(static n => n > 0);

            var collected = arityProvider.Collect();

            context.RegisterSourceOutput(collected, static (spc, arities) =>
            {
                var unique = new SortedSet<int>();
                foreach (var n in arities)
                    if (n > 0) unique.Add(n);

                foreach (var n in unique)
                {
                    string source = GenerateTuple(n);
                    spc.AddSource($"ChunkQueryTuple_{n}.g.cs", SourceText.From(source, Encoding.UTF8));
                }
            });
        }

        private static bool IsCandidate(SyntaxNode node)
        {
            // 语法预筛：形如 <expr>.QueryChunks<T0, T1, ...>() 的调用（语义确认在 GetArity 做）
            return node is InvocationExpressionSyntax inv &&
                   inv.Expression is MemberAccessExpressionSyntax ma &&
                   ma.Name is GenericNameSyntax gen &&
                   gen.Identifier.Text == Config.QueryChunksMethod &&
                   gen.TypeArgumentList.Arguments.Count >= Config.MinTupleArity &&
                   ma.Expression is ExpressionSyntax;
        }

        private static int GetArity(GeneratorSyntaxContext context, CancellationToken ct)
        {
            if (context.Node is not InvocationExpressionSyntax inv)
                return -1;
            if (inv.Expression is not MemberAccessExpressionSyntax ma)
                return -1;
            if (ma.Name is not GenericNameSyntax genName)
                return -1;

            var typeArgs = genName.TypeArgumentList.Arguments;
            if (typeArgs.Count < Config.MinTupleArity)
                return -1;

            var model = context.SemanticModel;

            // 符号匹配：接收者表达式类型必须是 EntJoy.ECS.World（防同名方法/改名误判）。
            var receiverType = model.GetTypeInfo(ma.Expression, ct).Type;
            string receiverFullName = receiverType?.ToDisplayString(SymbolDisplayFormat.FullyQualifiedFormat) ?? "";
            if (receiverFullName.StartsWith("global::", StringComparison.Ordinal))
                receiverFullName = receiverFullName.Substring("global::".Length);
            if (receiverFullName != Config.WorldFullName)
                return -1;

            return typeArgs.Count;
        }

        private static string GenerateTuple(int n)
        {
            var genParams = Enumerable.Range(0, n).Select(i => $"T{i}").ToList();
            string genList = string.Join(", ", genParams);
            string whereClause = string.Join(" ", genParams.Select(g => $"where {g} : struct"));
            string typeOfArgs = string.Join(", ", genParams.Select(g => $"typeof({g})"));

            var sb = new StringBuilder();
            sb.AppendLine("// <auto-generated/>");
            sb.AppendLine("using System;");
            sb.AppendLine("using System.Runtime.CompilerServices;");
            sb.AppendLine("using EntJoy;");          // BitMask（EntJoy.Mathematics，父命名空间）
            sb.AppendLine("using EntJoy.ECS;");
            sb.AppendLine();

            // ===== ChunkEnumerable<T0..Tn> =====
            sb.AppendLine($"public unsafe ref struct ChunkEnumerable<{genList}>");
            sb.AppendLine($"    {whereClause}");
            sb.AppendLine("{");
            sb.AppendLine("    private readonly EntityManager _entityManager;");
            sb.AppendLine("    private readonly QueryBuilder _builder;");
            sb.AppendLine();
            sb.AppendLine("    internal ChunkEnumerable(EntityManager em, QueryBuilder builder)");
            sb.AppendLine("    {");
            sb.AppendLine("        _entityManager = em;");
            sb.AppendLine("        _builder = builder;");
            sb.AppendLine("    }");
            sb.AppendLine();
            sb.AppendLine($"    public ChunkEnumerator<{genList}> GetEnumerator()");
            sb.AppendLine($"        => new ChunkEnumerator<{genList}>(_entityManager, _builder);");
            sb.AppendLine("}");
            sb.AppendLine();

            // ===== ChunkEnumerator<T0..Tn> =====
            sb.AppendLine($"public unsafe ref struct ChunkEnumerator<{genList}>");
            sb.AppendLine($"    {whereClause}");
            sb.AppendLine("{");
            sb.AppendLine("    private readonly EntityManager _entityManager;");
            sb.AppendLine("    private readonly QueryBuilder _builder;");
            sb.AppendLine("    private int _archIndex;");
            sb.AppendLine("    private int _chunkIndex;");
            sb.AppendLine("    private Archetype _currentArch;");
            sb.AppendLine("    private Chunk _currentChunk;");
            for (int i = 0; i < n; i++)
                sb.AppendLine($"    private int _t{i}Idx;");
            sb.AppendLine();
            sb.AppendLine($"    internal ChunkEnumerator(EntityManager em, QueryBuilder builder)");
            sb.AppendLine("    {");
            sb.AppendLine("        _entityManager = em;");
            sb.AppendLine("        _builder = builder;");
            sb.AppendLine("        _archIndex = 0;");
            sb.AppendLine("        _chunkIndex = 0;");
            sb.AppendLine("        _currentArch = null;");
            sb.AppendLine("        _currentChunk = default;");
            for (int i = 0; i < n; i++)
                sb.AppendLine($"        _t{i}Idx = -1;");
            sb.AppendLine("    }");
            sb.AppendLine();
            sb.AppendLine("    private bool MoveNextArchetype()");
            sb.AppendLine("    {");
            sb.AppendLine("        while (_archIndex < _entityManager.Archetypes.Length)");
            sb.AppendLine("        {");
            sb.AppendLine("            var arch = _entityManager.Archetypes[_archIndex];");
            sb.AppendLine("            _archIndex++;");
            sb.AppendLine("            if (arch != null && arch.IsMatch(_builder))");
            sb.AppendLine("            {");
            sb.AppendLine("                _currentArch = arch;");
            for (int i = 0; i < n; i++)
                sb.AppendLine($"                _t{i}Idx = arch.GetComponentTypeIndex<{genParams[i]}>();");
            sb.AppendLine("                _chunkIndex = 0;");
            sb.AppendLine("                return MoveNextChunk();");
            sb.AppendLine("            }");
            sb.AppendLine("        }");
            sb.AppendLine("        return false;");
            sb.AppendLine("    }");
            sb.AppendLine();
            sb.AppendLine("    private bool MoveNextChunk()");
            sb.AppendLine("    {");
            sb.AppendLine("        if (_currentArch == null) return false;");
            sb.AppendLine("        var chunks = _currentArch.ChunkList;");
            sb.AppendLine("        while (_chunkIndex < chunks.Count)");
            sb.AppendLine("        {");
            sb.AppendLine("            _currentChunk = chunks[_chunkIndex];");
            sb.AppendLine("            _chunkIndex++;");
            sb.AppendLine("            if (_currentChunk.EntityCount > 0)");
            sb.AppendLine("            {");
            sb.AppendLine("                return true;");
            sb.AppendLine("            }");
            sb.AppendLine("        }");
            sb.AppendLine("        _currentChunk = default;");
            sb.AppendLine("        return MoveNextArchetype();");
            sb.AppendLine("    }");
            sb.AppendLine();
            sb.AppendLine("    public bool MoveNext()");
            sb.AppendLine("    {");
            sb.AppendLine("        if (_currentArch == null)");
            sb.AppendLine("        {");
            sb.AppendLine("            return MoveNextArchetype();");
            sb.AppendLine("        }");
            sb.AppendLine("        while (_chunkIndex < _currentArch.ChunkList.Count)");
            sb.AppendLine("        {");
            sb.AppendLine("            _currentChunk = _currentArch.ChunkList[_chunkIndex];");
            sb.AppendLine("            _chunkIndex++;");
            sb.AppendLine("            if (_currentChunk.EntityCount > 0)");
            sb.AppendLine("                return true;");
            sb.AppendLine("        }");
            sb.AppendLine("        return MoveNextArchetype();");
            sb.AppendLine("    }");
            sb.AppendLine();
            sb.Append($"    public ChunkResult<{genList}> Current");
            sb.AppendLine();
            sb.AppendLine("    {");
            sb.AppendLine("        get");
            sb.AppendLine("        {");
            sb.AppendLine("            if (_currentChunk.MemoryBlock == nint.Zero) throw new InvalidOperationException();");
            sb.Append($"            return new ChunkResult<{genList}>(_currentChunk");
            for (int i = 0; i < n; i++)
                sb.Append($", _t{i}Idx");
            sb.AppendLine(");");
            sb.AppendLine("        }");
            sb.AppendLine("    }");
            sb.AppendLine("}");
            sb.AppendLine();

            // ===== ChunkResult<T0..Tn> =====
            sb.AppendLine($"public unsafe readonly ref struct ChunkResult<{genList}>");
            sb.AppendLine($"    {whereClause}");
            sb.AppendLine("{");
            sb.AppendLine("    private readonly Chunk _chunk;");
            for (int i = 0; i < n; i++)
                sb.AppendLine($"    private readonly int _t{i}Idx;");
            sb.AppendLine();
            sb.Append($"    internal ChunkResult(Chunk chunk");
            for (int i = 0; i < n; i++)
                sb.Append($", int t{i}Idx");
            sb.AppendLine(")");
            sb.AppendLine("    {");
            sb.AppendLine("        _chunk = chunk;");
            for (int i = 0; i < n; i++)
                sb.AppendLine($"        _t{i}Idx = t{i}Idx;");
            sb.AppendLine("    }");
            sb.AppendLine();
            sb.AppendLine("    public int Length => _chunk.EntityCount;");
            sb.AppendLine();
            for (int i = 0; i < n; i++)
            {
                sb.AppendLine($"    public {genParams[i]}* GetPtr{i}() => ({genParams[i]}*)_chunk.GetComponentArrayPointer(_t{i}Idx);");
            }
            for (int i = 0; i < n; i++)
            {
                sb.AppendLine($"    public Span<{genParams[i]}> GetSpan{i}() => new Span<{genParams[i]}>(GetPtr{i}(), Length);");
            }
            sb.AppendLine();
            sb.AppendLine("    /// <summary>获取指定 enableable 组件的位图掩码。</summary>");
            sb.AppendLine("    [MethodImpl(MethodImplOptions.AggressiveInlining)]");
            sb.AppendLine("    public unsafe BitMask GetEnabledMask<T>() where T : struct, IEnableableComponent");
            sb.AppendLine("    {");
            sb.AppendLine("        int idx = _chunk.Archetype.GetComponentTypeIndex<T>();");
            sb.AppendLine("        ulong* ptr = _chunk.GetEnableBitMapPointer(idx);");
            sb.AppendLine("        if (ptr == null)");
            sb.AppendLine("            throw new InvalidOperationException($\"Component {typeof(T).Name} is not enableable.\");");
            sb.AppendLine("        return new BitMask(ptr, Length);");
            sb.AppendLine("    }");
            sb.AppendLine();
            sb.AppendLine("    /// <summary>获取指定实体上 enableable 组件的启用状态。</summary>");
            sb.AppendLine("    [MethodImpl(MethodImplOptions.AggressiveInlining)]");
            sb.AppendLine("    public bool IsComponentEnabled<T>(int entityIndex) where T : struct, IEnableableComponent");
            sb.AppendLine("    {");
            sb.AppendLine("        int idx = _chunk.Archetype.GetComponentTypeIndex<T>();");
            sb.AppendLine("        return _chunk.GetComponentEnabled(idx, entityIndex);");
            sb.AppendLine("    }");
            sb.AppendLine();
            sb.AppendLine("    /// <summary>设置指定实体上 enableable 组件的启用状态。</summary>");
            sb.AppendLine("    [MethodImpl(MethodImplOptions.AggressiveInlining)]");
            sb.AppendLine("    public void SetComponentEnabled<T>(int entityIndex, bool enabled) where T : struct, IEnableableComponent");
            sb.AppendLine("    {");
            sb.AppendLine("        int idx = _chunk.Archetype.GetComponentTypeIndex<T>();");
            sb.AppendLine("        _chunk.SetComponentEnabled(idx, entityIndex, enabled);");
            sb.AppendLine("    }");
            sb.AppendLine("}");
            sb.AppendLine();

            // ===== World.QueryChunks<T0..Tn>（扩展方法：partial 跨程序集不合并，须用 this World） =====
            sb.AppendLine($"public static class ChunkQueryTupleWorldExtensions{n}");
            sb.AppendLine("{");
            sb.AppendLine($"    public static ChunkEnumerable<{genList}> QueryChunks<{genList}>(this World world)");
            sb.AppendLine($"        {whereClause}");
            sb.AppendLine("    {");
            sb.AppendLine("        var builder = new QueryBuilder();");
            sb.AppendLine($"        builder.All = new ComponentType[] {{ {typeOfArgs} }};");
            sb.AppendLine($"        return new ChunkEnumerable<{genList}>(world._entityManager, builder);");
            sb.AppendLine("    }");
            sb.AppendLine("}");
            sb.AppendLine();

            return sb.ToString();
        }
    }
}
