#nullable enable
using System;
using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.CSharp.Syntax;
using Microsoft.CodeAnalysis.Text;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading;

namespace EntJoy.ECS.SourceGenerator
{
    /// <summary>
    /// Disposable 组件注册生成器：扫描同程序集所有持有原生资源的 ECS 组件
    /// （<c>struct : IComponentData, IDisposable</c> 或 <c>[ECSComponent] partial struct : IDisposable</c>），
    /// 生成 <c>ComponentDisposableRegistry.RegisterAll()</c> 一行注册全部，消除逐个手写
    /// <c>ComponentTypeManager.RegisterDisposable&lt;T&gt;()</c> 的样板与漏注册 footgun。
    /// 对齐 SystemRegistry.RegisterAll 的自动收集模式。
    /// </summary>
    internal sealed class DisposableRegistrationSourceGenerator : IIncrementalGenerator
    {
        public void Initialize(IncrementalGeneratorInitializationContext context)
        {
            var provider = context.SyntaxProvider
                .CreateSyntaxProvider(
                    predicate: static (node, _) => IsCandidate(node),
                    transform: static (ctx, ct) => GetFullName(ctx, ct))
                .Where(static name => name != null);

            var collected = provider.Collect();

            context.RegisterSourceOutput(collected, static (spc, names) =>
            {
                var sorted = new SortedSet<string>(StringComparer.Ordinal);
                foreach (var n in names)
                    if (n != null) sorted.Add(n);

                if (sorted.Count == 0)
                    return;

                spc.AddSource("ComponentDisposableRegistry.g.cs", SourceText.From(Generate(sorted), Encoding.UTF8));
            });
        }

        /// <summary>语法预筛：struct 声明的基接口列表含 IDisposable。</summary>
        private static bool IsCandidate(SyntaxNode node)
        {
            return node is StructDeclarationSyntax s &&
                   s.BaseList != null &&
                   s.BaseList.Types.Any(t => t.Type.ToString().Contains(Config.IDisposable));
        }

        /// <summary>语义验证：实现 System.IDisposable，且是 ECS 组件（IComponentData 或 [ECSComponent]）。</summary>
        private static string? GetFullName(GeneratorSyntaxContext context, CancellationToken ct)
        {
            if (context.Node is not StructDeclarationSyntax candidate)
                return null;

            var model = context.SemanticModel;
            if (model.GetDeclaredSymbol(candidate, ct) is not INamedTypeSymbol typeSymbol)
                return null;

            // 必须实现 System.IDisposable（持有原生资源，销毁时需 Dispose）
            bool isDisposable = typeSymbol.AllInterfaces.Any(i =>
                i.Name == Config.IDisposable && i.ContainingNamespace?.ToDisplayString() == Config.NamespaceSystem);
            if (!isDisposable)
                return null;

            // 必须是 ECS 组件：实现 IComponentData，或带 [ECSComponent]（由 ECSComponentSourceGenerator 补 IComponentData）
            bool isEcsComponent =
                typeSymbol.AllInterfaces.Any(i =>
                    i.Name == Config.IComponentData && i.ContainingNamespace?.ToDisplayString() == Config.NamespaceEntJoyECS) ||
                typeSymbol.GetAttributes().Any(a =>
                    a.AttributeClass?.Name == Config.ECSComponentAttribute &&
                    a.AttributeClass.ContainingNamespace?.ToDisplayString() == Config.NamespaceEntJoyECS);
            if (!isEcsComponent)
                return null;

            return typeSymbol.ToDisplayString(SymbolDisplayFormat.FullyQualifiedFormat);
        }

        private static string Generate(IEnumerable<string> fullNames)
        {
            var sb = new StringBuilder();
            sb.AppendLine("// <auto-generated/>");
            sb.AppendLine("#nullable enable");
            sb.AppendLine("using System.Runtime.CompilerServices;");
            sb.AppendLine("using EntJoy.ECS;");
            sb.AppendLine();
            sb.AppendLine("/// <summary>自动收集并注册 Disposable 组件（由 DisposableRegistrationSourceGenerator 生成，模块加载时自动执行，无需手动调用）。</summary>");
            sb.AppendLine("internal static class ComponentDisposableRegistry");
            sb.AppendLine("{");
            sb.AppendLine("    [ModuleInitializer]");
            sb.AppendLine("    internal static void Initialize()");
            sb.AppendLine("    {");
            foreach (var name in fullNames)
            {
                sb.AppendLine($"        ComponentTypeManager.RegisterDisposable<{name}>();");
            }
            sb.AppendLine("    }");
            sb.AppendLine("}");
            return sb.ToString();
        }
    }
}
