#nullable enable
using System;
using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.CSharp.Syntax;
using Microsoft.CodeAnalysis.Text;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading;

namespace EntJoy.ECS.SourceGenerator
{
    /// <summary>
    /// 组件生命周期钩子注册生成器：扫描持有原生资源 / 需复制钩子的 ECS 组件
    /// （<c>: IDisposable</c> 或 <c>: ICopyable&lt;T&gt;</c>），生成
    /// <c>RegisterDisposable</c> + <c>RegisterCopyable</c> 的 [ModuleInitializer] 自动注册。
    /// </summary>
    internal sealed class DisposableRegistrationSourceGenerator : IIncrementalGenerator
    {
        public void Initialize(IncrementalGeneratorInitializationContext context)
        {
            var provider = context.SyntaxProvider
                .CreateSyntaxProvider(
                    predicate: static (node, _) => IsCandidate(node),
                    transform: static (ctx, ct) => Transform(ctx, ct))
                .Where(static info => info != null);

            var collected = provider.Collect();

            context.RegisterSourceOutput(collected, static (spc, infos) =>
            {
                var disposables = new SortedSet<string>(StringComparer.Ordinal);
                var copyables = new SortedSet<string>(StringComparer.Ordinal);
                foreach (var info in infos)
                {
                    if (info is null) continue;
                    if (info.IsDisposable) disposables.Add(info.FullName);
                    if (info.IsCopyable) copyables.Add(info.FullName);
                }

                if (disposables.Count == 0 && copyables.Count == 0)
                    return;

                spc.AddSource("ComponentDisposableRegistry.g.cs",
                    SourceText.From(Generate(disposables, copyables), Encoding.UTF8));
            });
        }

        /// <summary>语法预筛：struct 声明的基接口列表含 IDisposable 或 ICopyable。</summary>
        private static bool IsCandidate(SyntaxNode node)
        {
            return node is StructDeclarationSyntax s &&
                   s.BaseList != null &&
                   s.BaseList.Types.Any(t =>
                   {
                       string n = t.Type.ToString();
                       return n.Contains(Config.IDisposable) || n.Contains(Config.ICopyable);
                   });
        }

        private static RegistrationInfo? Transform(GeneratorSyntaxContext context, CancellationToken ct)
        {
            if (context.Node is not StructDeclarationSyntax candidate)
                return null;

            var model = context.SemanticModel;
            if (model.GetDeclaredSymbol(candidate, ct) is not INamedTypeSymbol typeSymbol)
                return null;

            bool isDisposable = typeSymbol.AllInterfaces.Any(i =>
                i.Name == Config.IDisposable && i.ContainingNamespace?.ToDisplayString() == Config.NamespaceSystem);
            bool isCopyable = typeSymbol.AllInterfaces.Any(i =>
                i.Name == Config.ICopyable && i.ContainingNamespace?.ToDisplayString() == Config.NamespaceEntJoyECS);

            if (!isDisposable && !isCopyable)
                return null;

            bool isEcsComponent =
                typeSymbol.AllInterfaces.Any(i =>
                    i.Name == Config.IComponentData && i.ContainingNamespace?.ToDisplayString() == Config.NamespaceEntJoyECS) ||
                typeSymbol.GetAttributes().Any(a =>
                    a.AttributeClass?.Name == Config.ECSComponentAttribute &&
                    a.AttributeClass.ContainingNamespace?.ToDisplayString() == Config.NamespaceEntJoyECS);
            if (!isEcsComponent)
                return null;

            return new RegistrationInfo
            {
                FullName = typeSymbol.ToDisplayString(SymbolDisplayFormat.FullyQualifiedFormat),
                IsDisposable = isDisposable,
                IsCopyable = isCopyable,
            };
        }

        private static string Generate(SortedSet<string> disposables, SortedSet<string> copyables)
        {
            var sb = new StringBuilder();
            sb.AppendLine("// <auto-generated/>");
            sb.AppendLine("#nullable enable");
            sb.AppendLine("using System.Runtime.CompilerServices;");
            sb.AppendLine("using EntJoy.ECS;");
            sb.AppendLine();
            sb.AppendLine("/// <summary>自动收集并注册组件生命周期钩子（由 DisposableRegistrationSourceGenerator 生成，模块加载时自动执行）。</summary>");
            sb.AppendLine("internal static class ComponentDisposableRegistry");
            sb.AppendLine("{");
            sb.AppendLine("    [ModuleInitializer]");
            sb.AppendLine("    internal static void Initialize()");
            sb.AppendLine("    {");
            foreach (var name in disposables)
                sb.AppendLine($"        ComponentTypeManager.RegisterDisposable<{name}>();");
            foreach (var name in copyables)
                sb.AppendLine($"        ComponentTypeManager.RegisterCopyable<{name}>();");
            sb.AppendLine("    }");
            sb.AppendLine("}");
            return sb.ToString();
        }

        private sealed class RegistrationInfo
        {
            public string FullName = "";
            public bool IsDisposable;
            public bool IsCopyable;
        }
    }
}
