using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.CSharp;
using Microsoft.CodeAnalysis.CSharp.Syntax;
using System.Collections.Generic;
using System.Linq;
using System.Text;

namespace EntJoy.SourceGenerator
{
    [Generator]
    public sealed class IJobEntitySourceGenerator : ISourceGenerator
    {
        public void Initialize(GeneratorInitializationContext context)
        {
            context.RegisterForSyntaxNotifications(() => new Receiver());
        }

        public void Execute(GeneratorExecutionContext context)
        {
            if (!(context.SyntaxReceiver is Receiver receiver))
                return;

            foreach (var candidate in receiver.Candidates)
            {
                var model = context.Compilation.GetSemanticModel(candidate.SyntaxTree);
                if (!(model.GetDeclaredSymbol(candidate) is INamedTypeSymbol jobType))
                    continue;

                if (!jobType.AllInterfaces.Any(i => i.Name == "IJobEntity"))
                    continue;

                var execute = jobType.GetMembers().OfType<IMethodSymbol>()
                    .FirstOrDefault(m => m.Name == "Execute" && m.Parameters.Length > 0 && m.ReturnsVoid);
                if (execute == null)
                    continue;

                string source = Generate(jobType, execute);
                context.AddSource($"{Sanitize(jobType.ToDisplayString())}_IJobEntityAdapter.g.cs", source);
            }
        }

        private static string Generate(INamedTypeSymbol jobType, IMethodSymbol execute)
        {
            string jobFullName = jobType.ToDisplayString(SymbolDisplayFormat.FullyQualifiedFormat);
            string adapterName = $"__EntJoy_IJobEntityAdapter_{Sanitize(jobType.ToDisplayString())}";
            string namespaceName = jobType.ContainingNamespace?.IsGlobalNamespace == false
                ? jobType.ContainingNamespace.ToDisplayString()
                : string.Empty;
            string componentDecls = string.Join("\n", execute.Parameters.Select((p, i) =>
                $"            var __c{i} = chunk.GetComponentDataSpan<{p.Type.ToDisplayString(SymbolDisplayFormat.FullyQualifiedFormat)}>();"));
            string callArgs = string.Join(", ", execute.Parameters.Select((p, i) =>
                p.RefKind == RefKind.In ? $"in __c{i}[i]" : $"ref __c{i}[i]"));

            var sb = new StringBuilder();
            sb.AppendLine("// <auto-generated/>");
            sb.AppendLine("using EntJoy;");
            sb.AppendLine("using EntJoy.JobSystem;");
            sb.AppendLine("using System.Runtime.CompilerServices;");
            sb.AppendLine();
            if (!string.IsNullOrEmpty(namespaceName))
            {
                sb.AppendLine($"namespace {namespaceName}");
                sb.AppendLine("{");
            }
            sb.AppendLine("public static partial class JobExtensions");
            sb.AppendLine("{");
            sb.AppendLine($"    public static JobHandle Schedule(this {jobFullName} job, QueryBuilder query, JobHandle dependsOn = default)");
            sb.AppendLine("    {");
            sb.AppendLine($"        return new {adapterName} {{ Job = job }}.Schedule(query, dependsOn);");
            sb.AppendLine("    }");
            sb.AppendLine();
            sb.AppendLine($"    public static JobHandle ScheduleWithWorkerCap(this {jobFullName} job, QueryBuilder query, int workerCap, JobHandle dependsOn = default)");
            sb.AppendLine("    {");
            sb.AppendLine($"        return new {adapterName} {{ Job = job }}.ScheduleWithWorkerCap(query, workerCap, dependsOn);");
            sb.AppendLine("    }");
            sb.AppendLine();
            sb.AppendLine($"    public static void Run(this {jobFullName} job, QueryBuilder query)");
            sb.AppendLine("    {");
            sb.AppendLine($"        new {adapterName} {{ Job = job }}.Run(query);");
            sb.AppendLine("    }");
            sb.AppendLine("}");
            sb.AppendLine();
            sb.AppendLine($"internal struct {adapterName} : IJobChunk");
            sb.AppendLine("{");
            sb.AppendLine($"    public {jobFullName} Job;");
            sb.AppendLine();
            // Schedule/ScheduleWithWorkerCap/Run 方法：调用 NativeJobScheduler 调度
            sb.AppendLine("    [MethodImpl(MethodImplOptions.AggressiveInlining)]");
            sb.AppendLine("    public JobHandle Schedule(QueryBuilder query, JobHandle dependsOn = default)");
            sb.AppendLine("    {");
            sb.AppendLine("        var world = World.DefaultWorld;");
            sb.AppendLine("        if (world == null) throw new InvalidOperationException(\"No active World found.\");");
            sb.AppendLine("        NativeJobHandle? nativeDep = dependsOn.GetNativeDependency();");
            sb.AppendLine("        return new JobHandle(NativeEcsScheduler.ScheduleChunk(ref this, world.EntityManager, query, nativeDep));");
            sb.AppendLine("    }");
            sb.AppendLine();
            sb.AppendLine("    [MethodImpl(MethodImplOptions.AggressiveInlining)]");
            sb.AppendLine("    public JobHandle ScheduleWithWorkerCap(QueryBuilder query, int workerCap, JobHandle dependsOn = default)");
            sb.AppendLine("    {");
            sb.AppendLine("        var world = World.DefaultWorld;");
            sb.AppendLine("        if (world == null) throw new InvalidOperationException(\"No active World found.\");");
            sb.AppendLine("        NativeJobHandle? nativeDep = dependsOn.GetNativeDependency();");
            sb.AppendLine("        return new JobHandle(NativeEcsScheduler.ScheduleChunkWithWorkerCap(ref this, world.EntityManager, query, workerCap, nativeDep));");
            sb.AppendLine("    }");
            sb.AppendLine();
            sb.AppendLine("    public void Run(QueryBuilder query)");
            sb.AppendLine("    {");
            sb.AppendLine("        var world = World.DefaultWorld;");
            sb.AppendLine("        if (world == null) throw new InvalidOperationException(\"No active World found.\");");
            sb.AppendLine("        var entityManager = world.EntityManager;");
            sb.AppendLine("        for (int i = 0; i < entityManager.ArchetypeCount; i++)");
            sb.AppendLine("        {");
            sb.AppendLine("            var arch = entityManager.Archetypes[i];");
            sb.AppendLine("            if (arch != null && arch.IsMatch(query))");
            sb.AppendLine("            {");
            sb.AppendLine("                foreach (var chunk in arch.GetChunks())");
            sb.AppendLine("                {");
            sb.AppendLine("                    if (chunk.EntityCount == 0) continue;");
            sb.AppendLine("                    Execute(new ArchetypeChunk(chunk), new ChunkEnabledMask(null, 0));");
            sb.AppendLine("                }");
            sb.AppendLine("            }");
            sb.AppendLine("        }");
            sb.AppendLine("    }");
            sb.AppendLine();
            sb.AppendLine("    [MethodImpl(MethodImplOptions.AggressiveInlining | MethodImplOptions.AggressiveOptimization)]");
            sb.AppendLine("    public void Execute(ArchetypeChunk chunk, in ChunkEnabledMask enabledMask)");
            sb.AppendLine("    {");
            sb.AppendLine(componentDecls);
            sb.AppendLine("        int count = chunk.Count;");
            sb.AppendLine("        for (int i = 0; i < count; i++)");
            sb.AppendLine("        {");
            sb.AppendLine($"            Job.Execute({callArgs});");
            sb.AppendLine("        }");
            sb.AppendLine("    }");
            sb.AppendLine("}");
            if (!string.IsNullOrEmpty(namespaceName))
            {
                sb.AppendLine("}");
            }
            return sb.ToString();
        }

        private static string Sanitize(string value)
        {
            var sb = new StringBuilder(value.Length);
            foreach (char c in value)
                sb.Append(char.IsLetterOrDigit(c) ? c : '_');
            return sb.ToString();
        }

        private sealed class Receiver : ISyntaxReceiver
        {
            public readonly List<StructDeclarationSyntax> Candidates = new List<StructDeclarationSyntax>();

            public void OnVisitSyntaxNode(SyntaxNode syntaxNode)
            {
                if (syntaxNode is StructDeclarationSyntax s &&
                    s.BaseList != null &&
                    s.BaseList.Types.Any(t => t.Type.ToString().Contains("IJobEntity")))
                {
                    Candidates.Add(s);
                }
            }
        }
    }
}
