#nullable enable
using System;
using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.CSharp;
using Microsoft.CodeAnalysis.CSharp.Syntax;
using Microsoft.CodeAnalysis.Text;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading;

namespace EntJoy.ECS.SourceGenerator
{
    /// <summary>
    /// QueryBuilder.WithAll&lt;T0..Tn&gt;() N 元组生成器：扫描 <c>builder.WithAll&lt;A,B,C&gt;()</c>
    /// 调用点（接收者符号类型必须是 <see cref="Config.QueryBuilderFullName"/>，arity ≥ 3），
    /// 为每个出现的 arity 生成一份泛型模板：
    ///   - 内部静态缓存 <c>ComponentTypes&lt;T0..Tn&gt;</c>（.Share 数组，与库内 1/2 元组同构）；
    ///   - 静态扩展类 <c>QueryBuilderWithAllExtensions{n}</c>，提供
    ///     <c>WithAll&lt;T0..Tn&gt;(this QueryBuilder)</c>。
    /// 
    /// 必须用扩展方法而非 partial：生成代码编译进调用方程序集（generator 以 Analyzer 引用，
    /// 见 EntJoySample.csproj），而 QueryBuilder 库类型在 EntJoy.ECS 程序集，跨程序集 partial
    /// 不合并。扩展类名带 arity 后缀防同名冲突。
    /// </summary>
    internal sealed class QueryBuilderTupleSourceGenerator : IIncrementalGenerator
    {
        public void Initialize(IncrementalGeneratorInitializationContext context)
        {
            var arityProvider = context.SyntaxProvider
                .CreateSyntaxProvider(
                    predicate: static (node, _) => IsCandidate(node),
                    transform: static (ctx, ct) => GetArity(ctx, ct))
                .Where(static n => n > 0);

            var collected = arityProvider.Collect();

            context.RegisterSourceOutput(collected, static (spc, arities) =>
            {
                var unique = new SortedSet<int>();
                foreach (var n in arities)
                    if (n > 0) unique.Add(n);

                foreach (var n in unique)
                {
                    string source = Generate(n);
                    spc.AddSource($"QueryBuilderWithAll_{n}.g.cs", SourceText.From(source, Encoding.UTF8));
                }
            });
        }

        private static bool IsCandidate(SyntaxNode node)
        {
            // 语法预筛：形如 <expr>.WithAll<T0, T1, ...>() 的调用（语义确认在 GetArity 做）
            return node is InvocationExpressionSyntax inv &&
                   inv.Expression is MemberAccessExpressionSyntax ma &&
                   ma.Name is GenericNameSyntax gen &&
                   gen.Identifier.Text == Config.WithAllMethod &&
                   gen.TypeArgumentList.Arguments.Count >= Config.MinTupleArity &&
                   ma.Expression is ExpressionSyntax;
        }

        private static int GetArity(GeneratorSyntaxContext context, CancellationToken ct)
        {
            if (context.Node is not InvocationExpressionSyntax inv)
                return -1;
            if (inv.Expression is not MemberAccessExpressionSyntax ma)
                return -1;
            if (ma.Name is not GenericNameSyntax genName)
                return -1;

            var typeArgs = genName.TypeArgumentList.Arguments;
            if (typeArgs.Count < Config.MinTupleArity)
                return -1;

            var model = context.SemanticModel;

            // 符号匹配：接收者表达式类型必须是 EntJoy.ECS.QueryBuilder（防同名方法/局部误判）。
            // 不能依赖方法符号（N 元组重载首次编译时尚不存在），只解析接收者类型。
            var receiverType = model.GetTypeInfo(ma.Expression, ct).Type;
            string receiverFullName = receiverType?.ToDisplayString(SymbolDisplayFormat.FullyQualifiedFormat) ?? "";
            if (receiverFullName.StartsWith("global::", StringComparison.Ordinal))
                receiverFullName = receiverFullName.Substring("global::".Length);
            if (receiverFullName != Config.QueryBuilderFullName)
                return -1;

            return typeArgs.Count;
        }

        private static string Generate(int n)
        {
            var genParams = Enumerable.Range(0, n).Select(i => $"T{i}").ToList();
            string genList = string.Join(", ", genParams);
            string whereClause = string.Join(" ", genParams.Select(g => $"where {g} : struct"));
            string typeOfArgs = string.Join(", ", genParams.Select(g => $"typeof({g})"));

            var sb = new StringBuilder();
            sb.AppendLine("// <auto-generated/>");
            sb.AppendLine("using EntJoy.ECS;");
            sb.AppendLine();

            // ===== ComponentTypes<T0..Tn>（内部静态缓存，与库内 1/2 元组同构） =====
            sb.AppendLine($"internal sealed class ComponentTypes<{genList}>");
            sb.AppendLine($"    {whereClause}");
            sb.AppendLine("{");
            sb.AppendLine("    /// <summary>共享的组件类型数组（只读，防止外部修改）</summary>");
            sb.AppendLine($"    public static readonly ComponentType[] Share = new ComponentType[]");
            sb.AppendLine("    {");
            sb.AppendLine($"        {typeOfArgs}");
            sb.AppendLine("    };");
            sb.AppendLine("}");
            sb.AppendLine();

            // ===== 扩展方法（partial 跨程序集不合并，须用 this QueryBuilder） =====
            sb.AppendLine($"public static class QueryBuilderWithAllExtensions{n}");
            sb.AppendLine("{");
            sb.AppendLine($"    public static QueryBuilder WithAll<{genList}>(this QueryBuilder builder)");
            sb.AppendLine($"        {whereClause}");
            sb.AppendLine("    {");
            // 零分配首调：直接引用静态 Share；后续链式：Merge 合并（对齐库内 1/2 元组语义）
            sb.AppendLine("        if (builder.All == null)");
            sb.AppendLine("        {");
            sb.AppendLine($"            builder.All = ComponentTypes<{genList}>.Share;");
            sb.AppendLine("            return builder;");
            sb.AppendLine("        }");
            sb.AppendLine($"        builder.All = QueryBuilderWithAllExtensions{n}.Merge(builder.All, ComponentTypes<{genList}>.Share);");
            sb.AppendLine("        return builder;");
            sb.AppendLine("    }");
            sb.AppendLine();
            sb.AppendLine("    /// <summary>合并两个只读类型数组（与库内 QueryBuilder.Merge 相同逻辑，扩展方法无法访问 private）。</summary>");
            sb.AppendLine("    private static ComponentType[] Merge(ComponentType[] a, ComponentType[] b)");
            sb.AppendLine("    {");
            sb.AppendLine("        var merged = new ComponentType[a.Length + b.Length];");
            sb.AppendLine("        Array.Copy(a, 0, merged, 0, a.Length);");
            sb.AppendLine("        Array.Copy(b, 0, merged, a.Length, b.Length);");
            sb.AppendLine("        return merged;");
            sb.AppendLine("    }");
            sb.AppendLine("}");
            sb.AppendLine();

            return sb.ToString();
        }
    }
}
