#nullable enable
using System;
using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.CSharp;
using Microsoft.CodeAnalysis.CSharp.Syntax;
using Microsoft.CodeAnalysis.Text;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading;

namespace EntJoy.ECS.SourceGenerator
{
    /// <summary>
    /// N 元组查询生成器：扫描 <c>world.Query&lt;T0..Tn&gt;()</c> 调用点（接收者符号类型必须是
    /// <see cref="Config.WorldFullName"/>），为出现的每个 N 元组 **arity**（N ≥ 3）生成一份
    /// 泛型模板：强类型 <c>QueryEnumerable</c>/<c>QueryEnumerator</c>/<c>EntityQueryResult</c>
    /// 及 <c>World.Query</c> 扩展方法（body 内 <c>typeof(T0..Tn)</c> 泛型化，非具体组合）。
    /// 运行时零反射。
    /// 
    /// 注意：按 arity 去重而非按具体类型组合去重——同 arity 不同组件组合共用同一份泛型定义，
    /// 避免重复生成同名泛型类型（CS0101）。扩展类名带 arity 后缀防同名冲突。
    /// </summary>
    internal sealed class QueryTupleSourceGenerator : IIncrementalGenerator
    {
        public void Initialize(IncrementalGeneratorInitializationContext context)
        {
            var arityProvider = context.SyntaxProvider
                .CreateSyntaxProvider(
                    predicate: static (node, _) => IsCandidate(node),
                    transform: static (ctx, ct) => GetArity(ctx, ct))
                .Where(static n => n > 0);

            var collected = arityProvider.Collect();

            context.RegisterSourceOutput(collected, static (spc, arities) =>
            {
                var unique = new SortedSet<int>();
                foreach (var n in arities)
                    if (n > 0) unique.Add(n);

                foreach (var n in unique)
                {
                    string source = GenerateTuple(n);
                    spc.AddSource($"QueryTuple_{n}.g.cs", SourceText.From(source, Encoding.UTF8));
                }
            });
        }

        private static bool IsCandidate(SyntaxNode node)
        {
            // 语法预筛：形如 <expr>.Query<T0, T1, ...>() 的调用（语义确认在 GetArity 做）
            return node is InvocationExpressionSyntax inv &&
                   inv.Expression is MemberAccessExpressionSyntax ma &&
                   ma.Name is GenericNameSyntax gen &&
                   gen.Identifier.Text == Config.QueryMethod &&
                   gen.TypeArgumentList.Arguments.Count >= Config.MinTupleArity &&
                   ma.Expression is ExpressionSyntax;
        }

        private static int GetArity(GeneratorSyntaxContext context, CancellationToken ct)
        {
            if (context.Node is not InvocationExpressionSyntax inv)
                return -1;
            if (inv.Expression is not MemberAccessExpressionSyntax ma)
                return -1;
            if (ma.Name is not GenericNameSyntax genName)
                return -1;

            var typeArgs = genName.TypeArgumentList.Arguments;
            if (typeArgs.Count < Config.MinTupleArity)
                return -1;

            var model = context.SemanticModel;

            // 符号匹配：接收者表达式类型必须是 EntJoy.ECS.World（防同名方法/改名误判）。
            // 注意：不能依赖方法符号（N 元组重载首次编译时尚不存在），只解析接收者类型。
            // ToDisplayString(FullyQualifiedFormat) 输出可能带 global:: 前缀，统一归一后比较。
            var receiverType = model.GetTypeInfo(ma.Expression, ct).Type;
            string receiverFullName = receiverType?.ToDisplayString(SymbolDisplayFormat.FullyQualifiedFormat) ?? "";
            if (receiverFullName.StartsWith("global::", StringComparison.Ordinal))
                receiverFullName = receiverFullName.Substring("global::".Length);
            if (receiverFullName != Config.WorldFullName)
                return -1;

            return typeArgs.Count;
        }

        private static string GenerateTuple(int n)
        {
            var genParams = Enumerable.Range(0, n).Select(i => $"T{i}").ToList();
            string genList = string.Join(", ", genParams);
            string whereClause = string.Join(" ", genParams.Select(g => $"where {g} : struct"));
            string typeOfArgs = string.Join(", ", genParams.Select(g => $"typeof({g})"));

            var sb = new StringBuilder();
            sb.AppendLine("// <auto-generated/>");
            sb.AppendLine("using System;");
            sb.AppendLine("using System.Numerics;");
            sb.AppendLine("using System.Runtime.CompilerServices;");
            sb.AppendLine("using System.Runtime.Intrinsics;");
            sb.AppendLine("using System.Runtime.Intrinsics.X86;");
            sb.AppendLine("using EntJoy.ECS;");
            sb.AppendLine("using EntJoy.ECS.JobSystem;");
            sb.AppendLine("using EntJoy.JobSystem;");
            sb.AppendLine();

            // ===== QueryEnumerable<T0..Tn> =====
            sb.AppendLine($"public unsafe ref struct QueryEnumerable<{genList}>");
            sb.AppendLine($"    {whereClause}");
            sb.AppendLine("{");
            sb.AppendLine("    private readonly EntityManager _entityManager;");
            sb.AppendLine("    private readonly QueryBuilder _builder;");
            sb.AppendLine();
            sb.AppendLine("    internal QueryEnumerable(EntityManager entityManager, QueryBuilder builder)");
            sb.AppendLine("    {");
            sb.AppendLine("        _entityManager = entityManager;");
            sb.AppendLine("        _builder = builder;");
            sb.AppendLine("    }");
            sb.AppendLine();
            sb.AppendLine("    [MethodImpl(MethodImplOptions.AggressiveInlining)]");
            sb.AppendLine($"    public QueryEnumerator<{genList}> GetEnumerator()");
            sb.AppendLine($"        => new QueryEnumerator<{genList}>(_entityManager, _builder);");
            sb.AppendLine("}");
            sb.AppendLine();

            // ===== QueryEnumerator<T0..Tn> =====
            sb.AppendLine($"public unsafe ref struct QueryEnumerator<{genList}>");
            sb.AppendLine($"    {whereClause}");
            sb.AppendLine("{");
            sb.AppendLine("    private readonly EntityManager _entityManager;");
            sb.AppendLine("    private readonly QueryBuilder _builder;");
            sb.AppendLine("    private readonly ComponentType[] _allEnabledTypes;");
            sb.AppendLine("    private int _archIndex;");
            sb.AppendLine("    private int _chunkIndex;");
            sb.AppendLine("    private int _slotIndex;");
            sb.AppendLine("    private int _count;");
            sb.AppendLine("    private Archetype _currentArch;");
            sb.AppendLine("    private Chunk _currentChunk;");
            for (int i = 0; i < n; i++)
            {
                sb.AppendLine($"    private int _t{i}Idx;");
                sb.AppendLine($"    private {genParams[i]}* _t{i}Base;");
            }
            sb.AppendLine("    private ulong* _combinedMask;");
            sb.AppendLine("    private int _ulongCount;");
            sb.AppendLine();
            sb.AppendLine($"    internal QueryEnumerator(EntityManager entityManager, QueryBuilder builder)");
            sb.AppendLine("    {");
            sb.AppendLine("        _entityManager = entityManager;");
            sb.AppendLine("        _builder = builder;");
            sb.AppendLine("        _allEnabledTypes = builder.AllEnabled;");
            sb.AppendLine("        _archIndex = 0;");
            sb.AppendLine("        _chunkIndex = 0;");
            sb.AppendLine("        _slotIndex = 0;");
            sb.AppendLine("        _count = 0;");
            sb.AppendLine("        _currentArch = null;");
            sb.AppendLine("        _currentChunk = default;");
            for (int i = 0; i < n; i++)
            {
                sb.AppendLine($"        _t{i}Idx = -1;");
                sb.AppendLine($"        _t{i}Base = null;");
            }
            sb.AppendLine("        _combinedMask = null;");
            sb.AppendLine("        _ulongCount = 0;");
            sb.AppendLine("    }");
            sb.AppendLine();

            // MoveNextArchetype
            sb.AppendLine("    [MethodImpl(MethodImplOptions.AggressiveInlining)]");
            sb.AppendLine("    private bool MoveNextArchetype()");
            sb.AppendLine("    {");
            sb.AppendLine("        while (_archIndex < _entityManager.ArchetypeCount)");
            sb.AppendLine("        {");
            sb.AppendLine("            var arch = _entityManager.Archetypes[_archIndex];");
            sb.AppendLine("            _archIndex++;");
            sb.AppendLine("            if (arch != null && arch.IsMatch(_builder))");
            sb.AppendLine("            {");
            sb.AppendLine("                _currentArch = arch;");
            for (int i = 0; i < n; i++)
                sb.AppendLine($"                _t{i}Idx = arch.GetComponentTypeIndex<{genParams[i]}>();");
            sb.AppendLine("                _chunkIndex = 0;");
            sb.AppendLine("                return MoveNextChunk();");
            sb.AppendLine("            }");
            sb.AppendLine("        }");
            sb.AppendLine("        return false;");
            sb.AppendLine("    }");
            sb.AppendLine();

            // MoveNextChunk
            sb.AppendLine("    [MethodImpl(MethodImplOptions.AggressiveInlining)]");
            sb.AppendLine("    private bool MoveNextChunk()");
            sb.AppendLine("    {");
            sb.AppendLine("        if (_currentArch == null) return false;");
            sb.AppendLine("        var chunks = _currentArch.ChunkList;");
            sb.AppendLine("        while (_chunkIndex < chunks.Count)");
            sb.AppendLine("        {");
            sb.AppendLine("            var chunk = chunks[_chunkIndex];");
            sb.AppendLine("            _chunkIndex++;");
            sb.AppendLine("            if (chunk.EntityCount > 0)");
            sb.AppendLine("            {");
            sb.AppendLine("                _currentChunk = chunk;");
            sb.AppendLine("                _count = chunk.EntityCount;");
            for (int i = 0; i < n; i++)
                sb.AppendLine($"                _t{i}Base = ({genParams[i]}*)chunk.GetComponentArrayPointer(_t{i}Idx);");
            sb.AppendLine("                _slotIndex = 0;");
            sb.AppendLine("                if (_allEnabledTypes != null && _allEnabledTypes.Length > 0)");
            sb.AppendLine("                {");
            sb.AppendLine("                    if (!ComputeCombinedMask(chunk))");
            sb.AppendLine("                    {");
            sb.AppendLine("                        _combinedMask = null;");
            sb.AppendLine("                        continue;");
            sb.AppendLine("                    }");
            sb.AppendLine("                }");
            sb.AppendLine("                else");
            sb.AppendLine("                {");
            sb.AppendLine("                    _combinedMask = null;");
            sb.AppendLine("                }");
            sb.AppendLine("                return true;");
            sb.AppendLine("            }");
            sb.AppendLine("        }");
            sb.AppendLine("        _currentChunk = default;");
            sb.AppendLine("        return MoveNextArchetype();");
            sb.AppendLine("    }");
            sb.AppendLine();

            // ComputeCombinedMask
            sb.AppendLine("    [MethodImpl(MethodImplOptions.AggressiveInlining)]");
            sb.AppendLine("    private bool ComputeCombinedMask(Chunk chunk)");
            sb.AppendLine("    {");
            sb.AppendLine("        _ulongCount = (chunk.EntityCount + 63) / 64;");
            sb.AppendLine("        ulong* combinedMask = TempBuffer.GetBuffer(_ulongCount);");
            sb.AppendLine("        _combinedMask = combinedMask;");
            sb.AppendLine("        for (int i = 0; i < _ulongCount; i++) combinedMask[i] = 0;");
            sb.AppendLine("        bool firstFound = false;");
            sb.AppendLine("        var archetype = chunk.Archetype;");
            sb.AppendLine("        foreach (var type in _allEnabledTypes)");
            sb.AppendLine("        {");
            sb.AppendLine("            int componentIndex = archetype.GetComponentTypeIndex(type);");
            sb.AppendLine("            if (componentIndex < 0) continue;");
            sb.AppendLine("            ulong* bitmap = chunk.GetEnableBitMapPointer(componentIndex);");
            sb.AppendLine("            if (bitmap == null) continue;");
            sb.AppendLine("            if (!firstFound)");
            sb.AppendLine("            {");
            sb.AppendLine("                for (int i = 0; i < _ulongCount; i++)");
            sb.AppendLine("                    combinedMask[i] = bitmap[i];");
            sb.AppendLine("                firstFound = true;");
            sb.AppendLine("            }");
            sb.AppendLine("            else");
            sb.AppendLine("            {");
            sb.AppendLine("                if (Avx2.IsSupported && _ulongCount >= 4)");
            sb.AppendLine("                {");
            sb.AppendLine("                    int i = 0;");
            sb.AppendLine("                    var orResult = Vector256<ulong>.Zero;");
            sb.AppendLine("                    for (; i <= _ulongCount - 4; i += 4)");
            sb.AppendLine("                    {");
            sb.AppendLine("                        var a = Avx.LoadVector256(combinedMask + i);");
            sb.AppendLine("                        var b = Avx.LoadVector256(bitmap + i);");
            sb.AppendLine("                        var andResult = Avx2.And(a, b);");
            sb.AppendLine("                        Avx.Store(combinedMask + i, andResult);");
            sb.AppendLine("                        orResult = Avx2.Or(orResult, andResult);");
            sb.AppendLine("                    }");
            sb.AppendLine("                    bool hasIntersection = !Avx.TestZ(orResult, orResult);");
            sb.AppendLine("                    for (; i < _ulongCount && !hasIntersection; i++)");
            sb.AppendLine("                    {");
            sb.AppendLine("                        combinedMask[i] &= bitmap[i];");
            sb.AppendLine("                        hasIntersection = combinedMask[i] != 0;");
            sb.AppendLine("                    }");
            sb.AppendLine("                    if (hasIntersection)");
            sb.AppendLine("                    {");
            sb.AppendLine("                        for (; i < _ulongCount; i++)");
            sb.AppendLine("                            combinedMask[i] &= bitmap[i];");
            sb.AppendLine("                    }");
            sb.AppendLine("                    else");
            sb.AppendLine("                    {");
            sb.AppendLine("                        return false;");
            sb.AppendLine("                    }");
            sb.AppendLine("                }");
            sb.AppendLine("                else");
            sb.AppendLine("                {");
            sb.AppendLine("                    bool hasAny = false;");
            sb.AppendLine("                    for (int i = 0; i < _ulongCount; i++)");
            sb.AppendLine("                    {");
            sb.AppendLine("                        combinedMask[i] &= bitmap[i];");
            sb.AppendLine("                        if (combinedMask[i] != 0) hasAny = true;");
            sb.AppendLine("                    }");
            sb.AppendLine("                    if (!hasAny) return false;");
            sb.AppendLine("                }");
            sb.AppendLine("            }");
            sb.AppendLine("        }");
            sb.AppendLine("        return firstFound;");
            sb.AppendLine("    }");
            sb.AppendLine();

            // MoveNext / Advance / Current
            sb.AppendLine("    [MethodImpl(MethodImplOptions.AggressiveInlining)]");
            sb.AppendLine("    public bool MoveNext()");
            sb.AppendLine("    {");
            sb.AppendLine("        if (_currentChunk.MemoryBlock != nint.Zero)");
            sb.AppendLine("            _slotIndex++;");
            sb.AppendLine("        return Advance();");
            sb.AppendLine("    }");
            sb.AppendLine();
            sb.AppendLine("    [MethodImpl(MethodImplOptions.AggressiveInlining)]");
            sb.AppendLine("    private bool Advance()");
            sb.AppendLine("    {");
            sb.AppendLine("        while (true)");
            sb.AppendLine("        {");
            sb.AppendLine("            if (_currentArch == null)");
            sb.AppendLine("            {");
            sb.AppendLine("                if (!MoveNextArchetype())");
            sb.AppendLine("                    return false;");
            sb.AppendLine("            }");
            sb.AppendLine("            else if (_currentChunk.MemoryBlock == nint.Zero)");
            sb.AppendLine("            {");
            sb.AppendLine("                if (!MoveNextChunk())");
            sb.AppendLine("                    return false;");
            sb.AppendLine("            }");
            sb.AppendLine("            if (_combinedMask != null)");
            sb.AppendLine("            {");
            sb.AppendLine("                while (_slotIndex < _count)");
            sb.AppendLine("                {");
            sb.AppendLine("                    int ulongIdx = _slotIndex >> 6;");
            sb.AppendLine("                    if (ulongIdx >= _ulongCount)");
            sb.AppendLine("                    {");
            sb.AppendLine("                        _slotIndex = _count;");
            sb.AppendLine("                        break;");
            sb.AppendLine("                    }");
            sb.AppendLine("                    int bitOffset = _slotIndex & 63;");
            sb.AppendLine("                    ulong mask = _combinedMask[ulongIdx] >> bitOffset;");
            sb.AppendLine("                    if (mask != 0)");
            sb.AppendLine("                    {");
            sb.AppendLine("                        int bitIndex = BitOperations.TrailingZeroCount(mask);");
            sb.AppendLine("                        _slotIndex += bitIndex;");
            sb.AppendLine("                        if (_slotIndex < _count)");
            sb.AppendLine("                            return true;");
            sb.AppendLine("                        break;");
            sb.AppendLine("                    }");
            sb.AppendLine("                    _slotIndex = (ulongIdx + 1) << 6;");
            sb.AppendLine("                }");
            sb.AppendLine("            }");
            sb.AppendLine("            else");
            sb.AppendLine("            {");
            sb.AppendLine("                if (_slotIndex < _count)");
            sb.AppendLine("                    return true;");
            sb.AppendLine("            }");
            sb.AppendLine("            _currentChunk = default;");
            sb.AppendLine("        }");
            sb.AppendLine("    }");
            sb.AppendLine();
            sb.AppendLine($"    public EntityQueryResult<{genList}> Current");
            sb.AppendLine("    {");
            sb.AppendLine("        [MethodImpl(MethodImplOptions.AggressiveInlining)]");
            sb.AppendLine("        get");
            sb.AppendLine("        {");
            sb.AppendLine("            if (_currentChunk.MemoryBlock == nint.Zero) throw new InvalidOperationException();");
            sb.Append($"            return new EntityQueryResult<{genList}>(");
            for (int i = 0; i < n; i++)
            {
                if (i > 0) sb.Append(", ");
                sb.Append($"_t{i}Base + _slotIndex");
            }
            sb.AppendLine(");");
            sb.AppendLine("        }");
            sb.AppendLine("    }");
            sb.AppendLine("}");
            sb.AppendLine();

            // ===== EntityQueryResult<T0..Tn> =====
            sb.AppendLine($"public unsafe readonly struct EntityQueryResult<{genList}>");
            sb.AppendLine($"    {whereClause}");
            sb.AppendLine("{");
            for (int i = 0; i < n; i++)
                sb.AppendLine($"    private readonly {genParams[i]}* _c{i};");
            sb.AppendLine();
            sb.AppendLine($"    internal EntityQueryResult({string.Join(", ", genParams.Select((g, i) => $"{g}* c{i}"))})");
            sb.AppendLine("    {");
            for (int i = 0; i < n; i++)
                sb.AppendLine($"        _c{i} = c{i};");
            sb.AppendLine("    }");
            sb.AppendLine();
            for (int i = 0; i < n; i++)
            {
                sb.AppendLine($"    public ref {genParams[i]} Comp{i}");
                sb.AppendLine("    {");
                sb.AppendLine("        [MethodImpl(MethodImplOptions.AggressiveInlining)]");
                sb.AppendLine($"        get => ref *_c{i};");
                sb.AppendLine("    }");
            }
            sb.AppendLine("}");
            sb.AppendLine();

            // ===== World.Query<T0..Tn>（扩展方法：partial 跨程序集不合并，须用 this World） =====
            // 类名带 arity 后缀：同程序集内不同 arity 生成不同类，防 CS0101 同名冲突。
            sb.AppendLine($"public static class QueryTupleWorldExtensions{n}");
            sb.AppendLine("{");
            sb.AppendLine($"    public static QueryEnumerable<{genList}> Query<{genList}>(this World world)");
            sb.AppendLine($"        {whereClause}");
            sb.AppendLine("    {");
            sb.AppendLine("        var builder = new QueryBuilder();");
            sb.AppendLine($"        builder.All = new ComponentType[] {{ {typeOfArgs} }};");
            sb.AppendLine($"        return new QueryEnumerable<{genList}>(world._entityManager, builder);");
            sb.AppendLine("    }");
            sb.AppendLine("}");
            sb.AppendLine();

            return sb.ToString();
        }
    }
}
