#nullable enable
using System;
using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.CSharp.Syntax;
using Microsoft.CodeAnalysis.Text;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading;

namespace EntJoy.ECS.SourceGenerator
{
    /// <summary>
    /// System 注册生成器（方案 A）：扫描同程序集所有 <c>struct : ISystem</c>，
    /// 生成 <c>SystemRegistry.RegisterAll(SystemRunner)</c> 一行注册全部，
    /// 消除逐个手写 <c>runner.RegisterSystem&lt;T&gt;()</c> 的样板。
    /// 依赖声明（[Read]/[Write]）保持现状，由 ScheduleGraph 反射读取。
    /// 限制：源生成器只能收集当前编译单元（用户程序集）内的 System。
    /// </summary>
    internal sealed class SystemRegistrationSourceGenerator : IIncrementalGenerator
    {
        public void Initialize(IncrementalGeneratorInitializationContext context)
        {
            var provider = context.SyntaxProvider
                .CreateSyntaxProvider(
                    predicate: static (node, _) => IsCandidate(node),
                    transform: static (ctx, ct) => GetSystemFullName(ctx, ct))
                .Where(static name => name != null);

            var collected = provider.Collect();

            context.RegisterSourceOutput(collected, static (spc, names) =>
            {
                var sorted = new SortedSet<string>(StringComparer.Ordinal);
                foreach (var n in names)
                    if (n != null) sorted.Add(n);

                if (sorted.Count == 0)
                    return;

                spc.AddSource("SystemRegistry.g.cs", SourceText.From(Generate(sorted), Encoding.UTF8));
            });
        }

        /// <summary>语法预筛：struct 声明的基接口列表含 ISystem。</summary>
        private static bool IsCandidate(SyntaxNode node)
        {
            return node is StructDeclarationSyntax s &&
                   s.BaseList != null &&
                   s.BaseList.Types.Any(t => t.Type.ToString().Contains(Config.ISystem));
        }

        /// <summary>语义验证：实现 EntJoy.ECS.ISystem，返回全限定类型名（global:: 前缀）。</summary>
        private static string? GetSystemFullName(GeneratorSyntaxContext context, CancellationToken ct)
        {
            if (context.Node is not StructDeclarationSyntax candidate)
                return null;

            var model = context.SemanticModel;
            if (model.GetDeclaredSymbol(candidate, ct) is not INamedTypeSymbol typeSymbol)
                return null;

            bool isSystem = typeSymbol.AllInterfaces.Any(i =>
                i.Name == Config.ISystem && i.ContainingNamespace?.ToDisplayString() == Config.NamespaceEntJoyECS);
            if (!isSystem)
                return null;

            // [DisableAutoCreation]：跳过自动收集（需手动 RegisterSystem<T>()，对齐 Unity DOTS）
            if (typeSymbol.GetAttributes().Any(a =>
                    a.AttributeClass?.Name == Config.DisableAutoCreation &&
                    a.AttributeClass.ContainingNamespace?.ToDisplayString() == Config.NamespaceEntJoyECS))
                return null;

            return typeSymbol.ToDisplayString(SymbolDisplayFormat.FullyQualifiedFormat);
        }

        private static string Generate(IEnumerable<string> systemFullNames)
        {
            var sb = new StringBuilder();
            sb.AppendLine("// <auto-generated/>");
            sb.AppendLine("#nullable enable");
            sb.AppendLine("using EntJoy.ECS;");
            sb.AppendLine();
            sb.AppendLine("/// <summary>自动收集的 System 注册入口（由 SystemRegistrationSourceGenerator 生成）。</summary>");
            sb.AppendLine("public static class SystemRegistry");
            sb.AppendLine("{");
            sb.AppendLine("    /// <summary>注册本程序集内所有 struct : ISystem 的 System（依赖仍由 [Read]/[Write] 特性声明）。</summary>");
            sb.AppendLine("    public static void RegisterAll(SystemRunner runner)");
            sb.AppendLine("    {");
            foreach (var name in systemFullNames)
            {
                sb.AppendLine($"        runner.RegisterSystem<{name}>();");
            }
            sb.AppendLine("    }");
            sb.AppendLine("}");
            return sb.ToString();
        }
    }
}
