<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <AllowUnsafeBlocks>true</AllowUnsafeBlocks>
    <Optimize>true</Optimize>
    <AssemblyName>EntJoy.Collections</AssemblyName>
  </PropertyGroup>
  <ItemGroup>
    <ProjectReference Include="..\EntJoy.Mathematics\EntJoy.Mathematics.csproj" />
  </ItemGroup>
</Project>
